roc-lang/roc

www/netlify.toml

This should only be merged after the repo has been made public.

Serve AUTHORS from roc-lang/roc repo

---

crates/roc_std/src/roc_list.rs

It looks like a lot of methods got added under the `impl` with the `T: Clone` requirement, when those methods did not need that restriction!

Don't require `Clone` on as many `RocList` methods

---

crates/compiler/gen_wasm/src/wasm32_result.rs
crates/compiler/test_gen/src/gen_primitives.rs

Add regression tests for #2419

---

TUTORIAL.md

The packages defintion needs a file and not a directory.
See also #3249

Fix Tutorial

---

TUTORIAL.md

Signed-off-by: Rod <randomer@users.noreply.github.com>

Fix the installation link

---

getting_started/README.md

Signed-off-by: Rod <randomer@users.noreply.github.com>

Fix broken installation links

---

FAQ.md

FAQ basic website

---

examples/ruby-interop/README.md

Signed-off-by: Richard Feldman <oss@rtfeldman.com>

Lower minimum Ruby version in ruby-interop example

---

README.md

See our prior discussion [here](https://roc.zulipchat.com/#narrow/stream/306878-off-topic/topic/casual.20conversation/near/293338300)
Signed-off-by: Jan Van Bruggen <JanCVanB@users.noreply.github.com>

Add installation & tutorial guide links to README

---

crates/cli/src/build.rs
crates/cli/src/lib.rs
crates/cli/src/main.rs
crates/compiler/load/src/lib.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/load_internal/src/work.rs

Supersedes #3617, as this takes a slightly different approach and #3617 is now outdated from main.

Don't monomorphize if roc foo.roc has errors

---

BUILDING_FROM_SOURCE.md

This error may occur frequently enough that it's worth mentioning in BUILDING_FROM_SOURCE

mention nix GLIBC version error

---

crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/test_gen/src/gen_num.rs

- make integer multiplication work for quadwords and lower
- implement float multiplication
- attempt at unsigned multiplication

dev backend mul

---

README.md

Also adds link to frequently asked questions

make README more human friendly

---

crates/compiler/mono/src/ir.rs

A couple simple refactorings:
- Co-locate subs and layout snapshots, since those will need to happen together
- Get rid of an extra function we didn't need
- Remove an unnecessary snapshot/rollback we were doing. We did one before calling `specialize_variable_help`, but also one inside of `specialize_variable_help` - there's no need to do both! I doubt this will seriously help our perf problems, but less copies are always better.

Cleanup snapshots in mono, getting rid of a redundant one

---

CONTRIBUTING.md

- also added a tip for people who've never made a PR on github before
- minor cleanup

Contributing: recommend fork

---

crates/repl_cli/src/lib.rs

Change repl behavior and instructions around quit

---

crates/compiler/builtins/src/bitcode.rs

improved lib dir error msg

---

.github/workflows/benchmarks.yml
.github/workflows/nightly_linux_x86_64.yml
.github/workflows/nightly_macos_apple_silicon.yml
.github/workflows/nightly_macos_x86_64.yml
.github/workflows/nix_linux_x86_64.yml
.github/workflows/nix_macos_apple_silicon.yml
.github/workflows/spellcheck.yml

- also updated checkout action

fix linux nightly

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/lib.rs

This is the end result of a pairing session with Folkert.

Execute raw bytes on Windows without spawning a process

---

.github/workflows/ubuntu_x86_64.yml
AUTHORS
Earthfile

Duplicates are hard to spot, but we can automate it using the magic of computers 🪄💻.
Yes I realise this is a bit over the top. I happened to notice one duplicate, then wondered how you'd automate that, and then a few minutes later there was code 🤷🤓

Check for duplicate AUTHORS

---

crates/glue/src/rust_glue.rs

Fix glue for into_ and as_ on single-tag unions

---

crates/cli/src/format.rs
crates/code_markup/src/markup/common_nodes.rs
crates/compiler/constrain/src/expr.rs
crates/compiler/exhaustive/src/lib.rs
crates/compiler/gen_llvm/src/run_roc.rs
crates/compiler/parse/src/ident.rs
crates/compiler/parse/src/number_literal.rs
crates/compiler/parse/src/parser.rs
crates/linker/src/lib.rs
crates/repl_expect/src/lib.rs

- clippy fixes
- more various clippy fixes

rust 1.63 clippy

---

TUTORIAL.md

This commit should be reverted once #3906 is fixed.

Tutorial edit until #3906 is fixed

---

crates/compiler/unify/src/unify.rs

Gives nice performance wins, in particular avoiding clones of
unification tables, which can grow quite large.
Closes #3940

Check for unifiability of lambda sets without a subs snapshot

---

crates/cli/src/lib.rs

I just noticed some minor inconsistencies.

Improve consistency in CLI help messages

---

crates/docs/src/lib.rs
crates/docs/src/static/index.html
www/netlify.toml

Adds prefetching for sidebar links in the generated docs, so they load instantly when you click them.

Docs improvements

---

crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/test_gen/src/gen_num.rs

- bitwise logical operators in the dev backend
- compact code
- compact some pattern matches

dev backend: bitwise logical operators

---

crates/cli/src/lib.rs
crates/linker/src/lib.rs

I was doing some investigative work for https://github.com/roc-lang/roc/issues/3125. Doing everything in-memory seems nice, but requires a bunch of changes in many places.

minor cleanup of surgery

---

crates/compiler/mono/src/ir.rs
crates/compiler/test_gen/src/gen_records.rs

Correctly perform record updates that come from thunks

---

crates/compiler/gen_llvm/src/llvm/build.rs

this is a bit of an ad-hoc solution. We will  fix this more properly when doing glue for functions
cc @brian-carroll

allow passing of RocStr by-value from a host

---

FAQ.md

[Rendered](https://github.com/roc-lang/roc/blob/5c8f91be887d6641d116d40133329b84a607e87d/FAQ.md#currying-and-the--operator)

Revise FAQ entry on currying and pipe operator

---

examples/interactive/file.roc

Signed-off-by: Jan Van Bruggen <JanCVanB@users.noreply.github.com>

Fix file example app executable name

---

crates/compiler/builtins/roc/Str.roc
crates/compiler/module/src/symbol.rs

Blocked by https://github.com/roc-lang/roc/issues/4018

Add `Str.replace*` builtins

---

crates/glue/src/rust_glue.rs
crates/glue/src/types.rs
crates/glue/tests/test_glue_cli.rs

Fix glue segfault for newtype wrappers around recursive tag unions

---

crates/compiler/constrain/src/expr.rs
crates/reporting/tests/test_reporting.rs

Span body of last branch in exhaustiveness checking

---

crates/compiler/gen_llvm/src/llvm/expect.rs
crates/repl_expect/src/lib.rs

Co-authored-by: Folkert de Vries <folkert@folkertdev.nl>

Copy list values from the correct offset when reporting expects

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/tests/cli_run.rs

Closes https://github.com/roc-lang/roc/issues/4038

Avoid example tests overwriting each other's platforms

---

crates/roc_std/src/roc_dict.rs

I learned a bunch of stuff while making FFI-safe (#3960) and realized this morning that it's not really well-documented. Here's some comments to make things easier for the next person!

document why Dict is the way it is

---

.github/workflows/nightly_macos_x86_64.yml

It's important to write the version file before building the release :)

roc version fix

---

FAQ.md

Some good points are being made here about code readability. Thank you. I propose a small correction that will hopefully
1. stop the "experts" from jumping at your throat (because what is described here is not "desugaring" in the technical PL sense)
2. convince others even more of your point, because "eta-expansion" sounds more scary than "desugaring" :)

Update FAQ.md: desugar ~> eta-expand

---

TUTORIAL.md

This PR updates the programs in the tutorial to have their types match with the newly introduced `Program` type.
I've tried to adequately also update the surrounding text explanations and I hope I didn't miss anything.

Update programs with Program.quick in the tutorial

---

crates/compiler/builtins/roc/Str.roc

Str.splitFirst should not find match if needle is longer than haystack

---

crates/reporting/src/error/parse.rs
crates/reporting/tests/test_reporting.rs

I've run into this syntax error a lot since I'm not super familiar with elm or roc style programming or functional programming in general.
Replaces #2129

fix expression indentation error

---

design/Abilities.md

Tried to be consistent with the google docs, took some creative liberty with problem references.
Not sure if the right directory, feel free to correct.

Abilities proposal markdown

---

crates/compiler/fmt/src/expr.rs
crates/compiler/fmt/src/lib.rs
crates/compiler/fmt/tests/test_fmt.rs

Properly format characters with escape sequences

---

FAQ.md
TUTORIAL.md
roc-for-elm-programmers.md

On `main`, they talk about `True` instead of `Bool.true`, etc.

Update boolean docs in tutorial

---

crates/repl_cli/src/lib.rs
crates/repl_test/src/cli.rs

Related to: #4160 
Let me know if this is more or less what you had in mind, or if you wanted something else.

Add tips to REPL

---

crates/compiler/can/src/def.rs
crates/reporting/src/error/canonicalize.rs
crates/reporting/tests/test_reporting.rs

Closes #4153 
Closes https://github.com/roc-lang/roc/issues/3385

Correctly compile top-level defs that are illegally self-recursive

---

crates/compiler/fmt/src/expr.rs
crates/compiler/fmt/tests/test_fmt.rs

Correctly format nested pipeline operators

---

crates/compiler/builtins/roc/Json.roc
crates/compiler/can/src/copy.rs
crates/compiler/can/src/def.rs
crates/compiler/can/src/exhaustive.rs
crates/compiler/can/src/module.rs
crates/compiler/can/src/pattern.rs
crates/compiler/constrain/src/pattern.rs
crates/compiler/mono/src/ir.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_derive/src/pretty_print.rs
crates/compiler/test_gen/src/gen_primitives.rs
crates/reporting/tests/test_reporting.rs

Support single-quote literal pattern matching

---

crates/repl_eval/src/eval.rs
crates/repl_test/src/tests.rs

Print bool correctly in repl

---

crates/reporting/src/error/type.rs
crates/reporting/tests/test_reporting.rs

Suggest Bool.true and Bool.false where tag literals are used

---

crates/compiler/builtins/roc/Hash.roc
crates/compiler/builtins/src/roc.rs
crates/compiler/fmt/src/def.rs
crates/compiler/fmt/tests/test_fmt.rs
crates/compiler/load/build.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/module/src/ident.rs
crates/compiler/module/src/symbol.rs
crates/compiler/parse/src/expr.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_gen/src/gen_abilities.rs
crates/compiler/test_mono/src/tests.rs
crates/reporting/tests/test_reporting.rs

As discussed on Zulip.
Part of #4195

Add the `Hash` builtin module

---

crates/compiler/builtins/roc/Num.roc
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_wasm/src/low_level.rs
crates/compiler/test_gen/src/gen_num.rs
crates/reporting/tests/test_reporting.rs
examples/breakout/platform/Cargo.lock
examples/gui/platform/Cargo.lock

https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/casual.20conversation/near/302305020

Have `Num.shift*By` functions shift by a `U8`

---

crates/compiler/fmt/src/module.rs
crates/compiler/fmt/tests/test_fmt.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/test_gen/src/gen_num.rs
crates/repl_cli/src/lib.rs
crates/repl_eval/src/eval.rs
crates/repl_expect/src/lib.rs
crates/repl_test/src/tests.rs
crates/repl_wasm/src/repl.rs

Rollup of a few misc. bug fixes.
Closes https://github.com/roc-lang/roc/issues/4212
Closes https://github.com/roc-lang/roc/issues/4210
Closes https://github.com/roc-lang/roc/issues/4208

Misc bugfixes 10-05

---

crates/compiler/derive/src/hash.rs
crates/compiler/derive_key/src/hash.rs
crates/compiler/test_derive/src/hash.rs
crates/compiler/test_gen/src/gen_abilities.rs

Part of https://github.com/roc-lang/roc/issues/4202
Part of https://github.com/roc-lang/roc/issues/4195
After this, we just need to support tags.
Blocked on  #4204

Support deriving `Hash` for inductive records

---

crates/compiler/builtins/roc/List.roc
crates/compiler/module/src/symbol.rs

builtin(list): expose walkTry

---

crates/compiler/builtins/roc/Num.roc
crates/compiler/can/src/builtins.rs

This will be needed ahead of the `Eq` ability.
Closes #4223

Implement Num.isZero as a low-level

---

examples/cli/cli-platform/src/lib.rs

Format CLI backtraces

---

examples/cli/args.roc
examples/cli/cli-platform/Arg.roc

This addresses my recent renaming/refactoring concerns in #4130

Rename "option" args

---

.github/workflows/markdown_link_check.yml

This PR purposely does not include fixes to links. However, I'll update the PR with the fixes once the CI process fails.

Add Markdown Link Check action

---

.github/workflows/ubuntu_x86_64.yml

Add a GitHub action step to test builtins format

---

crates/compiler/builtins/roc/List.roc
crates/compiler/module/src/symbol.rs
crates/compiler/test_gen/src/gen_list.rs

builtin(list): add List.countIf

---

crates/compiler/mono/src/ir.rs
crates/compiler/test_gen/src/gen_str.rs

Correctly destructure patterns that are assigned to a thunk'd value

---

TUTORIAL.md

Updated TUTORIAL.md to describe how to import application modules.

describe importing application modules in Tutorial docs

---

.github/workflows/ubuntu_x86_64.yml
crates/compiler/builtins/roc/Dict.roc
crates/compiler/builtins/roc/Hash.roc
crates/compiler/builtins/roc/List.roc
crates/compiler/can/src/builtins.rs
crates/compiler/module/src/symbol.rs

Adds a hasher implementation based on wyhash to the Dict.roc file. Will add the actual dictionary in a follow up PR.
I am not exactly sure on naming, but everything looks to be functioning. Added a lot of tests via `expect`.
Also, I exposed `List.getUnsafe`. That still need so be cleaned up.

Roc hasher impl

---

crates/compiler/can/src/annotation.rs
crates/compiler/can/src/def.rs
crates/compiler/constrain/src/builtins.rs
crates/compiler/solve/src/ability.rs
crates/compiler/solve/src/solve.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/types/src/types.rs
crates/reporting/tests/test_reporting.rs

Closes https://github.com/roc-lang/roc/issues/4259

Make sure type variables bound to abilities are instantiated in aliases

---

crates/compiler/builtins/roc/Num.roc
crates/compiler/builtins/roc/Str.roc

I have found it difficult to decipher some of the builtin functionality. I found the docs that had an expect call to be very helpful, so I've started adding them and checking they compile with ```roc test```. I'm not removing any content, though I have been trying to align the docs and make them more consistently formatted. Where there is no note I have been trying to add a description of the function.
Still a WIP.

adding expect and documentation for Str builtin

---

Cargo.lock
crates/compiler/alias_analysis/Cargo.toml
crates/compiler/alias_analysis/src/lib.rs
crates/compiler/arena_pool/Cargo.toml
crates/compiler/arena_pool/src/pool.rs
crates/compiler/build/src/link.rs
crates/compiler/build/src/program.rs
crates/compiler/build/src/target.rs

Hi
I replaced panic! with internal_error!.
I started with only panic! and only inside the crates `compiler/build`, `compiler/alias_analysis` and `compiler/arena_pool` to keep this PR small.
Related to https://github.com/roc-lang/roc/issues/2046

Replace panic! with internal_error! in `compiler/build`, `compiler/alias_analysis` and `compiler/arena_pool`

---

.github/workflows/markdown_link_check.yml
CONTRIBUTING.md
crates/compiler/gen_dev/README.md
crates/editor/README.md
crates/editor/editor-ideas.md
examples/static-site-gen/input/apple.md
examples/static-site-gen/input/banana.md
examples/static-site-gen/input/cherry.md
mlc_config.json

This PR is ready to merge.
This resolves https://github.com/roc-lang/roc/issues/3832

Repair broken links in Markdown

---

crates/compiler/builtins/roc/List.roc
crates/compiler/module/src/symbol.rs
crates/compiler/test_gen/src/gen_list.rs

Implements two more List funcs listed in #664 :)

builtin(list): add List.walkFrom, List.walkFromUntil

---

CONTRIBUTING.md

Setting this up can be a bit of a chore so it's nice to provide some motivation :)

added link to story commit signing

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/lib.rs

after much frustration: this works! no `memexec`  required!

use execve on windows!

---

crates/compiler/gen_llvm/src/llvm/compare.rs
crates/compiler/test_gen/src/gen_primitives.rs

Use runtime representation of values when building structural eq

---

crates/ast/src/lang/core/types.rs
crates/ast/src/solve_type.rs
crates/compiler/can/src/annotation.rs
crates/compiler/mono/src/layout.rs
crates/compiler/mono/src/layout_soa.rs
crates/compiler/solve/src/solve.rs
crates/compiler/types/src/pretty_print.rs
crates/compiler/types/src/subs.rs
crates/compiler/types/src/types.rs
crates/compiler/unify/src/unify.rs
crates/glue/src/types.rs
crates/reporting/src/error/type.rs
crates/reporting/tests/test_reporting.rs

Disallow typing optional fields when required fields are annotated

---

crates/linker/src/lib.rs
crates/linker/src/pe.rs

this makes `rocLovesC` work with the surgical linker on windows

resize reloc section when required

---

CONTRIBUTING.md

Add how to sign unsigned commits section

---

examples/cli/tui-platform/host.zig

Signed-off-by: Nick Gravgaard <nick@nickgravgaard.com>

Obvious refactor of TUI platform's event loop

---

TUTORIAL.md

…extra notes amended wherever necessary
This is a relatively small commit.
While going through the tutorial, I felt as if the ultimate goal is to have an interactive tutorial with the Roc editor. 
While its great, I would like to see the online tutorials to be complete and gives the learner a sense of where he is in the journey.
I have added a summary section, right before the advanced concepts as delimitation before proceeding futher. 
Hope this is fine.
Would love your feedback.

Added the interface modules and Summary sections. Reorganisation and 

---

crates/compiler/builtins/roc/Bool.roc

Updated the comments to be consistent in the use of words. Added expectations to illustrate the use of functions. 
This should be good for review.

updated docs for Bool.roc

---

devtools/vscodeflake.nix

Added example on how to install plugin that is not available on nix but is on vscode marketplace.

vscode marketplace example

---

crates/editor/editor-ideas.md

Based on [this message](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/How.20friendly.20can.20Roc.20be.3F/near/305085369). Thanks @lukewilliamboswell!

added Luke's editor ideas

---

getting_started/windows.md

This used to link to the closed issue about the windows surgical linker.

fix windows getting started

---

crates/reporting/src/error/parse.rs
crates/reporting/tests/test_reporting.rs

Add suggest lambda operator instead of when 

---

crates/compiler/fmt/src/pattern.rs
crates/compiler/fmt/tests/test_fmt.rs

add missing indent when formatting single-quoted char in pattern

---

crates/compiler/can/src/copy.rs
crates/compiler/can/src/def.rs
crates/compiler/can/src/exhaustive.rs
crates/compiler/can/src/module.rs
crates/compiler/can/src/pattern.rs
crates/compiler/can/src/traverse.rs
crates/compiler/constrain/src/pattern.rs
crates/compiler/mono/src/ir.rs
crates/compiler/problem/src/can.rs
crates/compiler/test_derive/src/pretty_print.rs
crates/compiler/types/src/types.rs
crates/reporting/src/error/canonicalize.rs
crates/reporting/src/error/type.rs
crates/reporting/tests/test_reporting.rs

Getting this in before exhaustiveness checking of list patterns, which will be the first interesting piece!

Canonicalization + Constraining of list patterns

---

.github/workflows/benchmarks.yml

I could not yet do this in #4347 because the folder structure of the branch and main was still different.

Compare benches of branch with main

---

TUTORIAL.md

Closes https://github.com/roc-lang/roc/issues/4452

Add list pattern matching to tutorial

---

crates/repl_expect/src/run.rs

Partial revert of commit 84178c66e1a026cb431193935f66877e8e90226e

fix "failed to truncate shared file"

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/lib.rs

Minor refactor for maintainability.

Use strum to automate keeping targets list in sync

---

crates/cli/tests/cli_run.rs
crates/compiler/alias_analysis/src/lib.rs
examples/cli/false-interpreter/False.roc

this makes the false interpreter compile on windows, and some small fixes to make the cli test succeed

fix stack overflow in alias analysis

---

crates/compiler/build/src/program.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/test_gen/src/helpers/llvm.rs

I contributed this a while ago, but we never changed our usages to the upstream version

use inkwell's FunctionIterator

---

BUILDING_FROM_SOURCE.md
getting_started/macos_apple_silicon.md
getting_started/macos_x86_64.md

add zig version to homebrew commands

---

crates/ast/src/module.rs
crates/cli/src/build.rs
crates/cli/src/lib.rs
crates/compiler/load/build.rs
crates/compiler/load/src/lib.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/load_internal/tests/test_load.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_derive/src/util.rs
crates/compiler/test_gen/src/helpers/dev.rs
crates/compiler/test_gen/src/helpers/llvm.rs
crates/compiler/test_gen/src/helpers/wasm.rs
crates/compiler/test_mono/src/tests.rs
crates/docs/src/lib.rs
crates/glue/src/load.rs
crates/linker/src/lib.rs
crates/repl_eval/src/gen.rs
crates/repl_expect/src/lib.rs
crates/reporting/src/report.rs
crates/reporting/tests/test_reporting.rs

Fix web REPL error formatting by routing the active Palette everywhere

---

crates/compiler/solve/tests/solve_expr.rs
crates/compiler/types/src/subs.rs

Chase under aliases during occurs checking

---

crates/compiler/alias_analysis/src/lib.rs
crates/compiler/gen_llvm/src/llvm/build.rs

this ran into trouble earlier in #2095 but we resolved a problem with recursion at some point, so now this just works.

morphic + reset/reuse

---

crates/cli/tests/cli_run.rs
crates/compiler/collections/src/vec_set.rs
crates/compiler/debug_flags/src/lib.rs
crates/compiler/solve/src/solve.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_gen/src/gen_primitives.rs
crates/compiler/test_gen/src/gen_tags.rs
crates/compiler/types/src/subs.rs
crates/compiler/types/src/types.rs
crates/compiler/unify/src/fix.rs
crates/compiler/unify/src/lib.rs
crates/compiler/unify/src/unify.rs
crates/reporting/src/error/type.rs
crates/reporting/tests/test_reporting.rs
examples/cli/cli-platform/Arg.roc

Fix solve/reporting panics that occur in the presence of type errors

---

www/public/favicon.svg

This was bothering me, so I fixed it!

Lighten favicon in dark mode

---

www/netlify.toml
www/public/tutorial/index.html

Fixes two Conent-Security Policy violations on roc-lang.org

Fix some CSP violations

---

crates/compiler/gen_wasm/README.md

Is this a good place for this?
Anything else that should be in it?

gen_wasm: Add debugging tips to readme

---

www/public/site.css
www/public/tutorial/index.html

Blocked on https://github.com/roc-lang/roc/issues/4595 (since the example given won't work until that's fixed!)

Add `dbg` section to tutorial

---

www/public/index.html

Signed-off-by: Salman Shaik <94877549+P8ace@users.noreply.github.com>

Added the correct link to swift lang site

---

crates/cli/tests/cli_run.rs
crates/cli/tests/known_bad/TypeError.roc
examples/cli/README.md
www/build.sh
www/public/tutorial/index.html

Also, docs for basic-cli now live at (for example):
https://www.roc-lang.org/packages/basic-cli/Stdout#line

Use `basic-cli` in tutorial

---

crates/compiler/parse/src/expr.rs
crates/compiler/parse/src/ident.rs
crates/compiler/parse/src/module.rs
crates/compiler/parse/src/parser.rs
crates/compiler/parse/src/pattern.rs
crates/compiler/parse/src/type_annotation.rs
crates/reporting/src/error/parse.rs

... to be much more readable, using combinators

Refactor collection_trailing_sep_e

---

crates/compiler/build/src/link.rs
crates/linker/src/lib.rs
examples/.gitignore

Step towards fixing https://github.com/roc-lang/basic-cli/issues/6

change matadata filename based on target

---

crates/packaging/src/tarball.rs
examples/.gitignore
www/public/tutorial/index.html

To fix https://github.com/roc-lang/basic-cli/issues/6

update tutorial, cleanup

---

crates/wasm_interp/src/execute.rs
crates/wasm_interp/src/value_stack.rs
crates/wasm_interp/tests/test_i32.rs
crates/wasm_interp/tests/test_i64.rs
crates/wasm_module/src/parse.rs

Just copy-and-pasting a load of i32 code and replacing 32 with 64.
There were a few other tweaks to fix some ops.
But the whole thing took less than an hour. 😄

Wasm interp i64ops

---

crates/wasm_interp/src/instance.rs
crates/wasm_interp/tests/test_convert.rs
crates/wasm_interp/tests/test_f32.rs
crates/wasm_interp/tests/test_f64.rs

The last few Wasm operators.
We now have a full instruction set! 🎉 
I had been thinking of leaving a few `todo!` because we'll probably never need them. _But_ then, whenever we hit some issue, we would always wonder "oh maybe this hits an unimplemented instruction". It seemed worthwhile to just eliminate that possibility.

Wasm interp final ops

---

crates/compiler/solve/src/ability.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_gen/src/gen_compare.rs
crates/compiler/types/src/subs.rs
crates/compiler/unify/src/unify.rs
crates/repl_expect/src/lib.rs
crates/reporting/tests/test_reporting.rs

Closes https://github.com/roc-lang/roc/issues/4594

Unify ranged numbers with flex able, modulo obligation checking

---

crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/compare.rs
crates/compiler/gen_llvm/src/llvm/refcounting.rs
crates/compiler/test_gen/src/gen_compare.rs

Ensure that llvm gen_ wrappers account different recursive pointers

---

.github/workflows/ubuntu_x86_64.yml
crates/linker/src/generate_dylib/elf64.rs

Generate a less hacky `libapp.so`, and test on CI that the `.so` that we generate is loadable.

Linux stub lib

---

crates/compiler/builtins/roc/Dict.roc
crates/compiler/builtins/roc/Hash.roc
crates/compiler/derive_key/src/hash.rs
crates/compiler/module/src/symbol.rs
crates/compiler/test_mono/generated/dict.txt

This was surprisingly simple. Tested it on the AOC example and it works.

add the ability to hash Nats

---

ci/package_release.sh

- add zig builtins to the release
- don't put executables and .o files in release
Closes #4706

fix release packaging

---

.github/workflows/nightly_macos_x86_64.yml

make macos nightly target generic x86_64

---

crates/glue/src/types.rs
crates/glue/tests/test_glue_cli.rs

Small PR to get Dict and Set type generation fixed in `roc glue`

fix glue generation for Dict and Set

---

www/public/site.js
www/public/tutorial/index.html

Without this, the table of contents is pretty annoying to use on mobile!

Close tutorial ToC after clicking a link

---

crates/compiler/parse/benches/bench_parse.rs

... in advance of some parser changes that need benchmarking :)

Fix parse benchmark and add a benchmark for parsing Num.roc

---

crates/repl_eval/src/eval.rs
crates/repl_test/src/tests.rs

Make sure byte-sized tag unions are printed as unions in the repl

---

crates/compiler/mono/src/debug/report.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_mono/generated/choose_correct_recursion_var_under_record.txt
crates/compiler/test_mono/src/tests.rs
crates/compiler/unify/src/unify.rs

This was leading us to have an infinitely-recursive type, which eventually causes layout to stack-overflow
Fixes #4739

Fix bug in unifying records

---

crates/cli/tests/cli_run.rs
crates/compiler/gen_llvm/src/llvm/bitcode.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/convert.rs
crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/test_gen/src/gen_str.rs

Remove use of pointer  get_element_type

---

crates/compiler/builtins/bitcode/src/str.zig

so it turns out we were doing a UB in the zig code, and with zig 10/llvm 15 this actually gives miscompilations. This is the sort of thing that rust catches, but we can get something similar in zig by using const pointers.

fix lifetime issue in RocStr.asU8Ptr

---

crates/compiler/mono/src/ir.rs
crates/compiler/test_mono/generated/issue_4557.txt
crates/compiler/test_mono/src/tests.rs

Appropriately substitute symbols in switch conditions

---

crates/compiler/mono/src/layout.rs

Turn off false-positive producing debug assert for now

---

crates/compiler/builtins/bitcode/src/list.zig

fix #4816
I'm still working on tests for this in https://github.com/roc-lang/roc/pull/4802

fix memory leak in List.concat

---

crates/ast/src/module.rs
crates/cli/Cargo.toml
crates/cli/src/build.rs
crates/cli/src/lib.rs
crates/compiler/build/src/link.rs
crates/compiler/builtins/src/bitcode.rs
crates/compiler/load/src/lib.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/load_internal/src/wasm_instant.rs
crates/compiler/roc_target/src/lib.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_gen/src/helpers/dev.rs
crates/compiler/test_gen/src/helpers/llvm.rs
crates/compiler/test_gen/src/helpers/wasm.rs
crates/compiler/test_mono/src/tests.rs
crates/docs/src/lib.rs
crates/glue/src/load.rs
crates/linker/src/lib.rs
crates/repl_eval/src/gen.rs
crates/repl_expect/src/lib.rs
crates/reporting/tests/test_reporting.rs

main goal is to create an entry point that we can use for tests that use compiled programs, but where using the CLI is not required. My main use case is more valgrind tests, but there might be other things too (e.g. benchmarks)

Refactor build

---

crates/compiler/builtins/bitcode/src/str.zig

fix #4856 
fix memory leak when the first argument of `Str.concat` is non-unique
the underlying issue was using length where capacity is now needed.

str concat non unique first argument

---

crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/mono/src/borrow.rs
crates/compiler/mono/src/code_gen_help/equality.rs
crates/compiler/mono/src/code_gen_help/refcount.rs
crates/compiler/mono/src/debug/checker.rs
crates/compiler/mono/src/decision_tree.rs
crates/compiler/mono/src/inc_dec.rs
crates/compiler/mono/src/ir.rs
crates/compiler/mono/src/tail_recursion.rs

as the title suggests.
Not sure if typing like this is desired, but there's only one way to find out 🙃

replace borrowed boolean with ownership enum

---

crates/compiler/gen_llvm/src/llvm/refcounting.rs
crates/compiler/test_gen/src/gen_tags.rs

Make sure to bump index of nullable-wrapped tag indices after null variants

---

examples/parser/Parser/Core.roc
examples/parser/Parser/Http.roc
examples/parser/parse-movies-csv.roc

Renaming this function so it looks better in pipelines
@rtfeldman suggested this in https://github.com/roc-lang/roc/pull/4858

Parser: rename apply->keep

---

crates/compiler/mono/src/decision_tree.rs
crates/compiler/mono/src/ir.rs
crates/compiler/test_gen/src/gen_primitives.rs
crates/compiler/test_mono/generated/pattern_as_nested.txt
crates/compiler/test_mono/generated/pattern_as_of_symbol.txt
crates/compiler/test_mono/generated/pattern_as_toplevel.txt
crates/compiler/test_mono/src/tests.rs

the special `[ first, .. as rest ]` list pattern is not yet implemented.

implement standard as patterns in mono IR

---

crates/compiler/solve/src/solve.rs

@folkertdev let me know if these wordings are clearer, I tried to address everything from the last review

Rephrase solve comments as per Folkert's review

---

examples/parser/Parser/Core.roc

shaves 1 second off of the HTTP parser tests

optimize Parser.Core

---

crates/compiler/parse/src/expr.rs
crates/compiler/test_syntax/tests/snapshots/pass/multi_backpassing_in_def.moduledefs.formatted.roc
crates/compiler/test_syntax/tests/snapshots/pass/multi_backpassing_in_def.moduledefs.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/multi_backpassing_in_def.moduledefs.roc
crates/compiler/test_syntax/tests/test_snapshots.rs

Fix multi-backpassing in top-level defs

---

.github/workflows/basic_cli_build_release.yml
.github/workflows/nightly_linux_x86_64.yml
.github/workflows/nightly_macos_apple_silicon.yml
.github/workflows/nightly_macos_x86_64.yml
.github/workflows/test_nightly_macos_apple_silicon.yml
.github/workflows/test_nightly_many_os.yml
ci/build_basic_cli.sh
ci/package_release.sh
www/build.sh

This is nicer for users and also makes things easier for cross-platform compatibility.

untar now creates single dir

---

crates/cli/tests/cli_run.rs
crates/compiler/test_gen/src/gen_tags.rs
crates/compiler/test_mono/generated/instantiate_annotated_as_recursive_alias_multiple_polymorphic_expr.txt
crates/compiler/test_mono/src/tests.rs

Need to ignore `hello` GUI example until https://github.com/roc-lang/roc/issues/4919 is resolved.

Fix a few tests that are failing on trunk

---

crates/compiler/builtins/bitcode/src/str.zig
crates/valgrind/src/lib.rs

fix memory leak in string trimming

---

crates/compiler/test_gen/src/gen_abilities.rs
crates/compiler/test_mono/generated/issue_4772_weakened_monomorphic_destructure.txt
crates/compiler/test_mono/generated/weakening_avoids_overspecialization.txt
crates/compiler/test_mono/src/tests.rs

Add some regression tests for problems weakening solves

---

crates/compiler/builtins/bitcode/src/list.zig
crates/compiler/builtins/bitcode/src/str.zig
crates/valgrind/src/lib.rs

use capacity instead of length in list deinit

---

.github/workflows/nix_store_cleanup.yml

Clean up the nix store once a week to prevent the disk from getting full.

added nix store gc job

---

crates/linker/src/metadata.rs
mlc_config.json
www/generate_tutorial/src/input/tutorial.md

Also added a better error message for #4948
Closes #4948

update tutorial basic-cli release

---

examples/static-site-gen/platform/src/lib.rs
www/generate_tutorial/src/input/tutorial.md
www/public/site.css

Some miscellaneous edits to the tutorial.

Tutorial Edits

---

crates/compiler/builtins/bitcode/src/str.zig
crates/compiler/test_gen/src/gen_str.rs

fix bug in Str.trim

---

crates/compiler/builtins/bitcode/src/str.zig
crates/compiler/test_gen/src/gen_str.rs

fix string split on overlapping delimiters

---

crates/packaging/src/cache.rs

Error for dynamically linked platforms on NixOS

---

www/generate_tutorial/src/input/tutorial.md

Closes #4634 
@Anton-4 request your review.

Adding Opaque types to Tutorial

---

.cargo/config
crates/cli/tests/cli_run.rs

Also fixes segmentation fault in gen_tags

ignore breakout test on windows

---

crates/compiler/builtins/roc/Dict.roc
crates/compiler/fmt/src/annotation.rs
crates/compiler/test_syntax/tests/test_fmt.rs

Closes https://github.com/roc-lang/roc/issues/4327.
I didn't see this issue was already assigned, I've searched on zulip but I didn't find anything.
I hope this PR is still welcomed.

Add spaces around ? in optional record field

---

crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/convert.rs

fix for when C has to return an empty tag union

---

crates/compiler/fmt/src/collection.rs
crates/compiler/fmt/src/def.rs
crates/compiler/test_syntax/tests/snapshots/pass/fn_with_record_arg.expr.formatted.roc
crates/compiler/test_syntax/tests/snapshots/pass/fn_with_record_arg.expr.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/fn_with_record_arg.expr.roc
crates/compiler/test_syntax/tests/test_snapshots.rs

Fix formatting of initial newlines in collections

---

crates/compiler/gen_llvm/src/llvm/refcounting.rs
crates/compiler/test_gen/src/gen_tags.rs

It's possible to have a nullable unwrapped code where the only material payload does not need refcounting operations. In this case the refcounting function is the trivial one.

Handle case where only other tag of nullable unwrapped needs no refcount

---

www/generate_tutorial/src/input/tutorial.md

@Anton-4  the last three of these I believe.

Tutorial: add 3 more spaces before colons

---

crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/module/src/symbol.rs
crates/compiler/test_gen/src/gen_list.rs
crates/compiler/test_gen/src/gen_primitives.rs
crates/compiler/test_gen/src/gen_records.rs
crates/compiler/test_gen/src/gen_str.rs
crates/compiler/test_mono/generated/anonymous_closure_in_polymorphic_expression_issue_4717.txt
crates/compiler/test_mono/generated/dict.txt
crates/compiler/test_mono/generated/encode_derived_nested_record_string.txt
crates/compiler/test_mono/generated/encode_derived_record_one_field_string.txt
crates/compiler/test_mono/generated/encode_derived_record_two_field_strings.txt
crates/compiler/test_mono/generated/encode_derived_tag_one_field_string.txt
crates/compiler/test_mono/generated/encode_derived_tag_two_payloads_string.txt
crates/compiler/test_mono/generated/weakening_avoids_overspecialization.txt

that in turn enables a bunch more functions and tests

dev backend: reading and writing 32, 16 and 8-bit values

---

www/generate_tutorial/src/input/tutorial.md

Thank you @Arkham for pointing this out.

Correct all uses of `Bool.true` and `Bool.false` in Tutorial

---

crates/compiler/builtins/roc/Num.roc
crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/test_gen/src/gen_num.rs
crates/compiler/test_gen/src/gen_result.rs

- 128-bit literals
- float comparisons
- float sqrt and natural logarithm

gen-dev: num additions

---

.github/workflows/nix_macos_x86_64.yml

Cachix was erroring and did not significantly speed things up, so I removed it.

remove cachix

---

crates/compiler/mono/src/inc_dec.rs

Make List.mapN properly add all decrefs

---

crates/compiler/parse/src/highlight.rs
examples/static-site-gen/output/style.css
examples/static-site-gen/platform/src/highlight.rs

Discovered a bug while converting more of the tutorial across to markdown. This PR is a fix for that, and add a test to mitigate regression.
@joshuawarner32 could you please review?

Fix bug for static-site syntax highlighting

---

crates/compiler/builtins/bitcode/src/str.zig

fixes #5075
The real change is just making all of the functions check for an empty string at the beginning. If so, they deinit the string and return an empty string. This gets rid of any allocations to prevent a memory leak.  I also made all of the three functions have the same structure. Most of the change is just removing an indent.
Note: if wanted, we could instead return the input string if it is empty. That would preserve the capacity of an empty string that is passed into `Str.trim*`. Given the string if fully empty, I feel like it is fine to dealloc and return a small string.

[Simple PR] fix mem leak in Str.trim and make all Str.trim* functions consistent

---

crates/compiler/parse/src/highlight.rs

This (I believe) brings us in line with the complete set of operators supported in Roc.

Produce combined tokens directly and add a few operators

---

examples/static-site-gen/platform/src/highlight.rs

I can't push to @joshuawarner32's PR #5090 on remote so I created this to fix static-site and tutorial formatting for that change.
I also tested this against Roc tutorial using a URL build.

Fix for static-site for highlight token changes.

---

examples/static-site-gen/platform/src/lib.rs

This PR adds support for recursive input folders so that this platform can process `.md` files within folders. 
It also updates functionality to ignore non-`.md` files and only process valid targets.

Add support for recursive folders in `examples/static-site-gen` platform

---

crates/docs/src/static/search.js
crates/docs/src/static/styles.css
www/public/site.css
www/public/site.js

I have added a copy button to code blocks in response to issue #5137 . The copy button only shows up on hover
Screenshots below

added copy button to tutorial code blocks

---

crates/docs/src/static/search.js
crates/docs/src/static/styles.css
www/public/site.css
www/public/site.js

* Fixed css that the copy button will scroll with code block
* Added mobile support for copy button
* Clicking the code block brings up the copy button

fix mobile support for button container

---

crates/compiler/test_gen/src/helpers/debug-wasm-test.html
crates/docs/src/static/styles.css
www/build.sh
www/public/site.css

@lukewilliamboswell I've made some small changes here:
- Removed the grey border, it looks cleaner without. [Relevant tweet about borders](https://twitter.com/erikdkennedy/status/1546530126900260864?s=20)
- Removed all border-radius. It's kind of a general design rule to make a design fit with your logo and our logo has straight lines and sharp corners.
- The API function and types like `isEmpty` and `concat` had the same background color as the code snippets. They're very different things so I'd like them to be easily distinguishable. This reasoning is based on [the squint test](https://www.learnui.design/blog/squint-test-ui-design-case-study.html). I'm not yet completely satisfied with my solution but I just wanted to make some quick improvements.
If you're interested in UI design, I …

some style changes

---

www/generate_tutorial/src/input/tutorial.md

Fix typo in walk tutorial

---

crates/repl_eval/src/eval.rs
crates/repl_test/src/tests.rs

Support tuples in the repl

---

crates/compiler/derive_key/src/decoding.rs
crates/compiler/derive_key/src/encoding.rs
crates/compiler/test_gen/src/gen_abilities.rs
crates/compiler/types/src/num.rs

Ranged number abilities are derived and compiled correctly

---

crates/repl_eval/src/eval.rs
crates/repl_test/src/tests.rs

Fix repl eval of Str.toDec

---

crates/compiler/derive_key/src/decoding.rs
crates/compiler/derive_key/src/encoding.rs
crates/compiler/derive_key/src/hash.rs
crates/compiler/derive_key/src/lib.rs
crates/compiler/late_solve/src/lib.rs
crates/compiler/mono/src/ir.rs
crates/compiler/solve/src/ability.rs
crates/compiler/solve/src/solve.rs
crates/compiler/solve/src/specialize.rs
crates/compiler/solve/tests/solve_expr.rs
crates/compiler/test_derive/src/encoding.rs
crates/compiler/test_gen/src/gen_abilities.rs

Now, `Bool` correctly implements Encode and Decode.

Fix Encode/Decode ability implementations for Bool

---

crates/compiler/solve/src/solve.rs
crates/reporting/tests/test_reporting.rs

Make sure openness constraint goes under tuples

---

crates/compiler/test_mono/generated/recursive_function_and_union_with_inference_hole.txt
crates/compiler/test_mono/src/tests.rs

Check in mono test that works now

---

crates/compiler/mono/src/layout.rs
crates/glue/src/RustGlue.roc
crates/glue/src/types.rs
crates/glue/tests/fixtures/advanced-recursive-union/platform.roc
crates/glue/tests/fixtures/advanced-recursive-union/src/lib.rs
crates/glue/tests/fixtures/basic-recursive-union/platform.roc
crates/glue/tests/fixtures/basic-recursive-union/src/lib.rs
crates/glue/tests/fixtures/nullable-unwrapped/platform.roc
crates/glue/tests/fixtures/nullable-unwrapped/src/lib.rs
crates/glue/tests/fixtures/nullable-wrapped/platform.roc
crates/glue/tests/fixtures/nullable-wrapped/src/lib.rs
crates/glue/tests/fixtures/union-with-padding/src/lib.rs
crates/glue/tests/test_glue_cli.rs
crates/roc_std/src/roc_box.rs

all current glue tests now pass

Glue recursive tag unions

---

crates/compiler/builtins/bitcode/src/dec.zig

Fixed dec division that envolves a number that has a hi word greater than 0 when converted into `U256` like `341dec / 341`.
This PR resolves #5259

Fix dec division problem

---

crates/compiler/test_gen/Cargo.toml
crates/compiler/test_gen/benches/list_map.rs
crates/compiler/test_gen/benches/quicksort.rs

make the list_map benchmark compile again

---

Cargo.lock
crates/valgrind/Cargo.toml
crates/valgrind/src/lib.rs

examples are by @JTeeuwissen. we needed a bit more flexibility in the tests, to allow toplevel definitions.

add extra valgrind tests

---

crates/repl_expect/src/lib.rs

Add reproducer for bug that's fixed now

---

crates/compiler/builtins/roc/Decode.roc

Add documentation for `Decode` builtin

---

crates/repl_eval/src/eval.rs
crates/repl_expect/src/lib.rs

Correct repl evaluation of toplevel numbers

---

crates/wasm_interp/src/wasi.rs

we need this to print messages when debugging refcounting tests

implement fd_fdstat_get

---

crates/wasm_interp/src/wasi.rs

As suggested by @folkertdev in #5293

Make WASI use write_all instead of write, and handle IO errors

---

crates/roc_std/src/lib.rs
crates/roc_std/tests/test_roc_std.rs

Support underscores in Dec numbers

---

crates/compiler/build/src/link.rs
crates/utils/command/src/lib.rs

switch checking for str.zig to be relative to the exectuable

---

crates/compiler/builtins/bitcode/src/main.zig
crates/compiler/builtins/bitcode/src/str.zig
crates/compiler/builtins/roc/List.roc
crates/compiler/builtins/src/bitcode.rs
crates/compiler/can/src/builtins.rs
crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_dev/src/object_builder.rs
crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/gen_wasm/src/low_level.rs
crates/compiler/module/src/low_level.rs
crates/compiler/mono/src/borrow.rs
crates/compiler/mono/src/code_gen_help/mod.rs
crates/compiler/mono/src/layout/intern.rs
crates/compiler/test_gen/src/gen_list.rs
crates/compiler/test_gen/src/gen_num.rs
crates/compiler/test_gen/src/gen_str.rs
crates/compiler/test_gen/src/gen_tags.rs
crates/compiler/test_gen/src/helpers/dev.rs

and other stuff required for running `RustGlue.roc`. we cannot run that file yet, and I've cut some corners here. But I think this is in a good state to merge, and we can do the full implementation later.

Dev backend list map

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/lib.rs
crates/cli/src/main.rs
crates/compiler/build/src/program.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_dev/src/object_builder.rs
crates/compiler/mono/src/layout.rs
crates/compiler/test_gen/src/helpers/dev.rs
crates/glue/src/load.rs

running glue with the dev backend. Also makes `exposed_generic` available, which makes many more examples build with the dev backend

Dev backend glue

---

crates/repl_eval/src/eval.rs
crates/repl_test/src/tests.rs

Fix repl evaluation of tuples

---

examples/nodejs-interop/wasm/hello.js

Now uses synchronous APIs instead of async and callbacks

Simplify wasm NodeJS example

---

crates/compiler/debug_flags/src/lib.rs
crates/compiler/types/src/subs.rs
crates/compiler/unify/src/unify.rs

See individual commits.
Closes #5330

Correct occurs cycle under alias argument but not alias real var

---

crates/compiler/build/src/program.rs
crates/compiler/builtins/bitcode/src/utils.zig
crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_dev/src/object_builder.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/mono/src/code_gen_help/mod.rs
crates/compiler/mono/src/code_gen_help/refcount.rs
crates/compiler/test_gen/src/gen_list.rs
crates/compiler/test_gen/src/gen_refcount.rs

I think the only missing things are more higher-order lowlevels, and then some various tests that cause segfaults. So much does already work though!
also fixes a bunch of bugs around use of float registers, and a bug in the dev/wasm refcounting: I changed some logic there before which skipped a recursive increment on lists, which the whole system does rely on.

Dev backend list tests

---

getting_started/linux_x86_64.md

I had improved this earlier for the macos getting started files but not for linux

use better zig install instructions

---

crates/compiler/builtins/bitcode/src/utils.zig
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_dev/src/object_builder.rs
crates/compiler/mono/src/code_gen_help/refcount.rs
crates/wasm_interp/src/instance.rs
crates/wasm_interp/src/lib.rs

Add support for reference counting seamless slices in the dev backends.

Dev refcount seamless slice

---

crates/cli/src/lib.rs

I added the absolute path for the current directory and the expected `.roc` to the diagnostic print.

Fixes issue #5394

---

crates/compiler/can/src/operator.rs
crates/compiler/can/tests/test_can.rs

Fixes an [issue](https://github.com/roc-lang/roc/pull/5389/files#r1193059159) pointed out by @ayazhafiz about record builder closure patterns potentially shadowing symbols in scope.
The generated closure `Pattern:Identifier`s will now use the name of the field prefixed by `#`, which makes it impossible to conflict with a symbol in the surface syntax. 
This allows code like this to compile:
```elm
number = "42"
succeed { 
number <- parse number,
raw: number,
}
```
@ayazhafiz suggested the `#` approach but also mentioned:
> Another way is to relay to the canonicalizer that these transformations do not shadows from the surface syntax.
That's what I started with, but then I realized that even though that would make the shadowing error go away, the symbol would still be shadowed and that might …

Prevent record builder field names from shadowing other symbols

---

crates/compiler/alias_analysis/src/lib.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_llvm/src/llvm/bitcode.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/compare.rs
crates/compiler/gen_llvm/src/llvm/convert.rs
crates/compiler/gen_llvm/src/llvm/expect.rs
crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/gen_llvm/src/llvm/refcounting.rs
crates/compiler/gen_wasm/src/backend.rs
crates/compiler/gen_wasm/src/low_level.rs
crates/compiler/mono/src/code_gen_help/equality.rs
crates/compiler/mono/src/code_gen_help/mod.rs
crates/compiler/mono/src/code_gen_help/refcount.rs
crates/compiler/mono/src/debug/checker.rs
crates/compiler/mono/src/drop_specialization.rs
crates/compiler/mono/src/ir.rs
crates/compiler/mono/src/ir/decision_tree.rs
crates/compiler/mono/src/layout.rs
crates/compiler/mono/src/layout/intern.rs
crates/glue/src/types.rs
crates/repl_eval/src/eval.rs

Depends on #5395
Part of #5354

Simplify record layout

---

crates/compiler/test_gen/src/gen_abilities.rs
crates/compiler/test_mono/src/tests.rs

[Context](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Test.20failures.20in.20gen_abilities.20after.20Json.20updates)

Disable some tests in debug failing with stack overflow

---

crates/cli_testing_examples/benchmarks/CFold.roc
crates/cli_testing_examples/benchmarks/Deriv.roc
crates/cli_testing_examples/benchmarks/NQueens.roc
crates/cli_testing_examples/benchmarks/QuicksortApp.roc
crates/cli_testing_examples/benchmarks/RBTreeCk.roc
crates/cli_testing_examples/benchmarks/RBTreeDel.roc
crates/cli_testing_examples/benchmarks/platform/Task.roc

improve benchmark error handling, bugfixes

---

crates/compiler/mono/src/drop_specialization.rs

fixes https://github.com/roc-lang/roc/issues/5430

updated drop_specialization for boxes

---

crates/compiler/gen_llvm/src/llvm/compare.rs
crates/compiler/test_gen/src/gen_tags.rs
crates/compiler/test_gen/src/helpers/llvm.rs

Correct tag ID matching of nullable wrapped tags

---

crates/compiler/can/src/annotation.rs
crates/compiler/constrain/src/pattern.rs
crates/compiler/uitest/tests/exhaustive/open_union_under_record.txt
crates/compiler/uitest/tests/exhaustive/open_union_under_tuple.txt

Implement openness constraints under records

---

crates/compiler/uitest/tests/solve/tuple_annotation.txt

Add test for tuple annotations

---

Cargo.lock
Cargo.toml
crates/editor/Cargo.toml
default.nix
examples/gui/breakout/platform/Cargo.toml
examples/gui/platform/Cargo.toml

confy is currently not used by the editor and it was giving problems on macos so I removed it

ditch confy

---

crates/compiler/builtins/bitcode/src/dec.zig

Also changes some zig panics to returning null. This will turn into the default num conversion error.

fix segfault in Num.toStr for Dec

---

crates/error_macros/src/lib.rs

Unless this is an inside joke that I am not aware of 😅

Fix small typo on user_error macro

---

crates/packaging/src/https.rs

Disallow @ and slash lookalikes on package url

---

crates/compiler/mono/src/inc_dec.rs

fixes https://github.com/roc-lang/roc/issues/5508

removed refcount type from proc

---

Cargo.lock
crates/compiler/load_internal/src/file.rs
crates/reporting/Cargo.toml
crates/reporting/src/report.rs

This is an initial proposal for the strategy on how to display nice error messages for HTTPS related errors
This is related to #5487

Nice messages for https errors

---

crates/ast/src/lang/env.rs
crates/ast/src/lang/scope.rs
crates/compiler/can/src/env.rs
crates/compiler/can/src/expr.rs
crates/compiler/can/src/pattern.rs
crates/compiler/can/src/scope.rs
crates/compiler/can/tests/test_can.rs
crates/compiler/fmt/src/spaces.rs
crates/compiler/parse/src/ident.rs
crates/compiler/problem/src/can.rs
crates/compiler/test_syntax/tests/snapshots/malformed/malformed_ident_due_to_underscore.expr.result-ast
crates/compiler/test_syntax/tests/snapshots/malformed/underscore_expr_in_def.expr.result-ast
crates/reporting/src/error/canonicalize.rs
crates/reporting/tests/test_reporting.rs

To see the improved error messages, see the tests added in `crates/reporting/tests/test_reporting.rs`
Fixes #3987

Improve some error messages involving ignored variables

---

crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/test_gen/src/gen_num.rs

Correctly compile add/sub/mulChecked for Dec

---

crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/mono/src/code_gen_help/equality.rs
crates/compiler/mono/src/ir/decision_tree.rs
crates/compiler/test_gen/src/gen_primitives.rs
crates/compiler/test_gen/src/gen_tags.rs

final bits of recursive tag unions, I think. There are still some issues with some recursive lambda sets, but I don't think the issue is in the tag union part of that logic? it's tricky, because those examples get pretty big and complicated.

Dev backend recursive tag unions

---

crates/compiler/load_internal/src/file.rs
crates/compiler/mono/src/drop_specialization.rs
crates/compiler/mono/src/reset_reuse.rs

fixes https://github.com/roc-lang/roc/issues/5547

Index array symbols unknown symbols

---

crates/compiler/mono/src/ir.rs
crates/compiler/test_mono/generated/dbg_str_followed_by_number.txt
crates/compiler/test_mono/src/tests.rs

Use correct variable when compiling dbg continuation

---

crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/convert.rs
crates/compiler/roc_target/src/lib.rs

- Address Folkert's comments
- Get rid of a useless load/store

Fast-follow on LLVM pass-by-reference

---

www/generate_tutorial/src/input/tutorial.md

add missing example

---

crates/compiler/builtins/roc/List.roc

Created with #5096 in mind. Made examples have assertions in them for clarity, which should be a standard imho.

Add examples to the docs of builtin List functions 

---

README.md

Also changed mentions of "Zulip chat" to "group chat", most people won't be familiar with Zulip

link to examples

---

crates/repl_eval/src/eval.rs
crates/repl_test/src/tests.rs

Correctly interpret reordered tag union payloads

---

www/public/repl/index.html

I have added the paragraph.
Do let me know if there are any changes to be done in it. Thanks!

added-para

---

examples/webserver/.gitignore
examples/webserver/Http.roc
examples/webserver/HttpInternal.roc
examples/webserver/build.sh
examples/webserver/main.roc
examples/webserver/platform/Cargo.toml
examples/webserver/platform/build.rs
examples/webserver/platform/host.c
examples/webserver/platform/main.roc
examples/webserver/platform/src/lib.rs
examples/webserver/platform/src/main.rs

Doesn't do much yet, but all the wiring is there.

Add basic webserver platform

---

crates/cli/tests/fixtures/multi-dep-str/platform/host.zig
crates/cli/tests/fixtures/multi-dep-thunk/platform/host.zig
crates/cli/tests/fixtures/packages/platform/host.zig
crates/cli_testing_examples/algorithms/fibonacci-platform/host.zig
crates/cli_testing_examples/algorithms/quicksort-platform/host.zig
crates/cli_testing_examples/benchmarks/platform/host.zig
crates/cli_testing_examples/expects/zig-platform/host.zig
crates/compiler/build/src/link.rs
crates/compiler/build/src/target.rs
crates/compiler/builtins/bitcode/src/compiler_rt.zig
crates/linker/src/pe.rs
crates/valgrind/zig-platform/host.zig
examples/cli/effects-platform/host.zig
examples/cli/tui-platform/host.zig
examples/platform-switching/zig-platform/host.zig

remove old compiler-rt workarounds for macos.

Compiler-rt cleanup macos

---

crates/compiler/mono/src/layout.rs
crates/compiler/test_mono/generated/capture_void_layout_task.txt
crates/compiler/test_mono/src/tests.rs
crates/compiler/types/src/subs.rs

Do not drop uninhabited captures from lambda sets 

---

examples/parser/Parser/Str.roc
examples/parser/package/ParserStr.roc

Fixes a bug in the parser example. See [this discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Parser.20example.20digits)

Rename digits parser to positiveInt and fix bug

---

README.md

Someone missed the group chat link in the README, so I'm trying to make it stand out more

readme visibility

---

flake.nix

Please let me know if you have any questions.

Added aliases for clippy and fmt to flake.nix

---

crates/glue/src/RustGlue.roc

We were passing arguments like `RocStr` from Rust over to Roc without wrapping them in `ManuallyDrop` (or, alternatively, calling `mem::forget` on them after the Roc call finished - but this is a less error-prone way to do it), which led to double-frees because Roc would free them and then later Rust would try to drop the RocStr and free it again.

Use ManuallyDrop to fix ownership bug in RustGlue

---

crates/cli_testing_examples/benchmarks/Deriv.roc
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/gen_llvm/src/llvm/refcounting.rs
crates/compiler/gen_wasm/src/backend.rs
crates/compiler/gen_wasm/src/low_level.rs
crates/compiler/mono/src/borrow.rs
crates/compiler/mono/src/code_gen_help/refcount.rs
crates/compiler/mono/src/layout.rs
crates/compiler/mono/src/layout/intern.rs

Not checking caused a memory leak

check inside a lambda set for whether it is reference counted

---

.github/workflows/windows_tests.yml
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/gen_dev/src/object_builder.rs
crates/compiler/test_gen/src/helpers/dev.rs

shared work with @lukewilliamboswell

Dev backend roc panic windows

---

crates/compiler/checkmate/www/package-lock.json
crates/compiler/checkmate/www/package.json
crates/compiler/checkmate/www/src/App.tsx
crates/compiler/checkmate/www/src/components/Common/EpochCell.tsx
crates/compiler/checkmate/www/src/components/EventItem/Variable.tsx
crates/compiler/checkmate/www/src/components/EventItem/types.ts
crates/compiler/checkmate/www/src/components/EventList.tsx
crates/compiler/checkmate/www/src/components/Events/index.ts
crates/compiler/checkmate/www/src/components/Graph/VariableNode.tsx
crates/compiler/checkmate/www/src/components/Graph/VariablesGraph.tsx
crates/compiler/checkmate/www/src/components/Ui.tsx
crates/compiler/checkmate/www/src/engine/engine.tsx
crates/compiler/checkmate/www/src/engine/subs.tsx

Adds a bunch of improvements.
This is coming along very nicely and is already a lot useful for analyzing the basis bug than it was 2 weeks ago 😅 I'd like to add a few more utilities before calling it and getting back to fixing bugs with this tool:
- Clean up the representation of types/variables
- Fix the loading of default variables. As you can see, they are currently missing.
- Add support for viewing two epochs at once. This is crucial for seeing what changed over a unification.
- Add support for viewing the root key of a variable. Right now this is invisible.
- Add basic support for listing constraints unifications arise as a result of.
- Publish this on a publicly visitable static site.
https://github.com/roc-lang/roc/assets/20735482/2fc41fe8-eebc-430a-bac4-2b79befc67cb

Checkmate UI improvements

---

www/public/repl/repl.css

#5724: fix css to fit content on full page without scroll

---

www/build.sh

The old request got rate limited sometimes so I used a token now.
I tried this before and it didn't work but now it does :shrug:
I also added `-v` to be able to debug this easier if it does fail.

use token with curl

---

mlc_config.json
www/build.sh
www/wip_new_website/build.roc
www/wip_new_website/content/community.md
www/wip_new_website/content/docs.md
www/wip_new_website/content/index.md
www/wip_new_website/content/install.md
www/wip_new_website/content/tutorial.md
www/wip_new_website/main.roc
www/wip_new_website/static/site.css

Spent some more time tinkering with the WIP site update. Still a lot more to do, but I wanted to get something that looks more acceptable.

More updates to wip site update

---

crates/compiler/build/src/link.rs
crates/compiler/test_gen/benches/list_map.rs
crates/compiler/test_gen/benches/quicksort.rs
flake.nix

fix `Couldn't find libgcc_s.so.1!`

---

www/build.sh

the new-abilities-syntax branch has been merged into basic-cli main

use basic-cli main branch again

---

crates/compiler/builtins/roc/Dict.roc
crates/compiler/builtins/roc/Set.roc
www/wip_new_website/main.roc

Remove some Dict and Set ability constraints

---

default.nix

I did this earlier in flake.nix but forgot about default.nix

set NIX_LIBGCC_S_PATH in default.nix too

---

CONTRIBUTING.md
devtools/signing.md

Some restructuring, small improvements and instructions for how to transfer your key from linux to windows when you are using a yubikey.

Updated commit signing guide

---

Cargo.lock
crates/compiler/parse/Cargo.toml
crates/compiler/parse/src/lib.rs
crates/compiler/parse/src/src64.rs

This is in preparation for caching and also SIMD parsing.
We don't use it for anything yet; this is just a checkpoint PR!

Add parser/Src64

---

crates/compiler/builtins/roc/Num.roc

Added some benchmarks, clarifications, etc.

Update Dec docs some more

---

.github/workflows/nix_macos_apple_silicon.yml
crates/compiler/gen_dev/src/generic64/aarch64.rs
crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/generic64/storage.rs
crates/compiler/gen_dev/src/generic64/x86_64.rs
crates/compiler/test_gen/src/gen_num.rs

all of gen_num should now work on aarch64 dev backend

AArch64 gen_num + gen_records tests

---

getting_started/linux_x86_64.md
getting_started/macos_apple_silicon.md
getting_started/macos_x86_64.md
getting_started/windows.md

fix(getting_started): Updated file names in installation examples

---

www/generate_tutorial/src/tutorial.roc
www/public/repl/index.html

We've had a docs index page for a while so there's no need to link to Bool anymore :)

no need to link to Bool anymore

---

examples/static-site-gen/platform/src/lib.rs

fix #5772
we can do better than this with glue eventually. This is correct at least

explicitly RocBox arguments when received as box

---

crates/compiler/arena_pool/src/pool.rs
crates/compiler/can/src/exhaustive.rs
crates/compiler/collections/src/soa.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/ident/src/lib.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/load_internal/src/work.rs
crates/compiler/mono/src/ir.rs
crates/compiler/mono/src/layout.rs
crates/compiler/parse/src/parser.rs
crates/compiler/test_solve_helpers/src/lib.rs
crates/compiler/types/src/subs.rs
crates/compiler/uitest/src/uitest.rs
crates/compiler/unify/src/unify.rs

fixes clippy warnings for rust 1.73

Clippy 1.73

---

crates/compiler/build/src/target.rs

The current behavior has the unintended consequence of (for example) building with `CodeModel::Large` when cross-compiling on a Mac, even when the target is something other than Mac. That in turn causes a strange linker error where it complains about PIC.
This fixes it!

Choose CodeModel using roc target, not Rust target

---

crates/compiler/builtins/roc/Str.roc
crates/compiler/module/src/symbol.rs
crates/compiler/test_gen/src/gen_str.rs
crates/compiler/test_mono/generated/compose_recursive_lambda_set_productive_nullable_wrapped.txt
crates/compiler/test_mono/generated/encode_derived_nested_record_string.txt
crates/compiler/test_mono/generated/encode_derived_record_one_field_string.txt
crates/compiler/test_mono/generated/encode_derived_record_two_field_strings.txt
crates/compiler/test_mono/generated/encode_derived_string.txt
crates/compiler/test_mono/generated/encode_derived_tag_one_field_string.txt
crates/compiler/test_mono/generated/encode_derived_tag_two_payloads_string.txt
crates/compiler/test_mono/generated/issue_2583_specialize_errors_behind_unified_branches.txt
crates/compiler/test_mono/generated/issue_4749.txt
crates/compiler/test_mono/generated/issue_4772_weakened_monomorphic_destructure.txt
crates/compiler/test_mono/generated/list_map_closure_borrows.txt
crates/compiler/test_mono/generated/list_map_closure_owns.txt
crates/compiler/test_mono/generated/polymorphic_expression_unification.txt
crates/compiler/test_mono/generated/recursively_build_effect.txt
crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_does_not_duplicate_identical_concrete_types.txt
crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_keeps_all_concrete_types_without_unification_of_unifiable.txt

Add Str.contains to builtins

---

getting_started/README.md
getting_started/macos_apple_silicon.md
getting_started/macos_x86_64.md

using curl prevents the `roc can't be opened because Apple cannot check it...`

improve macos getting started

---

crates/packaging/src/cache.rs

This fixes some race conditions that result in an "already exists" I/O error that we don't care about because the file that already exists has the contents that we want anyway.
I ran into this after running `cargo test` (several tests were trying to download the same basic-cli version and one of them failed with "already exists")

Make downloading packages more resilient

---

www/public/repl/repl.js
www/wip_new_website/InteractiveExample.roc
www/wip_new_website/content/index.md
www/wip_new_website/main.roc
www/wip_new_website/static/repl.css
www/wip_new_website/static/site.css
www/wip_new_website/static/site.js

Some homepage fixes

---

www/wip_new_website/content/tutorial.md
www/wip_new_website/static/site.css

This PR adds the Tutorial Table of Contents with some styling so that it looks ok and various screen sizes

WIP site updates

---

www/wip_new_website/content/bdfn.md
www/wip_new_website/content/community.md
www/wip_new_website/content/donate.md
www/wip_new_website/content/index.md
www/wip_new_website/content/install.md
www/wip_new_website/static/site.css

Also /install, /community, /bdfn, and /donate

Tweak WIP homepage copy

---

crates/docs/src/lib.rs
crates/repl_cli/src/lib.rs
www/generate_tutorial/src/input/tutorial.md
www/public/repl/index.html
www/wip_new_website/content/tutorial.md
www/wip_new_website/main.roc
www/wip_new_website/static/site.css
www/wip_new_website/static/site.js

Now looks basically like the current one, except with the new header bar and with a more comfortable width.

Update WIP tutorial

---

www/optimize.sh

Fix typo in optimize.sh

---

www/content/abilities.md
www/content/docs.md

This PR 
- Adds a section for Abilities to the roc Language Reference
Fix #6016

Add Abilities language reference

---

ci/build_basic_cli.sh
ci/build_basic_webserver.sh

https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/basic-cli.20reqwest.20lib.20size/near/403696559

optimize basic platform builds

---

README.md
www/content/docs.md
www/content/plans.md

[Rendered](https://github.com/roc-lang/roc/blob/plan/www/content/plans.md)

Add /plans

---

.github/workflows/ci_cleanup.yml
.github/workflows/ci_cleanup_nix_mac.yml

Temporary patch solution for https://github.com/roc-lang/roc/issues/6106

add daily nix cleanup workflow

---

crates/compiler/test_mono/generated/inspect_derived_dict.txt
crates/compiler/test_mono/generated/inspect_derived_list.txt
crates/compiler/test_mono/generated/inspect_derived_nested_record_string.txt
crates/compiler/test_mono/generated/inspect_derived_record.txt
crates/compiler/test_mono/generated/inspect_derived_record_one_field_string.txt
crates/compiler/test_mono/generated/inspect_derived_record_two_field_strings.txt

Somehow these made it into `main` in a broken state

Fix mono tests

---

examples/README.md

The examples from the dedicated repo are probably what most people want.

link to examples repo

---

crates/cli/tests/cli_run.rs
crates/cli_testing_examples/.gitignore
crates/cli_testing_examples/expects/expects.roc
crates/repl_expect/src/app.rs
crates/repl_wasm/src/repl.rs

Just was a missing case for seamless slices.

Support seamless slice in expects

---

CONTRIBUTING.md

No need to slow every new contributor down with #6100

use `--release` for tests

---

www/build-dev-local.sh

Addresses https://github.com/roc-lang/roc/issues/6079

restore simple-http-server

---

www/content/tutorial.md

Fixing _good first issue_ #6223

added [head, .. as tail] pattern matching example to tutorial

---

crates/reporting/src/error/parse.rs

Handle TrailingOperator parse error

---

crates/compiler/builtins/roc/Dict.roc
crates/compiler/builtins/roc/Set.roc
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/module/src/symbol.rs
crates/compiler/test_mono/generated/dict.txt
crates/compiler/test_mono/generated/inspect_derived_dict.txt
crates/compiler/uitest/tests/ability/specialize/set_eq_issue_4761.txt

Just addressing some comments from the last PR and adding a function.

Dict follow up and addition of releaseExcessCapacity

---

crates/compiler/gen_llvm/src/llvm/build.rs

I won't claim to know why `__muloti4` is special, but none of the other compiler-rt functions are. This seems to work and stop tests from hanging.
It also enables early DCE again which saves a tiny bit of compile time.

 Re-enable early DCE with fix for M1 mac

---

.github/workflows/nix_linux_x86_64.yml
.github/workflows/nix_macos_apple_silicon.yml
.github/workflows/nix_macos_x86_64.yml
.github/workflows/ubuntu_x86_64.yml
ci/roc_test_builtins.sh

We only used to test Dict.roc and Str.roc before

roc test all builtins

---

crates/lang_srv/README.md

The language server binary is now included with the nightly, so I updated the docs.

Update roc_ls docs

---

www/content/faq.md

Fixes bad formatting #6306
I my opinion there is no issue with people not knowing what FAQ means here. That is mainly relevant for the name of the link to this page.

Shorten faq titlte

---

.github/workflows/basic_cli_build_release.yml
ci/build_basic_cli.sh

- now using git tags
- renamed src folder to platform
- docs are generated in this workflow instead of needing to do it manually

basic-cli 0.7.1 release

---

ci/update_basic_cli_url.sh
crates/cli/tests/cli_run.rs
crates/compiler/test_syntax/tests/snapshots/pass/newline_in_packages.full.formatted.roc
crates/compiler/test_syntax/tests/snapshots/pass/newline_in_packages.full.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/newline_in_packages.full.roc
examples/cli/argsBROKEN.roc
examples/cli/countdown.roc
examples/cli/echo.roc
examples/cli/env.roc
examples/cli/fileBROKEN.roc
examples/cli/form.roc
examples/cli/http-get.roc
examples/cli/ingested-file-bytes.roc
examples/cli/ingested-file.roc
examples/helloWorld.roc
examples/inspect-logging.roc
examples/parser/examples/letter-counts.roc
flake.nix
www/content/platforms.md
www/content/tutorial.md

Also added a script to do this

update to basic-cli 0.7.1

---

crates/repl_wasm/build-www.sh
flake.lock
flake.nix

update nix revision

---

crates/reporting/src/cli.rs

Report shadowing error messages last

---

www/content/faq.md

This has been asked a couple of times; now there's a FAQ entry for it!

Add FAQ entry for bignums

---

crates/compiler/gen_llvm/src/llvm/lowlevel.rs

32-bit float checked float operations assumed f64

---

crates/compiler/build/src/program.rs

A user should be able to write `roc build app.roc --target=wasm32 --no-link --output out.o`.
Currently, we would output `out.wasm` in that case instead of listening to the user and outputting `out.o`. This stops overwriting the extension.

stop overwritting manually set file extensions

---

www/content/faq.md

This now uses the one from the homepage that's the right size and changes colors slightly based on light vs dark theme.

Update bird logo in FAQ

---

crates/compiler/builtins/bitcode/src/main.zig
crates/compiler/builtins/src/bitcode.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/gen_llvm/src/llvm/externs.rs

a workaround for https://github.com/llvm/llvm-project/issues/72908

fix for bugged setjmp/longjmp on windows/llvm

---

crates/compiler/gen_llvm/src/llvm/struct_.rs

Helps a bit with llvm optimizations and code gen.

build structs directly in the alloca

---

crates/compiler/load/Cargo.toml
crates/compiler/load/build.rs
crates/compiler/load/src/lib.rs

Fix for the remaining LLVM tests on Windows.

Use subs caching on windows

---

www/content/tutorial.md

Fixed some minor errors when going through the tutorial again.

Fix typos & minor errors in the tutorial

---

crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_dev/src/object_builder.rs
crates/compiler/test_gen/src/gen_list.rs
crates/compiler/test_gen/src/gen_num.rs
crates/compiler/test_gen/src/gen_str.rs
crates/compiler/test_gen/src/helpers/dev.rs
crates/glue/src/load.rs

couple of small extra fixes were needed to make this work again

glue with the dev backend works again

---

crates/compiler/gen_llvm/src/run_roc.rs
crates/compiler/parse/src/ast.rs
crates/repl_cli/src/cli_gen.rs
crates/repl_eval/src/eval.rs
crates/repl_eval/src/lib.rs
crates/repl_expect/src/app.rs
crates/repl_test/src/tests.rs
crates/repl_wasm/src/repl.rs

fixes https://github.com/roc-lang/roc/issues/5588 
fixes #5708
fixes https://github.com/roc-lang/roc/issues/5506
fixes https://github.com/roc-lang/roc/issues/5321
fixes https://github.com/roc-lang/roc/issues/4669
and likely fixes others too

List.get with negative index in repl

---

crates/compiler/gen_dev/src/generic64/mod.rs
crates/compiler/gen_wasm/src/wasm32_sized.rs
crates/compiler/test_gen/src/gen_list.rs
crates/compiler/test_gen/src/helpers/from_wasm32_memory.rs

- wrong layout used dev backend
- wrong offset used to turn interpret wasm32 bytes

List prepend bug

---

crates/compiler/builtins/bitcode/src/dec.zig
crates/compiler/builtins/bitcode/src/main.zig
crates/compiler/builtins/src/bitcode.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/gen_wasm/src/low_level.rs
crates/compiler/test_gen/src/gen_num.rs

fixes https://github.com/roc-lang/roc/issues/6212

`floor`, `ceiling` and `round` for `Dec`

---

crates/glue/tests/test_glue_cli.rs
crates/roc_std/src/lib.rs
crates/roc_std/tests/test_roc_std.rs

fix https://github.com/roc-lang/roc/issues/6259

pi is not 3

---

crates/glue/tests/test_glue_cli.rs

I am hoping this will increase the chances of hitting a repro of https://github.com/roc-lang/roc/issues/5924 with the legacy linker.

Update test_glue_cli to use surgical and legacy linker 

---

crates/compiler/builtins/bitcode/src/dec.zig
crates/compiler/builtins/bitcode/src/main.zig
crates/compiler/builtins/src/bitcode.rs
crates/compiler/gen_dev/src/lib.rs
crates/compiler/gen_llvm/src/llvm/lowlevel.rs
crates/compiler/gen_wasm/src/low_level.rs
crates/compiler/test_gen/src/gen_num.rs

fixes https://github.com/roc-lang/roc/issues/6069

`Num.pow` for `Dec`

---

crates/compiler/gen_dev/src/lib.rs

This is super slow. When trying to compile a "real" app like rocci-bird or the false interpreter, the compiler will just hang in repeated calls to this function.
I am not sure if this "fix" is valid. I would assume that hashing the names should be equivalent hashing the InLayout. The InLayout should be a unique id that maps to the layout. The layout should map to name. So I think it should be a fix.
I haven't done intensive testing, but this is way way faster.

Avoid generating actual lambda names

---

crates/compiler/can/src/module.rs
crates/compiler/test_mono/generated/issue_6174.txt
crates/compiler/test_mono/src/tests.rs

Don't skip closure captures when fixing them

---

crates/compiler/mono/src/ir.rs

fixes https://github.com/roc-lang/roc/issues/5798
fixes https://github.com/roc-lang/roc/issues/5505
they now hit a runtime error and then report the type errors that caused the crash

fix two repl panics

---

examples/nodejs-interop/wasm/hello.js

The naming mechanism has changed.
Instead of adding a test for this example now I'm going to make a good-first-issue to move this to the examples repo and add a test there (#6536 ).

fix nodejs example

---

.github/workflows/ci_manager.yml

This partially addresses https://github.com/roc-lang/roc/issues/6276, in that it adds checks for `*.rs` changes and, specifically, whether those are comments only or not.
If you find the pattern acceptable, the same logic analogously translates to other file types, including `*.roc` files, as requested in the corresponding issue.
The `check-changes` job still outputs only one result, namely `run_tests: ${{ steps.filecheck.outputs.run_tests }}`, but the `steps` are refactored in to work together in a map-reduce kind of a manner. There are individual steps for:
- checking whether there are any files we'd like to ignore or not (which is the already existing logic);
- checking whether there are any `.rs` file changes and whether those contain only comments or not;
- a "reduce" step which …

Update CI workflow to not run tests when only rs comments changed

---

crates/compiler/build/src/program.rs

I noticed that when using the emit-llvm-ir flag it's possible the IR is further altered if `fuzz` or `gen_sanitizers` is used. So the IR printed may not actually be the final version of the IR that is used. This could lead to confusion and may make debugging harder, so I fixed it :)
I also added some code style improvements.

emit-ir and style improvement

---

README.md

The website makes for a better experience.

Change examples link to website

---

crates/compiler/parse/src/blankspace.rs
crates/compiler/parse/src/expr.rs

Quick refactoring / follow-up to #6634

Remove unnecessary arg to check_indent

---

README.md
www/content/index.md

Also fixed some missing `</li>` tags

Add new individual sponsors

---

www/content/abilities.md

Closes https://github.com/roc-lang/roc/issues/6679

Update Inspect docs

---

www/content/tutorial.md

Edit: Resolves #5141 (thanks, Luke!)

Add tuples to /tutorial

---

www/content/plans.md

Remove `Inspect` from /plans

---

www/public/site.css

Mostly some tweaks around tutorial `<h3>` color. Also ran a CSS formatter on it.

Update tutorial CSS

---

crates/compiler/parse/src/header.rs
crates/repl_cli/src/lib.rs
crates/repl_eval/src/gen.rs
crates/repl_ui/src/repl_state.rs
crates/repl_wasm/src/repl.rs

Handles the new import defs in the REPL, allowing you to import local Roc modules and ingest files!
https://github.com/roc-lang/roc/assets/1724813/b4bcea7f-05e8-404f-b428-95802284e9b9

Support imports in REPL

---

www/content/platforms.md
www/content/tutorial.md

As it is, the tutorial example does not compile due to a missing import.
EDIT: also wanted to add, I love so many things I've seen in Roc so far - really looking forward to getting into it.

Import pf.Task in first application example

---

README.md
www/content/index.md

Also auto-formatted some markdown and HTML!

Add @agu-z to sponsors

---

www/content/abilities.md

Fix dead link

---

www/README.md

Fix a path typo in www/README

---

README.md
www/content/index.md

Add @jluckyiv to sponsors

---

crates/repl_ui/src/repl_state.rs

Close https://github.com/roc-lang/roc/issues/6578

Better message for bad ident name in repl

---

crates/compiler/can/src/desugar.rs
crates/compiler/can/src/suffixed.rs
crates/compiler/can/tests/test_suffixed.rs
crates/compiler/parse/src/ast.rs

Part of https://github.com/roc-lang/roc/issues/6765

Ignore def pattern for function args

---

examples/nodejs-interop/native-c-api/demo.c

Was just reading the code and noticed a typo. Hope you don't mind the PR! 😄

fix: typo in comments

---

crates/compiler/can/src/expr.rs
crates/compiler/can/src/suffixed.rs
crates/compiler/can/tests/test_suffixed.rs

Expect then bang

---

crates/compiler/can/src/suffixed.rs
crates/compiler/can/tests/test_suffixed.rs
crates/compiler/parse/src/ast.rs

detect await bang inside of when branches

---

www/content/tutorial.md

#6781 updated the examples in the tutorial to the new module/import syntax, but there were still some references to old concepts/syntax

tutorial: More modules and imports updates 

---

crates/compiler/can/tests/test_suffixed.rs
crates/compiler/parse/src/ast.rs

check if final expr in deps is suffixed

---

crates/compiler/can/tests/test_can.rs
crates/compiler/parse/src/expr.rs

Closes https://github.com/roc-lang/roc/issues/6763.
Didn't add new tests since this seems covered already.
Doesn't fix the issue in the repl - working on a followup.

fix: allow multiple newlines between signature and body

---

crates/compiler/can/src/pattern.rs
crates/compiler/constrain/src/pattern.rs
crates/compiler/load/tests/test_reporting.rs
crates/compiler/mono/src/ir/pattern.rs

Fix https://github.com/roc-lang/roc/issues/6825 by not crashing and instead displaying an error.

Handle multi pattern unbound list rest variables

---

crates/compiler/can/src/suffixed.rs
crates/compiler/can/tests/test_suffixed.rs

Desugar arg of dbg statement

---

README.md
www/content/index.md

Add @chiroptical to sponsors

---

crates/compiler/mono/src/layout.rs

it is prettier in debug output, and should also be more efficient

when inserting into an interner, re-use `Layout::UNIT` when possible

---

crates/glue/src/RustGlue.roc

Also update the import syntax!
This is need for some basic-webserver changes.

Update rust glue to allow for borrowing payloads from tags

---

crates/compiler/parse/src/pattern.rs
crates/compiler/test_syntax/tests/snapshots/pass/pattern_as.expr.result-ast
crates/compiler/test_syntax/tests/test_fmt.rs

Fix https://github.com/roc-lang/roc/issues/6521

Fix handling of spaces after for `as`

---

crates/compiler/can/src/annotation.rs
crates/compiler/uitest/tests/exhaustive/extend_uninhabited_without_opening_union.txt

fix openness inference for empty tag

---

Cargo.lock
crates/compiler/mono/Cargo.toml
crates/compiler/mono/src/ir.rs

Helps with https://github.com/roc-lang/roc/issues/6898

better mono repl error

---

crates/compiler/mono/src/code_gen_help/refcount.rs
crates/compiler/mono/src/drop_specialization.rs
crates/compiler/test_gen/src/gen_list.rs
crates/compiler/test_gen/src/gen_refcount.rs
crates/compiler/test_gen/src/helpers/dev.rs
crates/compiler/test_mono/generated/issue_6606_2.txt
crates/compiler/test_mono/generated/list_one_vs_one_spread_issue_4685.txt

Deal with a few refcounting bugs from the big list change.

Refcount followup

---

www/public/different-names/index.html

joinMap <=> concatMap
List.map2 x y Pair <=> zip

Add concatMap and equivalent of zip

---

devtools/flake.lock
flake.nix
nix/builder.nix
nix/default.nix
nix/fileFilter.nix

I wanted to use the roc debug compiler for basic-cli and this was a bit tedious, so I made it easier :)

expose roc debug compiler in nix

---

crates/compiler/builtins/roc/Num.roc

See also https://github.com/roc-lang/roc/issues/6959

Num.neg docs

---

roc-for-elm-programmers.md
www/content/tutorial.md

tutorial improvements

---

crates/cli/tests/cli_run.rs
crates/cli/tests/platform_requires_pkg/app.roc
crates/cli/tests/platform_requires_pkg/foo/Foo.roc
crates/cli/tests/platform_requires_pkg/foo/main.roc
crates/cli/tests/platform_requires_pkg/platform/host.zig
crates/cli/tests/platform_requires_pkg/platform/main.roc
crates/compiler/load_internal/src/file.rs

We were dropping packages from the platform header while loading.
Closes #6931

Load platform dependencies

---

crates/cli/src/format.rs
crates/compiler/parse/src/ast.rs
crates/compiler/parse/src/remove_spaces.rs
crates/compiler/test_syntax/src/test_helpers.rs
crates/compiler/test_syntax/tests/snapshots/pass/newline_in_packages.full.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/old_app_header.full.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/space_before_colon.full.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/suffixed_one_def.full.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/suffixed_optional_last.full.result-ast

Rename Full -> FullAst

---

www/content/plans.md

[zulip discussion](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Shadowing.20benefits.20via.20code.20acton.20and.2For.20formatter/near/462414401)

Include shadowing in Plans page

---

www/build.sh

Context: https://github.com/roc-lang/roc/issues/6987

avoid hiding segfaults

---

crates/README.md

Added a space so I can figure out how PRs work :sweat_smile:

fixed typo in readme

---

crates/cli/src/format.rs
www/content/platforms.md

If you search for `pf.Task`, you'll find more, but I'm not sure what to do with them.

Remove a couple remaining references to pf.Task

---

crates/compiler/mono/src/borrow.rs

fix tip 2 formatting

---

crates/compiler/load/tests/test_reporting.rs
crates/reporting/src/error/parse.rs

I improved the error message in response to https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.22final.20expression.20in.20that.20series.20of.20definitions.22/near/472405231

add final expression tip

---

crates/compiler/builtins/roc/Num.roc

Adds documentation for `Num.intCast`

Add Num.intCast documentation

---

crates/repl_cli/src/cli_gen.rs

In response to https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/.E2.9C.94.20Any.20advice.20on.20failing.20roc.20tests!.3F!/near/474092403

improved dylib error

---

crates/cli/tests/algorithms/fibonacci.roc
crates/cli/tests/cli_run.rs
crates/cli/tests/multiple_exposed/main.roc
crates/cli/tests/multiple_exposed/platform/host.zig
crates/cli/tests/multiple_exposed/platform/main.roc
crates/compiler/alias_analysis/src/lib.rs
crates/compiler/build/src/program.rs
crates/compiler/fmt/src/header.rs
crates/compiler/gen_llvm/src/llvm/build.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/load_internal/src/module.rs
crates/compiler/mono/src/ir.rs
crates/compiler/parse/src/header.rs
crates/compiler/parse/src/normalize.rs
crates/compiler/test_gen/src/helpers/dev.rs
crates/compiler/test_gen/src/helpers/llvm.rs
crates/compiler/test_syntax/tests/snapshots/pass/empty_platform_header.header.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/empty_platform_header.header.roc
crates/compiler/test_syntax/tests/snapshots/pass/function_effect_types.header.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/nonempty_platform_header.header.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/requires_type.header.result-ast
crates/language_server/src/analysis/tokens.rs
crates/repl_cli/src/cli_gen.rs

Two separate fixes here:
1. allowing any number of functions to be sent form app -> platform (mostly parsing fixes)
2. allowing any number of functions to be exposed from platform -> host

Enable exposing multiple functions from app -> platform -> host

---

www/build.sh

Puts all exercism exercises in one prompt.md and makes them available on the website.
This prompt file will make the LLM of your choice good at Roc :)

Started on roc prompt

---

crates/roc_std/src/lib.rs
crates/roc_std/tests/test_roc_std.rs

Discussed [here](https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/should.20roc_std.3A.3ARocDec.20support.20Default.2FOrd.3F/near/476758392) on Zulip.

Implement Default/PartialOrd/Ord for RocDec

---

www/content/tutorial.md
www/main.roc

Added llms.txt

---

Cargo.lock
crates/compiler/can/src/debug/pretty_print.rs
crates/compiler/can/src/def.rs
crates/compiler/can/src/expr.rs
crates/compiler/can/src/module.rs
crates/compiler/can/src/traverse.rs
crates/compiler/constrain/src/expr.rs
crates/compiler/load_internal/src/file.rs
crates/compiler/load_internal/src/module.rs
crates/compiler/load_internal/tests/test_load.rs
crates/compiler/lower_params/src/lower.rs
crates/repl_expect/Cargo.toml
crates/repl_expect/src/run.rs

Cleanup after #7227
If these were intended to be left in the codebase, feel free to close the PR 🙂

Cleanup after #7227

---

.gitignore

using [helix editor](https://helix-editor.com/), it's useful to specify workspace-lsp-roots with all the crate roots in a repo-local configuration file '.helix/config.toml'

git ignore helix config

---

crates/docs/src/lib.rs
crates/docs/src/static/search.js
crates/docs/src/static/styles.css

Restyle docs search

---

www/content/tutorial.md

Update tutorial with recent syntax changes

---

crates/compiler/gen_llvm/src/llvm/bitcode.rs

https://roc.zulipchat.com/#narrow/channel/463736-bugs/topic/LLVM.20IR.20output.20in.20compiler.20crash.20during.20AOC!

Fix pass by reference for compare fn

---

crates/compiler/builtins/bitcode/src/dec.zig

fix dec multiplication with overflow and saturation

---

crates/linker/src/elf.rs

Added the legacy linker recommendation as per https://github.com/roc-lang/roc/issues/7068

add legacy linker recommendation

---

crates/compiler/fmt/src/pattern.rs
crates/compiler/test_syntax/tests/snapshots/pass/pattern_with_as_parens.expr.formatted.roc
crates/compiler/test_syntax/tests/snapshots/pass/pattern_with_as_parens.expr.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/pattern_with_as_parens.expr.roc
crates/compiler/test_syntax/tests/test_snapshots.rs

Fix as pattern formatting inside apply

---

crates/glue/src/RustGlue.roc

See https://roc.zulipchat.com/#narrow/channel/231634-beginners/topic/Memory.20layout.20for.20tags.20.26.20records/near/486622379

Comment out failing glue assertion for now

---

ci/package_release.sh
crates/compiler/load_internal/src/file.rs
crates/packaging/src/tarball.rs

examples/cli was removed in https://github.com/roc-lang/roc/pull/6921

cli example removal cleanup

---

crates/compiler/fmt/src/annotation.rs
crates/compiler/fmt/src/expr.rs
crates/compiler/fmt/src/header.rs
crates/compiler/fmt/src/pattern.rs

Covers a _LOT_ of cases that I missed in the initial pass.

Fix snake case formatting

---

crates/docs/src/lib.rs
crates/docs/src/static/search.js
crates/docs/src/static/styles.css

Some small updates:
1. Better tablet layout, and better layout for narrow desktop screens (collapsed sidebar)
2. Collapsible sections in sidebar
3. Slightly darker color scheme
4. (The above unlocked) Syntax Highlighting in signatures for all entries!
5. A slightly different style for the module entries that is less in-your-face.

A few docs improvements

---

crates/docs/src/lib.rs

Fix for issue 7417 - Fix links generated for submodules

---

crates/compiler/build/src/link.rs
crates/compiler/build/src/program.rs
crates/linker/src/generate_dylib/macho.rs
crates/linker/src/lib.rs
crates/linker/src/macho.rs

Linking with surgical Mach-O linker will now produce an output executable, however it is not runnable as many things still need implementing. I do hope this PR narrows it down as to what is missing and needs implementing.

linker: refactor surgical Mach-O linker code

---

crates/compiler/build/src/link.rs
crates/linker/src/generate_dylib/macho.rs
crates/linker/src/lib.rs
crates/linker/src/macho.rs

This reverts commit 723e35f11e1b1744c77cde77e42ed2b48fff12a6, reversing changes made to 0ce43ffd1e2f1387370006e1c300fe8ec74343c7.
Due to failures in cli_tests, these got through because the merge was forced.

Revert "Merge pull request #7424 from kubkon/macho-surgery"

---

crates/cli/src/lib.rs
crates/cli/src/main.rs
crates/compiler/build/src/link.rs
crates/glue/src/load.rs
crates/linker/src/generate_dylib/macho.rs
crates/linker/src/lib.rs
crates/linker/src/macho.rs

Fixes macOS tests after landing #7424. Supersedes #7433.
cc @Anton-4 @bhansconnect @lukewilliamboswell

Revert 7435 revert pr7424

---

www/content/install/macos_apple_silicon.md

libz3 must be present on apple silicon.

Mention installing z3 on macos

---

crates/compiler/fmt/src/annotation.rs
crates/compiler/fmt/src/def.rs
crates/compiler/fmt/src/node.rs
crates/compiler/test_syntax/src/minimize.rs
crates/compiler/test_syntax/src/test_helpers.rs
crates/compiler/test_syntax/tests/test_fmt.rs

Migrate type vars to snake case (Redo)

---

crates/compiler/fmt/src/def.rs

This was missed in code review and merged

Remove superfluous println

---

crates/linker/src/macho.rs

Mach-O doesn't use compressed sections so we can safely ignore them.

linker/macho: remove redundant checks for compressed sections

---

docker/devcontainer/Dockerfile

As discussed in https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/devcontainer

added roc-devcontainer

---

.github/workflows/nix_linux_x86_64.yml
.github/workflows/ubuntu_x86_64_nix_debug.yml
crates/cli/tests/cli_tests.rs
crates/cli_test_utils/src/exec_cli.rs
crates/compiler/build/src/program.rs
flake.nix

The combination of `CMD_DEV`, `stdin` and using `check_build_and_run` was the problem.

fix cli_test effectful_form getting stuck

---

www/content/plans.md
www/content/tutorial.md

Minor updates to the Tutorial, post basic-cli snake_case and purity inference upgrades.

Updates for the Tutorial and Plans content

---

crates/compiler/builtins/bitcode/src/utils.zig

See [this short zulip discussion](https://roc.zulipchat.com/#narrow/channel/316715-contributing/topic/dec.2Eto_str.20test.20failing.20in.20debug.20mode.20on.20main) for more context.

remove unused var causing errors in debug tests.

---

crates/compiler/gen_dev/src/generic64/mod.rs

The intent of this change is to fix a bug calling `Num.shift_right_by(a, b)` mutates `a`. This was happening in the dev backend only, and the cause was some generated assembly which writes to register a is stored in. The fix here is to rewrite the code to only use `dst_reg` or `tmp_reg` as destination registers.
fixes #7501

fix Num.shift_right_by to not mutating src register

---

www/content/tutorial.md

See https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/breaking.20changes/near/493511154
Tested locally.

Add context and formatting to tutorial warning banner

---

flake.nix
nix/simple-http-server.nix

[context](https://roc.zulipchat.com/#narrow/channel/231634-beginners/topic/Trouble.20updating.20roc/near/493636680)

use my simple-http-server fork

---

crates/compiler/can/src/desugar.rs
crates/compiler/can/tests/test_can.rs
crates/compiler/fmt/src/expr.rs
crates/compiler/module/src/called_via.rs
crates/compiler/parse/src/expr.rs
crates/compiler/test_syntax/tests/snapshots/pass/single_question_binop_closure.expr.formatted.roc
crates/compiler/test_syntax/tests/snapshots/pass/single_question_binop_closure.expr.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/single_question_binop_closure.expr.roc
crates/compiler/test_syntax/tests/snapshots/pass/single_question_binop_tag.expr.formatted.roc
crates/compiler/test_syntax/tests/snapshots/pass/single_question_binop_tag.expr.result-ast
crates/compiler/test_syntax/tests/snapshots/pass/single_question_binop_tag.expr.roc
crates/compiler/test_syntax/tests/test_snapshots.rs

Implement the desugaring of `foo ? bar` to
```roc
when foo is
Ok(ok) -> ok
Err(err) -> return Err(bar(err))
```

Implement ? binop operator

---

www/content/docs.md
www/content/install/getting_started.md

The file was removed in b6082f8fc900e5d2576be64ba.

Remove links to roc-for-elm-programmers.md

---

crates/compiler/mono/src/tail_recursion.rs
crates/compiler/test_mono/generated/capture_void_layout_task.txt
crates/compiler/test_mono/generated/compose_recursive_lambda_set_productive_nullable_wrapped.txt
crates/compiler/test_mono/generated/dbg_in_expect.txt
crates/compiler/test_mono/generated/dbg_inside_string.txt
crates/compiler/test_mono/generated/dbg_str_followed_by_number.txt
crates/compiler/test_mono/generated/encode_derived_nested_record_string.txt
crates/compiler/test_mono/generated/encode_derived_record_one_field_string.txt
crates/compiler/test_mono/generated/encode_derived_record_two_field_strings.txt
crates/compiler/test_mono/generated/encode_derived_tag_one_field_string.txt
crates/compiler/test_mono/generated/encode_derived_tag_two_payloads_string.txt
crates/compiler/test_mono/generated/inspect_derived_dict.txt
crates/compiler/test_mono/generated/inspect_derived_list.txt
crates/compiler/test_mono/generated/inspect_derived_nested_record_string.txt
crates/compiler/test_mono/generated/inspect_derived_record.txt
crates/compiler/test_mono/generated/inspect_derived_record_one_field_string.txt
crates/compiler/test_mono/generated/inspect_derived_record_two_field_strings.txt
crates/compiler/test_mono/generated/inspect_derived_string.txt
crates/compiler/test_mono/generated/inspect_derived_tag_one_field_string.txt
crates/compiler/test_mono/generated/inspect_derived_tag_two_payloads_string.txt
crates/compiler/test_mono/generated/issue_4770.txt
crates/compiler/test_mono/generated/list_map_closure_borrows.txt
crates/compiler/test_mono/generated/list_map_closure_owns.txt
crates/compiler/test_mono/generated/recursive_function_and_union_with_inference_hole.txt
crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_does_not_duplicate_identical_concrete_types.txt
crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_keeps_all_concrete_types_without_unification_of_unifiable.txt

Related issue: #7531 
PRs that hit the issue: #7514 #7496
[Zulip conversation](https://roc.zulipchat.com/#narrow/channel/463736-bugs/topic/mono.20mismatch.20between.20mac.20aarch64.20and.20rest.20of.20targets/near/493982259)

proc sort fix #7531 

---

crates/compiler/builtins/roc/Str.roc

Just a couple of minor improvements.
Really happy to have these functions in! 😃

Tweak some `Str` documentation

---

crates/compiler/builtins/roc/Str.roc

More minor `Str` docs improvements

---

crates/compiler/builtins/roc/Str.roc

More minor tweaks to make the examples a bit more obvious.

Clarify some Str docs

---

crates/compiler/fmt/src/expr.rs
crates/compiler/test_syntax/tests/test_fmt.rs

Format apply funcs with try suffix correctly

---

build.zig
src/command.zig
src/main.zig
src/test.zig

- Improve cli command and option parsing -- refactor into a separate module and add tests.
- Configure all tests to run from cli using `zig build test` -- tests to run are specified in `src/test.zig`

Improve roc cli

---

.github/workflows/nix_macos_apple_silicon.yml
devtools/flake.lock
devtools/flake.nix
flake.lock
flake.nix

We no longer need graphics libraries since examples/gui was removed.

nix flake cleanup

---

build.zig
src/fuzz/repro.zig

Just a helper script. If a fuzzer fails, this can be run to test the failure case.

add a script to reproduce fuzzing failures

---

src/build/solve_functions.zig
src/build/specialize_functions.zig
src/check/canonicalize/Scope.zig
src/check/parse/tokenize.zig
src/collections/safe_list.zig
src/coordinate.zig

- Revert all changes made to parsing code to unblock Anthony's change: https://github.com/roc-lang/roc/pull/7597
- Split back out function solving and parsing

Split back out function solve and specialize

---

BUILDING_FROM_SOURCE.md

docs: add issue link

---

.github/workflows/ci_zig.yml
build.zig
src/base/Module.zig
src/check/canonicalize.zig
src/check/parse.zig
src/check/parse/IR.zig
src/check/parse/Parser.zig
src/check/parse/tokenize.zig
src/collections/safe_list.zig
src/fmt.zig
src/fuzz/tokenize.zig
src/test.zig

Note this commit is ~95% the work of Anthony Bullard <anthony.bullard@gmail.com>, I (Josh Warner) just rebased + fixed some bugs + signed it.

First draft of Zig version of Parser

---

src/check/parse/IR.zig
src/check/parse/Parser.zig
src/check/parse/tokenize.zig

- **Move some tokenizer errors to malformed tokens**
- **Add malformed nodes and diagnostics to the parser in place of panics**

Implement better malformed handling in the tokenizer/parser

---

src/check/parse/tokenize.zig
src/fuzz-tokenize.zig

Fix fuzz bugs

---

build.zig
build.zig.zon
src/check/parse.zig
src/check/parse/Parser.zig
src/check/parse/tokenize.zig
src/fuzz-tokenize.zig

Per @rtfeldman, remove unicode support for now. We can always add this back in the future.

Remove unicode support for now

---

src/check/parse.zig
src/check/parse/IR.zig
src/check/parse/Parser.zig
src/check/parse/tokenize.zig
src/fmt.zig
src/fuzz-tokenize.zig

Also added support for string interpolation and began catalog of parsing IR diagnostic tags.

[zig-compiler]: More parser features

---

src/check/parse/IR.zig
src/check/parse/Parser.zig
src/check/parse/tokenize.zig
src/fmt.zig
src/fuzz-tokenize.zig

Basic support for the new `match` expression, which replaces Classic Roc's `when...is`.

[zig-compiler] Match expression support and most patterns

---

src/check/parse/IR.zig
src/check/parse/Parser.zig
src/check/parse/tokenize.zig
src/fmt.zig

Everything expect Custom Types, Abilities(RIP?), and `where` clauses.

[zig] Parsing and Formatting Types - declarations and annotations.

---

src/collections/SmallStringInterner.zig

Simply more cleanup inspired by: https://www.hytradboi.com/2025/05c72e39-c07e-41bc-ac40-85e8308f2917-programming-without-pointers
Also, switched the default hash function.
Here are some benchmark results.
Overall, Fnv is a bit behind the other for small keys and way behind for larger keys. Decided to just go with the zig default string hash which seems quite performant May evaluate rapidhash once 0.14.0 comes out
Overall, not too worried about it.
```
benchmark              runs     total time     time/run (avg ± σ)     (min ... max)                p75        p99        p995
-----------------------------------------------------------------------------------------------------------------------------
Insert: Fnv1a_32 small 16162    1.959s         121.258us ± 5.033us    (111.917us ... …
```

String Interner Cleanup

---

build.zig.zon

Ok, now this works on mac and linux.

ugh, update again...broke mac fuzzing somehow

---

.github/workflows/ci_manager.yml
ci/zig_lints.sh
src/base.zig
src/build/lift_functions/IR.zig
src/build/lower_statements/IR.zig
src/build/reference_count/IR.zig
src/build/solve_functions.zig
src/build/specialize_functions/IR.zig
src/build/specialize_types/IR.zig
src/check/parse/Parser.zig
src/check/resolve_imports/IR.zig
src/collections.zig
src/types.zig

ignores init, deinit and re-exports

Zig lint improvements

---

build.zig
src/check/parse.zig

Also correct to minor printout typos.

Enable optimizing fuzz repro scripts

---

src/check/parse/Parser.zig
src/snapshots/fuzz_crash/fuzz_crash_013.txt

And unclosed block was previously looping forever

[Parser] avoid infinite loop

---

.github/workflows/ci_manager.yml

These files should not trigger ci manager in general

Ignore more files in the ci manager filter

---

src/build/specialize_types/IR.zig

Can you check all this @smores56? I've added `???` to the things I'm especially unsure about.

added comments to IR.zig

---

CompilerDictionary.md

Just a skeleton to make sure we're on the same page.
[context](https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/dict.2Emd/near/505836287)

Init Compiler Dictionary

---

src/check/parse/IR.zig
src/check/parse/Parser.zig
src/coordinate.zig
src/fmt.zig
src/snapshots/hello_world.txt

Got all the headers parsing and formatting.
Fixed function type annos inside of structs and similar collections.
- They will still need to be wrapped in Tuple type annos.

Parse other headers

---

src/check/parse/IR.zig
src/check/parse/Parser.zig
src/fmt.zig
src/snapshots/type_declarations.txt

Back at it, this time with arrow calls as specified in [this Zulip thread](https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/zig.20compiler.20-.20parser/near/512555187)

feat: [check] Parse and format local dispatch arrow calls

---

crates/cli/src/lib.rs
crates/cli/tests/snapshots/cli_tests__cli_tests__test_platform_simple_zig__module_params_arity_mismatch.snap
crates/cli/tests/snapshots/cli_tests__cli_tests__test_platform_simple_zig__module_params_bad_ann.snap
crates/cli/tests/snapshots/cli_tests__cli_tests__test_platform_simple_zig__module_params_unexpected_fn.snap
crates/cli_test_utils/src/command.rs
crates/compiler/build/src/program.rs
crates/glue/src/load.rs

The tip "You can run the program anyway with ..." is an easy way for people to hit bugs, so I removed it.

Remove run anyway tip

---

ci/zig_lints.sh
src/base.zig

Context: [#compiler development > casual conversation @ 💬](https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/casual.20conversation/near/517766720)

allow re-exports without comments

---

src/collections.zig
src/eval/stack.zig
src/main.zig
src/test.zig

I'm extracting this from the WIP interpreter into its own PR, because it's reasonably self-contained.

Add a stack memory system for the interpreter

---

src/cli_args.zig
src/main.zig

CLI Updates PR feedback

---

src/base/Package.zig
src/check/canonicalize.zig
src/check/canonicalize/CIR.zig
src/check/canonicalize/Diagnostic.zig
src/check/canonicalize/NodeStore.zig
src/check/check_types.zig
src/check/parse/AST.zig
src/coordinate/ModuleGraph.zig
src/coordinate_simple.zig
src/main.zig
src/reporting/renderer.zig
src/reporting/report.zig
src/snapshot.zig
src/test.zig

```roc
module [add]
add : U8, U8 -> U8
add = |x, y| x + y
```

Initial implementation of `roc check`

---

src/base/target.zig
src/collections.zig
src/layout/layout.zig
src/layout/store.zig
src/layout/store_test.zig
src/layout/work.zig
src/test.zig
src/types/types.zig

This isn't being used yet, but I want to land it before it picks up more merge conflicts.
This will definitely be used in code gen and the interpreter!

Add Layout

---

devtools/debug_tips.md
devtools/lldb_line_tracer.py

I was having some trouble filtering out what I wanted with uftrace, so I made a lldb tracer.

devtools tracer script

---

src/check/canonicalize.zig
src/check/parse/AST.zig
src/check/parse/NodeStore.zig
src/check/parse/Parser.zig
src/fmt.zig
src/snapshots/records/function_record_parameter.md
src/snapshots/records/function_record_parameter_capture.md
src/snapshots/records/function_record_parameter_rest.md
src/snapshots/records/pattern_destructure_nested.md
src/snapshots/records/pattern_destructure_simple.md
src/snapshots/records/pattern_destructure_with_rest.md
src/snapshots/records/pattern_function_parameter.md

Still trying to understand if/how to do `..` without an identifier.  Can add that to this PR or do it in a fast follow.

Parse record shorthand and as syntax in patterns

---

crates/compiler/mono/src/inc_dec.rs

Context: [#compiler development > slow build with lots of &#96;?&#96;](https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/slow.20build.20with.20lots.20of.20.60.3F.60/with/523083520)

refcount perf fix

---

src/check/parse/tokenize.zig

Also add debug asserts to make sure only tags labeled as interned can be pushed to the token buffer with the "interned" extra variant.
fixes fuzz bug:
zig build repro-tokenize -- -b XzD/ -v

add isInterned method to token tags

---

src/check/check_types.zig
src/check/let_polymorphism_integration_test.zig

@jaredramirez Here's the cleanup I talked about in that other PR!

Refactor instantiation

---

src/snapshot.zig

Couple more bits of low-hanging fruit. ~1800ms -> ~1400ms improvement on my machine.

Avoid extra buffer allocation in snapshot generation (~25% improvement)

---

.github/workflows/ci_zig.yml
src/snapshot.zig

This leads to a 4-6x speed increase in snapshot generation

Switch to using the c_allocator by default for snapshots

---

src/check/canonicalize.zig
src/check/check_types.zig

```roc
module [last]
last = |l|
match l {
[] => Err(EmptyList)
[.., e] => Ok(e)
}
```
```
$ zig build run -- check --no-cache test.roc
No errors found in 0.9 ms for test.roc
```

Fix type checking for empty list patterns

---

Glossary.md
src/types/types.zig

Additions to glossary and comments.

Glossary rank

---

src/repl/README.md
src/repl/eval.zig
src/snapshot.zig
src/snapshots/repl_basic_example.md

This is kind of a placeholder but I'm going to use it later.

Add repl snapshots

---

src/check/parse/Parser.zig
src/snapshots/fuzz_crash/fuzz_crash_050.md
src/snapshots/unused_vars_block.md

```
zig build repro-parse -- -b bW9kdWxlW11fMD17CikK -v
```

Fix parse crash in named underscore decl

---

src/check/canonicalize.zig
src/snapshots/expr/boolean_tuple.md

Add type-checking for True and False

---

src/check/parse/Parser.zig
src/fmt.zig
src/snapshots/binops.md
src/snapshots/expr_if_missing_else.md
src/snapshots/fuzz_crash/fuzz_crash_024.md
src/snapshots/fuzz_crash/fuzz_crash_032.md
src/snapshots/fuzz_crash/fuzz_crash_051.md
src/snapshots/if_then_else/if_then_else_simple_tag.md
src/snapshots/nominal/nominal_import_type.md
src/snapshots/nominal/nominal_mixed_scope.md
src/snapshots/nominal/nominal_tag_package_import.md
src/snapshots/nominal/nominal_tag_payload.md
src/snapshots/nominal/nominal_tag_payload_two.md
src/snapshots/nominal/nominal_tag_recursive_payload.md
src/snapshots/nominal/nominal_tag_simple.md
src/snapshots/plume_package/Color.md
src/snapshots/plume_package/Color.roc
src/snapshots/qualified_tag.md
src/snapshots/qualified_type_canonicalization.md
src/snapshots/qualified_with_anno.md
src/snapshots/statement/dbg_stmt.md
src/snapshots/statement/expect_stmt.md
src/snapshots/statement/expect_stmt_block_assertion.md
src/snapshots/statement/expect_stmt_top_level.md
src/snapshots/statement/return_stmt.md
src/snapshots/type_tag_union_basic.md

```
zig build repro-parse -- -b bW9kdWxlW317MAkwKSgwfQ== -v
```

Fix parse fuzz crash and improve formatting

---

src/check/canonicalize/Diagnostic.zig
src/playground/app.js
src/playground/index.html
src/playground/styles.css
src/snapshots/pass/exposed_not_impl.md

Update styles for playground

---

src/check/canonicalize.zig

Fix a small bug in pattern tuple elem canonicalization, where nested tuples would cause the outermost tuple to get extra elements in the type system.

Fix bug in pattern tuple element canonicalization

---

src/fmt.zig
src/snapshots/app_header__nonempty_multiline__commented.md
src/snapshots/app_header__nonempty_multiline__trailing_comma.md
src/snapshots/app_header__platform_not_first.md
src/snapshots/fuzz_crash/fuzz_crash_056.md
src/snapshots/fuzz_crash/fuzz_crash_057.md
src/snapshots/fuzz_crash/fuzz_crash_058.md
src/snapshots/where_clause/where_clauses_multi_type_vars.md

```
zig build repro-parse -- -b YXBwW117ZjpwbGF0Zm9ybSIiLHI6IiIsbzoiIn0= -v
zig build repro-parse -- -b bW9kdWxlW11zOmItPmMgd2hlcmUgbW9kdWxlKGEpLnQ6Yyx1Om8uLi4= -v
zig build repro-parse -- -b YXBwW117ZjpwbGF0Zm9ybSIiLHI6Igp9 -v
```

Fix parse fuzz errors

---

crates/docs/src/static/search.js

Fix browser error in tutorial. Fix code block copy button tutorial.

fix search.js

---

src/check/parse/AST.zig
src/check/parse/Parser.zig
src/snapshots/fuzz_crash/fuzz_crash_013.md
src/snapshots/fuzz_crash/fuzz_crash_021.md
src/snapshots/fuzz_crash/fuzz_crash_024.md
src/snapshots/fuzz_crash/fuzz_crash_027.md
src/snapshots/fuzz_crash/fuzz_crash_035.md
src/snapshots/fuzz_crash/fuzz_crash_036.md
src/snapshots/records/module_record_destructure.md
src/snapshots/records/statement_record_destructure.md

```roc
{ name, age, email } = person
```

Parse record destructure declarations

---

src/collections/safe_list.zig
src/serialization/CompactWriter.zig
src/serialization/README.md
src/serialization/mod.zig
src/serialization/test/compact_writer_test.zig

Initial implementation of `CompactWriter`, plus using it with `SafeList` and `SafeMultiList` and tests for all those.

Add CompactWriter to SafeList and SafeMultiList

---

src/base/Ident.zig
src/base/SmallStringInterner.zig
src/base/StringLiteral.zig
src/check/canonicalize/test/import_validation_test.zig
src/check/check_types/problem.zig
src/compile/CIR.zig

This is just the ones that are reachable from ModuleEnv, which are the ones we want to serialize.

Migrate all ArrayList/MultiArrayList to SafeList/MultiSafeList

---

src/base/Ident.zig
src/cache/CacheModule.zig
src/check/canonicalize.zig
src/check/canonicalize/test/exposed_shadowing_test.zig
src/check/canonicalize/test/import_validation_test.zig
src/check/check_types.zig
src/collections/ExposedItems.zig
src/collections/SortedArrayBuilder.zig
src/collections/mod.zig
src/compile/ModuleEnv.zig

This should be both more efficient as well as better for serialization.

Use SortedArrayBuilder over hash maps for exports

---

src/base/Ident.zig
src/base/StringLiteral.zig
src/base/test/base_test.zig
src/cache/CacheManager.zig
src/cache/CacheModule.zig
src/collections/ExposedItems.zig
src/collections/safe_hash_map.zig
src/collections/safe_list.zig
src/compile/NodeStore.zig
src/serialization/mod.zig
src/serialization/testing.zig
src/snapshot.zig
src/types/store.zig

Also delete `serializeFrom`/`serializeInto`, as they are no longer in use!

Use ModuleEnv.Serialized for caching

---

src/parse/Parser.zig

A follow up to #8166, adding the counter usage to type annos, patterns, and statements.

Fix parser stack overflow finish

---

src/collections/SortedArrayBuilder.zig

Clean up SortedArrayBuilder

---

src/canonicalize/test/exposed_shadowing_test.zig
src/canonicalize/test/import_validation_test.zig

These were disabled during the big module reorghanization. Now they're back, and in some cases skipped.

Uncomment a bunch of tests

---

crates/compiler/builtins/roc/Str.roc

remove broken links
