roc-lang/roc

crates/glue/src/types.rs
Previously, this used a hash map of layouts to fix up recursive pointers. This led to potential hash map key collisions, because sometimes you have two types with the same layout but different `Content`s. The new approach uses root `Variable`s, so it won't have this problem!
cc @BrianHicks - this fixes `pub inputs: roc_std::RocList<Rbt>` getting generated instead of `pub inputs: roc_std::RocList<Job>` in the example you sent me!
=> Fix recursive type glue

default.nix, devtools/vscodeflake.nix, flake.nix
I didn't want to run my editor formatter when doing #3763 but maybe it'd be nice to have the same style across the repo? Looks like `flake.nix` is already formatted with `nixfmt` (or it just happens to not have any diff, I suppose.)
If this is something we want, should I make a PR to change CI as well?
(based on #3763 but it doesn't look like I know how to make a PR stack across forks! Please only pay attention to f25786c, the only new commit on this branch.)
=> fix build on macos and format all nix files with nixfmt

.github/dependabot.yml
We could also limit to 1 a day or something, but since we're only looking at Cargo stuff for the moment it "should be fine."
=> open new dependabot PRs early in the morning, Belgium time

crates/compiler/can/src/module.rs, crates/compiler/collections/src/vec_map.rs, crates/compiler/collections/src/vec_set.rs, crates/compiler/mono/src/ir.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_primitives.rs
Closure captures can be transient, but previously, we did not handle
that correctly. For example, in
```
x = ""
inner = \{} -> x
outer = \{} -> inner {}
```
`outer` captures `inner`, but `inner` captures `x`, and in the body of
`outer`, we would not construct the closure data for `inner` correctly
before calling it.
There are a couple ways around this.
1. Update mono to do something when we are passed the captured
environment of a closure, rather than attempting to construct a
call-by-name's captured environment before calling it.
2. Fix-up closures during canonicalization to remove captured closures
that themselves capture, and replace them with their captures.
This patch does (2), since (1) is much more involved and is not likely
to bring a lot of wins. In general I think it's …
=> Transient captures in closures, and captures between mutually recursive defs

crates/compiler/module/src/symbol.rs, crates/compiler/types/src/subs.rs, crates/editor/src/graphics/lowlevel/vertex.rs, examples/breakout/platform/src/graphics/lowlevel/quad.rs, examples/gui/platform/src/graphics/lowlevel/quad.rs
While looking through the code, one thing I checked that is easy to miss is just proper layout attributes.
Some of the layouts were used as if they were stable, and converted to byte arrays, or [had bytemuck's Pod trait implemented without fulfilling its contract.](https://docs.rs/bytemuck/latest/bytemuck/trait.Pod.html#safety)
[By default the representation is `repr(rust)`](https://doc.rust-lang.org/reference/type-layout.html#the-default-representation), which has no guarantees at all. It can reorder fields and insert padding at will, theoretically even between compilations. I added `repr(C)`, which is Rust's interpretation of a stable platform-specific layout where I saw it is needed and some safety comments.
A brief look at your CI shows you are not running it on nightly, but if you …
=> Fix some layout reprs

Cargo.lock, crates/compiler/test_gen/Cargo.toml, crates/compiler/test_gen/src/gen_abilities.rs
Closes https://github.com/rtfeldman/roc/issues/3708
Closes https://github.com/rtfeldman/roc/issues/3709
=> Turn abilities tests for wasm dev and wasm LLVM back on

getting_started/README.md
I looked over the issues and couldn't find someone who has this covered.
Looking at https://github.com/roc-lang/roc/issues/3291 it seems you prefer to link to files, but it's not clear do you want Tutorial to be in the same directory or just link, hence I just fix the link.
Maybe even move TUTORIAL.md to getting_started.
Signed-off-by: Marko Vujanic <crashxx@gmail.com>
=> Update Tutorial Link from getting_started

crates/compiler/gen_dev/README.md
Super minor thing, but I was reading up on the dev backend and noticed the the file links in `gen_dev/README.md` were all dead. It seems `compiler/` was moved at some point into `crates/`. This PR adds the `crates` subfolder to the path for all file links.
=> Fix file links in gen_dev readme

crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_gen/src/gen_tags.rs
These work now that we have ways to compile polymorphic expressions.
Closes #1745
=> Add polymorphic expression reproduction cases from #1745

crates/compiler/can/src/expr.rs, crates/compiler/problem/src/can.rs, crates/compiler/solve/tests/solve_expr.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/tests/test_reporting.rs
Instead, suggest prefixing it with an underscore, or replacing with an
underscore.
Closes #3820
=> Don't suggest removing variable when it's bound in a branch pattern

crates/compiler/builtins/roc/Num.roc, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/test_gen/src/gen_num.rs, examples/benchmarks/Base64/Decode.roc, examples/benchmarks/Base64/Encode.roc, examples/benchmarks/Bytes/Encode.roc
The argument order of bitwise shift operators was swapped.
This was probably due to copying from elm.
For reference, see this zulip discussion:
https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/bit.20shift.20operations.20arguments.20swapped.3F
=> Bitshift operator argument swap

crates/cli/src/lib.rs, crates/cli/src/main.rs
This makes `roc dev` do the "build and then only run if there were no errors" logic which currently the plain `roc` command does.
The reason to split them out is so that the plain `roc` command can be reserved for `#!/usr/bin/env roc` scripts - which need to be in that format (no subcommands allowed, because some `env` implementations don't support passing through arguments to the specified executable).
Now we can say "use `roc dev` for normal development" and optimize the plain `roc` command for the scripting use case (e.g. have it ignore `expect`s, whereas `roc dev` should use them).
=> Add `roc dev` subcommand

crates/compiler/solve/src/ability.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/reporting/tests/test_reporting.rs
Supports stuff like
```
decoded = Str.toUtf8 "{\"first\":\"ab\",\"second\":\"cd\"}" |> Decode.fromBytes Json.fromUtf8
when decoded is
Ok rcd -> Str.concat rcd.first rcd.second
_ -> "something went wrong"
```
=> Allow inferred flex vars inside type constructors bound to an ability

ci/package_release.sh
The lib folder was previously introduced to prevent needing `crates/compiler/builtins/bitcode/src` but the nightly releases did not make use of it yet. Now they do :)
=> add lib folder to nightly releases

crates/compiler/fmt/src/expr.rs, crates/repl_test/src/tests.rs
REPL inputs are being parsed as `PlainLine`. This PR formats `PlainLine` string literals containing `\n` as triple-quoted block strings.
This works (as far as I can see) because the regular code formatting will parse `"\n"` as a `Line` containing `EscapedChar`, so the source code formatting will not be impacted by this change.
Closes #3793.
=> Fix invalid multiline string output in REPL

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/main.rs, crates/compiler/mono/Cargo.toml, crates/compiler/mono/src/ir.rs, crates/compiler/test_mono/Cargo.toml, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs
Rather than using `tracing` or similar crates we shim through a `roc_tracing` crate instead. Just added two logs for now. I'll add more after review if we agree this is okay.
=> Add a roc_tracing crate and basic tracing in mono

Cargo.lock, crates/cli/src/main.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs
Already starting to learn some interesting stuff. For example the sizes of massive lambda sets in false-interpreter:
```
2022-08-23T20:39:38.708260Z DEBUG roc_mono::layout: building lambda set layout var=66 size=(39, 14, 686)
2022-08-23T20:39:38.722131Z DEBUG roc_mono::layout: building lambda set layout var=3941 size=(37, 13, 677)
2022-08-23T20:39:38.722159Z DEBUG roc_mono::layout: building lambda set layout var=5519 size=(5, 3, 6)
2022-08-23T20:39:38.722176Z DEBUG roc_mono::layout: building lambda set layout var=5544 size=(3, 2, 3)
2022-08-23T20:39:38.722189Z DEBUG roc_mono::layout: building lambda set layout var=5550 size=(1, 1, 1)
2022-08-23T20:39:38.722216Z DEBUG roc_mono::layout: building lambda set layout var=5548 size=(1, 1, 1)
2022-08-23T20:39:38.722257Z DEBUG roc_mono::layout: …
```
=> Add traces for external specializations, specialization storage subs, and lambda set depths.

.github/workflows/test_nightlies.yml, ci/get_latest_release_url.sh
Downloads the latest nightly release for macos apple silicon and checks if the hello world example can be built and run successfully.
=> macos m1 nightly cron tests

.github/workflows/nightly_linux_x86_64.yml, Earthfile, ci/www-repl.sh, crates/repl_wasm/build-www.sh
The current process is:
- I build the web REPL every so often by running a script in the repo.
- This produces a .wasm and a .js file
- I commit those to a branch on one of my unused GitHub repos and push it
- Whenever our website is deployed, Netlify runs `www/build.sh`, which grabs a .zip from my repo, unzips the .wasm and a .js file, and moves them to a certain folder under www/build
After this PR
- Our nightly build adds an extra step to build that archive along with the various other artifacts
- We change the Netlify deployment script to download the archive from the Roc releases, instead of my repo (this wasn't possible when Roc was private)
=> ci: create a CI script to include the web REPL in nightly builds

crates/glue/src/rust_glue.rs
=> Use repr(transparent) for single-tag union glue

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/compiler/load/src/lib.rs, crates/docs_cli/Cargo.toml, crates/docs_cli/src/main.rs, crates/repl_expect/src/lib.rs
- boilerplate
- more boilerplate
- thread fx expects to the runner
- expect-fx runner implementation
- get expect-fx to actually run
- improve how we deal with the expect memory buffer
- fix compile error in test
- fix linux nightly, update checkout action
- re-enable cron
- fix merge conflict
- macos m1 nightly cron tests
- yml formatting fix
- need checkout for ci script
- typo
- more exact grep pattern
- change trigger from PR to cron
- Change repl behavior and instructions around quit
- mention recommended forking strategy
- Replace snapshot of subs/layout directly with "TypeState" snapshots
- Get rid of a redundant subs snapshot
- improved lib dir error msg
- clippy
- Add Mostly Void to Authors
- Remove duplicate AUTHORS entry
- put important text in bold
- disable subs caching on …
=> windows build cli

www/build.sh
Update the website build script to download the web REPL from our nightly builds instead of a personal repo belonging to me.
This will PR not pass CI until there is actually a nightly build to download! We'll have to wait until the day after #3817 is merged, then rerun CI.
=> Use nightly build of REPL when deploying the website

getting_started/linux_x86.md
I assume that we want to support non-Debian-based distros, and I assume that combining the update & install steps is safe.
Signed-off-by: Jan Van Bruggen <JanCVanB@users.noreply.github.com>
=> Add RPM/Fedora alternatives to Debian/Ubuntu commands

crates/cli/src/build.rs, crates/cli/src/lib.rs, crates/compiler/build/src/link.rs, crates/compiler/builtins/bitcode/build.zig, crates/compiler/builtins/build.rs, crates/compiler/gen_llvm/src/llvm/build.rs, examples/benchmarks/platform/host.zig
attempt to compile for windows from any platform. 
This now works
```
target/debug/roc build --precompiled-host=false --linker=legacy --target=windows64 examples/platform-switching/zig-platform/rocLovesZig.roc
```
but running it does not yet work with wine, for me. It would be cool if someone on windows could compile this branch and run the above command within WSL, and then try to run the exe on windows.
=> windows cross compilation

getting_started/README.md, getting_started/linux_x86.md, getting_started/macos_apple_silicon.md, getting_started/macos_x86.md, getting_started/other.md, getting_started/windows.md
- Adhere to [this Markdown style
guide](https://github.com/DavidAnson/markdownlint).
- Simplify & clarify various steps.
=> Reformat the "getting started" guides for clarity & cleanliness

crates/linker/src/lib.rs
simple refactor that makes it clear that we're fully rewriting these structs, rather than updating just some of the fields
=> surgical linker: use struct initialization syntax

crates/roc_std/src/lib.rs
Fixes UB in roc_std as discussed in #3897.
Signed-off-by: isaacthefallenapple <isaacthefallenapple@gmail.com>
=> Replace unsound `MaybeUninit` deref with `ptr::copy`

crates/compiler/load_internal/src/file.rs, crates/compiler/module/src/symbol.rs
In particular, don't run expects that come from modules with a different
package qualification (including subpackages; we can loosen this
restriction later), or builtins when run on userspace apps/interfaces.
Closes #3722
=> Only compile and run expects that belong to the same package

crates/compiler/derive_key/src/decoding.rs, crates/compiler/derive_key/src/encoding.rs, crates/compiler/derive_key/src/util.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_derive/src/decoding.rs, crates/compiler/test_derive/src/encoding.rs, crates/compiler/test_derive/src/util.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs
A key thing about unbound extension variables is that they provide no information. For example, given a type `[A Str]b`, one cannot do anything with `b` until it is resolved to a concrete type. This applies to implementations of abilities as well. For encoding/decoding, the most we can do is work on the concrete part of the type. Since only ground types can be fed into derived implementations, doing this is fine.
=> Support bound and unbound extension variables in deriving

crates/linker/src/lib.rs
strictly moving code around, to make the flow of `preprocess` easier to follow
=> surgical linker: extract finding surgeries in text

crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/tests/test_fmt.rs
As mentioned in this [Zulip topic ("Multiline string formatter bug")](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Multiline.20strings.20formater.20bug), formatting multi-line strings leads to invalid code. For example:
```
renderTree = \node ->
when node is
Data load ->
"""
\(load.text)
text!
"""
Link load ->
"""
Link!
Link!
"""
Tag load ->
"""
Tag!
Tag!
"""
```
is formatted to
```
renderTree = \node ->
when node is
Data load ->
"""\(load.text)
text!"""
Link load ->
"""Link!
Link!"""
Tag load ->
"""Tag!
Tag!"""
```
This PR will always put `"""` on separate lines and therefore always format multi-line strings on multiple lines. The single-line block string case is removed completely.
While multi-line strings are parsed as `Plaintext` containing a `\n` at the end of each …
=> Fix multiline string formatting

crates/linker/src/lib.rs
This is an attempt to fix #3883, though I'm not totally sure it does. At least for me, I don't see faster rebuilds of rust hosts, but also the rebuild time is already very close to zig.
So, I'm not sure it fixes that problem, but I think it's a useful feature anyway.
=> surgical linker: don't generate dynhost if it's unchanged

crates/compiler/builtins/roc/Str.roc, crates/compiler/test_gen/src/gen_str.rs
`Str.splitFirst` had a bug where if you passed the same string twice, it returned `Err NotFound`.
e.g.
it was:
```
Str.splitFirst "foo" "foo" == Err NotFound
```
With this fix it is:
```
Str.splitFirst "foo" "foo" == { before: "", after: "" }
```
I also added tests to both splitFirst and splitLast to catch this bug in the future.
[this](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/splitFirst.20doesn't.20work.20properly) zulip topic has more info.
=> Str splitfirst bugfix

.github/workflows/nightly_linux_x86_64.yml
Building it on 22.04 uses a newer libc than available on 20.04, which doesn't work.
Building on 20.04 does also work on 22.04.
- Also includes SHA and date in filename again.
=> build nightly on ubuntu 20.04

crates/compiler/late_solve/src/lib.rs, crates/compiler/unify/src/unify.rs
See https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/compilation.20time/near/296454046. Minimal speedup elsewhere but nice for pathological cases. Regardless, it's always better to do less work.
=> Attempt occurs checks for recursive lambda sets only during monomorphization

crates/compiler/gen_llvm/src/llvm/build.rs
Windows seems to interpret the C calling convention rather differently. We're still using zig 0.9 which has some known bugs in how it handles calling conventions. So, this PR is tiny with an unscientific fix. Hopefully we can get some additional test coverage on windows with this fix. Whenever it does not work, it will fail loudly because the LLVM IR is not compatible. So this has upsides if it works, and no real downsides I think.
For future reference, the signature for 
```llvm
define void @roc_builtins.str.to_int.i64(%"num.NumParseResult(i64)"* noalias nocapture nonnull sret(%"num.NumParseResult(i64)") %0, %str.RocStr* nonnull byval(%str.RocStr) align 8 %1) local_unnamed_addr #1 {
```
whereas on unix this just returns a `{ i64, i8 }`.
to test, please run
```
> cargo test-gen-llvm …
```
=> windows c calling convention

examples/interactive/README.md, examples/interactive/cli-platform/Path.roc, examples/interactive/cli-platform/Stdin.roc, examples/interactive/cli-platform/Stdout.roc, www/build.sh
For example: https://www.roc-lang.org/examples/cli/Http
These now get regenerated whenever we push an update the website!
Also added a link to the docs in the `examples/interactive` README.
=> Generate and host CLI platform example docs

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/str.zig, crates/compiler/builtins/bitcode/src/utils.zig
I spotted a few places in our Zig builtins where we could make better use of the capacity field.
I decided to look at this while working on the HTML example project, which involves a lot of string concatenation. In that program I pre-calculate the size of string needed, and do one `Str.reserve` before doing all the `Str.concat` stuff.
But reading through the Zig code I could see we hadn't really implemented things yet for this to actually work. These changes should help.
=> Use capacity better for realloc

crates/compiler/build/src/link.rs, crates/compiler/builtins/bitcode/build.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/build.rs, crates/compiler/builtins/src/bitcode.rs, crates/linker/src/lib.rs
get some infrastructure set up to use the surgical linker in cross-compilation to windows. This is not enabled by default yet: you have to toggle a boolean in the linker code to use it.
also we don't have working surgical linking yet, so this process will panic in the linker code.
=> Windows surgical cross compiling

crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/build_str.rs, crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/test_gen/src/gen_records.rs, crates/compiler/test_gen/src/helpers/llvm.rs
`RocDec` is passed differently on windows. I also found and fixed some other llvm IR mismatches on windows
=> windows RocDec & Zig 

getting_started/linux_x86.md, getting_started/macos_apple_silicon.md, getting_started/macos_x86.md
These installation steps are not just for examples, they're for all apps!
=> Reword "for examples" to "for apps" in installation guides

crates/compiler/collections/src/vec_map.rs, crates/compiler/late_solve/src/lib.rs, crates/compiler/late_solve/src/storage.rs, crates/compiler/mono/src/ir.rs, crates/compiler/types/src/subs.rs
This PR makes sure that when a module A exports a type to a module B, we reuse type variables already-exported to module B. Especially when there is a lack of let-generalization, this yields a nice speedup for modules that require a lot of similarly-related types from other modules. That is, the pathological case I've been working with halves in compile-time; for other programs there I could actually measure no difference, but the compile time doesn't get worse, so I think this is strictly positive. Benchmarks below.
```
$ hyperfine --warmup 10 'target/release/roc build examples/false-interpreter/False.roc --precompiled-host true' '../roc2/target/release/roc build examples/false-interpreter/False.roc --preco
mpiled-host true'
Benchmark 1: target/release/roc build …
```
=> Cache variables sent to a module's external specializations in mono

crates/compiler/test_gen/src/helpers/llvm.rs
extend the lifetime of a dll until after an assert. Hopefully this fixes segfaults on windows
=> keep dll loaded

.github/workflows/nix_macos_apple_silicon.yml, crates/cli/Cargo.toml, crates/cli/src/build.rs, crates/cli/src/lib.rs, crates/cli/tests/cli_run.rs, crates/cli_utils/src/helpers.rs, crates/compiler/build/src/program.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/types/src/num.rs, crates/editor/editor-ideas.md, crates/error_macros/src/lib.rs, crates/glue/tests/test_glue_cli.rs, crates/repl_test/src/tests.rs, crates/reporting/src/report.rs, www/public/repl/repl.js
Closes #3630, plus various related rephrasings!
"Host" is an unclear word for Roc app developers - is it the platform? part of the platform? a language? a machine? a CPU architecture? The word "platform" is similarly unclear sometimes (is it a CPU architecture?), but at least in the context of Roc that word (when unaccompanied by any clarifying adjective) should be reserved to mean "Roc platform" (the "Roc" part should just be implied, similarly to how "app" without any adjective just means "Roc app").
There are various overloadings of these two words in the repo, so this PR seeks to make vocabulary significantly more consistent for app developers, platform developers, and compiler contributors (though not enforcing the same vocabulary across those three contexts).
Additionally, this PR …
=> Reword "host" to "platform" for app developers

crates/docs/src/lib.rs
* No more unnecessary parens in type annotations
* Empty records now print as `{}` instead of `{ }`
* Instead of hardcoding `roc/builtins 1.0.0` at the top, just says "documentation" for now (so it's not actively wrong when it's not docs for builtins)
=> `roc docs` fixes

crates/repl_wasm/build-www.sh, www/public/repl/index.html, www/public/repl/repl.css, www/public/repl/repl.js
It turns out that the Roc compiler .wasm module can take a while to load. It's 1.4MB compressed. If you try to use the REPL in that time, you just see a JavaScript error in the "console" panel. Not great.
Instead let's disable the input during that time, and show a loading message.
Closes #4025
=> Disable Web REPL input until the compiler .wasm has loaded

.github/workflows/nightly_macos_x86_64.yml
The latest nightly timed out running the tests.
=> increase macos x86 nightly timelimit

crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/test_gen/src/gen_tags.rs
Resolves a discussion on Zulip: https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/When.20recursive.20structs.20aren't.20recursive
=> Complex bitcast recursive tag union pointers when we need them to be opaque

crates/compiler/mono/src/layout.rs, crates/compiler/test_mono/generated/num_width_gt_u8_layout_as_float.txt, crates/compiler/test_mono/src/tests.rs
Currently things like `1 / 200` lead to a miscompilation because we type
`200` (and as a result, both `1` and the division result) as a ranged
number with width >= U8. During mono that forces the number to become an
`I64` because our logic was that a ranged number can only become a float
if it's at least as wide as an I8. But this is incorrect; as long as the
type is wrapped in `Frac` constructor and it's a ranged number (and not
a ranged int), it should become a fractional type.
```
» 1 / 200
0.005 : Float *
```
Closes #4047
=> Allow any numeric range to become a float

crates/linker/src/pe.rs
preprocess the host .exe to make space for code and data sections from the app
This pass produces a working binary (verified with wine) that has the dummy sections
=> windows linker preprocess exe

crates/roc_std/src/roc_dict.rs, crates/roc_std/src/roc_list.rs, crates/roc_std/src/roc_set.rs
`RocDict` used a tuple of `(K, V)`, which wasn't FFI-safe (the error messages say that tuples have an unspecified layout.) This changes to structs, which do have a specified layout.
I was able to use this to get environment variable working in rbt, but I'm not sure what other kinds of testing would be appropriate here.
=> make RocDict FFI-safe

getting_started/linux_x86.md, getting_started/macos_x86.md
It can be undesirable to extract the nightly in the current (likely downloads) dir.
=> extract tar to dir

crates/compiler/can/src/exhaustive.rs, crates/compiler/exhaustive/src/lib.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/test_mono/generated/match_on_result_with_uninhabited_error_branch.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/types/src/subs.rs, crates/compiler/unify/src/unify.rs, crates/reporting/src/error/type.rs, crates/reporting/tests/test_reporting.rs
This PR makes it so that programs like
```
x : Result Str []
x = Ok "bluetrapese"
when x is
Ok s -> s
```
Now typecheck and compile, when previously they would yield an error that the `Err _` branch is not covered. In situations like the above, the `Err _` branch need not be covered, because that branch has an uninhabitable constructor - since the type of `x` is `[Ok Str, Err []]`, only values of constructor `Ok` can ever be created!
Closes #4054
=> Don't require pattern matching branches that are uninhabited 

ci/bench-runner/src/main.rs, crates/cli_utils/src/bench_utils.rs
The "🔨 Rebuilding platform...\n" message was recently modified to be sent to stderr so we can no longer just check if stderr was empty.
=> Fix benchmarks

CONTRIBUTING.md, getting_started/README.md
This document summarizes larger implementation- or research-heavy projects that may be suitable for someone who wants to contribute to Roc via a self-contained project. Most of these projects are expected to require sustained effort, which also makes them possibly suitable for academic theses.
Feel free to message me on Zulip to get edit rights to the document!
=> Advertise larger Roc project ideas in CONTRIBUTING

Cargo.lock, crates/compiler/builtins/roc/List.roc, crates/compiler/mono/Cargo.toml, crates/compiler/mono/src/decision_tree.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_mono/generated/match_on_result_with_uninhabited_error_branch.txt, crates/compiler/test_mono/generated/unreachable_branch_is_eliminated_but_produces_lambda_specializations.txt, crates/compiler/test_mono/generated/unreachable_void_constructor.txt, crates/compiler/test_mono/src/tests.rs, examples/benchmarks/platform/host.zig
With this, we now eliminate layouts like `[Ok Str, Err []]` to exactly `Str` at runtime. So now zero-size tags are zero-cost.
Addresses the attempt to do so in https://github.com/roc-lang/roc/pull/3465
Blocked on #4073
=> Unwrap layouts containing void layouts as newtypes

crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/module/src/symbol.rs
Previously, all unqualified modules imported in a platform would be prefixed with the platform shorthand. This is incorrect for builtins, which should always resolve to the builtin module unless they have an explicit namespace.
Closes #4084
Note: the linked #4084 mentions other issues that I'll break out into separate issues and patches. The changes are related but different in their sources, so I want to unblock folks with this patch, and address the other problems OOB.
=> Properly import builtin modules in platforms

crates/compiler/test_mono/generated/unreachable_void_constructor.txt, crates/compiler/test_mono/src/tests.rs, crates/roc_std/src/roc_dict.rs, crates/roc_std/src/roc_list.rs
It turns out that `RocDict`'s `IntoIterator` was broken: it segfaulted when reading values! After some experimentation, it turns out that `RocList.get` was accessing the wrong memory (it appears to have been wrong for short lists, at least?)
In `RocDict`'s case, however, iterating over a slice of the list instead of manipulating memory directly works fine, so I've just done that and dropped the problematic `get` implementation for now (as `RocDict`'s' `IntoIterator` was the only consumer.) If some brave soul wants to try implementing `get` again, great! But that's not me right now, and I don't want to leave broken code in the codebase waiting to bite someone else.
@zwilias: this fixes the segfault we saw yesterday!
=> fix Dict's IntoIterator

crates/linker/src/pe.rs
removes a bunch of hardcoding and extracts logic into functions.
In particular, we now preprocess the host. That adds two (at the moment) extra sections to the section table: .text (code) and .rdata (read-only data). 
Next we open up the app and find what symbols it exposes, and collect all the sections that we want to copy over to the host binary. We join all text sections into one, and all rdata sections into one. 
These are then copied, and a bunch of numbers need to be updated (and these need to be rounded to particular alignments).
I think this is all functionality we need for the `app -> host` direction. We might need the `.data` section too, but I don't think we need it? anyhow it's easy to add.
Next up, fighting the system linker to make the "host -> app" direction work.
=> Windows preprocess link

crates/compiler/load_internal/src/file.rs
[#4052](https://github.com/roc-lang/roc/issues/4052)
Improve error message by adding the directory path when trying to read a directory
=> Add directory path to error message when trying to read directory

crates/compiler/load_internal/tests/test_load.rs, crates/linker/src/generate_dylib/pe.rs, crates/linker/src/lib.rs, crates/linker/src/pe.rs
the magic sauce is the `-rdynamic` argument to zig, which ensures that host symbols are in the `.exe`s export section, and we can link them up with the code from the app.
=> windows surgical linker: call host functions from the app

crates/compiler/load_internal/src/file.rs
I tried out a recently improved error message and improved it further :)
- before:
- after:
=> Improve file problem msg

crates/cli/src/build.rs, crates/compiler/build/src/program.rs, crates/linker/src/lib.rs, crates/linker/src/pe.rs
keeps the roc application bytes in memory for a bit longer. When using the surgical linker, they are never written to disk.
=> keep app in memory

examples/interactive/cli-platform/Arg.roc
Previously, missing arguments would be reported incorrectly by the CLI
platform's arg parser, as [discussed on Zulip](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Args.20for.20CLI.20platform.3F/near/299068775).
This fixes that.
=> Localize parsing errors in the arg parser

crates/linker/src/elf.rs, crates/linker/src/generate_dylib/mod.rs, crates/linker/src/lib.rs, crates/linker/src/pe.rs
functional changes are small
- support static relocations in elf
- support inter-section relocations in the app (e.g. the code section uses a symbol in the rodata section; we have to fix that up after copying the two sections over)
but I renamed some imports, and cleaned up the windows tests we it's easier to add more zig host/app tests
=> PE inter-section relocations

crates/ast/src/lang/scope.rs, crates/compiler/can/src/def.rs, crates/compiler/can/src/module.rs, crates/compiler/can/src/scope.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/tests/fixtures/build/app_with_deps/Primary.roc, crates/compiler/load_internal/tests/fixtures/build/interface_with_deps/Primary.roc, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/module/src/symbol.rs, crates/compiler/problem/src/can.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/test_gen/src/helpers/dev.rs, crates/compiler/test_gen/src/helpers/llvm.rs, crates/glue/src/load.rs, crates/glue/tests/helpers/mod.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/tests/test_reporting.rs, examples/interactive/args.roc, examples/parser/Parser/CSV.roc, examples/parser/Parser/Str.roc, examples/parser/parse-movies-csv.roc
Also adds new reporting for when you import a value but don't actually use it. There are additional things to do, see #4096, but I don't think they're important to do in this patch.
=> Improve how builtin modules and their types are imported

Cargo.lock, crates/linker/Cargo.toml, crates/linker/src/lib.rs, crates/linker/src/pe.rs
turns out that actual windows is stricter than wine when it comes to loading programs. The current examples that work with wine don't run on actual windows, so I'm trying to validate our code piece-by-piece. 
This PR improves the preprocessing code so we can produce a runnable `preprocessedhost`. Normally that does not make sense, because that binary misses functions from the app. But if we don't even link an app, we now at least produce a valid binary.
=> Windows preprocessing

crates/compiler/builtins/roc/Hash.roc, crates/compiler/module/src/symbol.rs, crates/compiler/solve/src/ability.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/types/src/subs.rs, crates/reporting/tests/test_reporting.rs
This implements type-level checks that types can and cannot implement the `Hash` ability.
Part of #4195
=> Obligation checking for the `Hash` ability

crates/compiler/can/src/builtins.rs, crates/compiler/derive/src/hash.rs, crates/compiler/derive_key/src/hash.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/module/src/low_level.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/ir.rs, crates/compiler/solve/src/specialize.rs, crates/compiler/test_derive/src/hash.rs, crates/compiler/test_derive/src/pretty_print.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/unify/src/unify.rs
This PR builds upon #4209 to implement more performant hashers for tag unions. The main changes are:
- Derive hashing for recursive tag unions correctly (2517695ce4406532b67c64be906e179cff965d76)
- Do not hash discriminants for tags that are newtypes. In such cases the discriminant doesn't exist, or can be seen as constant, so hashing it provides no value to the hash. (a308ebb38c8a206987a4f9a1b75ba90947b2b1a6)
- Implement hashing discriminants for tags that need them in the derived implementation itself, rather than relying on a LowLevel. There are two benefits to this - (1) we can choose a smaller byte size (u8) for the discriminant in the common case, rather than having to always hash the upper bound of discriminant sizes, and (2) it gets rid of a low-level that we otherwise don't need. …
=> Improvements to hash deriving for tag unions

www/public/repl/repl.js
One line in the Web REPL was using the wrong DOM property, which caused it to silently throw an exception whenever it tried to append a new REPL output! Thankfully someone reported it in Zulip.
A DOM node can be either a Text node or an Element. `.childNodes` contains both, but `.children` only contains Elements. I was using `.childNodes` but assuming it would always be an Element. Switching to `.children` fixes it.
I'm not sure when this stopped working! The last PR added a loading state so I guess it was probably then. I definitely tested it at the time. 🤔 Maybe I reformatted the HTML just before pushing it, and ended up inserting a whitespace Text node by accident. 🤷 
After this is merged we should also update www from main.
=> Web REPL: ensure we only try to append to DOM Elements, not text nodes

www/public/repl/repl.js
Closes #4232
When you just hit Enter in the REPL, we try to turn the string `'\n'`, into a Roc program for the compiler, and it doesn't parse.
At some point in the past, hitting Enter used to give us an empty string rather than a newline, and repl.js was still handling the empty string. But at some point we added support for multi-line expressions and things changed.
The fix is to trim the input string before using it. I also decided to make it print an empty line in this case. You might want to put some space between your expressions.
=> www: handle empty input in web REPL

.github/workflows/nightly_macos_x86_64.yml
I believe updates to the VM image used by github require this change.
=> updated LLVM_SYS_130_PREFIX

crates/compiler/builtins/roc/Json.roc, crates/compiler/can/src/copy.rs, crates/compiler/can/src/def.rs, crates/compiler/can/src/exhaustive.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/src/module.rs, crates/compiler/can/src/pattern.rs, crates/compiler/constrain/src/builtins.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/mono/src/ir.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_derive/src/pretty_print.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/types/src/num.rs, crates/reporting/tests/test_reporting.rs, examples/parser/Parser/CSV.roc, examples/parser/Parser/Str.roc
Pretty excited about this one. As discussed on Zulip and elsewhere previously, we'd like single quote literals to behave like ranged number literals - we give them a minimum bounded size, but the exact number type they take on can be determined from the context, as long as the contextual type is as least as large as the lower bound.
That means things like this are now possible:
```
digits : List U8
digits = List.range '0' ('9' + 1)
List.contains digits '5'
```
whereas before you would have to use a bunch of casts here. See the diff for how this gets rid of some utility code in the Json and CSV parsers, making things easier to read (and more performant, since we need less casts).
Closes #2672
=> Single-quote literals behave like ranged numbers

examples/cli/cli-platform/Cargo.lock, examples/cli/cli-platform/Cargo.toml, examples/cli/cli-platform/src/lib.rs
Doesn't give you the line number, but is still super helpful:
```
Roc hit a panic: integer subtraction overflowed!
Printing backtrace. If it looks wrong, try rerunning your app without `--optimize` and with `--linker=legacy`
0: backtrace::backtrace::libunwind::trace
at /Users/bren077s/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
backtrace::backtrace::trace_unsynchronized
at /Users/bren077s/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
1: backtrace::backtrace::trace
at /Users/bren077s/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
2: backtrace::capture::Backtrace::create
at /Users/bren077s/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3. …
```
=> Add a backtrace to panics on the cli platform

getting_started/README.md, getting_started/linux_x86_64.md, getting_started/macos_x86_64.md
In the `getting_started` doc I accidentally wrote `x86` where I meant `x86_64`.
=> `x86` should be `x86_64`

crates/compiler/builtins/roc/List.roc
I was reading through the online docs. The description of the List data structure was out of date, and the refcounting example seemed incorrect.
=> Corrections for List docs

crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs
The mutual-recursion checks does not admit types that are not function types; because Roc is strict, only functional values can be involved in mutual recursion. However, this check was exercised by checking the head constructor of a type, which is not the correct way to do it. Aliases and opaque types may in fact be function types as well, so we must chase their actual contents.
Closes #4246
=> Correctly check mutual functional recursion between opaque types

examples/cli/cli-platform/Effect.roc, examples/cli/cli-platform/Stderr.roc, examples/cli/cli-platform/Stdout.roc, examples/cli/cli-platform/src/lib.rs
=> Add newline-less `Stdout.write` & `Stderr.write` to `cli-platform`

crates/docs/src/static/search.js
I thought it maybe helpful to focus the search box in Docs. I find I am constantly scrolling back and forth so being able to immediately focus the search box helps to find the function I am looking for.
=> roc docs add feature to focus search box using ⌘F, CTRL F, or F3 

Cargo.lock, ci/bench-runner/Cargo.lock, ci/bench-runner/Cargo.toml, crates/ast/Cargo.toml, crates/cli/Cargo.toml, crates/cli_utils/Cargo.lock, crates/cli_utils/Cargo.toml, crates/code_markup/Cargo.toml, crates/compiler/test_mono_macros/Cargo.lock, crates/glue/tests/fixture-templates/rust/Cargo.lock, crates/glue/tests/fixture-templates/rust/Cargo.toml
I'm a Rustling, but I think this better aligns with our current project status. Sometimes I see lots of version numbers in stdout, and the versions seem to alternate randomly between v0.1.0 and v0.0.1 - I hope this makes it more consistent, as well as obvious which packages are Roc's.
=> De-bump all v0.1.0 Roc packages to v0.0.1

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/utils.zig
It is implemented wrong and not used anywhere. Just removing it to clean up. Can be added correctly later if it is needed.
=> [Easy Review] Remove RocResult from utils.zig

crates/docs/src/static/index.html, crates/docs/src/static/search.js, crates/docs/src/static/styles.css
It turns out `/` on Firefox is already search, and we don't want to override that.
Also adds a tip to make the shortcut discoverable:
=> Search docs with S instead of /

www/public/index.html
The link to the web REPL results in a 404 because the `href` isn't specific enough and the browser interprets it as a relative URL.
=> www: fix REPL link

crates/docs/src/lib.rs
=> Fix prefetch links in the Standard Library page

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/str.zig, crates/compiler/builtins/bitcode/src/utils.zig, crates/compiler/builtins/roc/Str.roc, crates/compiler/test_gen/src/gen_str.rs, crates/roc_std/tests/test_roc_std.rs
Also, cleans up the alloc and realloc api for both list and str.
Updates Str.reserve to match List.reserve.
=> Add capacity growth to RocStr

Cargo.lock, Cargo.toml, crates/compiler/can/Cargo.toml, crates/compiler/can/src/abilities.rs, crates/compiler/can/src/module.rs, crates/compiler/collections/src/vec_map.rs, crates/compiler/collections/src/vec_set.rs, crates/compiler/load/Cargo.toml, crates/compiler/load/build.rs, crates/compiler/load/src/lib.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/src/lib.rs, crates/compiler/serialize/Cargo.toml, crates/compiler/serialize/src/bytes.rs, crates/compiler/serialize/src/lib.rs, crates/compiler/types/Cargo.toml, crates/compiler/types/src/subs.rs, crates/compiler/types/src/unification_table.rs
Currently, we only cache the `Subs` of builtin modules during the solve phase. But the type information for a solved module consists of more than Subs; it also includes the abilities store for the module, which is the cornerstone of how abilities work. This patch adds a custom serialization of the abilities store to a byte scheme so that we can cache and resolve modules that expose abilities or ability implementations as well. Caching for `Encode`, `Decode`, and `Hash` is turned on as a result.
@folkertdev and I talked about the approach here briefly. Initially we thought about bringing in serde, but after looking at that for a short while, I realized that's not the way to go, because serde is very viral and will require a bunch of base crates in the compiler to depend on it. The flat …
=> Serialize the abilities store and solved implementations for builtins

.github/workflows/nightly_macos_apple_silicon.yml
I added the version to the filename for macos x86_64 so I think it's good to add it to the apple silicon release as well for consistency and clarity.
=> add os version macos nightly

default.nix, flake.nix
Adds the ability to run `nix build` in the project, which will build the package derivation inside Nix.
I also changed the hashes in default.nix to match those in flake.lock - in fact, I'd consider removing them from default.nix and relying on flakes to do the build, but I didn't want to make possibly breaking changes.
=> Add default build to flake outputs

crates/compiler/builtins/bitcode/src/list.zig
fixes #4351
This also adds an extra optimization where we keep list b if it is unique and list a is not. This can potentially avoid a call to malloc.
=> Fix memory leak in List.concat

Cargo.lock, crates/compiler/can/src/builtins.rs, crates/compiler/can/src/copy.rs, crates/compiler/can/src/effect_module.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/src/module.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/derive/src/decoding.rs, crates/compiler/derive/src/encoding.rs, crates/compiler/derive/src/hash.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/ir.rs, crates/compiler/test_derive/src/pretty_print.rs, crates/repl_expect/Cargo.toml, crates/repl_expect/src/run.rs
@folkertdev this should unblock your work with abilities used in expects as we discussed on Zulip. I haven't added a test, since expects inside bodies don't seem to work yet. But I ran a smoke test with the example
```
main = 
expect 1 == 2
""
```
and the generated mono is correct.
=> Resolve ability specializations looked up in expects

crates/roc_std/src/lib.rs, crates/roc_std/src/roc_list.rs, crates/roc_std/src/roc_str.rs, crates/roc_std/tests/test_roc_std.rs
This was a request that came up when using Roc types with threads and async. They get quite inconvenient to pass from one thread to the next. These Wrappers should make that simpler.
=> Send safe roc list

crates/compiler/build/src/link.rs, crates/linker/src/pe.rs
math was incorrect if the `.rdata` section was bigger than 4k, and the `.dll` data is not in the first 4k page.
=> refine relocation location

crates/compiler/can/src/def.rs, crates/compiler/can/src/module.rs, crates/compiler/can/tests/test_can.rs, crates/compiler/solve/tests/solve_expr.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/tests/test_reporting.rs
Programs like
```
after : ({} -> a), ({} -> b) -> ({} -> b)
fx = after (\{} -> {}) \{} -> if Bool.true then fx {} else {}
```
are legal because they always decay to functions, even if they may not
look like functions syntactically. Rather than using a syntactic check
to check for illegally-recursive functions, we should only perform such
checks after we know the types of values.
Closes #4291
=> Make sure self-recursive checks only happen after typechecking

CONTRIBUTING.md, crates/compiler/builtins/roc/Dict.roc, mlc_config.json
This MR adds a command for testing the Dict module in the CI. I also added an example of how to use `Dict.update` with instructions on how to add and view said comments.
=> Add Dict module to the testing CI

CONTRIBUTING.md
We should recommend github's edit button for simple changes, those are signed automatically.
=> simple signing workaround

crates/compiler/builtins/roc/Decode.roc, crates/compiler/builtins/roc/Dict.roc, crates/compiler/builtins/roc/Set.roc, crates/compiler/can/src/abilities.rs, crates/compiler/can/src/def.rs, crates/compiler/can/src/derive.rs, crates/compiler/can/src/lib.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/module/src/symbol.rs, crates/compiler/solve/src/ability.rs, crates/compiler/solve/src/module.rs, crates/compiler/solve/src/specialize.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/types/src/types.rs, crates/reporting/src/error/type.rs, crates/reporting/tests/test_reporting.rs
[As discussed on Zulip](https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/Deriving.20ability.20impls.20for.20opaques)
See individual commits for details. This adds deriving support for Hash, Eq, Decoding, and Encoding.
We take care not to print errors observed in derived implementations; see the reporting tests.
Closes https://github.com/roc-lang/roc/issues/4228
=> Auto-derive ability implementations for opaques in canonicalization

crates/compiler/can/src/constraint.rs, crates/compiler/can/src/expected.rs, crates/compiler/solve/src/solve.rs
This is part one of addressing the present issues with emplacing type directly where type variables should be reused. Now, when an `Index<Type>` is converted to a variable in solving, we leave the converted variable in the `Type`'s place. Specifically, we keep an index to a `Cell<Type>`.
Note that this transformation is only temporary, it will be removed once we merge this with the `Type` SoA representation, but it is needed in the meantime as I transform the `Constrain` API to get rid of type-emplacement.
=> Leave variables behind when converting `Type`s to variables

crates/compiler/can/src/constraint.rs, crates/compiler/constrain/src/builtins.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/module.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/solve/src/solve.rs
This is part 2/many of getting rid of type emplacement. With this patch, we have most of the surface API of constraining take `Index<Type>` rather than a `Type` directly. With #4398, and later Types SoA, this will mean that `Type`s will be reused in such positions, rather than instantiating fresh type variables.
A follow up or two will clean up the rest of the API surface two, but avoiding batching to make incremental landing easier.
Blocked on #4398
=> Have most constraining APIs take a type index rather than `Type`

crates/compiler/parse/src/expr.rs
I'm making a separate PR for this because it's a substantial change but very self-contained: it extracts a way to parse a single def instead of only being able to parse an entire `Defs` at once.
This will be useful in the repl for detecting when the user has entered (for example) `x = 5` and we want to record that in the state and continue, rather than treating it as an incomplete def expression.
=> Extract parse_single_def

CONTRIBUTING.md
Newer contributors may have difficulty finding their way toward intermediate issues if we don't mention them.
=> mention intermediate issues

crates/README.md, crates/ast/src/lib.rs, crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/cli_utils/src/lib.rs
WIP - Need assistance. 
I've created a README.md for the Rust crates folder and linked to all of the sub-crates. Where I can I have added a brief description for each library. However it is difficult for me to piece it all together. 
I would appreciate any assistance you can provide adding to this. 
I have ran the the following with no issues.
```
cargo test
cargo fmt --all -- --check
cargo clippy --workspace --tests -- --deny warnings
```
=> adding crates/README.md for rust docs

crates/cli/src/format.rs, crates/compiler/fmt/tests/test_fmt.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/parse/benches/bench_parse.rs, crates/compiler/parse/src/blankspace.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/header.rs, crates/compiler/parse/src/ident.rs, crates/compiler/parse/src/module.rs, crates/compiler/parse/src/number_literal.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/src/pattern.rs, crates/compiler/parse/src/string_literal.rs, crates/compiler/parse/src/test_helpers.rs, crates/compiler/parse/src/type_annotation.rs, crates/compiler/parse/tests/test_parse.rs, crates/docs/src/lib.rs, crates/repl_cli/src/lib.rs
This removes the need to explicitly pass min_indent when using the parser combinators (as opposed to explicit `parse_` methods or closures).
In cases where we need to pass a _different_ `min_indent` to a nested parser, I introduce a variety of combinators - `reset_min_indent`, `set_min_indent`, `increment_min_indent`, and `absolute_column_min_indent`.
Note that this is purely a refactor, and doesn't change parser behavior. Eventually I'm planning on applying the rule described in #3655 more broadly, via a new combinator to replace many/most usages of `and!`.
My ultimate goal here is to evolve the current parser closer toward a purely combinator-based parser, at which point we can more easily transition smoothly to a formal(ish) grammar, or expand the meanings of combinators to include …
=> Refactor Parser trait to pass min_indent

Cargo.lock, crates/cli/src/build.rs, crates/cli_utils/Cargo.toml, crates/cli_utils/src/helpers.rs, crates/compiler/build/src/link.rs, crates/compiler/builtins/Cargo.toml, crates/compiler/builtins/build.rs, crates/compiler/test_gen/Cargo.toml, crates/compiler/test_gen/build.rs, crates/compiler/test_gen/src/helpers/llvm.rs, crates/compiler/test_gen/src/helpers/mod.rs, crates/editor/Cargo.toml, crates/editor/src/editor/mvc/ed_update.rs, crates/repl_wasm/Cargo.toml, crates/utils/src/lib.rs, crates/wasi-libc-sys/Cargo.toml, crates/wasi-libc-sys/build.rs
- Closes #4423: centralized commands for cargo, zig, and clang.
- Closes #3631: nice error messages for when rust, zig, or clang is not installed.
- Refactoring of `validate_output`; error messages now print the entire command with all arguments.
=> centralized commands, better errors, link build command refactoring

Cargo.lock, crates/compiler/can/src/exhaustive.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/exhaustive/Cargo.toml, crates/compiler/exhaustive/src/lib.rs, crates/compiler/solve/src/solve.rs, crates/compiler/unify/src/unify.rs, crates/reporting/src/error/type.rs, crates/reporting/tests/test_reporting.rs
Title says it all.
I've enumerated the algorithm I've used in the doc comments of `build_list_ctors_covering_patterns` in `exhaustive/src/lib.rs`. Please refer to that for documentation and an explanation of what this PR does.
Here are a few interesting uses and error messages:
```
» l : List [A, B]
…
… when l is
…     [] -> ""
…     [.., A] -> ""
── UNSAFE PATTERN ──────────────────────────────────────────────────────────────
This when does not cover all the possibilities:
6│>      when l is
7│>          [] -> ""
8│>          [.., A] -> ""
Other possibilities include:
[.., B]
I would have to crash if I saw one of those! Add branches for them!
```
```
» l : List {}
…
… when l is
…     [{}, .., _] -> ""
…     [_, .., {}] -> ""
…     [..] -> ""
── REDUNDANT PATTERN …
```
=> Exhaustiveness checking for list pattern matches

crates/compiler/mono/src/ir.rs, crates/compiler/test_gen/src/gen_primitives.rs
This patch continues to better support the compilation of polymorphic expressions by allowing us to distinguish captures of polymorphic expressions that require a non-default specialization. That's probably a lot of words that don't make much sense, so let's look at an example:
```
main =
ir = Ok ""
res =
Result.try ir \_ ->
when ir is
Ok "" -> Ok ""
_ -> Err Bad
```
this program generates two specializations for `ir` that must be fulfilled by the code generated for `main` - a specialization `(ir, Result Str [Bad])` which is the first argument to `try`, and a specialization `(ir#spec1, [Ok Str])` which is the capture of the closure passed to `try`. Previously, captures would not attempt to resolve symbol specializations, and instead use the default specialization, which in this case would …
=> Support monomorphic captures of body-polymorphic expressions in closures

crates/compiler/can/src/exhaustive.rs, crates/compiler/can/src/pattern.rs, crates/compiler/exhaustive/src/lib.rs, crates/compiler/mono/src/decision_tree.rs, crates/compiler/mono/src/ir.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_mono/generated/match_list.txt, crates/compiler/test_mono/src/tests.rs
Supports code generation of list pattern matches via decision trees.
Decision tree branches are guarded as follows:
- For exact-size list patterns, we match against the exact length of the list under question
- For slice patterns, we check whether the length of the list under question >= the minimum arity of the slice pattern
Indexing into a list just calls `List.getUnsafe` for the relevant elements we want to index, since after the guard succeeds, we know the list length is bounded.
Closes #4171
=> Decision tree compilation of list pattern matches

crates/compiler/exhaustive/src/lib.rs, crates/reporting/tests/test_reporting.rs
This fixes a bug in the list pattern matching code that caused crashes
in the presence of list guards, and simplifies the pattern splitting
algorithm to avoid complexity and allocations. Previously we would place
arguments-to-be-matched of constructors and lists at the front of
specialized rows for exhaustiveness checking, but at the back for
redundancy checking. Now, we always place them at the back - this avoids
needless allocation, and is not any worse, since we can still recover
the non-exhaustive witnesses by looking at the end of a list, instead of
the front.
=> Simplify constructor recovery

crates/compiler/can/src/constraint.rs, crates/compiler/constrain/src/builtins.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/module.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_derive/src/util.rs, crates/reporting/tests/helpers/mod.rs
Part 3/many of eliminating type emplacement. This patch adds on to #4399 by eliminating direct references to `Type` in the constraining API entirely; you can now only use constrained types via a `Index<Type>`, which in turn corresponds to exactly one type variable generated during solving, rather than possibly multiple.
Next we'll want to enforce that we eliminate `Type` to an `Index<Type>` at canonicalization, with types SoA.
=> Fully remove `Type` from the surface API of constraining

crates/compiler/test_mono/generated/dict.txt, crates/compiler/test_mono/generated/encode_derived_nested_record_string.txt, crates/compiler/test_mono/generated/encode_derived_record_one_field_string.txt, crates/compiler/test_mono/generated/encode_derived_record_two_field_strings.txt, crates/compiler/test_mono/generated/encode_derived_tag_one_field_string.txt, crates/compiler/test_mono/generated/encode_derived_tag_two_payloads_string.txt
Just committing the changes made when running the tests.
I think this broke due to a race between #4307 (which introduced a change without making updates to the mono tests), and #4451 (which enabled the mono tests).
=> Fix test_mono

crates/compiler/builtins/roc/List.roc, crates/docs/src/lib.rs, crates/docs/src/static/styles.css
=> Amend `List.walk` documentation with latest syntax

crates/compiler/parse/src/blankspace.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/src/pattern.rs, crates/compiler/parse/src/type_annotation.rs, crates/compiler/parse/tests/snapshots/fail/lambda_extra_comma.expr.result-ast, crates/compiler/parse/tests/snapshots/fail/lambda_missing_indent.expr.result-ast, crates/compiler/parse/tests/snapshots/fail/pattern_binds_keyword.expr.result-ast, crates/compiler/parse/tests/snapshots/fail/when_missing_arrow.expr.result-ast, crates/repl_cli/src/repl_state.rs, crates/reporting/src/error/parse.rs, crates/reporting/tests/test_reporting.rs
Most notably, this converts closure, `when`, and some `if` parsing to fully use combinators instead of custom parsing.
On the upside, this change fixes some bugs with error positions - where previously some errors involving `when` didn't correctly indicate where the when expr started - but rather pointed to some arbitrary point inside the when body. You can see this change in a few `reporting` test updates - where the error now actually shows the full context of the `when` expr that has the error.
=> Refactor several parse methods to use more combinators

crates/compiler/collections/src/soa.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve/src/specialize.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs
This checks in the first pass of Types SoA and introduces it to the frontend by introducing variables only through the SoA representation. Next, we'll move down the SoA representation to constraining, and then even further down, until we completely replace `Type` with the new representation.
=> Types SoA and Type -> Variable conversion via SoA

crates/compiler/can/src/constraint.rs, crates/compiler/constrain/src/builtins.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/pattern.rs, crates/reporting/tests/helpers/mod.rs
Rather than creating an `Index` in the constrainer at use site, provide an `Index<Expectation>` when constraining an expression directly. Less copying.
=> Lift constraining expectation indices up a level

crates/compiler/solve/src/solve.rs, crates/compiler/types/src/types.rs
Adds deep cloning for SoA types and variable substitution. In time we'll make the aliases representation use the SoA type by default.
Blocked on #4485
=> Types SoA for aliases instantiated during solving

crates/ast/src/builtin_aliases.rs, crates/ast/src/lang/core/def/def.rs, crates/ast/src/lang/core/types.rs, crates/ast/src/solve_type.rs, crates/compiler/can/src/annotation.rs, crates/compiler/can/src/copy.rs, crates/compiler/can/src/def.rs, crates/compiler/can/src/exhaustive.rs, crates/compiler/derive/src/util.rs, crates/compiler/derive_key/src/decoding.rs, crates/compiler/derive_key/src/encoding.rs, crates/compiler/derive_key/src/hash.rs, crates/compiler/late_solve/src/lib.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout_soa.rs, crates/compiler/problem/src/can.rs, crates/compiler/solve/src/ability.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve_problem/src/lib.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs, crates/compiler/unify/src/unify.rs, crates/glue/src/types.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/src/error/expect.rs, crates/reporting/src/error/type.rs
All the cases where `Erroneous` was used can be covered by canonicalization errors.
=> Remove `Erroneous` type and `Problem` for type

Cargo.lock, crates/compiler/types/Cargo.toml, crates/compiler/types/src/num.rs, crates/compiler/types/src/types.rs
```
[roc_load 0.0.1] [crates/compiler/solve/src/solve.rs:331] types.dbg(typ) = (`List.List` (`Num.U8`)), 68 -70->
[roc_load 0.0.1]   (`Decode.DecodeResult` 69
[roc_load 0.0.1]     ==> {result!: `Result.Result` 69 (`Decode.DecodeError` ==> [TooShort]73),
[roc_load 0.0.1]          rest!: `List.List` (`Num.U8`)})
```
=> Pretty-printer for debug representation of SoA types

examples/parser/platform/host.c, examples/platform-switching/c-platform/host.c, examples/ruby-interop/platform/host.c
I believe implicit declarations(=missing headers) used to be a warning in clang 13 but are now an error in clang 14.
This was the error caused by issue:
```
---- cli_run::platform_switching_main stdout ----
thread 'cli_run::platform_switching_main' panicked at '`roc` command had unexpected stderr: An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'Error:
Failed to rebuild host.c:
The executed command was:
"clang" "/Users/runner/work/roc/roc/examples/platform-switching/c-platform/host.c" "-o" "/Users/runner/work/roc/roc/examples/platform-switching/c-platform/host.o" "-fPIC" "-c"
stderr of that command: …
```
=> add missing includes for clang 14

crates/cli/src/lib.rs, crates/cli/tests/cli_run.rs, crates/cli/tests/fixtures/multi-dep-str/platform/host.zig, crates/cli/tests/fixtures/multi-dep-thunk/platform/host.zig, crates/cli_testing_examples/algorithms/fibonacci-platform/host.zig, crates/cli_testing_examples/algorithms/quicksort-platform/host.zig, crates/cli_testing_examples/benchmarks/platform/host.zig, crates/compiler/build/src/link.rs, crates/compiler/builtins/bitcode/src/utils.zig, crates/linker/src/pe.rs, crates/utils/src/lib.rs, examples/cli/effects-platform/host.zig, examples/cli/tui-platform/host.zig, examples/parser/platform/host.c, examples/platform-switching/c-platform/host.c, examples/platform-switching/zig-platform/host.zig, examples/ruby-interop/platform/host.c
Uses the nightly rust compiler to have executable expose symbols. We need these for surgical linking. Hopefully we can stabilize this flag, but until then,  using nightly for platforms on windows is fine.
=> Windows rust platforms

crates/compiler/can/src/constraint.rs, crates/compiler/collections/src/soa.rs, crates/compiler/constrain/src/builtins.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/module.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/solve/src/ability.rs, crates/compiler/solve/src/module.rs, crates/compiler/solve/src/solve.rs, crates/compiler/test_derive/src/util.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/types/src/types.rs, crates/reporting/tests/helpers/mod.rs, crates/reporting/tests/test_reporting.rs
Pushes the SoA representation of types even earlier, so that types are now stored into the SoA representation during constraining. The next step is to do this during canonicalization, at which point we can eliminate `Index<Type>` in constraining, apply the `EitherIndex` Variable optimization in types SoA, and hopefully have solved the type emplacement problem.
=> Begin Types SoA in constraining

examples/platform-switching/web-assembly-platform/README.md, examples/platform-switching/web-assembly-platform/host.js, examples/platform-switching/web-assembly-platform/host.zig
Cleaning up our Wasm example app.
- The readme instructions were wrong and didn't work! They also only gave an example of running a local http server with `npm`, so I added an option for Python too.
- The JavaScript mentioned that the WebAssembly streaming API was faster but didn't actually take full advantage of that! Fixed it and added comments.
- The Zig host contained a lot of unused code due to copy-pasting. This included some MacOS specific `comptime` code, which makes no sense in a host that only works on Wasm anyway.
=> Fixes for WebAssembly platform-switching example

crates/compiler/can/src/constraint.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/solve/src/solve.rs, crates/compiler/types/src/types.rs
In this PR,
- SoA types now index into a `Cell`; after we convert a type to a variable, the variable is emplaced into the cell for re-use.
- We eliminate traces of `type` in constraining, since that is no longer relevant - types are always stored in `Types`. There are still some vestiges that will be removed later.
Blocked on #4491
=> Emplace variables after converting SoA types, and remove types from constraining

crates/compiler/builtins/bitcode/src/expect.zig, examples/platform-switching/c-platform/host.c
MacOS SIGUSR1 is signal 30, not 10 as it is on Linux. At least on MacOS clang, we need the added headers to the c platform's host to compile correctly.
=> Fix inline expects on macos

Cargo.lock, crates/compiler/alias_analysis/Cargo.toml, crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs
Previously we only collected type names that appeared on the surface of a type during alias analysis, but certain types that need to be named (i.e. recursive types) may be observed only when we actually convert the IR to the morphic IR. Make sure we collect those appropriately.
This is a cherry pick of the relevant changes in #4121.
=> Collect deeply nested type names in alias analysis

crates/compiler/types/src/subs.rs
This materially improves performance for programs that are recursion-heavy (as most Roc programs will likely be).
```
$ hyperfine '/tmp/roc-old check examples/cli/cli-platform/Arg.roc' '/tmp/roc-new check examples/cli/cli-platform/Arg.roc' --warmup 10
Benchmark 1: /tmp/roc-old check examples/cli/cli-platform/Arg.roc
Time (mean ± σ):      53.8 ms ±   1.3 ms    [User: 87.3 ms, System: 10.8 ms]
Range (min … max):    52.2 ms …  60.4 ms    51 runs
Benchmark 2: /tmp/roc-new check examples/cli/cli-platform/Arg.roc
Time (mean ± σ):      45.0 ms ±   1.6 ms    [User: 59.4 ms, System: 11.3 ms]
Range (min … max):    42.6 ms …  49.8 ms    60 runs
Summary
'/tmp/roc-new check examples/cli/cli-platform/Arg.roc' ran
1.20 ± 0.05 times faster than '/tmp/roc-old check examples/cli/cli-platform/Arg.roc'
``` …
=> Use thread-local buffer for occurs check seen variables

crates/docs/src/static/styles.css, crates/reporting/src/report.rs, www/build.sh, www/public/repl/repl.css
I realized that our [Content-Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles) disallows inline `style` attributes, which we were using in a couple of places (and which the browser was blocking while giving an error in the console).
I changed these to use classes so the browser will actually use them! 😄
=> Fix some web styles

crates/repl_expect/src/lib.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/src/error/expect.rs, crates/reporting/tests/test_reporting.rs
- Added a newline after failed inline `expect` reports
- Revised wording for `UNNECESSARY WILDCARD` warnings
=> Reporting tweaks

crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/types/src/subs.rs
When we attempt to bind a type argument to an ability in an alias/opaque
instantiation, we create a fresh flex var to represent satisfaction of
the ability, and then unify the type argument with that flex var.
Previously, we did not register this fresh var in the appropriate rank
pool.
Usually this is not a problem; however, our generalization algorithm is
such that we skip adjusting the rank of redundant variables. Redundant
variables are those that are in the same unification tree, but are not
the root of the unification trees.
This means that if such a flex able var becomes the root of a
unification tree with the type argument, and the type argument is itself
generalized, we will have missed generalization of the argument.
The fix is simple - make sure to register the flex able var …
=> Ensure ability-bound variables are registered in their generalization pool

crates/compiler/derive_key/src/hash.rs, crates/compiler/derive_key/src/lib.rs, crates/compiler/mono/src/layout.rs, crates/compiler/solve/src/specialize.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/types/src/num.rs
=> Choose `hash` lambda for ranged numbers based on their default compilation width

crates/cli/src/format.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/parse/src/blankspace.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/header.rs, crates/compiler/parse/src/ident.rs, crates/compiler/parse/src/module.rs, crates/compiler/parse/src/number_literal.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/src/pattern.rs, crates/compiler/parse/src/state.rs, crates/compiler/parse/src/string_literal.rs, crates/compiler/parse/src/type_annotation.rs, crates/compiler/parse/tests/test_parse.rs, crates/repl_cli/src/repl_state.rs, crates/reporting/src/error/parse.rs, crates/reporting/tests/test_reporting.rs
As previously discovered with #4464, it's easy to accidentally mis-use the State value returned on the Err path.
There were mixed assumptions about what that State represents: (1) the State where the error occurred, or (2) the State at the beginning of the thing we were just parsing.
I fixed this up to always mean (2) - at which point we don't actually need to return the State at all - so it's impossible for further discrepency to creep in.
I also took the liberty to refactor a few more methods to be purely combinator-based, rather than calling `parse` directly.
=> Refactor parser methods to not return State as part of ParseError

www/netlify.toml
It was missing a `sha256-` prefix.
=> Fix Content-Security-Policy directive

www/public/site.css
The last change on https://github.com/roc-lang/roc/pull/4539 ended up breaking the src declaration (I've left a trailing `,` there instead of a `;` - sorry! 😅)
This PR fixes that and future-proofs the srcs for usage in other pages as well (since we were using relative src paths).
=> fix: site.css font-family broken sources

crates/cli/tests/cli_run.rs, crates/compiler/collections/src/vec_set.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/debug_flags/src/lib.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs, crates/compiler/unify/src/fix.rs, crates/compiler/unify/src/lib.rs, crates/compiler/unify/src/unify.rs, crates/reporting/src/error/type.rs, crates/reporting/tests/test_reporting.rs, examples/cli/cli-platform/Arg.roc
This supersedes #4121 as a "better" implementation of fixpoint fixing and related constraint bug fixes, the latter of which is now not necessary due to variable emplacement of types/Types SoA. Includes:
- Implementation of fixpoint-fixing, as described in https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/alias.20references.20to.20mutually.20recursive.20types. See also the new file `unify/src/fix.rs` for a description of the procedure and why we do it.
- [Correct emplace variables in type indices during translation](https://github.com/roc-lang/roc/commit/8cf896f03afdf09ca6ef603b6ccf384050f5df34) 
Prior to this commit, we emplaced type variables into `Index<TypeTag>`
only for translated top-level types. However, we need to be careful to
do this emplacement for …
=> Implement fixpoint-fixing and unconditionally emplace variables into type indices

crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/unify/src/unify.rs
With fixpoint-fixing, we don't want to re-unify type variables that were just fixed, because doing so may change their shapes in ways that we explicitly just set them up not to be changed (as fixpoint-fixing clobbers type variable contents).
However, this restriction need only apply when we re-unify two type variables that were both involved in the same fixpoint-fixing cycle. If we have a type variable T that was involved in fixpoint-fixing, and we unify it with U that wasn't, we know that the $U \notin \bar{T}$, where $\bar{T}$ is the recursive closure of T. In these cases, we do want to permit the usual in-band unification of $T \sim U$.
=> Correct when fixpoint-fixed type variables can be reunified

Cargo.lock, crates/cli/src/build.rs, crates/compiler/build/src/link.rs, crates/compiler/builtins/Cargo.toml, crates/compiler/builtins/bitcode/.gitignore, crates/compiler/builtins/build.rs, crates/compiler/builtins/src/bitcode.rs, crates/compiler/test_gen/Cargo.toml, crates/compiler/test_gen/build.rs, crates/compiler/test_gen/src/helpers/dev.rs, crates/linker/src/generate_dylib/macho.rs, crates/repl_wasm/Cargo.toml, crates/repl_wasm/build.rs, crates/utils/src/lib.rs
This should mean that nobody needs a `lib/` dir locally anymore, and can run `roc` from any directory without needing anything else downloaded for builtins to work properly (except in the specific case of when building wasm in `--optimize` mode, because at the moment we still need `zig` for that due to Zig not being able to generate `.bc` files for wasm yet. Also when building `--lib` on Windows, we use `zig build-lib` at the moment, and that depends on `str.zig` which is in `lib/`. Removing that Windows-specific dependency isn't blocked on any Zig features, we just don't have the surgical linker doing Windows DLL linking yet).
I verified that this works by doing a fresh checkout of this repo, building a `roc` binary, moving it to a freshly created empty dir with the `examples/` from the …
=> Use include_bytes! so builtin hosts live in binary

crates/compiler/constrain/src/expr.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/types/src/pretty_print.rs
The current type inference scheme is such that we first introduce the
types for annotation functions, then check their bodies without
additional re-generalization. As part of generalization, we also perform
occurs checks to fix-up recursive tag unions.
However, type annotations can contain type inference variables that are
neither part of the generalization scheme, nor are re-generalized later
on, and in fact end up forming a closure of a recursive type. If we do
not catch and break such closures into recursive types, things go bad
soon after in later stages of the compiler.
To deal with this, re-introduce the values of recursive values after we
check their definitions, forcing an occurs check. This introduction is
benign because we already generalized appropriate type variables anyway. …
=> Force occurs check for introduced types after checking annotated bodies

crates/wasm_interp/src/call_stack.rs, crates/wasm_interp/src/execute.rs, crates/wasm_interp/src/lib.rs, crates/wasm_interp/src/value_stack.rs, crates/wasm_interp/tests/test_opcodes.rs, crates/wasm_module/src/lib.rs, crates/wasm_module/src/opcodes.rs, crates/wasm_module/src/sections.rs
Implement function calls in the Wasm interpreter
When a function is called, we look up the `WasmModule` to find how many arguments it has and pop that many values off the `ValueStack`. We then create a new frame on the `CallStack` and insert the arguments as local variables there, along with the declared local variables.
When we load arguments, we just load whatever is there on the `ValueStack` without checking the value types. But we could add this check later. It might be useful for debugging compiler code gen issues.
We're also detecting `return` instructions and the implicit `return` that happens when we reach the end of the function. I decided to use an enum with `Break` and `Continue` and have the caller implement the actual loop. It's nice for testing and debugging to have a …
=> Wasm interp function calls

crates/reporting/src/error/expect.rs
...and without an `=` sign, but with a newline at the end!
=> Print `dbg` output in blue

crates/compiler/gen_wasm/src/code_builder.rs, crates/wasm_interp/src/call_stack.rs, crates/wasm_interp/src/execute.rs, crates/wasm_interp/src/main.rs, crates/wasm_interp/tests/test_opcodes.rs, crates/wasm_module/src/lib.rs, crates/wasm_module/src/sections.rs
- Implement block instructions `block`, `loop`, `if`, and `else`
- Implement branching instructions `br`, `br_if`, `br_table`
- Implement `i32.lt_s` (less than) because we need a comparison to make a loop!
- We now need to remember the address where each `loop` begins, so that we can jump backwards to it. This meant a change in how we keep track of nested blocks.
- Previously `ExecutionState` only knew the `block_depth` for the current function and `CallStack` kept track of block depths inside of `return_addrs_and_block_depths`
- But now `ExecutionState` has a full vector `block_loop_addrs` instead of just a depth. ~~So there's no need for `CallStack` to store block depths any more.~~ `CallStack` still keeps track of which blocks belong to which function.
- CLI can now pass arguments to …
=> Wasm interp branching

crates/wasm_interp/src/execute.rs, crates/wasm_interp/tests/test_opcodes.rs, crates/wasm_module/src/sections.rs
Indirect function calls
Wasm doesn't allow the program to access real code memory addresses, for security reasons.
Instead, the Wasm module has a table listing all functions that are passed around as "pointers" in the program. The "address" in the is actually an index into that table.
To implement the `call_indirect` instruction we need to implement those table lookups.
After this, the only remaining "big feature" is foreign function imports. Our tests use ~3 WASI imports and some user-defined imports.
Then it's a matter of working through the remaining ops one by one.
- I32/I64 ops: 25 each
- F32/F64 ops: 19 each
- conversion ops: 25
=> wasm_interp: indirect_call

www/public/site.css, www/public/tutorial/index.html
- Create CSS based navigation with toggle button for smaller screens
- Fix styles that were preventing the layout to correctly resize on smaller screens
- Bonus: updated nav and body background colors so they match the colors on our builtin docs
| **Before**  |  **After (Closed)** | **After (Open)**  |
|---|---|---|
|  <img width="429" alt="Screen Shot 2022-11-28 at 16 12 12" src="https://user-images.githubusercontent.com/3660797/204361641-314a249b-f16a-4c64-95f1-da835e81f524.png">  |  <img width="414" alt="Screen Shot 2022-11-28 at 16 11 41" src="https://user-images.githubusercontent.com/3660797/204361678-2ab027f3-8fa4-4985-a845-f05521645c34.png">  |  <img width="425" alt="Screen Shot 2022-11-28 at 16 11 48" src="https://user-images.githubusercontent.com/3660797/204361669-ec6a12f1-1722-4b …
=> fix: tutorial on mobile

www/public/site.css, www/public/tutorial/index.html
A few tweaks to `/tutorial` styles:
* Use `font-size: 16px` on mobile
* Use a better color for comments
* There was an inline `display:none` that was blocked by our content-security policy on Netlify; this is now in site.css
* Moved the table of contents toggle next to the "Tutorial" heading so it's only on /tutorial and not in the site-wide nav bar
* Went back to the previous header and background colors; after looking at it both ways, I think the docs pages should actually adopt these styles rather than the other way around! 😃
=> Tutorial style tweaks

crates/linker/src/lib.rs
platform-path is relative to the execution folder, not the input path
=> [Super easy review] fix stub lib path

crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/collection.rs, crates/compiler/fmt/src/module.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/header.rs, crates/compiler/parse/src/module.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/src/type_annotation.rs, crates/compiler/parse/tests/snapshots/pass/empty_app_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/empty_hosted_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/empty_interface_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/empty_platform_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/full_app_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/full_app_header_trailing_commas.header.result-ast, crates/compiler/parse/tests/snapshots/pass/function_effect_types.header.result-ast, crates/compiler/parse/tests/snapshots/pass/interface_with_newline.header.result-ast, crates/compiler/parse/tests/snapshots/pass/minimal_app_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/nested_module.header.result-ast, crates/compiler/parse/tests/snapshots/pass/nonempty_hosted_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/nonempty_platform_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/provides_type.header.result-ast, crates/compiler/parse/tests/snapshots/pass/requires_type.header.result-ast, crates/packaging/src/tarball.rs
... and refactor header parser to fully use combinators, in support of future combinator-based superpowers.
To make the parser a bit cleaner, I combined many of the pairs of `*_before` / `*_after` fields in the various header types with some variant of a zero-size `*Keyword` newtype, `Spaces`, and sometimes `KeywordItem` - to indicate some sort of item introduced by keyword.
I also removed the `maybe!` combinator that did exactly the same job as `optional`, and made all the cases that `optional` needed to allow backtracking explicit - by adding a `backtrackable` combinator.
=> Introduce `record!` combinator

crates/compiler/parse/src/ast.rs
I noticed there were several missing cases in this match statement - which obviously had been forgotten because they fell into the catch-all default at the bottom and the compiler never complained.
I rewrote the match to make it clear when we need to add new cases in the future.
I kinda wish rust had some way to indicate that I want to handle all cases where two elements of a tuple match; but alas.
=> Fix missing cases in Pattern::equivalent

Cargo.lock, Cargo.toml, crates/cli/tests/cli_run.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/src/work.rs
Whether a module has a dependency on another module for specialization
is already accounted for when the build graph was initially populated,
and should not be modified again.
Closes https://github.com/roc-lang/roc/issues/4622
=> Do not mark whether a module has specialization deps incrementally

crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_mono/generated/anonymous_closure_lifted_to_named_issue_2403.txt, crates/compiler/test_mono/generated/function_pointer_lambda_set.txt, crates/compiler/test_mono/generated/issue_2725_alias_polymorphic_lambda.txt, crates/compiler/test_mono/generated/lambda_capture_niches_have_captured_function_in_closure.txt, crates/compiler/test_mono/generated/lambda_capture_niches_with_non_capturing_function.txt, crates/compiler/test_mono/generated/specialize_closures.txt, crates/compiler/test_mono/generated/specialize_lowlevel.txt, crates/compiler/test_mono/generated/unreachable_branch_is_eliminated_but_produces_lambda_specializations.txt, crates/compiler/test_mono/src/tests.rs
1. [Do not attempt to handle aliasing of procs in variable assignments](https://github.com/roc-lang/roc/commit/68e364d897ed3d35a74d09f9650a5dfa7eeb2333)
Consider the aliasing of a scoped-defined lvalue
```
bar = ""
foo = bar
```
We need to generate an IR that is free of local lvalue aliasing, as this aids in
refcounting. As such, variable aliasing usually involves renaming the LHS in the
rest of the program with the RHS (i.e. [foo->bar]).
Previously, we also attempted to eliminate aliasing to procedures (either a
function pointer or a thunk) here - for example in a program like
```
f = \{} -> 1
var = f {}
```
This patch eliminates trying to handle such aliasing. The reasons are enumerated
below.
=== 1.
Doing so is not necessary - if we have `var = f` where `f` is either a proc or
thunk, …
=> Bugfix compilation of rvalue-determined lambda sets

crates/wasm_interp/src/instance.rs, crates/wasm_interp/src/lib.rs, crates/wasm_interp/src/main.rs, crates/wasm_interp/src/test_utils.rs, crates/wasm_interp/src/wasi.rs, crates/wasm_interp/tests/test_basics.rs, crates/wasm_interp/tests/test_mem.rs
Add functionality to call external Rust code from Wasm
I've decided to do this differently than other interpreters, because of all the frustration I've had with the usual way they do it.
They normally base it on the JS version, where you import an object of objects of functions. (The nesting allows you to have separate modules of functions)
The Rust translation of that architecture tends not to work so well. It ends up being a complex data structure with lambdas. Lambdas are a bit awkward in Rust and it's hard to maintain external state outside the Wasm module. But we _always_ want to do that!
Also they always make it really difficult or `unsafe` to access memory as plain bytes. I guess because they want to be multi-threaded. But don't think we care about that. We will just use a separate …
=> Wasm interp imports

Cargo.lock, Cargo.toml, crates/editor/Cargo.toml, crates/packaging/Cargo.toml, crates/packaging/src/cache.rs, crates/packaging/src/https.rs
This attempts to work around a problem [people have encountered on NixOS](https://roc.zulipchat.com/#narrow/stream/358903-Advent-of-Code/topic/Setting.20up.20environment.20.28nix.29/near/313333430).
I can't reproduce the problem locally, so...hopefully this fixes it in context!
=> Fallback to deep copy if `rename` fails when unpacking package tarball

crates/compiler/can/src/def.rs, crates/compiler/test_gen/src/gen_records.rs, crates/compiler/test_mono/generated/toplevel_accessor_fn_thunk.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/types/src/subs.rs
In https://github.com/roc-lang/roc/pull/3352 an optimization to transform `ra = .field` into
```
ra = \#rcd -[ra]-> #rcd.field
```
rather than
```
__ra1 = \#rcd -[__ra1] -> #rcd.field
ra = LambdaSet { __ra1 }
```
was introduced. However, this optimization is not correct when `ra =
.field` is defined as a toplevel thunk, for in such situations we
indeed want the thunk `ra` to return the lambda set it resolves to,
rather than repointing at itself.
Besides reverting this change, another option would be to convert
accessors into closures before translation of Can to IR. However, this
complicates the translation algorithm more than it already is, and I'd
like to avoid additional special-cases.
Closes https://github.com/roc-lang/roc/issues/4606
=> Do not bind accessors in toplevel thunks to their thunks' names

crates/compiler/can/src/def.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/src/module.rs, crates/compiler/collections/src/reference_matrix.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/problem/src/can.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/tests/test_reporting.rs
This patch provides errors for defs that are used only in possibly-mutual recursion, and are not reachable outside of their recursive closures. For example:
```
test_report!(
mutual_recursion_not_reached_nested,
indoc!(
r#"
app "test" provides [main] to "./platform"
main =
f = \{} -> if Bool.true then "" else g {}
g = \{} -> if Bool.true then "" else f {}
""
"#
),
@r###"
── DEFINITIONs ONLY USED IN RECURSION ──────────────────── /code/proj/Main.roc ─
These 2 definitions are only used in mutual recursion with themselves:
4│>      f = \{} -> if Bool.true then "" else g {}
5│>      g = \{} -> if Bool.true then "" else f {}
If you don't intend to use or export any of them, they should all be
removed!
"###
);
```
=> Provide warning for defs that are used only in (mutual) recursion

www/public/tutorial/index.html
I was following the cool tutorial and noticed this tiny typo.
I saw no PR to fix it, so I created one.
Signed-off-by: Marc Walter <walter.marc@outlook.com>
=> Fix `<code>` tag in tutorial

Cargo.lock, crates/cli/src/lib.rs, crates/compiler/exhaustive/Cargo.toml, crates/compiler/exhaustive/src/lib.rs, crates/compiler/load/src/lib.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/problem/src/can.rs, crates/compiler/problem/src/lib.rs, crates/compiler/solve_problem/src/lib.rs, crates/compiler/test_gen/src/helpers/llvm.rs, crates/compiler/test_mono/src/tests.rs, crates/repl_eval/Cargo.toml, crates/repl_eval/src/gen.rs, crates/repl_expect/src/lib.rs, crates/reporting/src/cli.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/src/error/expect.rs, crates/reporting/src/error/parse.rs, crates/reporting/src/error/type.rs, crates/reporting/src/report.rs, crates/reporting/tests/test_reporting.rs, examples/cli/env.roc
- Move `roc test` to have the behavior of `roc dev` in that it exits early if there are errors, but not warnings. That way in the short term people can get used to using `roc test` and it'll likely do what they want while minimizing compiler crashes, rather than instilling a habit of `roc check && roc test`. Once spurious crashes are minimized, moving `roc test` back to the test-even-with-errors mode will be natural.
- `roc dev` and `roc test` should stop only if there are errors, but continue if there are only warnings
I verified this works with several issues in the tracker and other experiments locally. Lets add tests after https://github.com/roc-lang/roc/pull/4659 lands, since Folkert is changing cli_run to better support test/dev in that PR.
Closes #4242
Closes #4484
Closes #4587
=> `test` has `dev` behavior, and `dev` does not exit if there are warnings

crates/compiler/gen_wasm/src/backend.rs, crates/compiler/gen_wasm/src/lib.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/checker.rs, crates/compiler/mono/src/debug.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/debug/report.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/lib.rs, crates/compiler/test_mono/src/tests.rs, crates/compiler/test_mono_macros/src/lib.rs
Implements a type-checker for the IR. The checker is primarily concerned with making sure layouts align everywhere a symbol is defined and used.
The checker output is pretty; for example,
```
── SYMBOL LAYOUT DOESN'T MATCH ITS USE ─────────────────────────────────────────
in quicksortHelp : (List I64, I64, I64) -> List I64 (no niche)
8 │              let `#UserApp.IdentId(5)` : I64 = StructAtIndex 0 `#UserApp.IdentId(21)`;
9 │>             let `#UserApp.IdentId(6)` : List [] = StructAtIndex 1 `#UserApp.IdentId(21)`;
10│              inc `#UserApp.IdentId(6)`;
#UserApp.partitioned defined here with layout List []
13│              let `#UserApp.IdentId(19)` : I64 = CallByName `Num.sub` `#UserApp.IdentId(5)` `#UserApp.IdentId(20)`;
14│>             let `#UserApp.IdentId(16)` : List I64 = …
```
=> Type-check mono IR

crates/compiler/can/src/constraint.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_derive/src/util.rs, crates/compiler/test_gen/src/gen_dict.rs, crates/compiler/test_gen/src/gen_set.rs
When ability specializations are statically known in the dependency graph, we inject a module dependencies' specializations prior to solving the module types. This injection copies the specialization lambda sets and ambient functions from module-independent storage into the host module's Subs.
Copying a dependent module's types out of storage "loses" rank information of the type in the original source module. This is by design, because the exported type may be at a level that is never reached in the module being imported into. Instead, imported types are imported at a constant rank (Rank::import), and then run through the standard generalization algorithm for let-bindings. This makes sure that imported variables available for generalization are lifted up to the generalization rank (Rank …
=> Correct generalization of imported specializations

crates/wasm_interp/Cargo.toml, crates/wasm_interp/src/call_stack.rs, crates/wasm_interp/src/instance.rs, crates/wasm_interp/src/lib.rs, crates/wasm_interp/src/main.rs, crates/wasm_interp/src/tests/test_basics.rs, crates/wasm_interp/src/tests/test_mem.rs, crates/wasm_interp/src/value_stack.rs, crates/wasm_interp/src/wasi.rs, crates/wasm_module/src/sections.rs
Start implementing WASI, and a Wasm stack trace, and fix some bugs.
These changes were enough to get some initial Zig builtin tests working.
- Implement some basic WASI syscalls
- `args_sizes_get`, `args_get`, `fd_write`, `proc_exit`
- Change the CLI to be compatible with other engines and `zig test`
- Don't require `--` before the Wasm arguments
- Make sure the WASI app sees its own path as `argv[0]`. (Interpreter removes its own `argv[0]`, its own flags, etc. before passing the rest down.)
- Implement a stack trace dump for the Wasm app
- At this stage, when debugging, I usually find I want a stack trace of the Wasm app, not the interpreter.
- Create an `Error` enum and convert lots of panics to `Result` and `?`.
- There are still panics for some things though. We'll see how it evolves. …
=> Wasm interp: WASI and stack trace

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/test_gen/src/gen_list.rs
When we concat a non-unique list with a unique list, we reuse the unique list, and start by moving all of its owned items to the end of the list. Previously, we used Zig's `mem.copy`, which expects that the copy destination is before the copy source - but this is incorrect for our case. Instead we need `mem.copyBackwards`.
Closes #4697
=> Fix concat of non-unique list with unique list

crates/cli/src/lib.rs, crates/cli/tests/fixtures/multi-dep-str/platform/host.zig, crates/cli/tests/fixtures/multi-dep-thunk/platform/host.zig, crates/cli_testing_examples/algorithms/fibonacci-platform/host.zig, crates/cli_testing_examples/algorithms/quicksort-platform/host.zig, crates/cli_testing_examples/benchmarks/platform/host.zig, crates/compiler/builtins/bitcode/src/expect.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/bitcode/src/utils.zig, crates/compiler/builtins/src/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/externs.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/linker/src/elf.rs, crates/repl_expect/src/run.rs, examples/cli/cli-platform/src/lib.rs, examples/cli/effects-platform/host.zig, examples/cli/false-interpreter/platform/src/lib.rs, examples/cli/tui-platform/host.zig, examples/parser/platform/host.zig, examples/platform-switching/c-platform/host.c, examples/platform-switching/rust-platform/src/lib.rs, examples/platform-switching/zig-platform/host.zig, examples/ruby-interop/platform/host.c, examples/static-site-gen/platform/src/lib.rs, www/public/tutorial/index.html
the child is now locked while the parent prints the expect/dbg. That means that the printing happens at the right moment (e.g. in relation to the roc app printing to stdout itself with effects) and we can do multiple prints in sequence.
=> use atomics for expect/dbg

crates/compiler/fmt/src/expr.rs, crates/compiler/parse/tests/snapshots/pass/multiline_string.expr.formatted.roc, examples/cli/cli-platform/Arg.roc
This is a fix for #4585.
The problem was that `roc_fmt::expr::fmt_str_literal()` was treating all the lines in a `StrSegment::Block` the same. Added logic to detect if a given segment is just `"\n"`.
I also had to change some of the files the tests run on to reflect the new format behavior.
This is also my first PR, so please let me know if there's anything I missed or did incorrectly. Any feedback is immensely appreciated.
=> Fix for #4585

crates/compiler/test_gen/src/helpers/llvm.rs
This stops test from failing when dlclose has an error.
=> remove explicit closing of dylib when testing

crates/compiler/fmt/src/module.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/parse/src/header.rs, crates/compiler/parse/src/module.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/tests/snapshots/pass/empty_platform_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/full_app_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/full_app_header_trailing_commas.header.result-ast, crates/compiler/parse/tests/snapshots/pass/function_effect_types.header.result-ast, crates/compiler/parse/tests/snapshots/pass/minimal_app_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/nonempty_platform_header.header.result-ast, crates/compiler/parse/tests/snapshots/pass/provides_type.header.result-ast, crates/compiler/parse/tests/snapshots/pass/requires_type.header.result-ast
Previously, if there was any platform, we assumed it was the one associated with the app and ignored the `to` field. After this change, you can specify multiple platforms for your app module, and only the one specified with the `to` field will be used as the app's platform.
This is sliced off from the `packages` branch.
=> Use app module's `to` to determine platform

Cargo.lock, crates/compiler/can/Cargo.toml, crates/compiler/can/src/debug.rs, crates/compiler/can/src/debug/pretty_print.rs, crates/compiler/can/src/lib.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_derive/src/decoding.rs, crates/compiler/test_derive/src/encoding.rs, crates/compiler/test_derive/src/hash.rs, crates/compiler/test_derive/src/tests.rs, crates/compiler/test_derive/src/util.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/types.rs, crates/compiler/unify/src/unify.rs
We must be careful to ensure that if unifying nested lambda sets
results in disjoint lambdas, that the parent lambda sets are
ultimately treated disjointly as well.
Consider
```
v1: {} -[ foo ({} -[ bar Str ]-> {}) ]-> {}
~ v2: {} -[ foo ({} -[ bar U64 ]-> {}) ]-> {}
```
When considering unification of the nested sets
```
[ bar Str ]
~ [ bar U64 ]
```
we should not unify these sets, even disjointly, because that would
ultimately lead us to unifying
```
v1 ~ v2
=> {} -[ foo ({} -[ bar Str, bar U64 ]-> {}) ] -> {}
```
which is quite wrong - we do not have a lambda `foo` that captures
either `bar captures: Str` or `bar captures: U64`, we have two
different lambdas `foo` that capture different `bars`. The target
unification is
```
v1 ~ v2
=> {} -[ foo ({} -[ bar Str ]-> {}),
foo ({} -[ bar …
```
=> Ensure that disjoint nested lambda sets force parents to be disjoint

.github/workflows/nightly_macos_x86_64.yml
Tests were creating another release with a different CPU target which caused the `Illegal instruction: 4` error on macos github CI servers.
=> fix macos x86_64 build target

crates/cli/src/build.rs, crates/compiler/build/src/link.rs
Both of these cases do not tie to a platform. The roc app can be built without considering the platform. It is often the case that the platform is using one of these options because roc cannot build the platform. This allows for more flexibility and avoids wasting time compiling the platform.
This ends up being required both for glue and fuzzing roc code. Both of those cases, this is required because roc cannot build the platform.
=> [simple PR] avoid building platform for link type dylib and no link

crates/cli/tests/cli_run.rs, crates/cli_testing_examples/.gitignore, crates/cli_testing_examples/expects/expects.roc, crates/compiler/alias_analysis/src/lib.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/module/src/symbol.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/inc_dec.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/reset_reuse.rs, crates/compiler/mono/src/tail_recursion.rs, crates/compiler/solve/tests/solve_expr.rs, crates/repl_expect/src/lib.rs, crates/repl_expect/src/run.rs
Previously, with a function like
```
f = \x ->
dbg x
x
```
we would store the type of the the lookup `x` before specialization, and moreover, would not disambiguate uses of dbg in specialized calls of `f`. This meant that the type of `x` would always been seen as an unbound variable, and nothing meaningful would be printed.
To support this, we now flow each specialized type of `x` through the backend, and have
- mono store into subs storage all specialized lookups
- the child send the type variable index of the specialized type
An expect frame now contains the type variable that should be indexed as a u32 right after the pointer to the copied value.
I also believe this means we can get rid of storing variables on the `Expectations` struct, which now is not used for anything other than …
=> Support using dbg/expect in polymorphic functions

crates/cli/Cargo.toml, crates/compiler/build/Cargo.toml, crates/compiler/build/src/program.rs
This allows using sanitizers with Roc. It is hidden behind the `sanitizers` feature and mostly for testing (This was a suggestion by Richard to avoid exposing this testing). Eventually we may want to expose it, but if so, we would want to expose it in a nice way. For example, could potentially have a `roc fuzz` command or something similar. This also adds address, memory, and thread sanitizers. They can be used with fuzzing or standalone.
Also, removed the unnecessary call to `llvm-as` from the debugir path code. `llc` can directly intake a `.ll` file.
=> [simple PR] Enable fuzzing and sanitizers

crates/compiler/builtins/bitcode/src/str.zig
fixes two memory leaks, based on the example in #4782
```
Str.withCapacity 10
|> Str.concat "foobar"
```
```
heapString = Str.concat "a string that is stored on the heap" "!"
Str.split heapString "\n"
|> ... 
```
I plan to (finally) add some tests for these builtins in a followup. There is however one more problem in that issue that I'll tackle first. (that problem is that `dbg` interacts with RC in invalid ways and we have use after free)
=> fix missing decref in split and concat

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/can/src/builtins.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_wasm/src/backend.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/module/src/low_level.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/inc_dec.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/reset_reuse.rs, crates/compiler/mono/src/tail_recursion.rs
previously `dbg` messed up refcounting, leading to use-after-free. Now we have more code, but it basically does nothing, which is what we want.
=> make dbg transparent to refcounting

crates/reporting/src/error/parse.rs, crates/reporting/tests/test_reporting.rs
Closes #4647
This PR improves the error message for unexpected `->` in certain contexts by showing both correct areas to use it.
=> Update error message to better explain `->`

www/build.sh
We can't run Roc code in our Netlify build yet because the Netlify build server doesn't have LLVM installed. (Installing it is possible, but challenging, and would eat up a lot of minutes; regardless, we don't have it at the moment.)
As such, this currently makes all our Netlify builds fail with:
We can fix this in the future, but for now this PR reverts the change so we can have deploys working again!
=> Don't build tutorial.html from .md on Netlify

crates/compiler/test_mono/generated/polymorphic_expression_unification.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/unify/src/unify.rs
Prior to the change to unify.rs, this test stack overflowed. Now the test passes, at least with (no_check).
=> Fix bug in unification of tag args in polymorphic contexts

crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_mono/src/tests.rs, crates/compiler/test_mono_macros/src/lib.rs
Follow layouts so that no recursive pointers appear in a layout without being wrapped by a recursive union, when comparing layouts in the IR checker.
=> Fix checking of recursive layouts in the ir-checker

crates/compiler/builtins/roc/Str.roc, crates/compiler/load_internal/src/docs.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/parse/src/ast.rs
Now you can specify docs above the module header and they'll generate docs that get printed before the first type entry. (So, basically an introduction to the module.)
=> Module header docs

crates/compiler/mono/src/borrow.rs
During borrow inference, SCCs of references between procs are first
constructed. Previously we didn't collect any references for HOLL calls,
but since such calls pass a Roc-function, we need to include a reference
to the Roc function.
=> Collect references to functions passed to HOLLs in borrow inference

crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/test_mono/generated/nullable_wrapped_with_non_nullable_singleton_tags.txt, crates/compiler/test_mono/src/tests.rs
The nullable ID always has zero tags. For everything else, we should
just match with the arity of the number of arguments, which doesn't
include the tag ID.
As @joshuawarner32 found in https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/.22attempt.20to.20subtract.20with.20overflow.22.20in.20ir.2Ers
=> Correct pattern matching of nullable wrapped tag unions 

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/build/src/program.rs, crates/compiler/gen_llvm/src/lib.rs, crates/compiler/gen_llvm/src/llvm/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/compare.rs, crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/mono/src/code_gen_help/equality.rs, crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/mono/src/code_gen_help/refcount.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/decision_tree.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_gen/src/helpers/llvm.rs, crates/glue/src/types.rs, crates/repl_cli/src/cli_gen.rs, crates/repl_eval/src/eval.rs, crates/repl_expect/src/run.rs
Another large PR on top of #4833 that interns the layouts of list elements, and does the tedious task of making the interner mutable in the LLVM backend. That's needed because the backend currently resolves recursive pointers when they arise. In the future I have some idea of how we can get rid of that.
=> Intern list element layouts and thread mut layout interner through LLVM backend

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_wasm/src/backend.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/debug/report.rs, crates/compiler/mono/src/inc_dec.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_gen/src/wasm_linking.rs, crates/repl_eval/src/eval.rs, crates/repl_expect/src/lib.rs
Renames `CaptureNiche` to the more generic `Niche` so that we can model other distinguishing factors in the future, adds documentation better describing what this is all about and why we need it, and hides the internal representation from everyone but layout.
=> Refactor and document the "niche" concept

crates/ast/src/lang/core/pattern.rs, crates/compiler/can/src/pattern.rs, crates/compiler/fmt/src/lib.rs, crates/compiler/fmt/src/pattern.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/src/pattern.rs, crates/compiler/test_syntax/tests/snapshots/pass/list_patterns.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/pattern_as.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/pattern_as.expr.roc, crates/compiler/test_syntax/tests/snapshots/pass/pattern_as_list_rest.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/pattern_as_list_rest.expr.roc, crates/compiler/test_syntax/tests/snapshots/pass/pattern_as_spaces.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/pattern_as_spaces.expr.roc, crates/compiler/test_syntax/tests/test_snapshots.rs
parses this sort of thing
when myRecord is
{ foo: Ok _ } as whole -> ...
_ -> ...
when myList is
[ first, .. as rest ] -> a
[] -> b
=> Parse pattern as

crates/compiler/build/src/program.rs
Just adds a more explicit fuzzing config behind the sanitizers feature flag. Makes it so I don't need to recompile but can use either fuzzer. Finally got `cargo fuzz` to work with it correctly. Also, `cargo fuzz` properly detects memory leaks which is quite nice.
=> Enable using both cargo-fuzz and afl.rs for fuzzing [Simple PR]

crates/compiler/gen_wasm/src/wasm32_result.rs, crates/compiler/intern/src/lib.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/code_gen_help/refcount.rs, crates/compiler/mono/src/debug/report.rs, crates/compiler/mono/src/decision_tree.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/glue/src/load.rs, crates/glue/src/types.rs, crates/repl_cli/src/cli_gen.rs, crates/repl_eval/src/eval.rs, crates/repl_expect/src/lib.rs, crates/repl_expect/src/run.rs
These patches wrap the layout interners in their own trait `LayoutInterner` that we'll use for the purpose of keeping certain layouts as constant-interned values, like `VOID` and `UNIT` are currently constant-valued.
This is another step in a massive one-shot patch I'll need to land next to support interning the rest of layouts. It'll also make it easier for us to support things like `stack_size` and `alignment_bytes` dispatched on the interner, rather than a layout itself
=> Wrap layout interners in own trait

crates/compiler/can/src/annotation.rs, crates/compiler/can/src/constraint.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/module.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs
This is step 1 of limiting let generalization. Start printing types in the solve tests that are unbound but ungeneralized (weak) with the `w_` prefix. Start marking let constraints that should never have variables generalized with a bit as so.
=> Print weak variables in tests and mark constraints that can't be generalized

examples/virtual-dom-wip/platform/Effect.roc, examples/virtual-dom-wip/platform/Html/Internal/Client.roc
Implements actual diffing on the virtual DOM. Up to now, it just re-rendered the view fresh every time.
I have still never actually run this code! To go further after this PR I will need to be able to debug it. So I think the next goal is to get all the compiler issues fixed so that the following commands all complete without a compiler crash.
```
$ roc build --target wasm32 examples/virtual-dom-wip/example-client.roc  
$ roc build examples/virtual-dom-wip/example-server.roc
$ roc test examples/virtual-dom-wip/platform/Html/Internal/Client.roc
```
=> Virtual DOM diff

BUILDING_FROM_SOURCE.md
linux aarch64 is untested so we should avoid giving the impression that it is supported.
=> remove mention linux aarch64

.github/workflows/nightly_macos_x86_64.yml
to allow nightlies to build until #4865 is resolved
=> skip `str_append_scalar` test on macos x86_64 nightly build

devtools/README.md, devtools/flake.lock, devtools/flake.nix
- fixes issue where square brackets are shown escaped(`\`) in the vscode terminal, thanks to the addition of `bashInteractive`
- adds toml extension
- adds roc syntax highlighting extension
- improved readme
- added flake.lock to pin dependencies
=> update vscode flake

crates/cli/tests/cli_run.rs, examples/parser/Parser/Core.roc, examples/parser/Parser/Http.roc
Another example of parsing in Roc, using a familiar format.
One day this could maybe form the lowest level of a web server framework! 🦄 
The only compiler issues I ran into were to do with `expect` evaluation.
- It tends to crash if the two sides of the `expect` don't match. For example if you compare two lists of different lengths, it often crashes. Often it's out-of-memory panics in bumpalo.
- Other times, when I do `expect actual == expected`, and `actual` is wrong, a corrupted String is printed for `expected`, containing UTF-8 replacement characters.
I couldn't get the `digits` parser to work without crashing, so for now I am leaving all of the numbers as strings. For example, instead of the OK status being `200`, it's `"200"`, for now!
=> Example parser for HTTP messages

crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs
Presently while generalizing type variables, we check variables
introduced at a scope for redundancy (whether they are not the root of
some unified set of variables). If a variable is redundant, its rank is
not adjusted. I believe the current logic to be the following:
- Each root of a unification tree will be introduced at some point,
exactly once. Its point of introduction will determine the rank of the
tree it's the root of
- If a variable is redundant, all of its redundant usages must be at the
same rank (assuming let generalization proceeds correctly),
so there is no need to adjust their rank as well
- As such, there is no need to adjust the rank of redundant variables,
as a performance optimization.
I believe this to be a hold-over from the original version of the solver
derived …
=> Remove check for redundancy before doing rank adjustment

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/compare.rs, crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/gen_wasm/src/backend.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/mono/src/code_gen_help/equality.rs, crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/mono/src/code_gen_help/refcount.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/decision_tree.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/glue/src/types.rs, crates/repl_eval/src/eval.rs
- [Do not require allocating Layouts in arena before interning](https://github.com/roc-lang/roc/commit/14a98f024c213fe93affcb18020e9837322f7192)
- [Store interned wrapped layout of lambda set on LambdaSet struct](https://github.com/roc-lang/roc/commit/8f669ebe5b008bb5d550b2b9fad794b4faf1918b)
The `LambdaSet` struct is frequently used independently to examine how a
lambda set should be packed or unpacked. However, it is also often
converted into a full layout via `Layout::LambdaSet(LambdaSet)` to be a
part of function arguments, for example.
In preparing to intern all layouts, we need a way to cheaply go from a
`lambda_set` to an interned `Layout::LambdaSet(lambda_set)`, since this
is a very common operation. The proposed solution is to keep the wrapped
layout cached on `LambdaSet` itself, …
=> Reduce layout intern allocations

crates/compiler/constrain/src/expr.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve/tests/solve_expr.rs
Variables introduced in branch patterns should never be generalized in
the new weakening model. This implements that. The strategy is:
- when we have a let-binding that should be weakened, do not introduce
its bound variables in a new (higher) rank
- instead, introduce them at the current rank, and also solve the
let-binding at the current rank
- if any of those variables should then be generalized relative to the
current rank, they will be so when the current rank is popped and
generalized
=> Implement weakening of variables introduced in branch patterns

crates/compiler/mono/src/decision_tree.rs
main is currently broken because of a non-conflicting diff that landed
before the interner change landed.
=> Fix missing parameter in to_relevant_branch_help

.github/workflows/macos_x86_64.yml
Execute all regular rust tests on the self-hosted x86_64 macos server on every PR. Previously we used to only do cli tests on the github macos x86_64 server.
=> added macos x86_64 PR workflow

crates/compiler/constrain/src/expr.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_mono/generated/monomorphized_list.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/types/src/pretty_print.rs, crates/repl_expect/src/lib.rs, crates/reporting/tests/test_reporting.rs
Enforces no generalization of let-bindings to
- strings
- chars
- lists
- when expressions
- if expressions
taking this slow to make sure it's right, things like `Var` and `AbilityMember` will also touch many places I think
=> Begin weakening let-bindings to non-function, non-number expressions

crates/compiler/gen_llvm/src/llvm/expect.rs, crates/repl_eval/src/eval.rs, crates/repl_expect/src/app.rs, crates/repl_expect/src/lib.rs, examples/parser/Parser/Http.roc
In the description of https://github.com/roc-lang/roc/pull/4858, I mentioned that `expect` seems to crash comparing lists of different lengths, instead of nicely reporting a test failure. Here's a reproduction of that.
I also remember getting crashes with the `digits` parser but that now seems to have a different crash in mono. See https://github.com/roc-lang/roc/pull/4895
```
RUST_BACKTRACE=1 target/debug/roc test examples/parser/Parser/Http.roc 
thread 'main' panicked at 'capacity overflow', /Users/briancarroll/.cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-3.11.0/src/collections/raw_vec.rs:691:5
stack backtrace:
0: rust_begin_unwind
at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at …
```
=> reproduce crash in `expect` with Lists of different length

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/valgrind/src/lib.rs
fix #4870
but ZSTs and lists almost certainly have other bad interactions that lead to leaks or double frees or juts bad things
=> handle zero-sized types in list decrement

crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_mono/generated/function_specialization_information_in_lambda_set_thunk.txt, crates/compiler/test_mono/generated/function_specialization_information_in_lambda_set_thunk_independent_defs.txt, crates/compiler/test_mono/src/tests.rs
This fixes #4734 and unblocks some work for glue of closures since that presumably needs argument/return layouts on the lambda set layout.
There are some follow ups I'd like to do after this, including
- https://github.com/roc-lang/roc/issues/4905 (we have one regression due to this problem)
- we can clean up `RawLayout::Function` since all the information needed there is now embedded in lambda sets.
I'll dump benchmarks here soon but I suspect with interning the delta will be very low.
=> Preserve function argument/return layouts in lambda set layouts

crates/ast/src/solve_type.rs, crates/compiler/can/src/annotation.rs, crates/compiler/can/src/copy.rs, crates/compiler/can/src/exhaustive.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/derive/src/decoding.rs, crates/compiler/derive/src/encoding.rs, crates/compiler/derive/src/hash.rs, crates/compiler/derive_key/src/encoding.rs, crates/compiler/derive_key/src/hash.rs, crates/compiler/mono/src/layout.rs, crates/compiler/solve/src/ability.rs, crates/compiler/solve/src/solve.rs, crates/compiler/test_derive/src/util.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs, crates/compiler/unify/src/fix.rs, crates/compiler/unify/src/unify.rs, crates/repl_eval/src/eval.rs, crates/reporting/tests/test_reporting.rs
Annotations like
```
f : {} -> [A]
```
are implicitly allowed to be used polymorphically in the output tag type.
Internally, we check this as equivalent to
```
f : {} -> [A]_
```
However, this is not quite right. This annotation allows the output type to grow in tag width, permitting code like
```
f : {} -> [A]
f = \{} -> if Bool.true A else B
```
to check, when it should not - we only want to allow the output tag to be polymorphic in its width, but not allow the type to invisibly grow in tag width.
The fix is to change the unification scheme so that when we have an implicitly-infer-openness variable like the extension variable here, we now instead model it as
```
f : {} -> [A]Openness(_)
```
where the variable under the `Openness` constraint can now only be unified with a polymorphic …
=> Do not permit implicitly-inferred-open extension vars to grow in tag width

crates/compiler/constrain/src/expr.rs, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_num.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/test_mono/generated/instantiate_annotated_as_recursive_alias_multiple_polymorphic_expr.txt, crates/compiler/test_mono/generated/monomorphized_tag.txt, crates/compiler/test_mono/generated/quicksort_help.txt, crates/compiler/test_mono/src/tests.rs, crates/repl_expect/src/lib.rs
This series of patches completes the type-level implementation of let-binding weakening as in the proposed document. That is, now, only let-bindings to syntactic functions or number literals are permitted to be generalized; all other expressions are weakened.
The relatively small surface of impacted code should be a sign that this is not too disruptive a change. As in #4885, the largest change continues to be with the change to `Dict.empty`/`Set.empty`'s interface to now necessarily be a thunk.
This is not the end of the story for weakening. As described in the document, there are several other designs that still need to be implemented. In particular, I'd like us to capture the following after this PR:
- The restriction that weakened type variables cannot appear in exposed values …
=> Finish weakening let-bindings

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/test_gen/src/gen_num.rs
This PR adds `Num.subWrap` support for the `gen_dev` target :)
Closes #3796
As specified in the issue, `Num.sub` currently works without dealing with panicking, so the implementation for `subWrap` can be a copy of `sub` for now.
I've enabled the `int_sub_wrap` test for the `gen-dev` feature
=> Add x86_64 wrapping subtraction support for gen_dev

crates/compiler/gen_dev/src/generic64/aarch64.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/test_gen/src/gen_num.rs
This PR fixes up the signed/unsigned inconsistency with the existing `less than` codegen and adds `greater than` codegen using the same flow.
AArch64 also seems to have a similar distinction between signed and unsigned compares, so this seems okay to do for now!
Issues related: #3844 #3842
Sidenote: should the 8-32 bit wide numbers use the same underlying `*_reg64_reg64_reg64` operation? If so we can add the pattern for those `IntWidth`s as well
=> gen_dev: fix signed/unsigned `less than` and add signed/unsigned `greater than`

crates/compiler/test_gen/src/gen_list.rs
While looking into more `gen_dev` things I could do I noticed that `List.len` was implemented - but a handful of the tests were not enabled for it. This PR simply enables more of the tests :)
=> gen_dev: enable more `List.len` tests for `gen-dev`

crates/compiler/fmt/src/def.rs, crates/compiler/test_syntax/tests/snapshots/pass/nested_backpassing_no_newline_before.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/nested_backpassing_no_newline_before.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/nested_backpassing_no_newline_before.expr.roc, crates/compiler/test_syntax/tests/test_snapshots.rs
=> Fix formatting of backpassing in a nested def with no newline

crates/cli/tests/cli_run.rs, crates/compiler/unify/src/unify.rs
When we unify variables in mono, we must invalidate the sections of the layout cache reached by those variables. Previously we did this by recording changed variables as those that were `merge`d. However this is not enough; we must also record all the parent types they came from. The reason is we may have something like
```
Alias (Foo, a) ~ Alias (Bar, U8)
```
where we will merge `a = U8` but we do not merge the aliases.
Closes #4919
=> Record changed variables if any nested variable has changed

.github/workflows/basic_cli_build_release.yml, crates/linker/src/elf.rs, crates/linker/src/lib.rs, crates/linker/src/metadata.rs, crates/packaging/src/tarball.rs, examples/helloWorld.roc, examples/parser/examples/letter-counts.roc
As discussed, pulled this commit from the llvm-15 branch and am submitting it by itself.
This enables the surgical linker to work with BIND_NOW. It does this by disabling the relocations that we deal with manually and defining all symbols.
=> surgical linker: remove jump slot relocations and update static symbols

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/test_gen/src/gen_list.rs, crates/roc_std/src/roc_list.rs
This PR adds and implementation for `List.withCapacity` using the zig builtin `listWithCapacity`.
I've changed the existing `with_capacity` test so we can validate the capacity by itself.
Closes #4930 :)
I would like to add that I have not tried implementing a builtin like this yet, so am unsure about the `load_literal` calls I'm making (are they using the right values?)
The new test is passing, but I'd like to implement `append` to make sure the layout works as intended :)
=> gen_dev: x86 Add `List.withCapacity` implementation

crates/compiler/can/src/def.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/ir.rs, crates/compiler/test_gen/src/gen_records.rs, crates/compiler/test_mono/generated/alias_variable_and_return_it.txt, crates/compiler/test_mono/generated/instantiate_annotated_as_recursive_alias_polymorphic_expr.txt, crates/compiler/test_mono/generated/let_x_in_x_indirect.txt, crates/compiler/test_mono/generated/rigids.txt, crates/compiler/test_mono/generated/toplevel_accessor_fn_thunk.txt
We no longer need this except for number literals, which are simple to handle.
=> Rip out polymorphic expression compilation

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/compare.rs, crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/gen_wasm/src/layout.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/mono/src/code_gen_help/equality.rs, crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/mono/src/code_gen_help/refcount.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/glue/src/types.rs, crates/repl_eval/src/eval.rs
This patch adds initial support for linking `RecursionPtr`s back to the union layouts they represent.
This is necessary for certain things like intersection recursive layouts, and gives us a path forward for addressing e.g. https://github.com/roc-lang/roc/issues/4905. It should also remove the need for utilities like `WhenRecursive` that the backends use.
Currently the compiler does not read the linked-back recursive pointers, but it does construct them correctly, and use them in layout comparisons. The bulk of the interesting changes are in `layout/intern.rs` , where a new `insert_recursive` method for interning recursive layouts has been introduced. The idea is that while building up a recursive layout, we will in its uses of `RecursivePtr` as `RecursivePtr(VOID)`, a recursive layout …
=> Initial support for linking recursive pointer layouts back to their source layouts

www/generate_tutorial/src/input/tutorial.md
"represents an the set of all" ->
"represents the set of all"
=> Remove redundant indefinite article in tutorial

Cargo.lock, crates/compiler/alias_analysis/Cargo.toml, crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/compare.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs
We still need WhenRecursive in the repl because that uses entry points in layout that operate over both layouts and variables, where we do not properly intern recursive layouts yet, but everywhere else WhenRecursive can be stripped out.
Also lifts some mutable usages of interners to not be mutable.
=> Get rid of WhenRecursive

crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/mono/src/code_gen_help/refcount.rs, crates/compiler/test_gen/src/gen_dict.rs
Closes #4679
#4683 fixed some wasm code gen issues for Dict, and now we can re-enable some tests.
One of the tests uncovered a bug in `mono::code_gen_help` (which generates refcounting code as IR for the dev backends). The `List` refcounting code does some pointer math with the data pointer and an alignment value. But it accidentally used the alignment of the `List` itself rather than the elements inside it.
=> Enable wasm dict tests

crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/debug/report.rs, crates/compiler/mono/src/decision_tree.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/compiler/mono/src/reset_reuse.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_mono/generated/recursively_build_effect.txt, crates/compiler/test_mono/src/tests.rs
- Adds a procedure for checking equality of layouts up to lambda sets. This is needed for the procedure that looks up a lambda's index in a lambda set, and for the ir-checker. This turns a test back on.
- Adds support for recursive lambda sets, where a capture links back to the lambda set itself. We intern these the same way we do regular recursive layouts.
Closes #4905
Closes #4694
This needs benchmarks; I will provide them soon.
=> Support equivalence for finding lambda sets

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/test_gen/src/gen_list.rs
Hey, PR with a couple more implementations for list operations in the dev backend :)
This PR closes #4960 and closes #4961 
I decided to group these as their implementations are similar and pretty straight-forward.
Haven't re-enabled the `list_bool_append` test as the bools are not supported in the dev backend within lists (yet).
=> gen_dev: add `List.reserve` and `List.append` using zig builtins

examples/parser/Parser/Http.roc, examples/parser/Parser/Str.roc
In this [PR](https://github.com/roc-lang/roc/pull/4858) I found I was getting crashes in `Parser.digits`. I worked around them by just leaving the relevant numbers as strings. Here's what happens when I try to parse the digits.
Tagging @folkertdev and @ayazhafiz since you have both done lots of work in mono.
```
thread 'main' panicked at 'internal error: entered unreachable code: symbol/layout `Parser.Core.combined` ProcLayout {
arguments: [
InLayout(
25,
),
InLayout(
139,
),
],
result: InLayout(
213,
),
niche: Niche(
Captures(
[
InLayout(
126,
),
InLayout(
137,
),
],
),
),
} combo must be in DeclarationToIndex
However 53 similar layouts were found:
...
```
=> Parse numbers in Http parser

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/test_gen/src/gen_num.rs
@bhansconnect I tried adding tests first, and expected the new tests to fail because I had not extended `build_num_sub` yet, but `cargo test gen_sub` passes on my machine. Am I missing something?
Closes #3792.
=> gen_dev: Support all number types in NumSub

www/public/index.html
Corrects two minor typos on the home page.
"communtiy" -> "community"
Signed-off-by: Jack Kellenberger <107156696+jmkellenberger@users.noreply.github.com>
=> Fixes two typos in index.html

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_gen/src/helpers/dev.rs
This PR adds `List.concat` and fixes a bug I introduced myself in `List.withCapacity`. It was using the layout of the list itself and not the list element to allocate. I've fixed this and brought in a macro helper from the llvm backend that's used to assert the `element_width` of lists.
`List.concat` is also implemented through the zig builtins.
This closes #4975 :)
I also noticed that the `clippy` CI check we use doesn't check with the `gen-dev` feature, so I fixed some of the lints I was running into in my editor. We may want to do a separate sweep of these lints at some point and perhaps check it in CI.
=> gen_dev: add `List.concat` and fix element width bug

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/compiler/gen_llvm/src/llvm/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/build_str.rs, crates/compiler/gen_llvm/src/llvm/compare.rs, crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/externs.rs, crates/compiler/gen_llvm/src/llvm/intrinsics.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, default.nix
upgrades to an inkwell version that supports llvm 15 (but llvm 15 is not yet enabled).
It then updates API usage in preparation of the llvm 15 upgrade
=> Update inkwell prepare llvm15

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/test_gen/src/gen_list.rs
Heyo, another PR for the dev backend :)
This time it's `List.prepend` which is similar to the existing `List.append` implementation.
I had to split up a test because some string usage caused invalid memory errors.
Closes #4981
=> gen_dev: add `List.prepend`

crates/cli/tests/cli_run.rs, examples/gui/breakout/hello-gui.roc, examples/gui/breakout/hello.roc
This is to prevent a name collision with breakout.roc example located in the same directory.
=> Use hello as app name for hello.roc example

crates/compiler/types/src/types.rs
SeqCst is definitely not needed here. Since this is just used for a debug counter and nothing relies upon the counter to provide any happens-before then Relaxed is all that is needed.
=> Atomic ordering for debug counter is stricter than nesscessary.

flake.nix, rust-toolchain.toml
`repl_wasm` requires Rust's `wasm32-unknown-uknown` toolchain and `wasm-pack` to be installed.
=> Add nix wasm32-unknown-unknown target and wasm-pack input

crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs
- When the layout cache is invalidated, we must compare all root keys in the cache to all root keys being invalidated. It is not enough to check variable equality since the roots may have changed.
- I want to make this more efficient later.
- Make sure the layout cache starts with zero layers. This way no extra variables hang around unnoticed if we are doing layout operations on the top-level.
- Debug tools
=> Fix a bug in layout cache and some more debugging tools

.gitignore, crates/compiler/build/src/link.rs
Usually the target folder directly contains `debug` or `release` but for different targets these can also be located in e.g. x86_64-unknown-linux-musl. My changes support that situation.
=> Support subfolders in target folder

crates/compiler/can/src/exhaustive.rs, crates/reporting/tests/test_reporting.rs
We should treat FunctionOrTagUnion types as tag unions for the purposes
of exhautiveness checking.
Closes #4994
=> Handle FunctionOrTagUnion types in exhaustiveness checking

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/test_gen/src/gen_list.rs
This PR fixes an issue where the function call building logic would consume the `HigherOrder` calltype.
Also drive-by added bools to list creation such that we can enable more tests.
=> gen_dev: Fix subtle issue with function call building and add bool to array creation in generic64

crates/compiler/builtins/roc/Str.roc
Unicode characters are escaped like `\u(00)` instead of `\{0x00}`. Tested that this is the same for the repl and the hello world example `Stdout.line "Hello,\u(0A)World!"`.
Found the correct syntax here:
https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/terminal.20unicode.20.2F.20colors/near/304768569
=> Fix unicode escape sequences in Str docs

crates/compiler/build/src/link.rs, crates/compiler/gen_dev/src/generic64/mod.rs
significantly simplifies the logic of allocating (which we'll use in some more places with box, tag, perhaps longer strings). 
cc @thehabbos007 you might like this
=> use `allocate_with_refcount` in the dev backend

README.md
**rwx** logo is missing. This is the best one I could find - it's from [their GitHub page](https://github.com/rwx-research/). Their current logo is provided as an inline SVG.
Signed-off-by: Henrikh Kantuni <henrikh.kantuni@gmail.com>
=> Fix rwx logo

.cargo/config
It isn't currently faster and it blocks user rustflags in their home/.cargo/config.toml
=> [Simple PR] Remove native from rust flags

crates/packaging/src/cache.rs
Static executables show "statically linked",
Yet static-pie show "ldd (address)"
So to account for that we should just check if there are any links with "=>"
=> fix error trigger for static-pie platforms

crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_mono/generated/recursive_lambda_set_has_nested_non_recursive_lambda_sets_issue_5026.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/types/src/pretty_print.rs, examples/helloWorld.roc
If a lambda set is non-recursive, but contains naked recursion pointers,
we should not fill those naked pointers in with the slot of the lambda
set during interning. Such naked pointers must belong to an encompassing
lambda set that is in fact recursive, and will be filled in later.
For example, `LambdaSet([Foo, LambdaSet(Bar, [<rec>])] as <rec>)` should
not have the inner lambda set's capture be filled in with itself.
Also, during reification of recursion pointers, we do not need to
traverse re-inserted lambda sets again, since they were just fixed-up.
Closes #5026 
Closes #4991
=> Do not fixup recursion pointers in non-recursive lambda sets

crates/compiler/mono/src/layout.rs
Lambda sets can only appear under function types, so we don't need to handle them independently in layout gen.
=> Remove unreachable lambda set layout branches

.github/workflows/windows_release_build.yml, .github/workflows/windows_tests.yml, crates/compiler/load/build.rs, crates/repl_wasm/build.rs, crates/repl_wasm/src/repl.rs
- `cargo build` was failing on windows due to the assumption that .o files were used, I've used `cfg` to use `.obj` on windows.
- I've added a CI workflow for `cargo build`, previously only the tests were built.
=> Windows build fixes + CI

crates/compiler/mono/src/ir.rs
refactor some code around host-exposed functions that will make it easier to add our glue changes. Nothing should have changed functionally
=> Ir refactor for glue

www/public/site.css
When inline code tags are split across newlines it becomes harder to read.
*Before*
*After*
=> Make it so inline code tags are not split across newlines

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/test_gen/src/gen_compare.rs
This PR adds some missing low-level functions, adjusting some of the existing ones. 
Does't quite close, but addresses some of the points in #3516
I noticed the `arguments!` macro in the LLVM backend, I think we could benefit from something like that in the dev backend, may look into that next.
One thing in this PR is how `not` is implemented as the bool representation is somewhat non-standard as outlined in https://github.com/roc-lang/roc/pull/3070/files#r906731092
I'm unsure what the conclusions were to that, but I've worked around this in the PR :)
=> gen_dev x86: misc low-level bool comparison functions 

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs
generates functions that evaluate roc closures, based on the layout of host-exposed functions. The mechanism for seeing whether a function is host-exposed is still based on the `as` aliases in platform `main.roc` modules. We'll have to figure out some other way of doing that eventually. 
the old mechanism also still fully works, the new functions are (for the moment) entirely unused.
=> Glue generate lambda set callers

www/public/site.css
As [Nick pointed out](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Tutorial/near/329053677) the tutorial doesn't look good on mobile if the inline code snippets are not wrapped on newlines.
I added a css rule to go back to normal line wrapping on mobile devices. This way the inline code snippets can still be on a single line on devices with a wider screen for a better reading experience
=> Wrap inline code on mobile devices

crates/compiler/can/src/debug/pretty_print.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/inc_dec.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/mono/src/layout/intern.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_does_not_duplicate_identical_concrete_types.txt, crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_keeps_all_concrete_types_without_unification.txt, crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_keeps_all_concrete_types_without_unification_of_unifiable.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/unify/src/unify.rs
There are times that multiple concrete types may appear in
unspecialized lambda sets that are being unified. The primary case is
during monomorphization, when unspecialized lambda sets join at the same
time that concrete types get instantiated. Since lambda set
specialization and compaction happens only after unifications are
complete, unifications that monomorphize can induce the above-described
situation.
In these cases,
- unspecialized lambda sets that are due to equivalent type variables
can be compacted, since they are in fact the same specialization.
- unspecialized lambda sets that are due to different type variables
cannot be compacted, even if their types unify, since they may point
to different specializations. For example, consider the unspecialized
lambda set `[[] + …
=> Lambda set compaction must preserve unique specializations of concrete types

crates/compiler/parse/src/blankspace.rs, crates/compiler/parse/src/highlight.rs, crates/compiler/parse/src/lib.rs, crates/compiler/region/src/all.rs, crates/compiler/test_syntax/tests/test_snapshots.rs, examples/static-site-gen/README.md, examples/static-site-gen/input/apple.md, examples/static-site-gen/output/style.css, examples/static-site-gen/platform/Cargo.lock, examples/static-site-gen/platform/Cargo.toml, examples/static-site-gen/platform/src/highlight.rs, examples/static-site-gen/platform/src/lib.rs
Adds syntax highlighting support for the static-site platform using the Roc parser. 
Can I request a review and some feedback please @Anton-4 and @joshuawarner32. Intention is for this to be used in the tutorial and for content on the Roc website.
I used strange colours in the example to visually separate the different css classes.
=> Roc parser syntax highlighting for static-site platform

www/generate_tutorial/src/input/tutorial.md
Adds content for package modules section to tutorial based on [zulip discussion](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/Tutorial.20Package.20Modules/near/340046795) and Richard's [design proposal](https://docs.google.com/document/d/1SRzBuW_hn17LzCpxk-DWCHqpegI2WzuLdQpE3-qc9Lc/edit).
=> Add Package modules section to tutorial

crates/compiler/parse/src/highlight.rs, crates/docs/src/static/styles.css, crates/highlight/src/lib.rs, www/generate_tutorial/src/input/tutorial.md, www/public/site.css
This PR groups a number of minor changes to the Docs and Tutorial
1. Fixes inline styles on markdown tables caused by using alignment in markdown
2. Fixes colors to conform to WCAG 2.0 AA standard for contrast
3. Removes styles that are no longer used, and improves commonality across Docs and Tutorial, improves consistency of formatting across classes and between light and dark modes
4. Upgrades styling of Documentation so that each function looks visually more like a "card"
5. Adds support for the `*`, `_`, `@` tokens in highlighting.
=> Docs updates and visual improvements

www/generate_tutorial/src/tutorial.roc
Changing "much more" to "more" avoids a one-word wrapping:
=> Tweak tutorial intro wording

crates/docs/src/static/styles.css
This makes the "cards" a bit more visually distinct from one another.
=> Increase spacing between docs entries

crates/cli/src/lib.rs, crates/cli/tests/editor.rs, crates/editor/src/editor/main.rs
`roc edit main.roc` did not work yet, I've also added tests for the three types of cli arg situations.
Context:
https://roc.zulipchat.com/#narrow/stream/257722-editor/topic/error.20when.20starting.20on.20macOS/near/339884894
=> fix `Arg::allow_invalid_utf8` clap error

crates/cli/tests/fixtures/multi-dep-str/platform/host.zig, crates/cli/tests/fixtures/multi-dep-thunk/platform/host.zig, crates/cli/tests/fixtures/packages/platform/host.zig, crates/cli_testing_examples/expects/zig-platform/host.zig, crates/compiler/builtins/bitcode/src/dec.zig, crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/bitcode/src/str.zig, crates/compiler/builtins/bitcode/src/utils.zig, crates/compiler/builtins/roc/List.roc, crates/compiler/builtins/src/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/roc_std/src/roc_list.rs, crates/valgrind/zig-platform/host.zig, examples/cli/false-interpreter/platform/src/lib.rs, examples/platform-switching/web-assembly-platform/host.zig, examples/platform-switching/zig-platform/host.zig, examples/virtual-dom-wip/platform/src/server-side/host.zig
This PR adds seamless slices for Lists in Roc. It does not add them to strings.
Now functions like `List.drop` and `List.subList` will return slices. This should greatly help with the parser use case if a parser is operating over a list of bytes.
=> Seamless slices for Lists

crates/compiler/builtins/bitcode/src/str.zig
From my quick testing using the code for testing this function in zig standard lib:
```
small ascii:     2.2x
small unicode:   0.9x
medium ascii:    15x
medium unicode:  1.01x
medium mix:      3.25x
large ascii:     32.8x
large unicode:   1.03x
large mixed:     3.35x
```
small being less than 8 bytes.
large being roughly greater than 512 bytes.
Not sure the exact turn over point, but only small unicode only strings are slower.
=> Add a fast path for validating ASCII charcters

crates/cli/tests/cli_run.rs, crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/str.zig
Found some bugs with fuzzing and valgrind. Mostly minor edges cases around empty seamless slices.
Fixed a bug in my new utf8 code where we accessed passed the end of the array. The fix did not effect performance in any meaningful way.
Also, seamless slices caused us to hit an older bug in sublist where we would not decrement the refcount of elements in lists if the list was not unique and the sublist was going to be empty.
=> Misc seamless slice bugs

crates/compiler/builtins/roc/Dict.roc, crates/compiler/test_mono/generated/dict.txt
Noticed that some methods were missing documentation when trying to look into the Dict builtin. I updated some documentation and added some additional tests.
=> add docs/tests to Dict builtin

www/generate_tutorial/src/input/tutorial.md
Hi I just started to learn roc and it is a really nice language!
While going through the tutorial, I found a possible mistake. This PR fixes it.
=> Fix a field name in tutorial to match its context

crates/compiler/can/src/module.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_mono/generated/recursive_closure_with_transiently_used_capture.txt, crates/compiler/test_mono/src/tests.rs
With a code like
```
thenDo = \x, callback ->
callback x
f = \{} ->
code = 10u16
bf = \{} ->
thenDo code \_ -> bf {}
bf {}
```
The lambda `\_ -> bf {}` must capture `bf`. Previously, this would not happen correctly, because we assumed that mutually recursive functions (including singleton recursive functions, like `bf` here) cannot capture themselves.
Of course, that premise does not hold in general. Instead, we should have mutually recursive functions capture the closure (haha, get it) of values captured by all functions constituting the mutual recursion. Then, any nested closures can capture outer recursive closures' values appropriately.
=> Ensure that closures inside recursive closures capture correctly

crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/test_gen/src/gen_tags.rs
When we load a structure with a nested recursive pointer, the pointer
may be loaded opaquely. We need to refine it to the concrete type wanted
by the layout.
This conversion can be removed after we upgrade to LLVM 15.
Closes https://github.com/roc-lang/roc/issues/5162
=> Properly recast nested recursion pointers to their expanded layouts as needed

crates/compiler/derive_key/src/decoding.rs, crates/compiler/derive_key/src/encoding.rs, crates/compiler/mono/src/ir.rs, crates/compiler/solve/src/solve.rs, crates/compiler/unify/src/unify.rs
- Derivation of abilities for recursive types should trivially pass under the recursion var
- When we adjust rank for an alias's type variable, don't adjust its lambda set variables. The reasoning is given in the diff.
Closes #4806
=> Fix a few bugs Virtual-DOM cropped up

crates/docs/src/lib.rs
This PR resolves #4474 .
Thank you for the review!
=> Treat html as text in markdown parsing to disallow html in docs

crates/roc_std/src/lib.rs, crates/roc_std/src/roc_str.rs
Otherwise, you will get compile errors with the std feature.
=> Only mark roc_std no_std if std feature is not present

crates/compiler/can/src/debug/pretty_print.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_mono/generated/compose_recursive_lambda_set_productive_nullable_wrapped.txt, crates/compiler/test_mono/generated/recursive_lambda_set_resolved_only_upon_specialization.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/unify/src/unify.rs
- If a recursion variable is the head of a type, always unify its structure with another recursion variable if the var hasn't been seen before. This is relevant because sometimes, the full recursive structure (in particular for a lambda set) may not be known until specialization.
I'd like to add a debug tool that specializes a function relative to another and prints all elaborations of the specialization. I'll do that in a separate PR.
- Handle nullable wrapped recursive lambda sets.
=> Fix compilation problems with recursive lambda sets

crates/compiler/gen_llvm/src/llvm/convert.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/repl_expect/src/lib.rs
when one tag had a bigger payload than another, the tag id was put in the wrong place
=> expect tag padding

crates/compiler/mono/src/ir.rs, crates/compiler/test_mono/generated/issue_4759.txt, crates/compiler/test_mono/src/tests.rs
There might be more symbols than field layouts when restructuring a
record if the record is a newtype.
Closes #4759
=> Remove inaccurate debug assertion in IR gen

crates/compiler/alias_analysis/src/lib.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_wasm/src/backend.rs, crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/debug/checker.rs, crates/compiler/mono/src/inc_dec.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/reset_reuse.rs
adds a null pointer Expr, which is useful as a placeholder for a missing reuse token (part of implementing perceus)
=> add NullPointer to mono::ir::Expr

crates/compiler/module/src/called_via.rs
**Update:** found a downside! `x * y |> Num.toStr` no longer works if we give it the *highest* precedence. So instead I tried moving its precedence to higher than everything except arithmetic operators. (So, just higher than comparisons.)
---
In [a Zulip thread](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/pizza.20precedence) we discussed making the `|>` operator have the highest precedence. There seemed to be only upsides and no downsides, so this PR does that!
Also, it implements some performance optimizations: namely, making precedence, associativity, and `Display` all use `const` lookup tables instead of conditionals.
=> Give |> the highest precedence, plus some perf opt

crates/compiler/types/src/subs.rs
Turns out this mark cache check is unreasonably effective, even if it is naive.
=> Do not revisit variables in an occurs check

crates/compiler/builtins/roc/Json.roc
I ran into this little problem while trying to use the `Json` module for the first time. I used the example as a guide to implement my first JSON decoder.
I got a little confused because I was not sure where the `fromUtf8` and `toUtf8` functions came from. From the `Str` module or maybe from the `Decode` module?
Because the example does not show how the functions were imported, we introduce some (in my eyes) unnecessary ambiguity.
I thought that qualified imports remove the ambiguity!?
=> use qualified imports for json example

crates/cli/tests/cli_run.rs
Some tests used to require multiple locks and one test acquired lock A but failed to acquire lock B, another test was holding lock B and required lock A. That way you get stuck! I've turned those multiple locks into a bigger shared one, deadlock proof.
=> fixed cli_run serial macro deadlock

crates/compiler/can/src/pattern.rs, crates/compiler/collections/src/soa.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/test_solve_helpers/src/lib.rs, crates/compiler/types/src/types.rs, crates/compiler/uitest/tests/recursion/calls_result_in_unique_specializations.txt, crates/compiler/uitest/tests/recursion/constrain_recursive_annotation_independently_issue_5256.txt, crates/reporting/tests/test_reporting.rs
The algorithm for solving recursive definitions proceeds in several
steps. There are three main phases: introduction of what's known,
solving what's not known, and then checking our work of what was
inferred against what the programmer claimed. Concretely:
1. All explicitly-annotated signatures in the mutually recursive set are
introduced and let-generalized.
2. Then, inference type variables (`_`) and unannotated def signatures are
introduced to the cycle, without generalization. The bodies of these
defs, that are either unannotated or have inference variables, are
solved.
3. The defs from step (2) are now let-generalized, since we now know
that their types are consistent. At this point, all the defs in the
cycle have their types introduced and let-generalized, but we still
haven't …
=> Introduce annotation in first step of recursive solving independently

crates/docs/src/static/styles.css, examples/static-site-gen/platform/Cargo.toml, examples/static-site-gen/platform/src/lib.rs, www/public/site.css
- Adds `syntect` dependency to static-site platform for syntax highlighting code
- Updates static-site inline code to use `roc!` prefix for highlighting Roc code (discussed below)
- Updates static-site fenced code blocks to support other languages
- Updates `.css` files for good coverage of syntect classes, tested with `haskell` and `rust` languages (note syntect doesn't support Elm however Haskell is a good substitute)
The platform currently highlights inline code blocks by default and assumes they are Roc. This worked well for the tutorial however, does not make sense when used in other places. The main motivation here is development of the Examples site, and a possible Articles site, which often include inline snippets which are not roc code. For example these could be shell commands, …
=> Support highlighting other languages using static-site platform

crates/compiler/solve/src/solve.rs, crates/compiler/uitest/tests/recursive_type/multiple_nested_recursive_lambda_sets.txt
If a lambda set appears in an occurs chain but it is itself already recursive, then it is should not be eligibil for modification in the occurs chain.
Closes #4725
=> Do not replace already-recursive lambda sets in occurs checks

crates/compiler/can/src/annotation.rs, crates/compiler/can/src/def.rs, crates/compiler/can/src/scope.rs, crates/compiler/test_solve_helpers/src/lib.rs, crates/compiler/types/src/types.rs, crates/compiler/uitest/src/mono.rs, crates/compiler/uitest/src/uitest.rs, crates/compiler/uitest/tests/recursive_type/freshly_instantiated_recursion_var_under_alias.txt, crates/compiler/uitest/tests/recursive_type/freshly_instantiated_recursion_var_under_opaque.txt
Like we instantiate nested lambda set variables and nested OIOP
variables for aliases, we need to do the same for recursion variables.
Closes #5264
=> Freshly instantiate nested recursion variables under aliases and opaques

crates/cli/tests/fixtures/multi-dep-str/platform/host.zig, crates/cli/tests/fixtures/multi-dep-thunk/platform/host.zig, crates/cli/tests/fixtures/packages/platform/host.zig, crates/cli_testing_examples/algorithms/quicksort-platform/host.zig, crates/cli_testing_examples/benchmarks/platform/host.zig, crates/cli_testing_examples/expects/zig-platform/host.zig, crates/compiler/build/src/link.rs, crates/compiler/builtins/bitcode/src/glue.zig, crates/valgrind/zig-platform/host.zig, examples/cli/effects-platform/host.zig, examples/cli/tui-platform/host.zig, examples/platform-switching/web-assembly-platform/host.zig, examples/platform-switching/zig-platform/host.zig, examples/virtual-dom-wip/platform/src/client-side/host.zig, examples/virtual-dom-wip/platform/src/server-side/host.zig
@lukewilliamboswell this should enable you to import `list.zig`, just done as `@import("glue").list.RocList`. That said, it may be more hassle to use than you want. It is pretty low level and everything is just bytes. Copying what the quicksort cli testing host does may be simpler for you. Though if you are using lists of bytes, this shouldn't be too bad.
=> enable using other zig libaries in host instead of just str.zig

Cargo.lock, crates/compiler/can/src/expr.rs, crates/compiler/can/src/module.rs, crates/compiler/can/src/operator.rs, crates/compiler/can/src/scope.rs, crates/compiler/can/src/string.rs, crates/compiler/parse/Cargo.toml, crates/compiler/parse/src/expr.rs
showing some love by making a little contribution. 
related to https://github.com/roc-lang/roc/issues/2046
=> Replace panic! with internal_error! in `compiler/parse` and `compiler/can`

crates/compiler/builtins/roc/List.roc
The example in the docs for `List.intersperse` mistakenly pass the separator as the first argument when it should be passing the list.
=> Fix `List.intersperse` docs example

crates/cli/src/lib.rs, crates/compiler/build/src/link.rs, crates/compiler/build/src/program.rs, crates/compiler/roc_target/src/lib.rs, examples/platform-switching/web-assembly-platform/host.zig
- Set opt_level correctly for all subcommands
- Properly run dev when requested
- use `wasm32-wasi` for llvm host and wasm backend
- fix wasm-ld warnings
=> Fix misc wasm compilation issues

crates/compiler/gen_dev/src/object_builder.rs
This is now required by newer versions of `ld`.
=> specify dev roc objects do not require an exec stack

crates/compiler/gen_dev/src/object_builder.rs
Just adding wrappers to make `ld` happy.
=> add missing symbols to dev object files on unix

crates/repl_cli/src/repl_state.rs
Fixes #5337.
I think this part of the code is just old and wans't updated correctly as things changed around it. The comments mentioned removed functions and I couldn't reproduce the issues they used as justifications for calling `ReplState::eval_and_format` after `parse_src` returned `ParseOutcome::Empty`. When the input is incomplete, the `Validator` will prevent a new input beeing emitted and thus if the user is in the middle of a `when` and wants a blank line, it won't get to `ReplState::step` since the validator will say the input is incomplete. If the user wants a blank line without adding identation, just use ctrl-j + ctrl-v.
Please let me know if there are any unhandled scenarios for this that I might have ignored.
=> fix: repl panic on empty line

crates/compiler/constrain/src/expr.rs, crates/reporting/tests/test_reporting.rs
Turns out we used to freely allow things like
```
f : U8, U8 -> U8
f = \x -> x
```
now we don't!
Closes #5236
=> Catch non-recursive function arity mismatches during typechecking

crates/compiler/solve/src/solve.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/test_mono/generated/issue_4770.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/test_solve_helpers/src/lib.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/subs.rs, crates/compiler/uitest/src/uitest.rs, crates/compiler/uitest/tests/exhaustive/catchall_branch_for_pattern_not_last.txt, crates/compiler/uitest/tests/exhaustive/catchall_branch_walk_into_nested_types.txt, crates/compiler/uitest/tests/pattern/generalize_openness_in_recursive_context_issue_4770.txt, crates/compiler/uitest/tests/recursive_type/generalize_introduced_recursion_variable_issue_4770.txt, crates/compiler/uitest/tests/solve/infer_contextual_crash.txt, crates/compiler/unify/src/unify.rs
- [Correctly introduce new openness variables at the union rank](https://github.com/roc-lang/roc/commit/7ac24e8afe66c07101bc51d5a1f002a9f027d15c)
- [Correctly introduce new recursion variables at the correct rank](https://github.com/roc-lang/roc/commit/e38b7949554549a9b293f93b002ebc4868ba79bd)
[Defer resolution of a recursion variable during union unification until merging](https://github.com/roc-lang/roc/commit/dd6cb957461c1ce3ab619ae51caa998de65adf8f)
Closes #4770
=> Various bug fixes to generalization and solving of recursion

BUILDING_FROM_SOURCE.md, CONTRIBUTING.md, crates/compiler/builtins/README.md, crates/compiler/builtins/bitcode/README.md, crates/compiler/gen_dev/README.md, crates/compiler/gen_dev/src/todo.md, crates/linker/README.md, design/editor/editor-ideas.md, design/language/Abilities.md, design/language/RocStr.md, getting_started/macos_x86_64.md, roc-for-elm-programmers.md, www/README.md, www/generate_tutorial/src/input/tutorial.md
Also from Luke Boswell: move Str.md as it looks more like a design doc than rust crate
This supersedes https://github.com/roc-lang/roc/pull/5066, which had unsigned commits and partial reverts.
=> markdown typo fixes

crates/compiler/load_internal/src/file.rs, crates/compiler/mono/src/ir.rs
Rather than calculating the HELS for each host-exposed layout (of which there may be multiple), we only need to calculate the HELS based on the top-level type of the host-exposed function.
Also renamed `GlueProcs.extern_names` to
`GlueProcs.legacy_layout_based_extern_names` since they are still currently generated based on the layout, but I think we want to generate all HELS via type variable.
Fixes false-interpreter builds in debug.
=> Determine host-exposed lambda sets once based on proc variable

Cargo.lock, crates/compiler/build/src/link.rs, crates/compiler/builtins/Cargo.toml, crates/compiler/builtins/bitcode/Cargo.toml, crates/compiler/builtins/bitcode/bc/Cargo.toml, crates/compiler/builtins/bitcode/bc/build.rs, crates/compiler/builtins/bitcode/build.rs, crates/compiler/builtins/src/roc.rs, crates/compiler/load/Cargo.toml, crates/compiler/load/build.rs, crates/compiler/module/src/symbol.rs
relates to https://github.com/roc-lang/roc/issues/2046
=> chore: replace panic! with internal_error! in compiler modules

.github/workflows/nix_linux_x86_64.yml
There used to be an uncaught failure of the gen-dev tests that only occurred on nix, this test should prevent that from happening in the future.
=> do test-gen-dev on nix too

.cargo/config.toml
Brendan benchmarked this a while ago and not using native is actually faster!
=> removed target-cpu native

crates/compiler/can/src/debug/pretty_print.rs, crates/compiler/mono/src/debug/report.rs, crates/compiler/mono/src/ir.rs, crates/compiler/types/src/types.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/src/error/type.rs, crates/reporting/src/report.rs, crates/vendor/pretty/src/lib.rs
Many times, in order to create a `ven_pretty::Doc` containing a text node, the pattern `alloc.text(format!(...))` would be used. This code then creates a fresh string that is then used in the `Doc`. However, many times only a small string is necessary and so the allocation could be optimized. The `ven_pretty` crate supports this through a `SmallString` type. Allocating a fresh string with `format!` also moves control away from the `DocAllocator` which isn't ideal, since it could also handle the string allocations. So, instead of creating a fresh string, one can simply call `alloc.as_string(format_args!(...))` and delegate the allocation to the `DocAllocator` without any loss in expressivity. So, in order to encorage this pattern, this commit also introduces the `text!` macro.
In order to …
=> refactor: remove needless string allocation in pretty printer

crates/docs/src/lib.rs
For debug builds only, instead of including the contents of files in `crates/docs/src/static` as string literals using `include_str!`, read the contents from the filesystem.
This means that Cargo no longer has to rebuild when e.g. `index.html` or `styles.css` change, allowing faster iteration on the theme and layout of the generated docs.
Opened per this conversation: https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/docs.20improvements/near/355812138
- Should I do more robust error handling on `fs::read_to_string` calls? Should that perhaps be another PR with better error handling for the `fs::write` calls as well?
- Do the comments sufficiently clarify what I did? 
- Any stylistic changes to make?
Many tests failed on my machine, even on `main` (MacOS 13.3.1 ARM). Hope I …
=> Docs: read static assets from fs for debug builds

crates/cli/tests/cli_run.rs, crates/compiler/build/src/link.rs
It turns out we did need this on mac M1 after all.
Need to find another solution to https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/macos.20linking.20error which doesn't cause a regression on M1s
=> Revert "remove undefined -dynamic_lookup"

crates/docs/src/lib.rs, crates/docs/src/static/styles.css
Generates a basic `index.html` for packages. The page contains only a list of exposed modules for now. 
I also renamed `sidebar_link_url` to `module_link_url`, since I am now using it outside of the sidebar context as well. 
Open to any and all feedback!
Paging @lukewilliamboswell for 👀
=> Docs: index.html for packages

mlc_config.json
The link checker recently started having problems with twitter links.
=> fix twitter max redirects

crates/ast/src/constrain.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/src/operator.rs, crates/compiler/can/tests/test_can.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/module/src/called_via.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/parser.rs, crates/compiler/parse/src/type_annotation.rs, crates/compiler/problem/src/can.rs, crates/compiler/test_syntax/tests/test_fmt.rs, crates/compiler/types/src/types.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/src/error/parse.rs, crates/reporting/src/error/type.rs, crates/reporting/tests/test_reporting.rs
Implements the syntax described in the [Record Builder proposal](https://docs.google.com/document/d/1Jo9nZCekkoF6SaDcRqPqoPcgPaAAvlNZC7v3kgVQ3Tc/edit) with [some changes](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/Record.20Builder.20Syntax/near/355286566):
```elm
usersAndPosts : Task { users: List User, posts: List Post } _
usersAndPosts = Task.succeed {
users <- Http.get "/users" |> Task.batch,
posts <- Http.get "/posts" |> Task.batch,
}
```
⭐  This is not specific to `Task`, it's just syntax sugar for applicative pipelines. As seen in [elm-json-decode-pipeline](https://package.elm-lang.org/packages/NoRedInk/elm-json-decode-pipeline/latest/) or [dillonkearns/elm-graphql](https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-SelectionSet#pipe …
=> Record Builder Syntax

.cargo/config.toml, crates/compiler/gen_dev/src/lib.rs
for symbols captured by a join point, they would be last seen within the join point, and therefore considered dead after the first iteration of the joinpoint. Now such variables are alive for the whole duration of the join point.
=> Last seen join points

Cargo.lock, Cargo.toml, crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/cli/tests/cli_run.rs, crates/compiler/build/src/program.rs, crates/docs/src/lib.rs, crates/docs_cli/src/main.rs, crates/packaging/src/cache.rs, crates/wasm_interp/src/main.rs, default.nix
Issue https://github.com/roc-lang/roc/issues/5388
Summary of changes
- Use `Arg.num_args`
- [Supersedes](https://github.com/clap-rs/clap/issues/2688) `multiple_values` and `takes_value`
- Use `Arg.value_parser`
- Replace `Arg.possible_values`
- Remove use of `Arg.allow_invalid_utf8`, either parsing directly to `PathBuf` or `OsString`
- Move custom parsing logic from usage to arg definition (e.g., `usize`)
- Use `ArgMatches.get_one` and `ArgMatches.get_many` in place of `ArgMatches.value_of*` and `ArgMatches.values_of*`
- Use [new flag/option idioms](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md?plain=1#L558)
- `Arg.action(ArgAction::SetTrue)` for flags
- Replace `ArgMatches.is_present` with `ArgMatches.get_flag` for flags
- Replace `ArgMatches.is_present` with …
=> Upgrade to clap 4

crates/cli/tests/cli_run.rs, crates/cli_utils/src/helpers.rs, crates/glue/tests/test_glue_cli.rs
Context: https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Linker.20error.20running.20.60roc.20glue.60.20tests
=> Consistent handling of ld chained fixup warning in cli/glue tests

Cargo.toml
Fixes omission in the [clap v4 upgrade](https://github.com/roc-lang/roc/pull/5405)
See [relevant bullet](https://github.com/clap-rs/clap/blob/2d4644a8703369d3a3c50dd58c713d48ab1da2ac/CHANGELOG.md?plain=1#LL590C32-L590C67) in changelog.
=> Fix `roc help`

crates/compiler/can/src/operator.rs, crates/compiler/can/tests/test_can.rs, crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/test_syntax/tests/test_fmt.rs, crates/reporting/src/error/type.rs, crates/reporting/tests/test_reporting.rs
As discussed in this [Zulip topic](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/label.20syntax.20for.20record.20builders), we'd like to try out a new syntax for Record Builder fields that keeps the `:` after the label:
```elm
usersAndPosts = Task.succeed {
users: <- Http.get "/users" |> Task.batch,
posts: <- Http.get "/posts" |> Task.batch,
}
```
The intention is to make it clearer that we are assigning a record field, and obvious that this isn't introducing a new name to scope.
=> New Record Builder `: <-` syntax

crates/docs/src/lib.rs, crates/docs/src/static/index.html, www/build.sh
An index.html was recently added that provided links to all the docs modules, it did not end up in the builtins folder but in the root folder, thereby replacing the home page for roc-lang.org. This PR fixes that.
=> fixed docs index.html overwrite

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/cli/src/main.rs
https://github.com/roc-lang/roc/issues/5388
`roc [FILE]` no longer requires `--`, to allow for better error messaging (see `foromat` example below). Subcommands are required up front to avoid ambiguity:
```
$ roc help
Run the given .roc file, if there are no compilation errors.
You can use one of the SUBCOMMANDS below to do something else!
Usage: roc [OPTIONS] [ROC_FILE] [ARGS_FOR_APP]...
roc <COMMAND>
```
`--` is still required for `roc <COMMAND>`:
```
$ roc help test
Run all top-level `expect`s in a main module and any modules it imports
Usage: roc test [OPTIONS] [ROC_FILE] [-- [ARGS_FOR_APP]...]
```
When `roc [FILE]` errors, we provide a hint about a possible misspelled subcommand:
```
$ roc foromat *
This file was not found: /Users/dlsmith/src/roc/foromat
Did you mean to use the …
```
=> Remove `--` requirement for `roc [FILE]` to allow better messaging

crates/compiler/mono/src/drop_specialization.rs, crates/compiler/mono/src/layout.rs, crates/compiler/test_mono/generated/issue_4749.txt, crates/compiler/test_mono/generated/issue_4770.txt, crates/compiler/test_mono/generated/issue_4772_weakened_monomorphic_destructure.txt, crates/compiler/test_mono/generated/rb_tree_fbip.txt, crates/compiler/test_mono/generated/specialize_after_match.txt, crates/compiler/test_mono/src/tests.rs
this allows drop specialization to remove increments before a pattern match to drop specialize drops in the pattern match branches.
=> allow lowlevel and match

crates/compiler/builtins/bitcode/src/compiler_rt.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/linker/src/elf.rs, crates/linker/src/pe.rs
Also removes the workaround in the surigical linker. This should mean we should get clear errors if we missed a function instead of crashes/segfaults.
Fixes #5471
=> Add all fns in compiler-rt that builtins are known to depend on

crates/compiler/test_gen/src/gen_num.rs
Found this simple typo while trying to understand the gen-dev part. Seems like now the test will be run and is ok.
=> Fix typo in gen-dev for float_add_overflow test

crates/cli/tests/cli_run.rs, crates/compiler/builtins/bitcode/build.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/bitcode/src/num.zig, crates/compiler/builtins/src/bitcode.rs, crates/compiler/gen_llvm/src/llvm/intrinsics.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs
Instead we use the zig standard library functions. The zig standard library functions never call libc. They will only use an llvm instrinsic if it does not generate a call to libc.
=> Stop using llvm instrinsics that just call libc

crates/compiler/gen_llvm/src/llvm/build.rs
Currently decref on unions with a tag causes an incorrect value_ptr to be created, resulting in memory not being deallocated. Which is especially notable as drop specialization inserts a lot of decrefs for unions. This should fix the problem.
=> DecRef union clear tag id

crates/compiler/build/src/program.rs
So that we can see how much time it takes to build LLVM IR vs run it through LLVM. For the dev backends this is immaterial
=> Differentiate generating final IR and dumping it to an object in cgen

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs
Current **num_mul** does what **num_mul_wrap** should do. So move code to wrapped and call it from **num_mul**. Also add comment for num_mul that we should panic on overflow.
=> Move old num_mul to num_mul_wrap and use that from num_mul

crates/docs/src/lib.rs, crates/docs/src/static/styles.css
This PR removes docs syntax highlighting for inline code snippets to improve consistency and align with the Tutorial behaviour. Does not affect fenced code blocks which are assumed to be Roc lang and highlighted.
Also a minor change to a variable name `cow_str` to `code_str` to clarify its usage.
=> Various updates for docs generation 

crates/glue/src/RustGlue.roc, examples/glue/glue.roc, examples/glue/rust-platform/src/lib.rs
uses `canDerivePartialEq` as a proxy for Hash and Ord. I think this is correct right now, we may need to give them custom `canDerive*` functions in the future.
=> glue: limit derives

README.md
It used to be necessary to link to a specific module page but a module overview page was recently added.
=> link docs to overview

www/build.sh
Currently we only have docs for the latest git version, this PR also adds docs for 0.3.2
=> basic-cli docs site for 0.3.2

crates/compiler/build/src/program.rs, crates/compiler/gen_llvm/src/llvm/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/gen_llvm/src/llvm/struct_.rs, crates/compiler/test_gen/src/helpers/llvm.rs
some changes to make the llvm 15 upgrade easier
- in the next release, more llvm operations need a type argument
- enum values that are not 0 cause issues
- we should generally prefer 32-bit indices for GEP
=> Llvm 15 preparations

crates/reporting/src/error/parse.rs, crates/reporting/tests/test_reporting.rs
Fixes [this issue](https://github.com/roc-lang/roc/issues/5516)
=> Give better error messages when provides is missing in header

crates/compiler/builtins/roc/Dict.roc, crates/compiler/builtins/roc/List.roc, crates/compiler/builtins/roc/Set.roc, crates/compiler/module/src/symbol.rs, crates/compiler/test_mono/generated/dict.txt, crates/compiler/uitest/tests/ability/specialize/set_eq_issue_4761.txt
Also remove some unnecessary Hash and Eq restrictions
=> Add some missing Dict and Set functions

crates/compiler/mono/src/code_gen_help/equality.rs, crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/mono/src/code_gen_help/refcount.rs, crates/compiler/mono/src/ir.rs
not a significant change, but I want CI to run on this.
our goal is to remove `Boxed` soon (and just use `NonNullableUnwrapped` for our `Box.Box`)
=> use Ptr instead of Boxed in the code-gen-help

crates/linker/src/elf.rs, crates/linker/src/macho.rs
The `i8` is a `u8` on raspberry pi 4 aarch64 linux, `c_char` takes care of this automatically.
=> aarch64 linux c_char fix

crates/compiler/parse/src/header.rs, crates/compiler/test_syntax/tests/snapshots/pass/space_before_colon.full.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/space_before_colon.full.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/space_before_colon.full.roc, crates/compiler/test_syntax/tests/test_snapshots.rs
=> Allow spaces before and after the colon in the `packages` header section

www/README.md
`--index` makes it so that you don't need to go explicitly to /index.html
=> added http-server arg

crates/compiler/build/src/target.rs
This fixes the error `relocation R_AARCH64_MOVW_UABS_G0_NC cannot be used against local symbol`.
This fix is already in #5577 but that PR is stuck on a difficult segfault.
=> aarch64 linux error fix

crates/compiler/builtins/roc/List.roc, crates/glue/src/RustGlue.roc, crates/glue/tests/fixtures/advanced-recursive-union/src/lib.rs, crates/glue/tests/fixtures/basic-recursive-union/src/lib.rs, crates/glue/tests/fixtures/nullable-wrapped/src/lib.rs, crates/glue/tests/fixtures/union-with-padding/src/lib.rs, crates/glue/tests/fixtures/union-without-padding/src/lib.rs
Fixes https://github.com/roc-lang/roc/issues/5681
Also makes it so that if there are any `()`s in the Rust signatures, they get dropped.
=> RustGlue.roc improvements

crates/docs/src/lib.rs, crates/docs/src/static/index.html
`ROC_DOCS_URL_ROOT` was previously used to put "hardcoded" links in many href's, now we put the root in the HTML base tag and use relative links everywhere. I already used this for the basic-cli 0.3.2 docs.
=> use html base for single source of truth

www/build.sh
https://github.com/roc-lang/roc/pull/5661 uses js and css from the current directory, but we did not move those files before, this PR fixes that.
=> fix basic-cli docs css+js

.github/workflows/nightly_old_linux_arm64.yml
When the rust version is upgraded this can take a long time on a raspberry pi.
=> updated arm64 CI timeout

crates/compiler/can/src/expr.rs, crates/compiler/can/src/operator.rs, crates/repl_test/src/cli.rs, crates/repl_test/src/tests.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/tests/test_reporting.rs, www/generate_tutorial/src/input/tutorial.md
String interpolation can now include any expression as long as it doesn't contain newlines, comments, or other string interpolations.
=> Allow expressions inside string interpolation

crates/compiler/build/src/link.rs, crates/linker/src/generate_dylib/macho.rs
Apparently the only way to suppress this is by giving `ld` the `-w` flag (suppress all warnings). As we've previously learned, changing the thing it's warning about either breaks macOS on x64 or on ARM, so suppressing the warning seems like the only option to prevent it from printing all the time.
In the future, switching to surgical linking on macOS will be a nicer permanent fix for this!
=> Fix macos ld warning

www/build.sh
All basic-cli releases are now scanned for a docs.tar.gz and a docs website is set up for every release that has one.
=> better basic-cli docs site automation

.github/workflows/windows_tests.yml, crates/compiler/gen_dev/src/generic64/aarch64.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/storage.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_dev/src/object_builder.rs, crates/compiler/mono/src/code_gen_help/mod.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_gen/src/helpers/dev.rs
proof of concept of roc_panic. I think a `crash` is the only thing that panics at the moment though, so still some work left to do after this to really get parity.
=> dev backend: roc panic

Cargo.lock, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/test_gen/Cargo.toml, crates/compiler/test_gen/src/helpers/llvm.rs
fixes two issues in the windows dev backend. This _almost_ makes `gen_num` pass, but there is still a bug in `num_to_str` that turns out to be hard to debug. So for now this is not tested on CI yet.
=> Fix 2 bugs in windows dev backend

crates/glue/src/RustGlue.roc
Previously, we were unconditionally generating impls like `Eq`, `Ord`, and `Hash` for tag unions, but that's invalid if the tag union (for example) contains floats. Now we do the same check we do for `derive` before doing these.
=> Situationally gen Eq/Ord/Hash glue for tag unions

crates/reporting/src/error/type.rs
Tuples with ellipses were printed as `(…}` instead of `(…)`
Separately, we were including spaces inside the parens (like we do for records, but shouldn't do for tuples).
=> Fix formatting in tuple errors

crates/compiler/builtins/roc/Hash.roc, crates/compiler/load_internal/src/docs.rs, crates/compiler/parse/src/ast.rs, crates/docs/src/lib.rs
We now generate docs for:
* Ability declarations (e.g. `Hash.Hash`)
* Ability constraints in type annotations
* Tuples
* `as` in type annotations
Also this improves a minor off-by-one space error in `->` docs generation for function annotations.
=> Fix various missing docs implementations

crates/cli/tests/cli_run.rs
the basic-cli build process does not yet include the necessary files for windows
=> ignore inspect_logging on windows

crates/glue/src/load.rs
This reverts commit 7be590fae9ab0a5ef65abd23190a499f5c9e99ca.
Unfortunately it breaks the `glue` command we're using at work, so I need to revert it so we can upgrade to the latest nightly `roc`! cc @folkertdev 
(We can diagnose later, but for now I just need to unblock the upgrade.)
=> Revert "glue: find platform main file"

crates/compiler/builtins/roc/Dict.roc, crates/compiler/test_mono/generated/dict.txt
This update makes wyhash bad seed resist.
In old version of wyhash certain seeds would ruin the randomness. Changes applied are based off of this diff: https://github.com/wangyi-fudan/wyhash/compare/a5995b9..77e50f2#diff-f2d41a4fb60c2bf10ac6c27f698993daf9aab9e9e2afc809d4966c6fa5d1c709
All test values were generated with the wyhash c++ library to verify the new implementation is correct. C++ Script here:
https://github.com/bhansconnect/roc-dict/blob/main/cc-hash-bench/src/wyhash-tests.cc
=> Update to wyhash final 4

crates/ast/src/constrain.rs, crates/compiler/builtins/README.md, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/mono/src/ir/literal.rs, crates/compiler/mono/src/layout/intern.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/types/src/pretty_print.rs, crates/repl_test/src/tests.rs
Now when we put in the repl `0.1 + 0.2` and the result is a `Dec` (see https://github.com/roc-lang/roc/pull/5792) it doesn't print `0.3 : Float *` - which is not the answer we would have gotten from a floating-point calculation!
=> Rename Float to Frac in more places

.github/workflows/windows_tests.yml, crates/compiler/builtins/bitcode/src/compiler_rt.zig, crates/compiler/builtins/bitcode/src/libc.zig, crates/compiler/builtins/bitcode/src/utils.zig, crates/compiler/gen_llvm/src/llvm/externs.rs
With these changes running `zig build test` on Windows in `crates/compiler/builtins/bitcode` results in all 153 tests passing. 
These currently look hacky and I'm not sure I am qualified to fix these. Request a review to understand what should be fixed so this could be merged.
=> Fixes for Windows zig builtin tests

.github/workflows/windows_tests.yml, crates/compiler/builtins/bitcode/src/libc.zig, crates/compiler/builtins/bitcode/src/libc/folly/memcpy.zig, crates/compiler/builtins/src/bitcode.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs
the wrong calling convention was used. the assembly we use assumes systemv, but on windows, .C would be the win64 calling convention. This has now been fixed
=> fix  memcpy on windows

crates/repl_wasm/README.md, www/public/repl/index.html, www/public/repl/repl.css, www/public/repl/repl.js
In #5790, I added `:help` text to the top of the history panel, as a little last-minute touch.
It worked by adding a fake input and output to the history and then removing just the input from the DOM.
It also removed the entry from the `inputHistory` array, to prevent it appearing in the panel when you hit the UP arrow enough times.
However this introduces a mismatch between the number of items in `inputHistory` array and the number of `.history-item` divs in the DOM, which caused each REPL output to appear *above* the user input that caused it! 🙃
The fix is to just make all of this separate from history!
We just make a separate call into Rust to get the initial `:help`, instead of trying to reuse code for two things that turn out not to be as similar as I thought.
If you want to test …
=> Fix Web REPL ordering bug

flake.nix
Just trying to make it clearer what needs to be done when updating llvm and zig versions in the nix flakes. Now the llvm version number only needs to change in one place. On top of that, the zig version number is specified in the same place.
=> Remove duplicate references to llvm package version number

crates/compiler/parse/src/parser.rs, crates/reporting/src/error/parse.rs, crates/reporting/src/report.rs, crates/reporting/tests/test_reporting.rs
Tries to fix #5793
I did not implement all of `BadInputError`, because I don't quite understand when `TooManyLines` and `BadUtf8` happen. They are checked at a different place.
To make the output work, I had to filter out the control characters, because the terminal will respect a misplaced CR and therefore mess up the output. So it made sense to me to filter it out, but I'm not sure if I did it correctly and if I did it in the right place.
=> Implement error messages for (parts of) BadInputError

crates/compiler/builtins/bitcode/benchmark/dec.zig
It took a really large sample size for the numbers to stabilize, but on my M1 mac:
```
Dec/F64:
addition:       0.65
subtraction:    0.78
multiplication: 4.07
division:       31.80
```
There is definitely more variance in the dec results compared to fp.
=> make dec bench functional again and much more robust

crates/compiler/gen_dev/src/generic64/aarch64.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_dev/src/object_builder.rs, crates/compiler/test_gen/src/helpers/dev.rs
aarch64 macho will need some experimentation with what relocation type to use. this makes some 50 tests in `gen_num` pass, and there are some general cleanups for the backend in here too
=> working aarch64 elf tests

crates/compiler/builtins/roc/Num.roc
I'm not sure where/how we should best display the range. Is this fine? This prints the same amount of info as the integer ranges above.
Also remove extra numbers from float result for 0.1 + 0.2. Floats only have 16 decimal places of precision and the rest generally is not printed.
=> Clarify Dec range and decimal places in docs

www/public/repl/index.html, www/public/repl/repl.js
For narrower screens, or high zoom, the text overflows in the web REPL and you need to scroll horizontally to see it.
That's not great, and doesn't match what we see in the terminal.
We were using `pre` to get a "source code" font and also make the browser respect newlines instead of ignoring them.
The problem is that `pre` makes it so we _must_ specify everywhere we want a line break! So at the edge of the panel, it overflows instead of wrapping. (`pre` has the CSS property `whitespace: no-wrap` by default.)
To fix this, I changed the `pre` to a `div`. To get the "source code" style back, I used an existing CSS class called `code`. And to make the browser respect newlines, I added some JS to replace `\n` with `<br>` in the compiler output.
So now the browser will respect newlines where …
=> Wrap text in web REPL history panel

crates/repl_test/src/state.rs, crates/repl_ui/src/repl_state.rs
Resolves [this issue](https://github.com/roc-lang/roc/issues/2666).
The change is simple! I also wrote some tests associated tests.
As a follow-up, would it be useful to auto-indent, not just for record definitions but also when statements, closures and maybe others?
I checked and we currently manage newlining with the `rustyline` library, [where](https://docs.rs/rustyline/latest/src/rustyline/lib.rs.html#526) unfortunately adding tabs after submitting incomplete input (such as with `record = {`) is not configurable. Any suggestions on how to manage that?
=> Add newline for partial record definition

crates/roc_std/src/lib.rs, crates/roc_std/tests/test_roc_std.rs
Fixes [this issue](https://github.com/roc-lang/roc/issues/5813).
In summary, negative decimal-point numbers (Fracs and Decs) are represented with an offset decimal point because the negative sign was incorrectly accounted for in the offset calculations. One test was also incorrect.
This PR does the following:
- fix the faulty offset calculations
- simplify somewhat the `RocDec::to_str_helper` method
- add a dedicated test
=> Fix decimal-point number representation

crates/repl_cli/src/lib.rs, crates/repl_test/src/cli.rs, crates/repl_test/src/state.rs, crates/repl_test/src/tests.rs, crates/repl_test/src/wasm.rs, crates/repl_ui/src/lib.rs, crates/repl_ui/src/repl_state.rs, crates/repl_wasm/src/repl.rs, examples/static-site-gen/output/style.css, www/generate_tutorial/src/input/tutorial.md, www/wip_new_website/content/tutorial.md
Whenever I see it in the repl it bothers me, and I've never actually wanted to use it. I think it was a reasonable experiment to try, but ultimately it didn't work out.
I think if we want to try something like this again, maybe another thing to try would be to have a special variable like `prev` or something which gives you access to the previous answer you got, and then maybe `prev2` for the answer before that (etc), so you wouldn't have to see the name of the variable cluttering the output...but for now I just want to go back to the simpler, cleaner repl we had before this.
=> Remove the whole #val1 thing from repl

crates/docs/src/lib.rs, crates/docs/src/static/favicon.svg, crates/docs/src/static/index.html, crates/repl_cli/src/lib.rs, crates/repl_test/src/cli.rs, crates/repl_test/src/state.rs, crates/repl_test/src/tests.rs, crates/repl_ui/src/lib.rs, www/public/different-names/index.html, www/public/index.html, www/public/repl/index.html, www/public/repl/repl.css, www/public/repl/repl.js, www/public/site.css, www/public/styles.css, www/wip_new_website/main.roc
This styles `/repl` to look more like other parts of the site.
Also it makes some tweaks to the scrolling and resizing behavior:
* The textarea gets focus as soon as the web repl finishes loading
* If you add multiple lines, the textarea grows automatically
* Nothing has a vertical scroll bar except the page, and whenever you enter something, the page scrolls to the end. This way, you can always scroll without needing your cursor to be anywhere in particular.
=> Style Web REPL

crates/compiler/builtins/bitcode/benchmark/dec.zig, crates/compiler/builtins/roc/Num.roc
Repeating what I commented on zulip:
Ok. So these are benchmark numbers that I am confident in and have double checked the assembly of (on m1):
```
Dec/F64:
addition:       0.55
subtraction:    0.53
multiplication: 15.09
division:       53.74
sin:            3.90
cos:            3.62
tan:            2.34
asin:           1.83
acos:           1.72
atan:           1.73
```
The caveats are:
1. When looking at smaller benchmarks addition/subtraction perf can greatly be hurt. I think the issue is that addition and subtraction require a potential jump to `roc_panic` (could have a branch misprediction). It also is simply more instructions overall. Floats are consistent. Dec is not. So with smaller benchmarks, Dec's have a lot of variance here and can be like 2x slower than floats. But in a hot …
=> Try to get consistent and accurate dec benchmarks

crates/compiler/build/src/link.rs
This simple solution seems to just work, I am a bit surprised, I swear that I tried it before and hit linker issues. Anyway, if we update the basic-cli platform it drops from about 100MB to about 15MB.
Note: we may need to add a special init function to stop linker based dead code elimination. That or special linker commands to keep `roc_*` functions. Currently this is working on my x86 machine without it though.
Guide here if needed on the init function:
https://stackoverflow.com/questions/43712979/how-to-export-a-symbol-from-a-rust-executable
=> Allow rust binaries to remove dead code

www/public/repl/index.html, www/public/repl/repl.css, www/public/repl/repl.js, www/public/site.css
Now it looks like this: (my fonts aren't loading right locally, but they should look the same as they currently do once deployed)
As the middle part grows, it expands to have the usual full-page scrollbar; it just expands to fill any remaining space so the textarea starts out on the bottom of the page.
=> Give web repl some mobile-friendly styling

crates/compiler/parse/src/keyword.rs, crates/compiler/parse/src/type_annotation.rs, crates/compiler/test_syntax/tests/snapshots/fail/where_type_variable.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/fail/where_type_variable.expr.roc, crates/compiler/test_syntax/tests/snapshots/pass/where_ident.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/where_ident.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/where_ident.expr.roc, crates/compiler/test_syntax/tests/test_snapshots.rs
Allows `where` to be used as an identifier in defs and record fields:
```elm
where : Str
where = "Home"
meeting : { where: Str }
meeting = { where: "Home" }
```
It's still not a valid type variable because that'd conflict with `where ... implements ...`.
Closes #5823
=> Allow `where` to be used as an identifier (except in type vars)

www/public/repl/repl.js
In #5863 I make `result_addr` a number, whereas it used to be an object.
I forgot to change the initial value though! It's still an object!
The initial value is always overwritten, so it has no effect on functionality. But the whole point of that PR was code clarity, so let's fix it!
The default git diff isn't really enough to see that this is correct. You might want to "view file" and see the other 2 usages of the field, which treat it as a number.
This fix is not urgent because everything works. But people might look at the source code after I do a talk on it tomorrow and get confused.
=> Fix a confusing initial value in the web REPL JS

Cargo.lock, Cargo.toml, examples/cli/cli-platform/Cargo.toml
This fixes the the breaking tests before building nightlies on macos, due to a bug in the latest releases of reqwest.
```
The roc command:
"/Users/m1ci/actions-runner2/_work/roc/roc/target/release/roc --max-threads=1 /Users/m1ci/actions-runner2/_work/roc/roc/examples/cli/ingested-file.roc --"
had unexpected stderr:
🔨 Rebuilding platform...
Undefined symbols for architecture arm64:
"_SCDynamicStoreCopyProxies", referenced from:
__ZN20system_configuration13dynamic_store14SCDynamicStore11get_proxies17h9364091d51e512b0E in macos-arm64.o
"_SCDynamicStoreCreateWithOptions", referenced from:
__ZN20system_configuration13dynamic_store14SCDynamicStore6create17ha461b4b2450916f0E in macos-arm64.o
"_kSCDynamicStoreUseSessionKeys", referenced from: …
```
=> force reqwest version

crates/compiler/gen_dev/src/generic64/aarch64.rs
When a function returns via arg pointer, the caller sets XR (x8) to the address where the return value goes. We were sometimes using XR as a temporary register while loading args, which lead to a segfault when returning.
It will now use `X15` instead which is reserved for scratch in our assembly.
=> AArch64: Use scratch register instead of XR while loading args

crates/compiler/build/src/program.rs, crates/compiler/load/build.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/src/module.rs, crates/reporting/src/cli.rs
Now instead of hanging the compiler, it exits with an error and prints a suggestion to try `roc check`.
I tried to get it to print the errors that had accumulated so far, but it consistently reported that there were 0 errors to report. There might be some way to get it to do that, so I didn't delete the (nontrivial, but zero runtime cost if there's no error) infrastructure work that it took to set that up, but I'm gonna check this in as-is because it already improves things.
=> Improve what happens when mono panics

crates/compiler/gen_llvm/src/llvm/build.rs
This should help basic-webserver work!
=> Quick C ABI fix

Cargo.toml, crates/compiler/test_gen/src/helpers/dev.rs
this significantly reduces the amount of debug info (like, 400MB for test-gen-dev) in development builds, but still gives good backtraces on panics.
the only thing I think we lose is that if you load a test binary into a debugger (gdb, lldb), you get less info. But that is very rare, so I think this is just a pure win effectively.
=> default to `line-tables-only`

www/wip_new_website/optimize.sh, www/wip_new_website/static/site.css
As discussed in the Zulip chat, here's a script (or beginnings of a script) for minimizing the static assets used in the website.
This script requires 2 things:
- `hb-subset`, which is a binary in some harfbuzz package or another (@Anton-4 said they would help would this, hopefully that's the right @).
- The full `.ttf` files of the fonts, instead of `.woff`/`.woff2` files. 
On my machine, I just downloaded the `.ttf` files directly and placed them at the root of the `fonts` folder (removing the `-Regular` from the names). I _guess_ the only downside of this is that when developing (not using the script) you'll get 404s for the `.woff2` files, but it'll still load the `.ttf`s. I'm not sure the best way to proceed with this part, since the static files are in a completely different repo. …
=> Add optimize.sh script for website

crates/cli/src/format.rs, crates/cli/src/lib.rs, crates/cli/src/main.rs
New `roc format` flags: `--stdin` and `--stdout` (they can be used separately or together):
Editor plugins for code formatting apparently like to use stdio for this!
=> Support `roc format` to stdout/from stdin

crates/compiler/test_gen/src/helpers/wasm.rs, crates/compiler/test_gen/src/helpers/wasm_test_platform.c, crates/repl_wasm/src/repl_platform.c, www/public/repl/repl.js
I don't know JS very well so this works but might be unidiomatic? 
it now looks lilke this
=> report roc_panic to the user in the web repl

crates/compiler/build/src/link.rs
Depending on the linux distro, lib will contain 32bit libraries. We want the 64bit version of libraries if they exist, so check lib64 first.
=> Check lib64 before lib when linking

crates/glue/src/RustGlue.roc, crates/glue/tests/fixtures/closures/app.roc, crates/glue/tests/fixtures/closures/platform.roc, crates/glue/tests/fixtures/closures/src/lib.rs, crates/glue/tests/test_glue_cli.rs
Closure captures should just be a list of bytes. They also need to call the size function to figure out how many bytes to load. Roc does not return a RocFunction type directly otherwise.
=> Fix glue for closures

crates/reporting/src/error/parse.rs
fix #5683
When the file doesn't contain the expected header, I first check if the file content is UTF-8 encoded. Depending on the result, I show a different message. For example, running roc on a binary file leads to this error:
```
── MISSING HEADER ───────────────────────────────────────────────── ./test.bin ─
I am expecting a header, but the file is not UTF-8 encoded.
I am expecting a module keyword next, one of interface, app, package
or platform.
```
=> Set a better error msg for non uft8 encoded files

crates/roc_std/src/lib.rs
These traits all are supported on rust result and for simplicity, I just directly depend on the rust result version to implement all of these.
=> add missing traits to RocResult

www/wip_new_website/static/site.css
Changed the lightness of the color (V in HSV) from 6% to 9%, to prevent eye-strain for myself (and maybe others!).
The contrast between text/bg slightly reduces (although still passes WCAG), but we can change text color to be slightly brighter versions of what they are now if someone mentions the text being too dark (although even comparing side by side it's barely noticeable).
=> lighten bg color for site

crates/compiler/mono/src/ir.rs
This fixes an issue where number related type errors cause a crash in repl. For example, using a negative number for `Nat` like `List.dropAt [1, 2, 3] -1` as in #5916. so as f64 number.
I think this PR fixes some of #5916.
=> Fix crash caused by number related type error in repl

crates/compiler/constrain/src/expr.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/module/src/called_via.rs, crates/compiler/types/src/types.rs, crates/repl_test/src/tests.rs, crates/reporting/src/error/type.rs, crates/reporting/src/report.rs
fix #1668
I went a bit further than the ticket description and, along with binary operators, I also handled unary operators and string interpolation.
See the [tests](https://github.com/roc-lang/roc/blob/c858031f744371396b198002a2f09ad516db0e43/crates/repl_test/src/tests.rs#L659-L761) for examples of error messages.
I suspect we might run into the same kind of issue when desugaring fields access functions for records. However, I don't know Roc well enough yet to be able to see what could be wrong. If someone can think of a case that would raise the same issue with record desugaring, please provide a short example. And I'll fix it as well.
=> Show the right fct name in type error messages

examples/helloWorld.roc, examples/inspect-logging.roc, examples/parser/examples/letter-counts.roc
There are more uses of basic-cli 0.5.0 left but I mainly want to check 0.6 with all CI workflows.
=> upgrade some examples to basic-cli 0.6

www/content/community.md, www/content/docs.md, www/content/fast.md, www/content/friendly.md, www/content/tutorial.md, www/public/site.css
This PR
- Updates the first part of the Tutorial to reflect latest changes to REPL
- Includes a link for users to use [roc-lang.org/repl](https://www.roc-lang.org/repl) as an alternative to using roc cli
- Fixes css for colon's in tutorial
- Adds documentation link to `roc-lang/basic-webserver` in website
- Fixes a number of broken links that pointed to `/wip`
=> Update Tutorial & Website

www/content/fast.md, www/content/functional.md
I was reading through these pages again and just noticed a couple of spelling errors.
=> Website typo fixes

crates/linker/src/elf.rs
That's a problem with the dynamic loader:
https://discourse.nixos.org/t/no-such-file-of-directory-when-trying-to-execute-binary-file/6150
When linking `libapp.so` with `host.zig`, zig puts in the binary the standard path for the dynamic loader on linux:
`/lib64/ld-linux-x86-64.so.2`
However in NixOS, that file is somewhere else in the nix store (see: https://nixos.wiki/wiki/Packaging/Binaries#The_Dynamic_Loader). Removing the `-target` switch makes zig uses the host target for linking and puts the right path to the dynamic loader in the resulting binary. As we want to execute that binary file in this test, it makes sense to use the default target anyway.
Note that this is relevant for the creation of the binary only. For the creation of the object file, it doesn't really matter. But I …
=> Fix zig_host_app on NixOS

crates/compiler/builtins/roc/List.roc, crates/compiler/exhaustive/src/lib.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/mono/src/ir/decision_tree.rs, crates/compiler/mono/src/ir/pattern.rs, crates/compiler/mono/src/layout/semantic.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_mono/generated/anonymous_closure_in_polymorphic_expression_issue_4717.txt, crates/compiler/test_mono/generated/encode_derived_nested_record_string.txt, crates/compiler/test_mono/generated/encode_derived_record_one_field_string.txt, crates/compiler/test_mono/generated/encode_derived_record_two_field_strings.txt, crates/compiler/test_mono/generated/encode_derived_string.txt, crates/compiler/test_mono/generated/encode_derived_tag_one_field_string.txt, crates/compiler/test_mono/generated/encode_derived_tag_two_payloads_string.txt, crates/compiler/test_mono/generated/issue_4749.txt, crates/compiler/test_mono/generated/issue_4772_weakened_monomorphic_destructure.txt, crates/compiler/test_mono/generated/unspecialized_lambda_set_unification_does_not_duplicate_identical_concrete_types.txt, crates/compiler/test_mono/generated/weakening_avoids_overspecialization.txt
Still need to add some tests, but seems to be working!
Fixes #5187
=> Pattern match rest as

.github/workflows/nix_macos_apple_silicon.yml
The CI server fills up quickly with these shells, leading to `out of space` errors.
=> auto delete old nix shells

BUILDING_FROM_SOURCE.md
This is only necessary for running GUI examples.
=> remove libxkb-common requirement

www/content/tutorial.md
In the code examples of tutorial Tasks part, there were 2 places where the `main` function was mistakenly named `task`.
=> fix naming error in tutorial

www/content/tutorial.md
This line is confusing because the string interpolation appears later in the tutorial now. 
I tried to replace it with something in that fits the style of the rest of the tutorial :)
=> remove ref to string interpolation in start of tutorial

crates/compiler/load/tests/test_reporting.rs, crates/compiler/parse/src/expr.rs, crates/reporting/src/error/parse.rs
Fix #5939
The problem in this input is not the presence of Unicode characters. It is the presence of a tab character (the larger space in the comment). Remove only that character and roc is happy to run the test without any trouble.
Anyway, the tab error is rightly identified by the parser but was swallowed and converted to `EExpr::DefMissingFinalExpr`, leading to that confusing error. Keeping it makes roc print the right error.
=> Dont swallow bad input while parsing spaces

crates/compiler/load/tests/test_reporting.rs, crates/reporting/src/error/canonicalize.rs
=> Fix typo 'I trying' -> 'I am trying'

BUILDING_FROM_SOURCE.md
- `zig` needs `lib` directory
- `llvm` needs development headers
- Keep installation instructions together
- Group by platform
- No longer split installation and debugging instructions
=> Re-organize the LLVM build instructions

crates/highlight/src/lib.rs
This PR 
- Updates the `@` token from a Keyword/Punctuation to an UpperIdent token for correct styling syntax highlighting.
=> Change `@` token an UpperIdent

getting_started/macos_x86_64.md
llvm16 requires z3
I believe zstd is also required by llvm
Related to #6053
I think these deps should not be necessary once we setup llvm with musl.
=> add macos x64 required dependencies

crates/docs/src/static/styles.css
Make side nav in docs more readable
=> Add CSS border to module functions in docs nav

Earthfile
https://github.com/mozilla/sccache/issues/1988
This change fixes the nightly Old Linux x86_64 build
=> fix sccache install

crates/compiler/mono/src/code_gen_help/mod.rs
=> fix dropping the wrong argument for List.map when it captures

crates/compiler/gen_dev/src/generic64/aarch64.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/storage.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs
=> Switch callee register

www/content/tutorial.md
This PR
- Corrects the name of Tags heading to match Table of Contents
- Adds a link to the Task and Error Handling example
- Adds a section to link to the Examples once reader has finished tutorial (before the Advanced section)
- Adds a section on Importing Files at build time
- Adds a section on Record Builder syntax sugar
- Removes the section on Phantom Types
=> Tutorial Updates

www/content/index.md, www/content/repl/index.md
Fix #6013 
Add the `spellcheck="false"` attribute for REPL text area elements.
=> Add spellcheck attribute for REPL

crates/compiler/builtins/roc/Str.roc
The docs for `Str.walkUtf8` were not valid Roc code. Now they are!
=> Fix Str.walkUtf8 docs

www/content/tutorial.md
This fixes the issue raised [here](https://github.com/roc-lang/roc/issues/5501#issuecomment-1837186378). I also simplified the language a bit for non-native English speakers.
=> Update tutorial executable naming section

.github/workflows/ci_manager.yml
This will prevent accidental merging with errors, like we had in #6113
=> create single final job for required checks

crates/compiler/can/src/operator.rs, crates/compiler/test_mono/generated/dbg_in_expect.txt, crates/compiler/test_mono/generated/dbg_str_followed_by_number.txt, crates/compiler/uitest/tests/ability/specialize/inspect/opaque_automatic.txt, crates/compiler/uitest/tests/ability/specialize/inspect/opaque_automatic_late.txt
This is to workaround #6167 and can be reverted once it is fixed
=> change debug to call `Inspect.inspect` instead of inlining it

BUILDING_FROM_SOURCE.md, crates/cli/src/lib.rs, crates/compiler/build/src/program.rs, crates/compiler/builtins/bitcode/build.zig, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/externs.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/test_gen/benches/list_map.rs, crates/compiler/test_gen/benches/quicksort.rs, crates/compiler/test_gen/src/helpers/llvm.rs, crates/glue/src/load.rs, crates/repl_cli/src/cli_gen.rs, crates/repl_expect/src/run.rs, flake.nix
This gets function debug info working. Was just a minor bug.
After that, it changes the `roc` api to enable debug info generation. Firstly, we no longer just strip all debug info. We leave it in for both Development and Normal builds. It is still strip by default in optimized builds unless `--profiling` is passed.
The old `--debug` flag was renamed to `--emit-llvm-ir`. ~~It still does the same thing though of emitting llvm ir and then trying to run it through debugir.~~ It just emits the `.ll` file and doesn't use `debugir` anymore.
~~I am not sure it is worth keeping around `debugir`, but I left it for now. `debugir` is still not updated to the latest version of llvm. So I think it is simply not function rn. On top of that, if we generate our own debug info and that works, I think there …
=> Fix debug info

crates/packaging/src/https.rs, crates/reporting/src/report.rs
This PR is to fix the improve the error message when the URL provided to download a platform is incorrect and the server returns a 404.
=> Improving error messages when encountering a 404 while fetching a platform

crates/repl_ui/src/repl_state.rs
Inspired by watching @kristoff-it's experience using Roc for the first time.
Theoretically there's a downside to special-casing `exit` here, but I predict in practice approximately zero people ever run into it. 😄
=> Make it easier to exit `roc repl`

crates/glue/src/ZigGlue.roc
This PR adds the initial template for a Zig glue implementation. Its purpose is to show put the basic parts together as a base to add additional functionality. 
Tested using `roc glue ../roc/crates/glue/src/ZigGlue.roc src/glue/ src/main.roc` with [ostcar/roc-wasi-platform](https://github.com/ostcar/roc-wasi-platform)
=> Initial template for Zig glue 

README.md
The logo was there, but it was not mentioned in the text.
=> Add Decem to the list of companies

crates/compiler/fmt/src/spaces.rs, crates/compiler/test_syntax/tests/test_fmt.rs
The `format` command was not handling `PatternAs`, so formatting was failing like in the issue below.
Closes https://github.com/roc-lang/roc/issues/6197
=> Fix format for the 'as' keyword

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/bitcode/src/str.zig, crates/compiler/builtins/src/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/build_str.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs
Trying to make naming more consistent and clearer here. Especially with some future planned changes, I think calling it the allocation pointer instead of the refcount pointer will help with some clarity. Also, remove all of the redundant `str_` prefixes.
=> Cleanup list and str builtin naming from refcount to allocation

crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/intrinsics.rs
Early DCE was sometimes cleaning up functions that we actaully still needed. At some point we can come back to it and try to properly protect all special functions. Until then, this still enables DCE, but it runs later with the full generated Roc module.
=> Remove early DCE of bitcode

www/content/tutorial.md
The change renames some variables in the pipeline operator examples to `f` to imply a function. This should make it easier for beginners to understand the operator.
Closes #5914
=> docs: update operator desugering table

crates/compiler/gen_llvm/src/llvm/build.rs
Fixes:
```
thread 'main' panicked at 'Undefined Symbol in relocation, (+925, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+5e)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "__udivti3", address: +0, size: +0, kind: Label, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/elf.rs:1486:25
```
=> add __udivti3 to must_keep

crates/compiler/builtins/roc/Num.roc
Fix: [#6261](https://github.com/roc-lang/roc/issues/6261) Removed all the mentions of Num.format
=> Fix: #6261 Removed all the mentions of Num.format

.github/workflows/nix_macos_apple_silicon.yml, crates/compiler/test_mono/src/tests.rs
=> more visible+better mono error

default.nix, flake.nix, getting_started/README.md, getting_started/nix.md, nix/builder.nix, nix/templates/default.nix, nix/templates/simple/flake.nix, www/content/install.md
I updated the install docs to call out nix specially. To make onboarding easier I added a flake template which people can use to boilerplate out a new roc project with nix.
I also fixed https://github.com/roc-lang/roc/issues/6148 so people can do `nix run github:roc-lang/roc -- <roc_cli_args>` to play with roc easily.
There is still the issue of the nightly binary not working on nixos but using `steam-run` works for some people. I had mixed results, on my laptop it worked but on my desktop it did not. 
I think if we add a ci job to push the cli build to a public cachix and then have users run `cachix use <roc-cache>` they won't need to build from source as often
=> Add install docs for nix + fix `nix run` for using the roc cli 

www/build.sh
This was caused by https://github.com/roc-lang/basic-cli/pull/144
Old error:
```
+ cargo run --bin roc-docs downloaded-basic-cli/src/main.roc
Compiling roc_docs_cli v0.0.1 (/Users/m1ci/actions-runner2/_work/roc/roc/crates/docs_cli)
Finished dev [unoptimized + debuginfo] target(s) in 2.67s
Running `target/debug/roc-docs downloaded-basic-cli/src/main.roc`
── FILE NOT FOUND ──────────────────────────────────────────────── UNKNOWN.roc ─
I am looking for this file, but it's not there:
downloaded-basic-cli/src/main.roc
Is the file supposed to be there? Maybe there is a typo in the file
name?
```
=> fix file not found in website build script

crates/compiler/can/tests/test_can.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/parse/tests/test_parse.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/test_gen/src/gen_definitions.rs, crates/compiler/test_gen/src/gen_dict.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_gen/src/gen_num.rs, crates/compiler/test_gen/src/gen_primitives.rs, crates/compiler/test_gen/src/gen_records.rs, crates/compiler/test_gen/src/gen_result.rs, crates/compiler/test_gen/src/gen_set.rs, crates/compiler/test_gen/src/gen_tags.rs, crates/compiler/test_gen/src/gen_tuples.rs, crates/compiler/test_mono/src/tests.rs, crates/compiler/test_syntax/tests/test_fmt.rs, crates/repl_expect/src/lib.rs, crates/repl_test/src/tests.rs, crates/valgrind/src/lib.rs
I put the fix to this new clippy rule in a separate PR because it's massive and now the reviewer does not need to look for the other clippy changes between these ones.
All changes are one of the following:
- r#"..."# to r"..."
- r###"..."### to r#"..."#
- r###"..."### to r"..."
=> fix clippy (1.72.1) unnecessary hashes

crates/packaging/src/https.rs
Closes #6302 
Updates the `Read` implementation of `ProgressReporter` to support printing progress in KB's for packages of size < 1 MB.
=> Update ProgressReporter to display download progress in KB

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_dev/src/object_builder.rs, crates/compiler/test_gen/src/gen_num.rs
fix #6334 
this is the proper fix. it makes decimals use `mulWithOverflow` and panics on overflow. This surfaced a bug in the dev backend where it used a by-value rocstr instead of a by-pointer one. This is now fixed. That should mean many more tests work for gen_num, if the dev backend uses the panicking variant of the operation (it often does not though, but we can change that now).
=> implement panic on overflow for mul in the dev backend

crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/valgrind/src/lib.rs
ensure unions get freed even if they have no RC fields (hit when using box)
=> Fix RC for unions with non-refcounted fields

crates/compiler/can/tests/test_can.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/string_literal.rs, crates/compiler/parse/tests/test_parse.rs, crates/compiler/test_syntax/tests/test_snapshots.rs
This adds support for string interpolation using `$(...)` syntax. It keeps the existing `\(...)` for now, to ease the transition. The plan is:
1. Land this PR
2. In separate PRs, update `basic-cli` and examples to use the new syntax
3. In another PR, update `roc format`, tutorial, documentation, etc. to use the new syntax
4. In a separate PR after that, introduce a deprecation warning for using `\(...)` so we can find the remaining instances easily.
5. Eventually, remove the old syntax. (There's no rush on this; maybe we end up accomplishing this by not including `\(` in the upcoming parser rewrite.)
=> Add support for $(...) string interpolation syntax

crates/compiler/can/src/expr.rs, crates/compiler/can/src/operator.rs, crates/compiler/can/src/pattern.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/string_literal.rs, crates/compiler/test_syntax/tests/test_snapshots.rs
In a future change we can have it rewrite either to `$(...)` to make upgrading easier.
=> Preserve `\(...)` and `$(...)` in `roc format` for now

.github/workflows/basic_cli_test_arm64.yml
This script tests the latest release of basic-cli but one example used `$(which cat)` in a string, which is causing issues with the new interpolation syntax. I now just delete the `$` for that specific file before testing.
=> interpolation version mismatch patch

crates/compiler/gen_llvm/src/llvm/build.rs
We just missed setting it. Set it as specified in the docs: https://thedan64.github.io/inkwell/inkwell/debug_info/index.html#setting-up-the-module-for-holding-debug-info
Not sure why it is 3, but that is the value in the llvm tutorial as well: https://llvm.org/docs/SourceLevelDebugging.html
Fixes #6367
=> Set debug info version

crates/compiler/parse/src/string_literal.rs
Previously you had to escape it, e.g. `'\$'` instead of `'$'` - this was an unintentional regression.
=> Fix single-quote `'$'` parsing

crates/glue/tests/fixture-templates/rust/Cargo.toml, examples/cli/false-interpreter/platform/Cargo.toml, examples/glue/rust-platform/Cargo.toml, examples/gui/breakout/platform/Cargo.toml, examples/gui/platform/Cargo.toml, examples/platform-switching/rust-platform/Cargo.toml, examples/static-site-gen/platform/Cargo.toml
I don't know if this matters at all, but I don't think we should use "rlib". The [rust docs](https://doc.rust-lang.org/reference/linkage.html) suggest using "lib" by default. "lib" probably just aliases to "rlib", but it lets the compiler pick what it wants. I don't think this will fix anything, but I am half hopeful it will somehow fix #6121.
Other thing to test that probably won't fix #6121, but is worth just double checking is changing the library name such that the binary and library don't have the same name.
=> Stop using "rlib"

crates/cli/tests/cli_run.rs, crates/cli/tests/known_bad/UnusedImportButWithALongFileNameForTesting.roc, crates/compiler/load/tests/test_reporting.rs, crates/compiler/load_internal/tests/test_load.rs, crates/reporting/src/report.rs
Closes #6378
- Changes the header formatting to comply with what's described in the issue.
- Makes all broken tests conform.
- Adds an additional test for the case where the file path gets truncated.
=> Improve filename visibility in error messages

crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/src/file/reporting.rs, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/parse/src/header.rs
We have a few issues with the language server hanging 
#6336 
#6269 
#6185 
#6200
I believe these are all caused by the same problem.
When an interface header has a qualified import which is invalid syntax or a app header tries to import from a package shorthand that doesn't exist. eg:`interface A import [pf.Task]` The messages
between the state_thread and the worker_task thread die out and they are then both left sitting waiting for messages that never come.
I have fixed this by just checking if there are any package imports that are invalid and failing to load if so
I know the implementation is a little rough but given the module-params syntax changes will render package shorthands obsolete this seemed like a reasonable short term fix.
=> Fix hang from bad imports

crates/highlight/src/lib.rs
This should fix repl snippets in docs (code snippets beginning with `»`) rendering empty after the `»` prompt.
=> Highlight after special-casing repl snippets

crates/cli/src/lib.rs, crates/cli/src/main.rs
Closes #6419
If the file or directory to be formatted is not given on the `roc format` command line, the formatter assumes that the current working directory should be formatted. 
This pull request prevents this behavior if the ` --stdin` or `--stdout` options of the ` roc format`  command are present, 
This pull request also explains that `DIRECTORY_OR_FILES` defaults to the current working directory if missing on the command line.
=> Prevent roc format from reading $PWD when --stdin or --stdout options given

crates/cli/src/lib.rs, crates/compiler/build/src/program.rs, crates/glue/src/load.rs
@rtfeldman totally understand if this is consider too immature of a use case to be worth adding, but I am trying to enable a nice fuzz testing experience in Roc. I totally restarted by `roc-fuzz` platform and I think it can become a really nice experience for package authors, but it requires some sort of `--fuzz` flag to instrument the roc code.
I have a prototype that now works on mac as a prebuilt-platform. So I am pretty sure I will be able to bundle of this and distribute as a standard platform. The end user would just write a fuzz target and run: `ROC_LINK_FLAGS="-lc++" roc run fuzz-target.roc --fuzz -- fuzz`
Targets are a work in progress, but currently they look like this:
```elm
target : Target (List U8, U8)
target = {
name: "my target",
generator,
test,
}
generator : Generator …
```
=> add `--fuzz` option to roc

www/content/tutorial.md
The tutorial was still using the deprecated string interpolation syntax.
=> tutorial update str interpolation syntax

crates/packaging/src/tarball.rs
They are also a supported format for the legacy linker.
=> support .a archives in bundling

crates/compiler/build/src/link.rs
Needed for fuzzing and for platforms that aren't ready to use the surgical linker
=> add ROC_LINK_FLAGS support to linux

crates/compiler/gen_llvm/src/llvm/build.rs
The current version will fail if run through the `opt` tool. nonnull should have no data attached.
=> Fix the nonnull attribute

.github/workflows/basic_cli_build_release.yml, .github/workflows/basic_cli_test_arm64.yml, .github/workflows/basic_webserver_build_release.yml, .github/workflows/benchmarks.yml, .github/workflows/ci_manager.yml, .github/workflows/devtools_test_linux_x86_64.yml, .github/workflows/devtools_test_macos_apple_silicon.yml, .github/workflows/docker.yml, .github/workflows/macos_x86_64.yml, .github/workflows/markdown_link_check.yml, .github/workflows/nightly_linux_arm64.yml, .github/workflows/nightly_linux_x86_64.yml, .github/workflows/nightly_macos_apple_silicon.yml, .github/workflows/nightly_macos_x86_64.yml, .github/workflows/nightly_old_linux_arm64.yml, .github/workflows/nightly_old_linux_x86_64.yml, .github/workflows/nix_linux_arm64_cargo.yml, .github/workflows/nix_linux_arm64_default.yml, .github/workflows/nix_linux_x86_64.yml, .github/workflows/nix_macos_apple_silicon.yml, .github/workflows/nix_macos_x86_64.yml, .github/workflows/spellcheck.yml, .github/workflows/test_nightly_macos_apple_silicon.yml, .github/workflows/test_nightly_many_os.yml, .github/workflows/ubuntu_x86_64.yml, .github/workflows/windows_release_build.yml, .github/workflows/windows_tests.yml
This PR updates the GitHub Action steps to get rid of the warnings displayed in CI, see https://github.com/roc-lang/roc/issues/6428.
There are also a few whitespace cleanup changes my editor made automatically :-)
=> Update GitHub Action step versions (#6428)

crates/compiler/fmt/src/spaces.rs, crates/compiler/test_syntax/tests/snapshots/pass/mixed_docs.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/not_docs.expr.formatted.roc
The formatter used to replace `###` with `# ##` but this can be not what you want in some cases, like [here](https://github.com/roc-lang/roc/issues/6328#issuecomment-1902691185).
This change does prevent the autofixing of scenarios like this:
```
x = \y ->
``` 
to:
```
x = \y ->
```
Warning for this scenario seems to be best suited for a future Roc linter.
=> Format allow more hashtags

crates/glue/src/RustGlue.roc
```rs
/// A tag named ``DirReadErr``, with the given payload.
pub fn DirReadErr(f0: UnwrappedPath, f1: roc_std::RocStr) -> Self {
Self {
f0
f1
}
}
```
becomes
```rs
/// A tag named ``DirReadErr``, with the given payload.
pub fn DirReadErr(f0: UnwrappedPath, f1: roc_std::RocStr) -> Self {
Self {
f0,
f1
}
}
```
=> Fix syntax errors from RustGlue's tag generated code

crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/bitcode/src/num.zig, crates/compiler/builtins/src/bitcode.rs, crates/compiler/gen_dev/src/generic64/aarch64.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/storage.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/mono/src/layout/intern.rs, crates/compiler/test_gen/src/gen_num.rs
fixes #6348
some implementations needed to run glue with the `--dev` flag. That still does not work, so some glue-specific stuff will follow in a later PR.
=> Dev backend glue primitives

crates/docs/src/lib.rs
set `ENABLE_HEADING_ATTRIBUTES` in `pulldown_cmark`
resolves roc-lang/roc#6420
=> allow attributes in doc headers

crates/compiler/can/src/expr.rs, crates/compiler/test_mono/generated/lambda_capture_niches_with_other_lambda_capture.txt, crates/repl_test/src/tests.rs
fixes https://github.com/roc-lang/roc/issues/6312
@rtfeldman the new `can` design can probably have a better solution here, but this is the simplest way to force it to be a string and get a good error message.
=> force interpolated variables to be of type string

Earthfile
`cargo install` builds from source, this is much faster and more reliable.
=> Don't build wasm-pack from source

crates/compiler/gen_llvm/src/llvm/build.rs
I always thought this was wrong. Saw it again today and decided to look it up. Windows will return by pointer for anything over 64bits on an x86_64 machine.
Note: this is wrong for windows aarch64, but I will correct that in a PR where I clean up targets.
https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#return-values
https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170#return-values
@lukewilliamboswell I'm not sure the state of windows tests, but do you have anything you can do to double check this/test locally on windows?
=> Correct windows return by pointer calculation

crates/cli/tests/cli_run.rs, crates/cli_testing_examples/expects/expects.roc, crates/compiler/build/src/link.rs, crates/repl_expect/src/lib.rs, crates/repl_expect/src/run.rs
fixes https://github.com/roc-lang/roc/issues/6350
this only works though if the inline expect is in some other binding. if it is within a top-level expect it hits a mono todo. That should be straightforward to fix, but will happen later/separately
=> make an inline expect triggered by a top-level expect work

crates/reporting/src/error/parse.rs
I hit one these errors when first trying out roc, and the error message was not helpful. I don't know roc well at all, so suggestions for improving the error message would be appreciated.
When a packages section in the header has a missing or misplaced comma, roc just spits out the string. After this commit, we get a nicer error message.
Examples of wrong syntax and the error messages:
```shell
$ RUST_BACKTRACE=full roc dev ./hello.roc
── WEIRD PACKAGES LIST in ./hello.roc ──────────────────────────────────────────────
I am partway through parsing a header packages list, but I got stuck
here:
1│  app "hello"
2│      packages {
3│          ,
^
I am expecting a comma or end of list, like
packages { package_name: "url-or-path", }
```
```shell
$ RUST_BACKTRACE=full roc dev ./hello.roc
── …
```
=> Better error message for bad packages list

www/public/different-names/index.html
List.first on https://www.roc-lang.org/different-names is linking to https://www.roc-lang.org/builtins/List#join instead of https://www.roc-lang.org/builtins/List#first so this PR corrects that. 
Discussion: https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/2023.20website.20update/near/419937244
=> Fix List.first anchor link on the different-names webpage

www/content/tutorial.md
We can make the "confusions" section collapsible with #6510 in the future.
=> clarification inline expect

crates/repl_eval/src/gen.rs, crates/reporting/src/report.rs
Previously this was using an empty filename but that seems potentially confusing during debugging.
The empty filename also created issues with logical filename restrictions added in https://github.com/roc-lang/roc/pull/6506.
=> repl now uses replfile.roc behind the scenes.

www/public/site.js
In the `Try Roc` tutorial, the explanation for string interpolation was referencing `\` instead of `$`.
=> Fix explanation in Try Roc

www/public/different-names/index.html
The /site.css has a new outline
Added the `<main>` tag to the document.
This gives room on the left to the page
https://github.com/roc-lang/roc/issues/6470
Tested in desktop emulating 
desktop 1440x900
=> fix: different-names style upgrade

crates/compiler/can/src/expr.rs, crates/compiler/load/tests/test_reporting.rs
Without this change, errors are only being caught when a variable is bound in exactly one of the patterns.
Closes https://github.com/roc-lang/roc/issues/6279
=> Improve handling of multi pattern unbound variables

crates/compiler/build/src/link.rs
This exports all symbols on wasm builds. This is necessary since zig 0.11. When there are individual build scripts for platforms, then it will be possible only to export the necessary symbols. For now, this is the only way to export functions to the wasm host.
=> Export all symbols on wasm builds

www/content/tutorial.md
https://github.com/roc-lang/roc/blob/main/examples/parser/README.md says this is its new destination.
=> Fix link to parser in tutorial

.github/workflows/ci_manager.yml
Closes https://github.com/roc-lang/roc/issues/6276.
The same rationale from https://github.com/roc-lang/roc/pull/6539 applies here analogously for `.roc` files.
The `check-changes` job still outputs only one result, namely `run_tests: ${{ steps.filecheck.outputs.run_tests }}`, but the `steps` are refactored in to work together in a map-reduce kind of a manner. There are individual steps for:
- checking whether there are any files we'd like to ignore or not (which is the already existing logic);
- checking whether there are any `.rs` file changes and whether those contain only comments or not;
- checking whether there are any `.roc` file changes and whether those contain only comments or not (this is a new step added in this PR);
- a "reduce" step which determines what subset of tests …
=> Update CI workflow to not run tests when only roc comments changed

crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/compiler/build/src/program.rs, crates/compiler/load_internal/src/file.rs, crates/glue/src/load.rs, crates/reporting/src/cli.rs
When running `roc test`, I've noticed that when there are errors reported, there's no newline character at the end of the report, which depending on the OS, will output the prompt immediately after the report.
On the other hand, there is a newline character, in the absence of any errors, as a result of `roc test`.
This PR proposes, for consistency purposes, adding a newline character to the end of the report in the aforementioned first case.
It seems that `print_error_warning_count`, which was introduced in [this](https://github.com/roc-lang/roc/commit/00d1ac0aef9c6e60b93dc4c4b3f1c5fbc192289d) commit is currently unused. Just wanted to double-check, if this has been intentional.
The following are abbreviated execution runs, demonstrating the state of matters, prior to introducing the …
=> Add a newline when reporting test failures

crates/cli/src/lib.rs, crates/reporting/src/cli.rs, crates/reporting/src/report.rs
Currently the console is boldfaced (and stays so) after running `roc check` or `roc test`. This is because the definition in https://github.com/roc-lang/roc/blob/main/crates/reporting/src/report.rs#L260 contains a `[1;` in front of the color code. This improves the readability of the colored numbers but is not reset properly by the code `[39m` that we currently have in these two cases. This code only resets the color but not the type face.
I used the constant code `[0m` to reset both, the color and the type face.
Another way would be an explicit reset of color and type face but this seems to be too noisy for me.
By the way I removed the buggy and unused `color_reset` constant.
=> Use constant ANSI code to reset boldfaced colors in reporting

crates/compiler/build/src/program.rs
Reproducible via the following:
```elm
> cat ./test.roc 
app "test"
packages { pf: "../platform/main.roc" }
imports []
provides [] to pf
tmp = "Test!"
> roc test ./test.roc
Failed with error: FileProblem { filename: "../platform/main.roc", error: NotFound }<command prompt starts here>
```
=> Add newline after "Failed with error" msg

www/content/tutorial.md
added because of https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.E2.9C.94.20.60expect.60.20is.20wonderful!
=> add context for expect

Cargo.lock, crates/compiler/fmt/src/pattern.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/src/module.rs, crates/compiler/load_internal/src/module_cache.rs, crates/lang_srv/Cargo.toml, crates/lang_srv/src/analysis.rs, crates/lang_srv/src/analysis/analysed_doc.rs, crates/lang_srv/src/analysis/completion.rs, crates/lang_srv/src/analysis/completion/formatting.rs, crates/lang_srv/src/server.rs
This builds upon my other pr #6134 adding completion for modules and their contents.
It also fixes issues with the panic wrapper not correctly catching panics from async calls.
It lays some the groundwork for completion of type aliases, getting some of the data we need in the right place, and creating a method for completing them,  but doesn't fully implement that feature. 
Alias completion is complex because we need a way to know we are within a type definition.
=> Completion of Modules and imports 

crates/compiler/can/src/expr.rs, crates/compiler/can/src/operator.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/test_syntax/tests/snapshots/pass/suffixed.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/suffixed.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/suffixed.expr.roc, crates/compiler/test_syntax/tests/snapshots/pass/suffixed_nested.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/suffixed_nested.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/suffixed_nested.expr.roc, crates/compiler/test_syntax/tests/test_snapshots.rs, crates/lang_srv/src/analysis/tokens.rs
This PR;
- Adds support for parsing and formatting the suffix `!` for idents e.g. `foo! (bar! baz) (blah stuff)` as described in [chaining syntax proposal](https://docs.google.com/document/d/1mTEZlOKqtMonmVsIGEC1A9ufs1TQHhVgZ52Vn-13GeU/edit)
=> Add `!` suffix to parser

crates/compiler/mono/src/borrow.rs, crates/compiler/mono/src/inc_dec.rs, crates/compiler/mono/src/lib.rs
NOTE: this is not actually hooked up
there are also these limits
- only considers `List *` and `Str` layouts, or lambda sets containing just those layouts
- only looks at calls to lowlevels (so not other function calls)
the next step is to walk the topological sort of procs and for each SCC run this inference until fixpoint. At that point we can call other (user) functions and pass arguments as borrowed. I'm not sure yet if we need to change something about functions themselves when one of the arguments is passed to it as borrowed. I suspect we do which means more thinking is required
=> infer for a proc whether it is OK to pass an argument as borrowed

crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/ident.rs, crates/compiler/parse/src/pattern.rs, crates/compiler/test_syntax/tests/snapshots/pass/suffixed_nested.expr.result-ast, crates/docs/src/lib.rs
This PR;
- Moves the parsing for suffixed things into `chomp_identifier_chain` to improve reliability (only valid `Idents` can be suffixed) and enable nesting within expressions.
Tested using 
```roc
app "desugar-bang"
packages {
cli: "../basic-cli/platform/main.roc",
}
imports [
cli.Stdout, 
cli.Task,
cli.File,
cli.Path,
]
provides [main] to cli
main =
path = Path.fromStr "echo.txt"
{} = 
"Opening file: " 
|> Str.concat (Path.display path) 
|> Stdout.line!
str =
File.readUtf8 path
|> Task.onErr! \err -> Task.ok (Inspect.toStr err)
Stdout.line str
```
=> De-sugar bang `!` operator - part 2

www/content/tutorial.md
Hi there! Just filing a fix for an issue I ran into while working through the tutorial.
```
» Num.xor
── NOT EXPOSED ─────────────────────────────────────────────────────────────────
The Num module does not expose `xor`:
4│      Num.xor
^^^^^^^
```
=> Update `Num.xor` to `Num.bitwiseXor` in tutorial

crates/compiler/fmt/src/spaces.rs, crates/compiler/load_internal/tests/fixtures/build/no_deps/Docs.roc, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/blankspace.rs, crates/compiler/parse/src/highlight.rs, crates/compiler/test_syntax/tests/snapshots/pass/docs.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/docs.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/docs.expr.roc, crates/compiler/test_syntax/tests/test_snapshots.rs
This turned out to be more of a parsing issue -- `##foo` was not being parsed as a doc comment. The formatting code already adds a space between `##` and the comment content (see https://github.com/jschear/roc/blob/81be1441841f2005edd3e49eaa010e9085d53a7c/crates/compiler/fmt/src/spaces.rs#L190).
Closes #6582.
=> Add spaces to doc comments

www/content/tutorial.md
`roc run` discards `dbg` statements.
=> tutorial: correct when `dbg` active

crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/parser.rs, crates/reporting/src/error/parse.rs
Fix #6618 
```
── UNEXPECTED COMMA in test.roc ────────────────────────────────────────────────
I am trying to parse an expression, but I got stuck here:
1│  app "Test"
2│      packages {
3│          pf: "https://github.com/roc-lang/basic-cli/releases/download/0.8.1/x8URkvfyi9I0QhmVG98roKBUs_AZRkLFwFJVJ3942YA.tar.br",
4│      }
5│      imports [
6│          pf.Stdout,
7│      ]
8│      provides [main] to pf
9│
10│  main =
11│      # Not the "," which shouldn't be in the function call here.
12│      a = myFunction 1, 2
^
This comma in an invalid position.
```
=> Add error reporting for unexpected comma

crates/compiler/derive_key/src/lib.rs, crates/compiler/load/tests/test_reporting.rs, crates/reporting/src/error/type.rs, roc-for-elm-programmers.md, www/content/faq.md, www/content/tutorial.md
I strongly believe that seeing the word "optional" is priming people wrong when it comes to this feature. Especially given roc does not have an `Optional/Option/Maybe` type, so users look for an alternative and find this.
This PR changes the name to "default value record fields". It updates all docs and errors.
It does not update compiler internal naming.
That can be updated in a follow up PR if we want to, but I am also fine leaving it cause it is not exposed to users.
=> Change docs/errors from "optional" to "default value" record fields

Cargo.lock, Cargo.toml, crates/compiler/load/Cargo.toml, crates/compiler/load/tests/test_reporting.rs, crates/compiler/load_internal/Cargo.toml, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/test_syntax/Cargo.toml, crates/compiler/test_syntax/tests/test_fmt.rs, crates/test_utils/src/lib.rs, crates/test_utils_dir/Cargo.toml, crates/test_utils_dir/src/lib.rs
This PR splits test_utils into two as the dependencies for `remove_dir_all` are not compatible with WASM tests, and these utils are helpful for test in `roc_can`.
=> Split `test_utils`

crates/compiler/can/src/suffixed.rs, crates/compiler/can/tests/test_suffixed.rs
This PR implements support for suffixed conditionals in `when`, and also suffixed `when` branches as described in [Chaining Syntax Proposal](https://docs.google.com/document/d/1mTEZlOKqtMonmVsIGEC1A9ufs1TQHhVgZ52Vn-13GeU/edit?usp=sharing).
**Note:** this only supports `when` expressions and not `when` statements. Support for `when` as a statement is left for a future PR. Until then, `when` can only be used as the final expression in a sequence of defs, as it will not be unwrapped if it is in the middle of a sequence of other statements.
```
$ cargo run -- dev test.roc
Finished dev [unoptimized + debuginfo] target(s) in 0.29s
Running `target/debug/roc dev test.roc`
PASS 1
PASS 2
PASS 3
```
```roc
app "when-example"
packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.9. …
```
=> Add support for suffixed `when` expressions

crates/compiler/builtins/roc/Num.roc
This commit has a minor fix to the example in the docstring of `Num.shiftLeftBy`.
One line in the example reads:
```roc
0b0000_0101 |> shiftLeftBy 2 == 0b0000_1100
```
which is false:
```sh
zsh ❯ roc repl
The rockin' roc repl
────────────────────────
Enter an expression, or :help, or :q to quit.
» 0b0000_0101 |> Num.shiftLeftBy 2 == 0b0000_1100
Bool.false : Bool
```
The result should instead be `0b0001_0100`:
```sh
zsh ❯ roc repl
The rockin' roc repl
────────────────────────
Enter an expression, or :help, or :q to quit.
» 0b0000_0101 |> Num.shiftLeftBy 2 == 0b0001_0100
Bool.true : Bool
```
=> Minor fix to the docstring of `Num.shiftLeftBy`

crates/compiler/can/src/desugar.rs, crates/compiler/can/tests/test_suffixed.rs
The PR fixes the recursion to unwrap a nested suffixed for top level def.
For example, the following would not have been fully unwrapped and therefore is fixed with this change.
```roc
run = line! (nextMsg!)
```
=> Fix recursion for suffixed `!` in top-level def

crates/compiler/test_syntax/fuzz/Cargo.toml
The fuzzer is intentionally not part of the workspace (it requires nightly, and we don't want to make `cargo check --all` fail in the main workspace), so we can't use workspace-based config.
=> Fix syntax fuzzer cargo config

nix/builder.nix, nix/default.nix
Looks like 88c4a3af4e23d00aaf95c8f79bbf8d9e1056f363 broke nix builds for the `lang-server` package. This PR fixes it.
=> Fix lang-server nix package build crash

crates/compiler/can/src/suffixed.rs, crates/compiler/can/tests/test_suffixed.rs
This PR adds support for the case when a leaf node is a suffixed Apply. 
Fix #6661
=> Support additional trailing `!`

.github/workflows/test_nightly_many_os.yml
zlib suddenly is no longer included in the macos 13 github action runner image...
=> fix missing zlib on macos-13

crates/glue/platform/TypeId.roc, crates/glue/platform/Types.roc
Tested using `cargo run -- glue crates/glue/src/JsonGlue.roc test-glue/ test-platform.roc`
```roc 
platform "test"
requires {} { main : Foo }
exposes []
packages {}
imports []
provides [mainForHost]
Foo := [Number U8, String Str]
mainForHost : Foo
mainForHost = main
```
```roc 
app "main"
packages {
pf: "https://github.com/roc-lang/basic-cli/releases/download/0.9.0/oKWkaruh2zXxin_xfsYsCJobH1tO8_JvNkFzDwwzNUQ.tar.br",
}
imports [
pf.Stdin,
pf.Stdout,
pf.Task,
]
provides [
main,
] to pf
main =
result = Stdin.line!
when result is
End ->
Task.ok {}
Input name ->
Stdout.line! "Hello, $(name)"
```
```roc
app "json-glue"
packages {
pf: "../platform/main.roc",
json: "https://github.com/lukewilliamboswell/roc-json/releases/download/0.7.0/xuaMzXRVG_SEhOFZucS3iBozlRdObWsfKaYZMHVE_q0.tar.br",
} …
```
=> Add abilities for glue types

www/content/tutorial.md
=> Fix minor heading issue in tutorial

crates/language_server/src/registry.rs, crates/language_server/src/server.rs
This is an attempt to fix some of the main crashes and hangs in the language server process.
from looking at logs I'm seeing two main issues: 
- Occasional panics crashing the process.
- Analysis hangs that eat memory and make the process unresponsive
This tries to fix the hangs with a timeout and removes instances of unwrap that can cause panics
=> Reduce lsp crashes

roc-for-elm-programmers.md
* update outdated info on string interpolation
* update a few links:
* fix anchors;
* there is no "Abilities" section in the tutorial
=> Minor fixes in roc-for-elm-programmers.md

crates/compiler/can/src/suffixed.rs, crates/compiler/can/tests/test_suffixed.rs, crates/compiler/parse/src/ast.rs
This PR adds support for unwrapping suffixed `!` and correctly handling `dbg` statements.
Fix #6672 
```roc
main =
foo = getFoo!
dbg foo
bar foo
```
=> Handle `dbg` when unwrapping suffixed `!`

www/public/site.css
This re-adds the CSS corresponding to the REPL prompt in the tutorial section.
When code is copied, the prompt symbol (`» `) doesn't get copied alongside the code, which matches the expected behaviour.
The behaviour has been tested by building the website locally and inspecting the output corresponding to the tutorial page.
- ZulipChat [thread](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/tutorial.20repl.20prompt/near/437026456).
=> Re-add REPL prompt CSS to tutorial

www/content/tutorial.md
Regarding "oak" vs "", I changed it to follow the example:
```roc
table = \{ height, width, title ? "oak", description ? "a wooden table" } ->
```
=> Fix typos in tutorial.md

.github/workflows/ubuntu_x86_64.yml, crates/language_server/src/analysis.rs, crates/language_server/src/convert.rs, crates/reporting/src/report.rs
The language server uses the `Generic` error reporting style which assumes the window is a little wider than editor diagnostic popups typically are.
This PR changes that so that only the report title is included without decorators or path:
In the future, we could probably improve LS reports further under this new mode.
=> Narrower reports from language server

crates/language_server/src/analysis/parse_ast.rs
[This Zulip thread](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Syntax.20error.20in.20the.20tutorial.3F/near/437730768) mentioned that saving an old app header in Zed "removes a lot of stuff". So, I tried it myself and I found that it was indeed dropping imports:
It looks like I forgot to upgrade header imports when calling the formatter through the language server. When this PR is merged, it should work like the CLI formatter:
https://github.com/roc-lang/roc/assets/1724813/441a99e6-c429-4c2e-89cb-4b8899852f0c
=> Upgrade header imports when formatting through lang server

crates/repl_ui/src/repl_state.rs
This error can be hit when entering for example `F = \x -> x % 3` so I added a tip for that.
Long term we want to further improve this error with https://github.com/roc-lang/roc/issues/6722.
=> Improve error message

www/build.sh, www/main.roc
Fixes example description "Example of index.html in the Roc programming language." etc. discussed in #6741
=> Fix example page title and description

crates/compiler/can/src/def.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/problem/src/can.rs, crates/reporting/src/error/canonicalize.rs
Now we have separate error messages for if you use `*` or `_` in type aliases or opaque types.
In a future PR I'd like to also give special error messages for using `_` in ability member definitions.
=> Revise errors for undeclared type vars in aliases

crates/cli/src/lib.rs, crates/packaging/src/tarball.rs
If any of the modules in a package has an ingested file import, we will now add it to the tarball bundle. 
Fails if the file is outside the dir containing the entry point.
=> Include ingested files in package tarballs

crates/compiler/build/src/link.rs
If the target specific prebuilt static binary `legacy_host_file` is not found, check for a generic e.g. `libhost.a`  on macOS or `libhost.so` on linux.
This change simplifies the build process when developing a platform locally. A dedicated build script which can translate between the targets for native and roc filenames is no longer required. 
For example, when using `cargo build` or `zig build` to produce a static library named `host` for the native target, a generic  `libhost` file is produced. This is the default behaviour and produces a debug build. 
To use this prebuilt binary it needs to be renamed to the equivalent roc target specific name for the current target using an alternate build script. This can be done using build tools such as `build.rs`, and `build.zig`, or …
=> Look for a generic default host `libhost` for prebuilt platform binary

crates/compiler/parse/src/expr.rs, crates/repl_ui/src/repl_state.rs
Close https://github.com/roc-lang/roc/issues/6574
Tested manually these scenarios:
1. type `# comment` and evaluate
```
» # comment
Enter an expression to evaluate, or a definition (like x = 1) to use later.
- ctrl-v + ctrl-j makes a newline
- :q quits
- :help shows this text again
»
```
2. paste multiline code and evaluate
```
» # comment
… x = 42
42 : Num *
```
=> Ignore comments in repl

crates/packaging/src/tarball.rs
Follow up from #6757 with a fix for the ingested file paths. 
The current implementation duplicates the relative path, so for example `go-builtins/roc_std.h` will be `go-builtins/go-builtins/roc_std.h`.
```
thread 'main' panicked at crates/packaging/src/tarball.rs:306:25:
Cannot bundle go-builtins/go-builtins/roc_std.h (imported in package/Go.roc) since it's outside package
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I changed to look for `..` in the path instead, as this prevents importing files above the package root.
This patch used to create [this release bundle](https://github.com/lukewilliamboswell/roc-glue-code-gen/releases/tag/0.1.0).
=> Fix importing ingested file when bundling packages

module_with_params_and_multiline_exposes.header.roc
This removes what seems to be a leftover copy of `crates/compiler/test_syntax/tests/snapshots/pass/module_with_params_and_multiline_exposes.header.roc` from the root dir of the project.
This is the reference [commit](https://github.com/roc-lang/roc/commit/370013b9604d187b5362e9bb12a585ab13187732).
=> Remove redundant test snapshot from root dir

www/content/index.md
I primarily want to rename the assigned variable to something other than `list`, to lead with something engaging that doesn't risk confusion with `List`. These changes seem to fit nicely, with only two extra characters of screen width consumption. However, I'm open to any changes that make this both more intuitive and more fun :)
I don't like that this pushes the "Roc: A fast..." text slightly to the left, but I haven't read `www/` well enough (yet?) to know how to improve that.
=> Add some more fun to the homepage example

crates/repl_eval/src/eval.rs, crates/repl_test/src/tests.rs
Addresses part of #6709. I might need a little bit of help on this one.
My understanding of rust macros is limited - I suspect the `f64_helper!` and `f32_helper!` macros could be elided. I was trying to avoid adding a trait just for dispatching on the number printing function at the end.
I also think my usage of `Expr::Num("Num.nanF64")` is wrong since we aren't actually implementing these as literals - there must be another AST node type for getting something from a module?
There are a few pieces of documentation in `Num.roc` that could be updated to reflect these changes.
Finally, I wasn't sure if there was any runtime (zig) code for printing numbers as strings that we also want to consider? (Sorry, my understanding of the system as a whole is limited at this stage).
=> Print special float values as Num.nanF64, etc

www/content/install/getting_started.md, www/content/install/index.md, www/content/install/linux_x86_64.md, www/content/install/macos_apple_silicon.md, www/content/install/macos_x86_64.md, www/content/install/nix.md, www/content/install/other.md, www/content/install/windows.md, www/content/tutorial.md, www/main.roc
Addresses #6764 
Key changes
- `install.md` is now in `www/content/install/index.md`
- guides from `getting_started/` are now in `www/content/install/`
- guides' h1 headings were shortened to fit better on the site
- urls were updated within the install/ files
Questions
- I moved the `getting_started/README.md` to `www/content/install/getting_started.md`. It has a lot of overlap with the `install/index.md`. Would it be desirable to combine them somehow? Or is it intended to replace it? I found that it was linked from the Tutorial installation section, so I also updated that link in the meantime.
- I used relative paths with `.html` extensions. Was that ok? Or are we supposed to leave the .html extension off of the URL paths? 
- Any other changes?
=> move everything in getting_started folder to website

www/content/faq.md, www/content/tutorial.md
I made an attempt at updating the module headers in the tutorial to use the new syntax. I mostly just ran the old ones through the roc formatter and made sure that the accompanying text was updated to describe the changes.
=> update module header syntax in the tutorial

.github/workflows/basic_cli_build_release.yml, .github/workflows/basic_webserver_build_release.yml, .github/workflows/macos_x86_64.yml, .github/workflows/nightly_macos_x86_64.yml, .github/workflows/test_nightly_many_os.yml
[macos-11 CI runner is deprecated and will soon be removed](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
=> remove macos-11

README.md
Reopening https://github.com/roc-lang/roc/pull/6787 - hopefully CI will pass this time :slightly_smiling_face:
=> Fix "Installation guide" link in README.md

www/content/docs.md
The old link points to the docs of the main branch, for which the docs are currently broken (I'm investigating). We do want this to point to the docs of the latest release anyway, see also github.com/roc-lang/roc/issues/6796.
=> point basic-cli docs to latest release

crates/compiler/load_internal/src/file.rs
When loading a platform module as the root, the `is_root_module` flag in `HeaderInfo` would get set to `false`. This caused issues with docs generation.
Closes: #6804
=> Fix platform root module flag

www/content/tutorial.md
`isCapitalized` no longer exists.
Related to #6810
=> isCapitalized > startsWith

crates/compiler/test_gen/src/gen_num.rs
this comment was added originally in 24e6cd80e7, but was a comment on a `if cfg!(not(wasm)) {...}` block. Later that `if` was removed but the comment was not, and eventually got copied to another location making it even harder to figure out why it's there.
=> rm dead FIXME comment

ci/package_release.sh, crates/compiler/build/src/link.rs, crates/wasi-libc-sys/build.rs
This PR addresses the following issues:
* #6029 
* #5573 
The net result of this PR is the roc binary in the release package is able to run the `nodejs-interop/wasm` example using the instructions in the README.
The release package now looks like:
```shell
$ earthly +build-nightly-release --RELEASE_FOLDER_NAME=out
$ tar tf out.tar.gz
(truncated for brevity where globs are shown)
out/
out/examples/**
out/crates/
out/crates/compiler/builtins/bitcode/*
out/crates/roc_std/**
out/roc
out/roc_language_server
out/lib/
out/lib/wasi-libc.a
out/LICENSE
out/LEGAL_DETAILS
```
The original issue was the roc CLI was using the [WASI_LIBC_PATH](https://github.com/roc-lang/roc/blob/794c20956de5f22019fe1bf1cad6bf7b738add52/crates/wasi-libc-sys/src/lib.rs#L22) to lookup the path to `wasi-libc.a`. When …
=> fix: wasi-libc.a library packaging

crates/cli/tests/cli_run.rs, crates/cli/tests/fixtures/transitive-deps/direct-one-and-two.roc, crates/cli/tests/fixtures/transitive-deps/direct-one.roc, crates/cli/tests/fixtures/transitive-deps/direct-zero.roc, crates/cli/tests/fixtures/transitive-deps/one/One.roc, crates/cli/tests/fixtures/transitive-deps/one/main.roc, crates/cli/tests/fixtures/transitive-deps/two/Two.roc, crates/cli/tests/fixtures/transitive-deps/two/main.roc, crates/cli/tests/fixtures/transitive-deps/zero/Zero.roc, crates/cli/tests/fixtures/transitive-deps/zero/main.roc, crates/compiler/load_internal/src/file.rs
We were never loading the packages of a package / platform. This caused the compiler to hang if your app depended on a package transitively.
=> Load packages of packages

crates/cli/src/lib.rs
Closes #6797 and also cleans up a few things I noticed (in separate commits).
The issue is that we get the "exit status" here...
https://github.com/roc-lang/roc/blob/6a074adcf235beaa171c962bf71742325e98cf9c/crates/cli/src/lib.rs#L1245-L1249
...but `status` isn't actually the _exit_ status.
Per [waitpid(2)](https://linux.die.net/man/2/waitpid), `libc::WEXITSTATUS(status)` is what we're looking for.
=> Make `roc dev someFile.roc` forward exit status

crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/compiler/build/src/program.rs, crates/linker/src/elf.rs, crates/linker/src/lib.rs, crates/linker/src/macho.rs, crates/linker/src/pe.rs, crates/linker/src/util.rs
Splitting this off from #6696
This PR modifies the API for preprocessing host binaries for surgical linking. 
```
$ roc preprocess-host --help
Runs the surgical linker preprocessor to generate `.rh` and `.rm` files.
Usage: roc preprocess-host [OPTIONS] <host> <platform> <lib>
Arguments:
<host>      Path to the host executable where the app was linked dynamically
<platform>  Path to the platform/main.roc file
<lib>       Path to a stubbed app dynamic library (e.g. roc build --lib app.roc)
Options:
--verbose  Print detailed information while pre-processing host
-h, --help     Print help
```
=> Update preprocess host API

crates/compiler/load/tests/test_reporting.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/module/src/symbol.rs
The compiler would hang when it encountered an import with a module name that matched a builtin name regardless of whether it was package-qualified.
```roc
import pf.List
```
Instead of hanging we will now report the usual `FILE NOT FOUND` error, or `IMPORT NAME CONFLICT` if it exists.
This will help prevent some confusion when `Task` becomes a builtin.
=> Fix hang on qualified import with builtin name

www/content/install/index.md, www/public/site.css
This PR adds a banner to the `/plans` page on the `/install` page of the website.
=> Add plans banner to `/install` page

www/content/platforms.md
Since this page was last updated, the snippet at the top is no longer accurate.
This is similar to #6781 and #6795 
FYI, I would love some more documentation on how to implement custom platforms. I will be looking into this myself though and might write some :)
=> Update platforms page to match new syntax

crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/compiler/build/src/program.rs, crates/compiler/solve/src/kinds.rs, crates/error_macros/src/lib.rs, crates/glue/src/load.rs
There are a lot of entry points for a Roc program. They should probably
be all consolidated into one, but for now, when FunctionKind is needed,
determine it from the environment. This fixes EXPERIMENTAL_ROC_ERASE for
`roc test` etc.
Also print the location of a failure when `internal_error!` is called. I
think this should panic instead, and I thought it used to - does anyone
know if that changed?
=> Make sure FunctionKind is determined in all entry points

Cargo.lock, Cargo.toml, crates/cli/src/lib.rs, crates/fs/Cargo.toml, crates/fs/src/file.rs, crates/fs/src/lib.rs, crates/fs/src/native_path.rs
Splitting this off from some foundational work on caching.
The basic idea here is that in really big Roc projects, incremental rebuilds will involve a huge amount of file reads and writes to/from both source files and in the future also cache files, so it's beneficial to have tight control over how file I/O works - including the (minimum number of) syscalls involved.
=> Add no_std fs

crates/cli/tests/cli/combine-tasks.roc, crates/cli/tests/cli/parse-args.roc, crates/cli/tests/cli_run.rs, crates/compiler/can/src/desugar.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/tests/test_can.rs, crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/spaces.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/module/src/called_via.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/parser.rs, crates/compiler/problem/src/can.rs, crates/compiler/test_syntax/tests/test_fmt.rs, crates/language_server/src/analysis/tokens.rs, crates/reporting/src/error/canonicalize.rs, crates/reporting/src/error/parse.rs, crates/reporting/src/error/type.rs
This PR implements the new style of the record builder syntax (using map2 functions) as described by @agu-z in [this Zulip thread](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/map2-based.20record.20builders/near/446284737).
- Since the old syntax works differently from the new one, there's no way to automatically upgrade existing record builders, but at least for now, the old syntax is still supported. The old syntax has been renamed to "old-style record builders" in the code and in our error reporting to imply to users that the old version of record builders are out-of-date. We have freedom with this PR to decide at our leisure when to deprecate the old style.
- This PR only handles the implementation, I'm doing the documentation and website/tutorial updates in a separate …
=> Implement new builder syntax alongside old one

crates/compiler/load_internal/src/file.rs, crates/compiler/parse/src/src64.rs
`./crates/repl_wasm/build-www.sh` used to generate some rust warnings, now they're gone :)
=> fix wasm repl warnings

crates/compiler/builtins/bitcode/src/list.zig
So when working with the new basic-cli `mmap` function, I realized that it could cause segfaults and was very confused. Turns out we had a few lingering seamless slice bugs.
Verified this functionality is correct using lldb and my mmap example from basic-cli.
=> fix slice refcounting mistakes that can modify data before a list

crates/compiler/gen_llvm/src/llvm/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/compare.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_llvm/src/llvm/refcounting.rs, crates/compiler/gen_llvm/src/llvm/scope.rs, crates/compiler/gen_llvm/src/llvm/struct_.rs, crates/compiler/test_gen/src/gen_primitives.rs
Only generates allocas in the entry block of a function. This is what llvm wants; it optimizes better, and it avoids many common stack overflow cases.
The main complication here is dealing with joinpoints. They recurse on themselves and can overwrite values in allocas. For anything that is passed by reference, create a slot of the joinpoint args. On jumping to that slot, copy all of the args over. This ensures that a unique copy is ready for the joinpoint. It also ensures we don't pass a pointer to a stale alloca.
fixes #6139
fixes #6282
fixes #6213
fixes #6434
=> llvm: only generate `alloca` in the entry block

crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_llvm/src/llvm/bitcode.rs, crates/compiler/gen_llvm/src/llvm/build_list.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_wasm/src/backend.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/module/src/symbol.rs, crates/compiler/mono/src/code_gen_help/copy.rs, crates/compiler/mono/src/code_gen_help/mod.rs
Generate element copying functions in roc to avoid `memcpy` as much as possible. If size and alignment are know at compile time, copying can be way faster.
This is a huge perf gain for sorting. I still think we have room to grow in the algorithm we use (and maybe falling back to pointer sorting for large sized elements), but a great start:
```shell
$ hyperfine /tmp/tmp-old /tmp/tmp
Benchmark 1: /tmp/tmp-old
Time (mean ± σ):      2.871 s ±  0.007 s    [User: 2.858 s, System: 0.003 s]
Range (min … max):    2.865 s …  2.889 s    10 runs
Benchmark 2: /tmp/tmp
Time (mean ± σ):     193.4 ms ±   1.4 ms    [User: 189.7 ms, System: 1.7 ms]
Range (min … max):   192.3 ms … 197.8 ms    14 runs
Summary
/tmp/tmp ran
14.84 ± 0.11 times faster than /tmp/tmp-old
```
helps #6294
fixes #6450
=> Generate copy functions in roc and pass them into zig

.gitignore, crates/compiler/builtins/bitcode/.gitignore, crates/compiler/builtins/bitcode/fuzz_in_tmux.sh, crates/compiler/builtins/bitcode/src/fuzz_sort.zig, crates/compiler/builtins/bitcode/src/list.zig, crates/compiler/builtins/bitcode/src/main.zig, crates/compiler/builtins/bitcode/src/sort.zig
Switch sorting over to [fluxsort](https://github.com/scandum/fluxsort). This is a modern and super fast sorting algorithm ([perf info here](https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/faster.20sorting/near/454705605)). 
As part of the change, end up generating 4 specialization of sorting based on whether or not the closure is refcount and whether the element size is so large that it is smarter to sort a list of pointers rather than sorting the actual list.
I am pretty confident in the implementation cause I have run a solid amount of fuzzing.
fixes #6293
fixes #6294
=> Fast Builtin Sorting

crates/compiler/parse/src/expr.rs
=> Give an error for record builders in patterns instead of crashing

crates/cli/tests/cli_run.rs, crates/compiler/load/tests/test_reporting.rs, crates/reporting/src/error/type.rs
Errors like this come up often:
```
── TYPE MISMATCH in examples/helloWorld.roc ────────────────────────────────────
This 1st argument to this function has an unexpected type:
13│      args |> List.dropFirst 1 |> List.map parseNumber!
^^^^^^^^^^^
This parseNumber value is a:
(Str -> Task.Task (Int Unsigned8) [Exit (Num *) Str])
But this function needs its 1st argument to be:
InternalTask.Task a b
Tip: Type comparisons between an opaque type are only ever equal if
both types are the same opaque type. Did you mean to create an opaque
type by wrapping it? If I have an opaque type Age := U32 I can create
an instance of this opaque type by doing @Age 23.
```
In this case the tip would put you on the wrong path. Given that I strongly suspect that most times when users see this tip, it puts them …
=> improve opaque types tip

.github/workflows/ci_manager.yml, .github/workflows/ubuntu_x86_64_debug.yml, Cargo.lock, crates/cli_utils/Cargo.toml, crates/cli_utils/src/helpers.rs
We only used to test with `cargo test --release` in the past, in debug mode more assertions are checked.
=> cargo test in debug mode

www/content/index.md
This interactive code example does not include backpassing, unless I'm mistaken. Instead, it uses the `!` operator.
I also reordered the syntax sugar list to match the order they appear in the example.
=> Remove "backpassing" and add "the `!` operator"

roc-for-elm-programmers.md, www/content/tutorial.md
This PR updates the documentation to clarify how to chain functions that return a `Result`.
1. Added a note about the upcoming syntax sugar for that (i.e., the `?` operator) in the `roc-for-elm-programmers.md` page, at the start of the backpassing section (since backpassing will be replaced, IIUC). The note links to #6828.
2. Added a `Result`-chaining example in the tutorial, as well as a note that some syntax sugar for this is coming.
=> Improve Result-chaining documentation

www/content/tutorial.md
The **Reserved Keywords** paragraph in the tutorial was not quite up to date, as some keywords were missing (e.g., `exposing`) while others were deprecated (e.g., `hosted`). Moreover, many keywords are not actually reserved: you can create a def called `app` or `module`, this does not cause any issues because these keywords are used in a different context, so there is no risk of ambiguity or conflict.
Therefore I updated this paragraph to clearly distinguish the *reserved* keywords from the other keywords. I also sorted the keywords alphabetically for the reader's convenience.
=> Update and clarify reserved vs non-reserved keywords in the tutorial

www/content/plans.md
I noticed the section was in there twice, word-for-word the same.
=> Remove duplicated mentioning of planned glue changes

crates/compiler/builtins/roc/Num.roc
This fixes the failure of `test_fmt::test_fmt_builtins`. This slipped by CI because we don't run `roc format` of tests if only comments changed. Made #6969 to fix this in the future.
=> fmt Num.roc

CONTRIBUTING.md, devtools/debug_tips.md
I have added some debugging tips and moved them to their own md file. The details tag feels more suited for smaller blocks of text. Now we can also provide a link to the debug tips, instead of telling people to scroll down at contribution tips.
=> more debug tips

.cargo/config.toml, .github/workflows/ubuntu_x86_64_debug.yml, ci/check_debug_vars.sh
I added a CI check to make sure the flags in cargo/config.toml and crates/compiler/debug_flags/src/lib.rs are in sync. I also enabled `ROC_CHECK_MONO_IR` for the cargo tests in debug mode.
=> Debug flags

crates/cli/src/lib.rs
We were [trying to get the target argument](https://github.com/roc-lang/roc/blob/0bffd6001c7b27794222db76ba0eb48506935871/crates/cli/src/main.rs#L165) when the preprocess-host command was called, but that command did not actually have the target argument, it was always using the default value.
I was able to discover his by running the debug compiler with basic-cli's build.roc. Clap has a debug_assertion that checks this.
This was the error I got:
```
thread 'main' panicked at crates/cli/src/main.rs:166:18:
Mismatch between definition and access of `target`. Unknown argument or group id.  Make sure you are using the argument id and not the short or long flags
```
=> make target an argument for preprocess-host

crates/glue/src/types.rs
This debug_assert was failing due to https://github.com/roc-lang/basic-cli/issues/242 but I still want to be able to run all the other debug_asserts, so I allowed skipping it with an env var SINGLE_TAG_GLUE_CHECK_OFF.
=> allow glue check toggle

www/content/install/getting_started.md
Seeing MacOS at this position may be confusing for most non-nix macos users.
=> adjust getting started

www/content/tutorial.md
The new map2-based record builders haven't been added to the tutorial yet, this does that without deferring to an explanation of the feature outside of the tutorial as we used to do.
=> Update docs for new record builders

crates/compiler/build/src/link.rs
Anaconda also has a codesign and we want to use the macos one, see https://github.com/pyinstaller/pyinstaller/issues/8581#issuecomment-2147311833
=> use macos codesign

.github/workflows/nightly_macos_apple_silicon.yml, Cargo.lock, Cargo.toml, ci/basic_nightly_test.sh, crates/compiler/module/Cargo.toml, crates/compiler/module/src/module_err.rs, crates/compiler/module/src/symbol.rs, crates/docs/Cargo.toml, crates/glue/Cargo.toml, crates/utils/error/Cargo.toml, crates/utils/error/src/lib.rs, www/content/install/macos_x86_64.md
We were expecting `zstd` to be installed on Mac for Roc, but we only used it in two crates:
- snafu: there were two enums that used Snafu for deriving `Error`
- object: the compression/decompression feature uses `zstd`, but we weren't using the feature
By removing that code, we can remove the dependency
=> Remove barely used zstd dependency

.github/workflows/nightly_macos_apple_silicon.yml
The nightly won't build without this line
=> llvm still needs zstd

examples/platform-switching/rust-platform/src/lib.rs
`roc_str` will not print without flushing if it does not contain a newline and you're using --linker=legacy
=> flush write_all

crates/compiler/gen_llvm/src/llvm/convert.rs
With the version of llvm we are on, `i128` is only aligned to 8 bytes. We were using `i128` to set the alignment of aggregate types. This was leading the the wrong alignment. Instead use `f128` which is actually aligned to 16 bytes on our current version of llvm
=> Fix alignment of 16 byte types

www/content/tutorial.md
While following the tutorial I came across two problems that this PR addresses:
- The example for **Reading values from tasks** does not work when copied and pasted.
- And the hash link for the heading `### [Reading values from tasks](#inspect) {#task-input}` seems to link to the wrong "[Displaying Roc values with Inspect.toStr](https://www.roc-lang.org/tutorial#inspect)" section further down the page.
=> Fix incorrect hash link in tutorial

crates/cli/tests/cli_run.rs, crates/cli/tests/module_params/Menu.roc, crates/cli/tests/module_params/pass_task.roc, crates/compiler/lower_params/src/lower.rs
Passing functions that produce `Task` through params would work if used directly:
```roc
module { echo } -> [menu]
menu = \name ->
echo "Hi, $(name)!"
```
However, it would cause an error when the param was threaded to another top-level function.
```roc
menu = \name ->
indirect name
indirect = \name ->
echo "Hi, $(name)!"
```
The issue seems to be caused by reusing `Variable`s for the destructures added to each top-level function. We will now create a fresh var, and let the type checker unify them properly.
=> Fix threading params that produce Task

crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/pattern.rs, crates/compiler/test_mono/generated/as_pattern_in_closure_arg.txt, crates/compiler/test_mono/generated/opaque_as_pattern_in_closure_arg.txt, crates/compiler/test_mono/generated/record_as_pattern_in_closure_arg.txt, crates/compiler/test_mono/src/tests.rs, crates/compiler/test_syntax/tests/snapshots/pass/arg_pattern_as.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/arg_pattern_as.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/arg_pattern_as.expr.roc, crates/compiler/test_syntax/tests/test_snapshots.rs
The [lower params PR fixed](https://github.com/roc-lang/roc/pull/7009/files#diff-f2e694070279a75a71087060b23b0a1d2599c038b508df2ab93e4649f018a080) the root cause that prevented `as` patterns from working in closure arguments. 
However, the formatter would remove the required parens around the pattern, causing a parse failure.
=> Fix formatting of `as` patterns in closure arguments

crates/compiler/can/src/desugar.rs, crates/compiler/can/src/module.rs, crates/compiler/can/src/scope.rs, crates/compiler/can/tests/helpers/mod.rs, crates/compiler/can/tests/snapshots/test_suffixed__suffixed_tests__dbg_expr.snap, crates/compiler/can/tests/test_suffixed.rs, crates/compiler/load/tests/helpers/mod.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/module/src/symbol.rs, crates/compiler/test_mono/generated/dbg_expr.txt, crates/compiler/test_mono/generated/dbg_inside_string.txt, crates/compiler/test_mono/generated/dbg_nested_expr.txt, crates/reporting/src/error/type.rs
This PR builds on https://github.com/roc-lang/roc/pull/7038, fixing some issues with the initial implementation. The PR following this one will add support for `dbg` in pipelines.
Fix a bug in `dbg` expression desugaring by using the module scope to generate unique identifiers instead of the variable store.
In the initial implementation of `dbg` expressions we used the `VarStore` to generate unique identifiers for new variables created during desugaring. We should have instead used the current module's `Scope`, which handles identifiers within the module. Each scope has its own incrementing variable count which is independent of the shared variable store. The scope is used to generate new identifiers at other points in canonicalization, such as when assigning a global identifier to …
=> Fix dbg expression desugaring and improve dbg error reporting

www/content/tutorial.md
=> fix typo in "because"

www/content/tutorial.md
This PR adds a section on the `?` try operator.
As the `Result.try` + `?` section was getting a bit long, I added an explicit "Error  handling" section. I think it's an important topic so it's worth making it stand out a bit more.
Also, when the `!` operator is introduced, I think it's useful to say it's similar to the `?` operator, but for `Task` instead of `Result`.
=> Update the tutorial to add the ? operator

www/content/tutorial.md
I tried to keep it as short and simple as possible.
I used `1 + dbg n` instead of `dbg n + 1` to avoid any confusion about operator precedence.
=> Add a short paragraph to explain dbg forwarding, fixes #7061

www/content/abilities.md
=> Uppercase naming consistency in abilities docs

crates/compiler/gen_llvm/src/llvm/convert.rs, crates/glue/src/RustGlue.roc
Explicit padding changes the c-abi when passed to/returned from functions. This is leading to incorrect loading of types like `Task U64 {}`.
=> Avoid explicit tag padding

crates/cli/tests/cli_run.rs, crates/cli/tests/module_params/MultilineParams.roc, crates/cli/tests/module_params/multiline_params.roc, crates/compiler/can/src/desugar.rs, crates/compiler/can/src/module.rs, crates/compiler/can/src/pattern.rs
Module param patterns do not appear in defs and therefore weren't automatically run through desugaring. 
Amongst other, this fixes an [issue](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Compiler.20panic.20with.20module.20params/near/471801244) where `canonicalize_record_destructures` would panic when it run into a multiline params pattern because it didn't expect `Pattern::SpaceBefore` nodes to exist at that point.
=> Desugar module param patterns before canonicalization

www/content/tutorial.md
Support for e.g. `RunErr : _` got removed 4 months ago, see https://github.com/roc-lang/roc/commit/8357bd8c91a811b171912d072f24fa17a08019a8 . [More context](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.E2.9C.94.20Type.20alias.20definitions.20may.20not.20use.20inferred.20types/near/472047806).
=> Update tutorial _

Cargo.lock, crates/cli/Cargo.toml, crates/cli/build.rs, crates/cli/src/lib.rs, crates/cli/src/main.rs
Addresses #7030.
I'm not that experienced with Rust and I'm not familiar with the style and priorities of the Roc compiler team, so I'd appreciate feedback on anything that looks out of place or inefficient :sweat_smile: 
I think this is nearly done, but I'm getting a default commit timestamp when I run it locally:
```
roc built from commit 6d0a9b69d, committed at 1980-01-01T00:00:00.000000000Z
```
I think it's a default timestamp, maybe for reproducible builds? But that doesn't make sense to me because it's not a build timestamp, it's a commit timestamp :thinking:
Again, any help is appreciated! :grinning:
=> Add commit information to roc versions built from source

crates/compiler/can/src/desugar.rs, crates/compiler/can/tests/snapshots/test_suffixed__suffixed_tests__issue_7081.snap, crates/compiler/can/tests/snapshots/test_suffixed__suffixed_tests__issue_7081.snap.new, crates/compiler/can/tests/test_suffixed.rs
Fix #7081 
Tested using `main.roc` below
```roc
app [main] {
pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.15.0/SlwdbJ-3GR7uBWQo6zlmYWNYOxnvo8r6YABXD-45UOw.tar.br",
}
import pf.Stdout
inc = \i ->
if i > 2 then
Err MaxReached
else
Ok (i + 1)
expect
run = \i ->
newi =
i
|> inc?
|> inc?
Ok newi
result = run 0
result == Ok 2
main =
Stdout.line! "Hello world"
```
```sh
$ nix develop
$ cargo run -- test main.roc
Finished dev [unoptimized + debuginfo] target(s) in 0.42s
Running `target/debug/roc test main.roc`
0 failed and 1 passed in 566 ms.
```
=> Desugar suffixed `ValueDef::Expect` nodes

crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/compiler/load_internal/src/file.rs, crates/docs/src/lib.rs, crates/glue/src/load.rs, crates/language_server/src/analysis.rs, crates/language_server/src/convert.rs, crates/packaging/src/cache.rs, crates/repl_eval/src/gen.rs
Related to #6616, this pull request introduces the following changes: 
1. Changes the `roc_cache_dir()` function to return `~/.cache/roc` instead of `~/.cache/roc/packages`
2. Introduces a new function, `roc_cache_packages_dir()`, which returns `~/.cache/roc/packages`
3. Updates all existing uses of `roc_cache_dir()` with `roc_cache_packages_dir()` for parity with existing behavior
=> Fix `roc_cache_dir()` and introduce `roc_cache_packages_dir()` (#6616)

flake.nix
1. The issue is fixed upstream.
2. It blocks all other rustflags set by end users like "fuse-ld=lld" which improves compilation perf.
=> Remove stale RUSTFLAGS export

www/content/tutorial.md
Leaving off `Str` results in an error like the following:
```
── TYPE MISMATCH in ....0/SlwdbJ-3GR7uBWQo6zlmYWNYOxnvo8r6YABXD-45UOw/main.roc ─
Something is off with the type annotation of the main required symbol:
2│      requires {} { main : Task {} [Exit I32 Str]_ }
^^^^^^^^^^^^^^^^^^^^^^^
This #UserApp.main value is a:
Task {} [Exit …, …]
But the type annotation on main says it should be:
Task {} [Exit … Str, …]
...
```
etc.
=> Typofix type signature for `main` in tutorial

crates/cli/src/main.rs, crates/cli/tests/cli/form.md, crates/cli/tests/cli_run.rs
This commit alters `roc check` to be able to run on Markdown files. The overall flow is:
- check if the file has a `.md` extension
- if it does extract any fenced code blocks marked as Roc
- write those blocks to temp files
- run `roc check` sequentially on every temp file
- print out the results of `roc check`
- exit early if any individual `roc check` has non-zero exit status
- if the file does not have `.md` extension proceed as before
=> Initial Sketch of roc check on Markdown

crates/cli/src/lib.rs, crates/cli/tests/cli/argv0.roc, crates/cli/tests/cli_run.rs
When we run `roc run <file>` or `roc <file>` then Roc will compile a binary and run it. Before this commit we would set the path to the compiled binary as argv[0]. This commit changes the behavior to make argv[0] in the binary correspond to the roc file being ran.
This is what shells like sh or bash do. If you create a file `test.sh` with the contents `echo "$0"` then run `bash test.sh`, that will print `test.sh` and not `bash`. Scripts can make use of $0 to get their own location, for instance to find files relative to themselves on the filesystem.
Related Zulip conversation:
https://roc.zulipchat.com/#narrow/channel/302903-platform-development/topic/getting.20args.20when.20using.20.60roc.20run.60.3F/near/477528914
=> Set argv[0] to .roc file passed to 'roc run'

crates/compiler/can/src/copy.rs, crates/compiler/can/src/exhaustive.rs, crates/compiler/checkmate/schema.json, crates/compiler/checkmate/src/convert.rs, crates/compiler/checkmate/www/src/components/Content/HeadConstructor.tsx, crates/compiler/checkmate/www/src/components/Content/index.ts, crates/compiler/checkmate/www/src/components/Graph/VariableNode.tsx, crates/compiler/checkmate/www/src/schema.d.ts, crates/compiler/checkmate_schema/src/lib.rs, crates/compiler/derive_key/src/decoding.rs, crates/compiler/derive_key/src/encoding.rs, crates/compiler/derive_key/src/hash.rs, crates/compiler/derive_key/src/inspect.rs, crates/compiler/mono/src/ir.rs, crates/compiler/mono/src/layout.rs, crates/compiler/solve/src/ability.rs, crates/compiler/solve/src/deep_copy.rs, crates/compiler/solve/src/solve.rs, crates/compiler/types/src/pretty_print.rs, crates/compiler/types/src/subs.rs, crates/glue/src/load.rs, crates/glue/src/types.rs
Remove a variant of `FlatType` that I noticed was unused.
=> Remove unused EmptyTuple variant from FlatType enum

crates/docs/src/lib.rs, crates/docs/src/static/index.html, crates/docs/src/static/search.js, crates/docs/src/static/styles.css
closes roc-lang/roc#6540
I use this [example from w3.org](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/) to help with the Aria labeling on the search type ahead.
=> Added search by signature in docs

crates/cli/tests/cli_run.rs, crates/cli/tests/module_params/Alias.roc, crates/cli/tests/module_params/different_types.roc, crates/cli/tests/module_params/issue_7116.roc, crates/compiler/solve/src/solve.rs
When a module depends on another one with params, we copy the params' variable of the latter into the former, which we later use to unify against the record expression in the `import`. However, we were using a single copy of the variable for all imports of a given module which can cause the expected type to become more restricted than it really is.
We didn't have a general issue for this problem, but this fixes #7116 which is related.
=> Unify import params on copied variable

crates/cli/tests/cli_run.rs, crates/cli/tests/module_params/ImportInExpect.roc, crates/cli/tests/module_params/NoParams.roc, crates/compiler/mono/src/ir.rs
During canonicalization, we create `ImportParams` expressions for all imports even none are supplied. This allows us to provide nice error messages during type checking if they're missing.
For nested defs and expects however, these would make it to mono where we would crash if we found them. We'll now drop them there.
Closes #7025
=> Fix imports in expects 

crates/compiler/load/tests/test_reporting.rs, crates/reporting/src/error/parse.rs
Handle `return` syntax errors in parser reporting
=> Report `return` syntax errors

crates/compiler/load/tests/test_reporting.rs, crates/reporting/src/error/parse.rs
Quite a few unhandled syntax errors have accumulated over the years. It's easy to forget to handle these in reporting because we have wildcard `match` branches that just call `todo!()`:
```
thread 'main' panicked at crates/reporting/src/error/parse.rs:681:14:
not yet implemented: unhandled parse error: Return(ReturnValue(Start(@11579), @11579), @11572)
```
That experience is pretty bad when you hit one. You don't know which file the error is in, and you only get byte offsets instead of a line and column.
We should handle all of those, but in the meantime, this PR removes all wildcard pattern matching on parser errors to prevent more cases from accumulating.
Furthermore, it improves the experience for the existing unhandled cases by printing a more intentional report that includes the file …
=> Improve experience for unhandled parse errors

ci/build_basic_cli.sh, ci/build_basic_webserver.sh, crates/compiler/build/src/program.rs, crates/packaging/src/cache.rs
This behavior is now enabled by default, the flag got removed in https://github.com/roc-lang/roc/pull/6859
=> remove mentions of --prebuilt-platform

crates/cli/src/lib.rs
Closes #5103 
I didn't do any fancy. I just loops through all the passed file. Let me know if you want me to do something else.
=> Roc test can now support multiple files

crates/compiler/load_internal/src/file.rs, crates/compiler/worker/src/worker.rs
Occasionally, we'll run into panics during compilation which prior to this diff
would cause the compiler to hang indefinitely after printing the initial panic message.
Note that this simplified/renamed worker 'wakeup' system seems to leave around a bit of a code smell - that this perhaps indicates we should rework/refactor in order to avoid the necessity of having separate wakeup and message stealing systems... but one problem at a time!
=> Prevent panics in worker threads from causing deadlocks

crates/compiler/can/src/annotation.rs, crates/compiler/can/src/def.rs, crates/compiler/can/src/desugar.rs, crates/compiler/can/src/expr.rs, crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/load_internal/src/docs.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/normalize.rs, crates/compiler/problem/src/can.rs, crates/language_server/src/analysis/tokens.rs, crates/repl_eval/src/gen.rs, crates/reporting/src/error/canonicalize.rs
Remove enum variants that I noticed were unused:
`Expr::MalformedClosure`
`RuntimeError::MalformedClosure`
`AssignedField::Malformed`
`Tag::Malformed`
=> Remove unused malformed related variants

.github/workflows/ci_manager.yml, .github/workflows/improve_panics.yml
Implements @Anton-4's idea on #2046 for automatically checking when the number of panics/expects/etc., increases.
Clippy doesn't scan test code by default, so this won't get in the way of using `unwrap` in tests, to @rtfeldman's point.  I also manually verified this by adding/removing `unwrap`s within and outside of test modules, and verifying that the count went up or down as expected.
I wasn't sure if I should make this new workflow be triggered by `ci_manager.yml` or if it's fine to be triggered on every PR pipeline.  At least one other workflow is like this (`spellcheck.yml`) so I went with the latter, but I'm happy to change it however you'd like.
=> Block PRs that increase the amount of panics in non-test code

crates/compiler/can/src/desugar.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/src/suffixed.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/normalize.rs, crates/language_server/src/analysis/tokens.rs
While debugging an issue, I noticed the `Expect` variant of `ast::Expr` was unused
=> Remove unused ast::Expr::Expect

crates/compiler/roc_target/src/lib.rs
arm64 causes issues on raspberry pi
=> back to old architecture display

crates/compiler/build/src/program.rs
This PR restores the functionality to build a roc app into an object file without a host gives an error `Legacy linking failed`. 
```
$ roc build --no-link --emit-llvm-ir examples/simple.roc
Legacy linking failed: Failed to find any legacy linking files; I need one of these three paths to exist:
examples/../platform/macos-arm64.a
examples/../platform/macos-arm64.o
examples/../platform/libhost.a
```
This was likely broken in #6859, here is the previous implementation that provided this functionality. 
```rust 
// We don't need to spawn a rebuild thread when using a prebuilt host.
let rebuild_thread = if matches!(link_type, LinkType::Dylib | LinkType::None) {
None
} else if is_platform_prebuilt {
// <---snipped--->
```
=> Restore `roc build --no-link` pipeline

.github/workflows/nix_linux_x86_64.yml, crates/compiler/gen_dev/src/generic64/aarch64.rs, crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/generic64/x86_64.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/test_gen/src/gen_num.rs
The intent of this change is to support `Num.neg` for Dec, F32, and F64 types in the repl.
Dec negation was implemented across gen-dev, gen-llvm, gen-wasm as a call to the compiled zig function `bitcode::DEC_NEGATE`.
f32 and f64 negation were implemented already for gen-llvm, gen-wasm.
for gen-dev x86_64, float negation is implemented by flipping the sign bit, which means `xorps` for f32, and `xorpd` for f64
for gen-dev aarch64, there is conveniently a `fneg` instruction
Closes #6959
=> impl Num.neg for Dec,F32,F64 in repl

Cargo.lock, Cargo.toml, crates/compiler/collections/src/lib.rs, crates/compiler/collections/src/push.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/specialize_types/Cargo.toml, crates/compiler/specialize_types/src/expr.rs, crates/compiler/specialize_types/src/lib.rs, crates/compiler/specialize_types/src/mono_type.rs, crates/compiler/specialize_types/src/specialize_expr.rs, crates/compiler/specialize_types/src/specialize_type.rs, crates/compiler/specialize_types/tests/test_specialize_types.rs, crates/compiler/types/src/subs.rs, crates/compiler/types/src/types.rs, crates/reporting/src/error/type.rs, crates/soa/Cargo.toml, crates/soa/src/either_index.rs, crates/soa/src/lib.rs, crates/soa/src/soa_index.rs, crates/soa/src/soa_slice.rs, crates/soa/src/soa_slice2.rs
This isn't trying to do anything with expressions yet; all it does is that you give it a `Variable` and `Subs` and it monomorphizes that variable.
This is based on the `cor` implementation at https://github.com/ayazhafiz/cor/blob/b67174d98b6dde16809b3606f9f88d4863d8743f/experiments/lss/monotype/lower_type.ml#L62-L63
=> Specialize types pass

crates/compiler/can/src/constraint.rs, crates/compiler/load/tests/helpers/mod.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/solve/src/module.rs, crates/compiler/solve/src/solve.rs, crates/compiler/test_derive/src/util.rs, crates/test_compile/src/help_solve.rs
When a function is `!`-suffixed but pure we produce a warning. This is what we want in most cases, but as Brendan [pointed out in Zulip](https://roc.zulipchat.com/#narrow/channel/316715-contributing/topic/Help.20upgrade.2Ftest.20purity.20inference/near/484085983), an app should be able to provide a pure function to a platform that allows an effectful one.
=> Allow suffixed pure functions that are exposed to the host

.github/workflows/nix_linux_x86_64.yml
Looks like this also happens without --features="wasm32-cli-run"
=> glue_cli_tests single threaded

crates/compiler/builtins/bitcode/src/dec.zig, crates/compiler/test_gen/src/gen_num.rs
Previously, it would return zero instead of panicking.
=> Fix division of zero by zero for Dec

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/test_gen/src/gen_num.rs
I noticed calling `Num.isFinite` without any arguments will crash the repl. This was because it was inferring the type to be `Dec` which is a valid type for these functions (assuming they can take any `Frac *`), but there was no implementation in gen-dev.  This change adds trivial implementations of `isNaN`, `isFinite` and `isInfinite` for `Dec` which return `false`, `true` and `false` respectively.
=> implement Num.isNaN,isFinite,isInfinite for Dec

crates/docs/src/static/search.js, crates/docs/src/static/styles.css
Now you can use the arrow keys to move up and down the results, press Enter to select to one, and press Esc to hide the search results.
=> Make search box keyboard-friendly

crates/docs/src/static/search.js, crates/docs/src/static/styles.css
https://github.com/roc-lang/roc/pull/7272 should be merged first!
Now we show all search results rather than limiting them to 5. Otherwise, there's no way to scroll to see the rest of the results - and the most straightforward way to let you scroll through the results is to just show them all!
Also, we truncate to ellipses if a search result takes more than 3 lines to display. (You can see that happen in the first result.)
=> Show all search results, each with max of 3 lines

crates/docs/src/lib.rs, crates/docs/src/static/index.html, crates/docs/src/static/styles.css
This design seems to fit the search bar better. 
---
Also moved the "LLM docs" link to the package overview, to simplify the nav bar for the common case:
---
On mobile, I also moved the nav to after the main content, on the theory that if you're coming from the main page, you have all the modules listed right away anyway, and otherwise you might just be searching anyway:
=> Make the top bar go the full width of docs page

crates/compiler/builtins/bitcode/src/num.zig, crates/compiler/gen_wasm/src/low_level.rs, crates/compiler/test_gen/src/gen_num.rs
The intent of this change is to catch integer overflow in the zig bitcode implementation of `NumPowInt`, and turn that into a `roc_panic` with a good error message. This change also ends up implementing `PowInt` in gen-wasm for all integer types.
Closes #7062
=> Num.powInt: panic on overflow

crates/compiler/gen_dev/src/generic64/mod.rs, crates/compiler/gen_dev/src/lib.rs, crates/compiler/gen_llvm/src/llvm/bitcode.rs, crates/compiler/gen_llvm/src/llvm/lowlevel.rs, crates/compiler/test_gen/src/gen_num.rs
MulSaturated and AddSaturated are now implemented for u128, i128
SubSaturated is now implemented for Dec even if it's a little strange to saturate at a decimal value:
```
» Num.subSaturated -170_141_183_460_469_231_731dec 1
-170141183460469231731.687303715884105728 : Dec
```
I decided to rm the `build_num_{mul,add}_saturated` methods because they don't require any asm-specifics. They either call out to bitcode, or in the case of floats, use the non-saturated version.
=> gen-dev: complete Num{Mul,Add,Sub}Saturated impls

crates/compiler/load_internal/src/file.rs
Without the platform data for a run of `roc check SomeFile.roc` we blow up on an assert that all type checking has been done when the root module is exposed.  Here we actually add the platform data when the platform path is RootIsModule.
Closes #7175
=> Add platform data for a check run with a single file

www/content/install/index.md, www/content/tutorial.md
=> fix tutorial styling

crates/cli/tests/cli_tests.rs, crates/cli/tests/test-projects/module_params/effect_module.roc, crates/compiler/load_internal/src/file.rs, crates/compiler/unify/src/unify.rs
This fixes two issues:
1. when running rock check on a module using purity inference the compiler think it's in task effect mode and looks for "stdout" instead of "stdout!"
2. effectful functions provided as module params not unifying properly, causing errors like this:
```
This is the type I inferred:
{ stdin! : {} => Result (List U8) [
EndOfFile,
StdinErr [
AlreadyExists,
BrokenPipe,
Interrupted,
NotFound,
Other Str,
OutOfMemory,
PermissionDenied,
Unsupported,
],
], … }
However, AoC expects:
{ stdin! : effectful function, … }
```
=> Purity inference module params fixes

Cargo.lock, crates/error_macros/src/lib.rs, crates/language_server/Cargo.toml, crates/language_server/src/server.rs
This prevents the compiler from calling exit when crashing when running within the language server. 
Instead, we panic and the language server then catches that panic.
I had no idea it was calling exit rather than panicking this  whole time and this was why I could never seem to unwind the panics  :facepalm: 
This will massively improve the language server experience!
=> Prevent compiler errors from terminating the language server process

crates/compiler/constrain/src/expr.rs, crates/compiler/load/tests/test_reporting.rs
I thought that return type vars would auto-generalize with their containing functions, but I was incorrect, and Weaver was failing to type-check because of it. This generalizes return type vars and validates it works with an otherwise failing test case.
=> Generalize return vars

crates/roc_std/src/roc_box.rs
This is intended as a convenience for platform authors implementing roc_dealloc, addressing the use case in [this zulip thread](https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/Host.20iteration.20access.20to.20roc.20resource.20heaps).
=> add RoxBox::as_refcount_ptr

crates/compiler/can/src/suffixed.rs, crates/compiler/gen_dev/src/run_roc.rs, crates/compiler/parse/tests/test_parse.rs, crates/compiler/specialize_types/src/specialize_type.rs, crates/compiler/test_gen/src/helpers/dev.rs, crates/compiler/unify/src/unify.rs, crates/linker/src/macho.rs, crates/linker/src/pe.rs, crates/repl_test/test_wasm.sh, crates/repl_wasm/src/externs_js.rs
This makes it nicer to work with dbg! normally, because grepping the code base for dbg!() reveals only the usages of it that are currently active.
=> Convert unused dbg!()s to eprintln!()s

crates/cli/src/format.rs, crates/cli/src/main.rs, crates/compiler/fmt/src/annotation.rs, crates/compiler/fmt/src/collection.rs, crates/compiler/fmt/src/def.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/fmt/src/header.rs, crates/compiler/fmt/src/lib.rs, crates/compiler/fmt/src/pattern.rs, crates/compiler/test_syntax/src/test_helpers.rs, crates/compiler/test_syntax/tests/test_fmt.rs, crates/language_server/src/analysis/analysed_doc.rs, crates/language_server/src/analysis/parse_ast.rs, crates/repl_eval/src/gen.rs, crates/reporting/src/error/expect.rs
That has a few advantages:
* We avoid a bunch of extra parameter-passing "noise", since the vast majority of formatting code doesn't need to care about this setting beyond just passing it to nested format calls.
* It aligns really well with the "global" nature of this setting, and makes it impossible to have bugs where e.g. one callsite forgets to pass the correct value to it's children - which would lead to parts of the tree not being migrated. If this is truly a global setting on Buf, that simply can't happen.
=> Move MigrationFlags from an argument on format* to a field on Buf

crates/compiler/can/src/constraint.rs, crates/compiler/can/src/copy.rs, crates/compiler/can/src/desugar.rs, crates/compiler/can/src/expr.rs, crates/compiler/can/src/traverse.rs, crates/compiler/can/tests/snapshots/test_suffixed__suffixed_tests__issue_7081.snap, crates/compiler/can/tests/test_can.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/fmt/src/expr.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/lower_params/src/lower.rs, crates/compiler/lower_params/src/type_error.rs, crates/compiler/mono/src/ir.rs, crates/compiler/parse/src/ast.rs, crates/compiler/parse/src/expr.rs, crates/compiler/parse/src/normalize.rs, crates/compiler/solve/src/solve.rs, crates/compiler/solve_problem/src/lib.rs, crates/language_server/src/analysis/tokens.rs, crates/reporting/src/error/type.rs
This uses the implementation of a proper `try` keyword in the recent https://github.com/roc-lang/roc/pull/7296 PR to implement the existing ? operator more robustly. We also specialize our error messages to display `try` vs. `?` accurately.
=> Use new try impl for ? operator

crates/compiler/can/src/desugar.rs
We were seeing parsing errors when using ? in bare statements. 
This allows statements in Task-world that are try statements. This is fixed in purity-inference, so just a stop-gap.
=> Fix ?-suffixed statements

crates/compiler/builtins/bitcode/src/utils.zig
`testing_roc_alloc` now allocates additional bytes so that  both the full allocation and the data are aligned at 16 bytes. `testing_roc_dealloc`now assumes these bytes are allocated, and aligned at 16 bytes, and deallocates them along with the data and the size
=> 7287 make testing roc alloc align the allocation

crates/docs/src/static/search.js
Search on `<module>.<entry>`
Searching on `<entry>` still works
Module is case insensitive:
=> Allow search on qualified names in docs

crates/cli/src/lib.rs
This is just inconvenient and does not make our api better. Leads to users thinking that roc does not optimize well. This also allows `roc dev --optimize` (which is the exact same as `roc --optimize`). If a user wants to do that, it should be fine.
This will all eventually be replaced by the larger cli rewrite.
=> Stop ignoring `--optimize` in `roc --optimize main.roc`

crates/compiler/specialize_types/src/mono_expr.rs, crates/compiler/specialize_types/src/mono_ir.rs, crates/compiler/specialize_types/src/mono_type.rs, crates/compiler/specialize_types/src/specialize_type.rs, crates/compiler/specialize_types/tests/helpers/mod.rs, crates/compiler/specialize_types/tests/specialize_structs.rs, crates/test_compile/src/help_specialize.rs
Currently, `to_mono_expr` returns `Nothing` when it encounters an empty record and it discards fields that are empty.
For simplicity, we decided to do this at a later stage, so this changes it to return a new `MonoExpr::Unit` variant.
=> Do not discard empty types in `specialize_types`

crates/cli/src/lib.rs, crates/compiler/gen_llvm/src/llvm/build.rs, crates/compiler/gen_llvm/src/llvm/expect.rs, crates/compiler/test_gen/src/helpers/llvm.rs
Decouple `--dev` from generating `dbg` or `expect`. Instead
1. Always generate `dbg` outputs no matter the mode.
2. Generate `expect` in all development and normal runs via `roc run main.roc` or `roc main.roc`.
Note: expect conditionals are always generated, we should really remove expect nodes during Can to avoid generating their conditionals. When we do, we can remove `LlvmBackendMode::BinaryWithExpect`. I was going to do that in this pr, but it felt complex to wire the state I want into Can. Also, want to land this to fix `dbg` on main.
=> Dbg and Expect Fixes and Improvements

ci/repl_basic_test/src/main.rs, crates/cli/src/main.rs, crates/compiler/build/src/program.rs, crates/compiler/load/build.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/tests/test_load.rs, crates/compiler/parse/src/parser.rs, crates/compiler/test_gen/src/helpers/llvm.rs, crates/compiler/test_mono/src/tests.rs, crates/compiler/uitest/src/mono.rs, crates/docs/src/lib.rs, crates/glue/src/load.rs, crates/language_server/src/analysis.rs, crates/language_server/src/convert.rs, crates/repl_eval/src/gen.rs, crates/valgrind_tests/src/lib.rs
This now makes the language server use the correct range when encountering a file load error.
So now parse errors won't all appear at the very top!
=> Add lsp range info for file load errors 

crates/language_server/src/analysis/analysed_doc.rs, crates/language_server/src/server.rs
Previously, the language server would crash on the following program when requesting completions with the cursor after `ç`:
```roc
module []
a = ç
```
=> Fix language server crash on UTF-8 completion

crates/compiler/alias_analysis/src/lib.rs
Surprisingly this actually increases perf of some benchmarks. My guess is that it fixes bugs during looping and thus reduces work. Specifically cFold and derive see minor gains ~1.5%; rBTreeCk sees a big gain ~4%. NQueens is the only benchmark that sees a lost at ~2%.
False interpreter also see a 0-5% perf improvement depending on the exact input. That said, the improvement was noisy.
ref #7367
=> limit morphic to trivial analysis to avoid inplace mutation bugs

crates/docs/src/static/styles.css
See #7299.
I did not add the flash discussed in the issue, so perhaps this PR will not close the issue.
@Anton-4  I like the Roc website because it is plain and simple. I think adding flashes, animations etc. will not improve the user experience. In my opinion the current highlighting does the job.
However, if you insist on adding some transition effects, I can probably do it in another PR, when I find another moment of free time. 
-------------------------
Designs that I also considered and found them inferior (but I'm open to discussion):
=> Highlight current :target entry name (#7299)

crates/docs/src/lib.rs, crates/docs/src/static/index.html, crates/docs/src/static/search.js, crates/docs/src/static/styles.css
~~Just a prototype~~
This is now being merged in earnest.
Desktop (Light/Dark mode side-by-side):
Desktop w/ Search (Light/Dark side-by-side):
Mobile(Dark mode):
Mobile w/ Sidebar open (Dark mode):
Mobile w/ Search open (Dark mode):
Mobile (light mode):
Mobile w/ Sidebar open (Light mode):
Mobile w/ Search open (Light mode):
=> New docs template

crates/compiler/builtins/roc/Task.roc, crates/compiler/module/src/symbol.rs
Add `Task.combine` to facilitate using record builders with Tasks while they're still part of Roc.
Also, put a message by the top of the `Task.batch` function that `Task.combine` is what should now be used for record builders.
=> Add Task.combine

crates/compiler/load_internal/src/file.rs, crates/compiler/load_internal/tests/test_load.rs
A package that depended on another package would hang forever because nothing registered the other package as a module to load like it would with an App.  This fixes that.
Closes #7407
=> #7407: Register package dependent packages

crates/repl_test/src/tests.rs, crates/roc_std/src/lib.rs
The intent of this change is to allow roc repl parse bare numbers using the 'e' exponent notation, eg '1e3' as a notation for '1000'. This was previously failing because '1e3' is internally parsed using the `RocDec::from_str` function which didn't support 'e' exponent notation.
Fixes #7351
=> RocDec::from_str accept 'e' exponent notation

crates/roc_std/src/lib.rs, crates/roc_std/src/roc_list.rs, crates/roc_std/src/roc_str.rs
Found this bug when working on basic-cli. If we write a read only refcount to something that is already read only, we risk trying to write to the static section of the binary that is write protected. This will crash. Use a conditional to avoid the write.
=> avoid writing to readonly refcounts

crates/compiler/builtins/bitcode/src/utils.zig
By avoiding atomic refcounting for any threadlocal variable, this greatly improves performance. Leads to the performance of threadlocal refcounting being only ~4% behind non-atomic refcounting. The old atomic refcounting could be as far as ~50% behind (though normally 10-20%).
This does not enable anything atomic related.
If we enable all forms of data loading (List.get, Box.unbox, loading recursive tag) to propagate the atomic flag, this should be a reasonable implementation for roc by default. With propagation, a platform would just set a list to atomic. On load, individual elements would also get set to atomic. We also should probably revert back to threadlocal if an atomic refcount drops to 1 (assuming it is safe, not sure it actually is).
=> Improve roc atomic refcounting by using first bit as threadlocal

crates/compiler/builtins/bitcode/src/str.zig, crates/compiler/builtins/bitcode/src/utils.zig
It is minorly debatable if this is the best behaviour, but if a user requests exactly `n` elements, we should trust that they only need `n` elements. This increases the chances of reallocating in-place instead of needing to copy all the data in the array. The only special case is requesting 1 more element. In the case of only requesting 1 element, we keep the old behaviour of growing in larger chunks. This behaviour now matches reserve and push_back in the folly library more fully. Though technically if you request reserving 1 in folly, it will only add 1 element of capacity. This doesn't work with current roc, cause we always reserve 1 before appending. I think this is fine though.
Some context from zulip: https://roc.zulipchat.com/#narrow/channel/302903-platform-development/topic/Should. …
=> if the user reserves a specific number of elements, trust them

BUILDING_FROM_SOURCE.md
We're now using LLVM 18.x and zig 0.13.0, but we still have references to 16 and 0.11.0 respectively.
=> Update versions in BUILDING_FROM_SOURCE

crates/linker/src/lib.rs, crates/linker/src/macho.rs
These are dependent on the CPU architecture and are 4KB for x86_64, and 16KB for aarch64.
=> linker/macho: fix load_align_constraint to correct page size values

crates/compiler/can/src/constraint.rs, crates/compiler/constrain/src/expr.rs, crates/compiler/constrain/src/module.rs, crates/compiler/constrain/src/pattern.rs, crates/compiler/load/tests/test_reporting.rs, crates/compiler/solve/src/deep_copy.rs, crates/compiler/solve/src/solve.rs, crates/compiler/uitest/tests/recursion/calls_result_in_unique_specializations.txt, crates/compiler/uitest/tests/recursion/constrain_recursive_annotation_independently_issue_5256.txt
Landing some simplifications ahead of a change to make named type variables where things are known to be a concrete type illegal.
See individual commits for details.
=> Minor simplifications to typechecker

www/build.sh, www/content/docs.md
Now that we are building the docs for `basic-cli` and hosting them in their own repo, we can stop building them in this repo. The 2 PRs to enable this in `basic-cli`:
[add 0.17.0 and 0.18.0 static docs](https://github.com/roc-lang/basic-cli/pull/307) [MERGED]
[add docs from latest commit](https://github.com/roc-lang/basic-cli/pull/306) [AWAITING APPROVAL]
This change will unblock merging of [changing all builtins to snake_case](https://github.com/roc-lang/roc/pull/7463)
=> Remove basic-cli docs gen from compiler

crates/compiler/mono/src/borrow.rs
Error message previously said "less arguments". However, the word "less" should be used for continuous (measured as a whole) quantities such as water, whereas "fewer" should be used for discreet (countable) quantities. Arguments are discreet, so this error message should say "fewer".
=> Fix grammatical error in monomorphization borrower error message

crates/linker/src/macho.rs
The general idea behind this changeset is that we actually do not want shift any of the loadable segments (and sections) in memory/file offsets. Instead we can ensure prior to generating host that we have enough room in the load commands section via linker flag `-headerpad <size>` which instructs the linker to leave `size` space between the end of the load commands and the start of the first section.
With this out of the way, my proposal is to pre-insert the maximum number of load commands that may be required, set their vmaddr/offset/size values to 0, and then prune in the surgical link stage. We will pre-insert those segment load commands after existing segment load commands but before `__LINKEDIT` segment load command to please Apple tooling (or die trying).
To illustrate this, here's …
=> linker/macho: redo bits of preprocessing host

crates/docs/src/static/search.js
This comes up when clicking a link that changes the URL fragment only, meaning the page doesn't transition and the box doesn't get closed that way. (Currently the search box just stays open and you have to close it manually.)
=> Close docs search box when an entry is selected

crates/cli/tests/benchmarks/AStar.roc, crates/cli/tests/benchmarks/closure.roc, crates/compiler/builtins/roc/Decode.roc, crates/compiler/builtins/roc/List.roc, crates/compiler/builtins/roc/Result.roc, crates/compiler/load_internal/tests/fixtures/build/app_with_deps/AStar.roc, crates/compiler/load_internal/tests/fixtures/build/module_with_deps/AStar.roc, crates/compiler/module/src/symbol.rs, crates/compiler/solve/tests/solve_expr.rs, crates/compiler/test_gen/src/gen_abilities.rs, crates/compiler/test_gen/src/gen_list.rs, crates/compiler/test_gen/src/gen_result.rs, crates/compiler/test_mono/generated/choose_correct_recursion_var_under_record.txt, crates/compiler/uitest/tests/ability/smoke/decoder.txt
=> Replace `Result.map` with `Result.map_ok`

crates/language_server/src/analysis/tokens.rs
Fixes panic:
```
thread 'main' panicked at crates/language_server/src/analysis/semantic_tokens.rs:31:13:
attempt to subtract with overflow
[Error - 11:21:33 AM] Request textDocument/semanticTokens/full failed.
Message: Any { .. }
Code: -32603
```
Panics because `analysis::semantic_tokens::arrange_semantic_tokens` expects token positions to always be increasing.
=> Fix: `AppHeader::iter_tokens` iterates `provides` twice

crates/compiler/fmt/src/expr.rs, crates/compiler/parse/src/normalize.rs, crates/compiler/test_syntax/tests/snapshots/pass/if_bang_then_bang_indented_else.expr.formatted.roc, crates/compiler/test_syntax/tests/snapshots/pass/if_bang_then_bang_indented_else.expr.result-ast, crates/compiler/test_syntax/tests/snapshots/pass/if_bang_then_bang_indented_else.expr.roc, crates/compiler/test_syntax/tests/snapshots/pass/if_then_weird_indent.expr.formatted.roc, crates/compiler/test_syntax/tests/test_fmt.rs, crates/compiler/test_syntax/tests/test_snapshots.rs
This is step 1 in removing the syntax all together. The formatter will now seemlessly migrate everyone to the usual if/then/else syntax. After everyone has had a chance to upgrade, we can then remove this from the parser (in a future PR).
=> Remove indented-else syntax from the formatter

crates/compiler/builtins/roc/Str.roc
This syntax doesn't exist yet, but we can revert this once it does! 😄
=> Have Str docs not use static dispatch (yet!)

crates/glue/writing_a_glue_plugin.md
This .md file documents everything I've learned about the in-memory layout of primitives, structs, and the seven different tag union types. This should be helpful for anyone looking to write a glue plugin themselves. There are a few TODOs left scattered around for things I either haven't figured out or lack context on.
=> Add documentation for glue shape memory layouts

crates/cli/tests/cli_tests.rs, crates/cli/tests/test-projects/issue7461.roc, crates/compiler/mono/src/drop_specialization.rs, crates/compiler/test_mono/generated/rb_tree_fbip.txt
=> Fixed drop specialization for join point bodies

crates/cli/tests/benchmarks/Base64/Encode.roc
I believe that when this test was created over 4 years ago, Encode had its own U8 or something. However, if anyone knows what this comment intended to say, please correct me!
=> Correct comment about long-removed Encode.unsignedInt8

.github/workflows/fuzzer.yml, crates/compiler/fmt/src/expr.rs
This is currently causing a bunch of fuzzing noise in main. Also added a comment to clarify this behavior is intended to be short-lived.
=> Suppress TrySuffix movement around PncApply unless --migrate is passed

www/InteractiveExample.roc, www/build-dev-local.sh, www/content/docs.md, www/content/index.md, www/content/platforms.md, www/content/tutorial.md, www/main.roc, www/public/site.css
=> Update homepage and tutorial

crates/docs/src/static/styles.css
Commit a3762f60ad1dbac3e40faa3db8f104bbd92d38d9 marked the current (:target) entry using background color. But then 11e736f3e8993ee39a7733bcb99c79c04a8857e5 set the background color for all entries. Thus we need another way to highlight the entry pointed at by the URL fragment.
See https://github.com/roc-lang/roc/pull/7377#issuecomment-2565529772.
Closes #7299 (see https://github.com/roc-lang/roc/issues/7299#issuecomment-2567111453).
Screenshots:
=> Mark :target entry using border

BUILDING_FROM_SOURCE.md
=> Add macos build tip

.github/workflows/ci_manager.yml, .github/workflows/ci_zig.yml, build.zig, src/fuzz/cli.zig, src/main.zig
1. Switch fuzzer to ReleaseSafe
2. Update not on fuzzer needing llvm
3. Use c allocator as our gpa
4. Use musl on linux.
5. Just `zig build test` in CI.
=> Minor cleanup zig

.github/workflows/ci_manager.yml
The filter system matches if any filter matches.
This meant that the old `other_than_zig` was always matching everything.
~~Changed to simpler system where we only check for zig changes. On zig changes we run zig, otherwise, we run the old compiler.~~
Changed to two separate filter. For the filter with negatives, everything has to match. This leads to the negatives properly removing files. For the zig filter, any one piece has to match.
=> Fix the filter

.github/workflows/ci_manager.yml
Turns out that `predicate-quantifier` is v3 syntax of `dorny/paths-filter`, not v2. Update to v3 for it to work right.
=> Fix filter try 2

.github/workflows/ci_zig.yml
This will fail until we get our tree together. Just making a PR so we make sure to circle back to this.
=> enable zig ast check and target only the new compiler

src/base.zig, src/base/Ident.zig, src/base/Module.zig, src/base/ModuleEnv.zig, src/base/ModuleIdent.zig, src/build/lift_functions/IR.zig, src/build/lower_statements/IR.zig, src/build/reference_count/IR.zig, src/build/specialize_functions/IR.zig, src/build/specialize_types/IR.zig, src/check/canonicalize.zig, src/check/canonicalize/IR.zig, src/check/canonicalize/Scope.zig
Because of our new module + ident resolution mechanism, all idents within a module have unique IDs, even when imported from other modules. We now store which module exported which ident both in the `Module.Store` and the `Ident.Store` for a 2-way relationship, meaning we always know the exporting module of an ident given its `Idx`, meaning a pairing of `Module.Idx` and `Ident.Idx` is no longer needed.
=> Remove redundant ModuleIdent

src/base/Ident.zig, src/build/lift_functions/IR.zig, src/build/solve_functions.zig, src/collections/interner/IdentName.zig, src/collections/safe_list.zig, src/test.zig
When starting work on the function solve step of the compile, I immediately ran into several compile issues from various base functions when setting up a test. This MR fixes those compile issues. I went with my best guess for each issue, happy to change anything that's wrong - I'm far from a Zig expert.
Also, when running `zig build test`, tests in `src/build/solve_functions.zig` were not run unless I added that path to `src/test.zig`. I haven't used Zig in a while, so I'm not sure if there are some semantics I don't understand about `refAllDeclsRecursive`. Happy to revert that line if needed.
=> Fix various zig errors in base/collections

build.zig, build.zig.zon
Use an optional dependency to avoid downloading AFL when it isn't needed.
Only download dep and build AFL + fuzzers when `-Dfuzz` is added.
Also, only build afl for native unix targets (it can't cross compile and doesn't support windows).
=> Improve fuzzing build script

flake.nix, src/base/Ident.zig, src/base/Module.zig, src/base/ModuleEnv.zig, src/base/Package.zig, src/base/Region.zig, src/build/lift_functions.zig, src/build/lift_functions/IR.zig, src/build/lower_statements.zig, src/build/lower_statements/IR.zig, src/build/reference_count.zig, src/build/reference_count/IR.zig, src/build/solve_functions.zig, src/build/specialize_functions.zig, src/build/specialize_functions/IR.zig, src/build/specialize_types.zig, src/build/specialize_types/IR.zig, src/check/canonicalize.zig, src/check/canonicalize/IR.zig, src/check/canonicalize/Scope.zig, src/check/parse/IR.zig, src/check/resolve_imports.zig, src/check/resolve_imports/IR.zig, src/collections/interner/FieldName.zig, src/collections/interner/IdentName.zig, src/collections/interner/StringLiteral.zig, src/collections/interner/TagName.zig, src/collections/safe_list.zig, src/coordinate.zig, src/test.zig
Based on Brendan's comment [here](https://github.com/roc-lang/roc/pull/7600#discussion_r1950140222), this PR manually lists most compiler stagings & other files in `test.zig`, then resolves various errors.
There was a weird issue causing tests to pass, but `zig build test` to fail around public structs being re-exported. If you had a few files defined like:
```zig
// lower_statements/IR.zig
pub const Self = @This();
// lower_statements.zig
const lower_statements = @This();
pub const IR = @import("./lower_statements/IR.zig");
```
Then running tests fail with a very weird error:
```
Build Summary: 2/5 steps succeeded; 1 failed
test transitive failure
└─ run test transitive failure
└─ zig test Debug native-native-musl 1 errors
└─ run gencat (gencat.bin.z) cached
└─ zig build-exe gencat Debug …
```
=> Manually list files in test.zig and resolve errs

.github/workflows/ci_zig.yml, build.zig
These steps are used in CI for fast feedback on code.
On top of that, the `check` step can be used with `zls` for better results: https://kristoff.it/blog/improving-your-zls-experience/
The steps also work with `-Dfuzz` to check the repro exe is valid when changing other targets.
Also did some generic cleanup of the build script.
=> add proper check and check-fmt step

src/base/Ident.zig, src/base/Module.zig, src/base/ModuleEnv.zig, src/base/StringLiteral.zig, src/build/solve_functions.zig, src/check/canonicalize/IR.zig, src/check/canonicalize/Scope.zig, src/check/parse.zig, src/check/parse/tokenize.zig, src/collections/SmallStringInterner.zig, src/collections/utils.zig, src/fmt.zig
This PR ended up mixing two things kinda unintentionally.
Firstly, it improves the small string interner.
The interner uses an unmanaged hash map with context to store deduplicated strings. Since the strings are all meant to be small, instead of storing lengths, it just null terminates the strings. Also, removed some extra mappins that are not needed to be in the small string interner. It only deals with storing unique small strings and giving them an index
As part of the above update, I changed the interner to use a general purpose allocator instead of an arena.
That change led to a much larger change of following the error trailing and updating many things from an arena to a general purpose allocator. In general, roc will actually use very few arenas in the default path. Arenas are only …
=> Fix up SmallStringInterner and use GPA

src/check/parse/IR.zig, src/check/parse/Parser.zig, src/check/parse/tokenize.zig, src/fmt.zig
And Expect, Crash, and Return statements too....
And Static Dispatch-style dot access.
=> [zig]: Parsing Records and Tuples and BinOps

src/check/parse/IR.zig, src/check/parse/Parser.zig, src/fmt.zig
This syntax is deprecated.
Closes #7451 
Closes #7440
=> [zig]: Remove `*` from types and add `...` expression

build.zig, src/snapshot.zig, src/snapshots/001.txt, src/snapshots/002.txt, src/snapshots/some_folder/002.txt, src/test.zig
Adds a snapshot tool that iterates through all the snapshot text files in `src/snapshots/*.txt` and re-generates the AST/IR's for each compiler stage.
```
$ zig build snapshot
info: processed 2 snapshots in 1ms.
$ zig build snapshot -- --verbose
info: src/snapshots/002.txt
info: src/snapshots/001.txt
info: processed 2 snapshots in 2ms.
```
Here is an example of a snapshot file.
```
~~~META
description=Basic example to develop the snapshot methodology
~~~SOURCE
module [foo, bar]
foo = "one"
bar = "two"
~~~PARSE
(file
(header
'foo'
'bar')
(decl
(ident
'foo')
(string_part))
(decl
(ident
'bar')
(string_part)))
```
=> Initial snapshot testing tool

build.zig, build.zig.zon
This enables fuzzing on linux. Users need to manually install `afl++`, but then they can use `-Dsystem-afl`.
Hopefully a proper fix to zig afl can happen at some point, but until then, this is good enough.
=> allow using system installed AFLPlusPlus

build.zig.zon
afl-cc can pick the wrong defaults, new version uses afl-clang-lto
=> update zig-afl-kit again.

build.zig.zon
AFL_CC_COMPILER is inconsistent base on exact afl version and exact OS version. Leave it to the end users.
=> update zig-afl-kit again again.

src/base/sexpr.zig, src/check/parse.zig, src/check/parse/IR.zig, src/snapshots/001.txt, src/snapshots/some_folder/002.txt
This should make the snapshots a bit more compact and easy to read
=> Always format sexprs with three or fewer elements on one line

build.zig, src/fuzz-repro.zig
Allow reproducing with a base64 input on the commandline. Also make verbosity of the script a toggle.
As part of this cleanup the `-Dfuzz` arg.
`zig build repro-x -- ...` will run a repro with args (no `-Dfuzz` needed). `zig build fuzz-x -Dfuzz` will still build a fuzzer.
=> Improve fuzzing reproductions

src/check/parse/Parser.zig
Just a bug caught by the fuzzer. Parser was hanging. It is preferably to crash with a message instead of looping forever.
=> [parser] crashing is better than looping forever

src/check/parse/IR.zig, src/main.zig
1. Get rid of std.log. We want to directly write our output io and not use a logger framework
2. Make the formatter fail and exit early on parse failures.
=> [cli] minor cleanup

src/check/parse/Parser.zig
This is another case where the parser hangs.
Convert it to a crash instead.
repro: `zig build repro-parse -- -b cC4w -v`
text: `p.0`
=> [parser] crash instead of hang

.github/workflows/ci_zig.yml, build.zig, build.zig.zon, src/base.zig, src/build/lift_functions/IR.zig, src/build/specialize_functions/IR.zig, src/build/specialize_types/IR.zig, src/check/canonicalize/Scope.zig, src/check/parse/IR.zig, src/check/parse/Parser.zig, src/check/parse/tokenize.zig, src/cli.zig, src/coordinate.zig, src/coordinate/Filesystem.zig, src/coordinate/ModuleGraph.zig, src/fuzz-parse.zig, src/snapshot.zig, src/types.zig
Note, this is still using stale llvm. But that doesn't actually matter:
1. We don't actually use llvm yet
2. Due to eventually generating bitcode directly, llvm version is not strictly tied to zig.
Will update llvm version in a follow up. Just waiting on https://github.com/ziglang/zig-bootstrap to update to 0.14.0 (I could do it, but as mentioned above, no rush)
=> Update to zig 0.14.0

src/README.md, src/check/parse.zig, src/check/parse/IR.zig, src/check/parse/Parser.zig, src/check/parse/tokenize.zig, src/fmt.zig, src/snapshots/001.txt, src/snapshots/003.txt, src/snapshots/add_var_with_spaces.txt, src/snapshots/if_then_else.txt, src/snapshots/some_folder/002.txt, src/snapshots/type_declarations.txt
This is ready for review and merging
=> [zig] Parser: Add support for basic import exposes

src/check/parse/tokenize.zig
As discussed here: https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/zig.20compiler.20-.20spike/near/504579627
I assume in the long term, support will be added to the parser to notice when double opBar or opAmpersand should be consider an `and` or `or`. Then the formatter will fix things up.
For now, double bar is always a lambda and double ampersand is invalid.
=> Remove `||` and `&&` from tokenizer

src/check/parse/IR.zig, src/check/parse/Parser.zig, src/fmt.zig
Adds the Region struct to all nodes.  Needed for error reporting, and making formatting work correctly.
=> [zig] Parser: Add Region to node

build.zig, build.zig.zon
Fixes fuzzing on macos.
Since 0.14.0, macos fuzzing has not been coverage guided. It has just been random.
=> Have zig directly generating fuzzing instrumentation

src/check/parse/tokenize.zig, src/snapshots/fuzz_crash/fuzz_crash_014.txt
Minor tokenizer cleanup to deal with cases where there are no digits in a number. For example `0b` is invalid without `0b010`. It is required that the prefix be followed by at least one digit. Same with exponents. `7e` is invalid without `7e22`.
Also moved a few functions under `Token.Tag` so that they can be used directly (ex. `token.tag.isKeyword()`)
=> [Tokenizer] create malformed nodes for numbers with no digits

src/check/parse/tokenize.zig, src/snapshots/fuzz_crash/fuzz_crash_015.txt
With the old printing, ints would sometimes turn into floats after print. For example `0o0.0` would reprint as `111.1`.
Instead, for any int 3 characters or longer, we always print with the base. This ensures it will tokenize as an int and only an int. The reprint above becomes `0x0.0` which tokenizes the same.
All 1 and 2 character ints should still be fine.
They are guaranteed to only be numbers or to already be invalid. `0b` is invalid due to missing the digits.
Also adds a handful of doc comments.
=> [tokenizer] fix int printing

src/check/parse/Parser.zig, src/snapshots/fuzz_crash/fuzz_crash_016.txt
Missed stopping on EndOfFile.
Leads to running a function expecting valid input and crashing.
=> [parser] Fix crash found by fuzzer

.github/workflows/ci_zig.yml, .gitignore, build.zig, src/README.md
This gets us incremental compilation and a fast feedback loop. Instead of a `check` step, this depends on `-Dno-bin`.
Note, we should look into [per-build config](https://zigtools.org/zls/configure/per-build/) and switching back to simply `check` at some point. Currently that doesn't seem to play nice with `-fincremental`.
=> Enable incremental compilation

src/collections/utils.zig, src/coordinate/Filesystem.zig, src/fmt.zig, src/main.zig
Also supports formatting multiple passed in args.
Also prints the overall execution time.
=> Expand roc format to support directories

src/fmt.zig, src/main.zig
Just wires an arena for args and misc tiny allocations. Leads to ~4% perf improvement when formatting 100 files on my x86 machine (slower cache hierachy). This is likely due to skipping allocating small strings for the paths when querying the directory.
=> Use an arena for tiny allocations

src/fmt.zig, src/main.zig
Also improve formatter output.
Now counts total successes and failures.
Prints errors from failures
Print final success count, failure count, and execution time
This is a large perf gain ~8% on my x86 machine (slow memory hierarchy).
Also, filed a issue to the zig compiler about this: https://github.com/ziglang/zig/issues/23274
=> Allocate only once when loading files

src/base/Ident.zig, src/base/ModuleEnv.zig, src/base/StringLiteral.zig, src/check/parse/IR.zig, src/check/parse/Parser.zig, src/check/parse/tokenize.zig, src/collections/SmallStringInterner.zig, src/collections/safe_list.zig
Switches over to using `initCapacity` for many types. Likely in the long term, everything should always use `initCapacity`. The sizes are all guesses currently, but they have meaningful performance impacts for limitted overhead. Once we have a larger corpus, would be great to tune.
This is another 5-10% perf gain on top of everything else.
=> Add default capacities

build.zig, src/README.profiling.md, src/base/StringLiteral.zig, src/collections/utils.zig, src/main.zig, src/tracy-shutdown.cpp, src/tracy.zig
TRACY_NO_EXIT is used to force tracy to wait for the profiler to finish collecting data before shutting down. Sadly, it doesn't work on macos.
As a workaround, directly call into the tracy profiler on exit. Request shutdown (which will start flushing data) and wait for shutdown to complete. This makes the equivalent of TRACY_NO_EXIT the default.
Not, this only works on clean shutdown through `main` or `fatal`. Any other shutdown will miss this codepath and exit before tracy fully dumps data.
=> [tracy] wait for shutdown

crates/compiler/builtins/bitcode/src/utils.zig
This unlocks new use cases like multithreading. Hopefully can unblock background threads in basic webserver. Simplifies multithreaded use cases in general.
This is just direct use of atomic refcounting always. Surprisingly, atomtic refcounts are pretty fast and this generally is not a perf hit. That said, deeply nested tags (like cons lists) and other worst case scenarios can see major pain from this. Still like worth just tell people to avoid crazy data schemes with tons of pointer chasing. I would guess that most users won't really notice this except in very specific benchmarks. If this does lead to significant perf issue, we can roll back or look into a few other optimizations. This also is likely to disproportionately hurt older and lower power hardware.
=> switch roc to atomic refcounts

README.md
Heya! Just a tiny change in the README 😅 
Previously, this linked to the templated docs file on GitHub. I believe the website rendering is so much nicer and it's in line with what's done for other links.
Thanks for working on Roc, you all. Can't wait to use it some when I find a chance.
=> README: link to rendered FAQs

src/base/ModuleEnv.zig, src/check/parse/IR.zig, src/check/parse/Parser.zig, src/check/parse/tokenize.zig
Based on a discussion with Richard (quite a while ago at this point), lets default to over-allocating our array sizes. This is in hopes that the normal flow never reallocates. We really don't use that much memory in total and this enables the compiler to see solid speed gains. Until we find a reason not to or get better heuristics, lets use memory to save time.
Also removes and extraneous debug print and updates one case of `initWithCapacity` to `initCapacity`
=> Increase default capacities

src/check/parse/tokenize.zig
resolves #6928
- Should it store some state while iterating through the characters, and combine multiple consecutive non-printable chars into a single diagnostic?
- Is there anything else I need to do to implement a new diagnostic type other than just adding a new enum variant?
- Are there any display concerns with pointing the diagnostic at solely non-printable chars? Are they escaped when displayed to the user? I wasn't able to figure out how the diagnostics get presented to the user, I just used the `repro-tokenize` binary to ensure that my diagnostic was received by the tokenizer.
=> add diagnostic for nonprintable unicode in str literals

crates/repl_expect/src/app.rs
The speed trade-off for the old compiler has changed, this assert is highly preferable to getting a Segmentation fault.
This change was done due to [#beginners > Segmentation fault during exercism tests for phone-number @ 💬](https://roc.zulipchat.com/#narrow/channel/231634-beginners/topic/Segmentation.20fault.20during.20exercism.20tests.20for.20phone-number/near/515392897).
=> Change assert

crates/cli/src/lib.rs
`roc build` used to try to build roc code even if there were errors, but this easily produces panics (like in #7779). Given that we're making a new compiler, it makes sense to change this "setting" in the old one for user friendliness.
=> change `roc build` to build only if check passes

src/check/parse/IR.zig, src/check/parse/Parser.zig, src/fmt.zig
Fixes a common source of fuzzer crashes, and just better for code health.  Motivated by [#compiler development > zig compiler - fuzzing @ 💬](https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/zig.20compiler.20-.20fuzzing/near/518841712)
=> fix: Remove parse panics and unreachables

src/check/parse/IR.zig, src/check/parse/Parser.zig, src/check/parse/tokenize.zig, src/fmt.zig, src/snapshots/fuzz_crash/fuzz_crash_018.txt
Advance can advance more than one position.
It will skip newlines.
As such, we need to get the correct offset here.
=> Deal with bad offset for identifier

.github/workflows/ci_zig.yml
This is bloating our cache storage and occasionally leads to CI failures. Instead, just cache the zig executable, but rebuild roc from scratch.
=> Stop caching the zig cache

src/snapshot.zig
This means that if the snapshot testing panics, we don't end up with a partially-written (e.g. corrupted) snapshot
=> Buffer snapshot data instead of writing directly to the file

src/check/check_types/occurs.zig, src/check/check_types/unify.zig, src/test.zig, src/types/store.zig, src/types/types.zig
This PR implements the `occurs` check for type variables. This means, for a given type variable:
* Resolve it to its type (ie follow `redirect`s until we get a concrete type)
* Recursively unwrap all subtype variables for the type (ie all tags in tag unions, record fields in records, etc)
* Check if we run into a variable we've seen already before
This is the 1st step in the larger project of supporting recursive types in the type system, but only for nominal types – [as outlined here](https://github.com/roc-lang/rfcs/blob/ayaz/compile-with-lambda-sets/0101-compiling-recursive-types.md#1-recursive-types-must-have-a-explicit-point-of-recursion). This check is not yet used anywhere, that will come in a follow-up PR.
> There has been some discussion in Zulip recently around if it's possible …
=> Implement Occurs Check

src/base/ModuleEnv.zig, src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/check_types.zig, src/check/check_types/occurs.zig, src/check/check_types/unify.zig, src/coordinate.zig, src/coordinate/ModuleGraph.zig, src/snapshot.zig, src/types/store.zig
This PR makes `ModuleEnv` own the type store (instead of the other way around, which is what we currently have), as discussed in Zulip. 
This was fairly straightforward with the only exception of `coordinate.zig`. Previously, type stores were created for each module through the `ModuleWork` abstraction. I'm not really sure the intended semantics of `ModuleWork`, so I'm not sure how to port this, and I've left it as a `TODO` for now. I'm happy to make whatever change is necessary, if anyone could give me some direction 😄
=> Make ModuleEnv own types.Store

crates/compiler/can/src/abilities.rs, crates/compiler/serialize/src/bytes.rs
Fixed a warning that shows when using rust 1.87: `unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned...`. This could solve some of the flaky builds we've been seeing on macos :crossed_fingers:
=> fix undefined behavior warning

src/check/check_types/occurs.zig, src/check/check_types/unify.zig, src/test.zig
This MR updates `unify` to add a recursion check.
The strategy here is to track the depth of recursion in `unify`, and if we exceed a certain depth (currently 8), we do a full occur check. The thinking here is that the vast majority of types are not recursive and so should not pay the cost of running the occurs check unless absolutely necessary. 
The potential drawback to this strategy is that simple recursive types, such as `A := (Str, A)` will loop several times before we detect that it is infinite. However, given that error like this are fairly uncommon, this price seems reasonable to pay. 
Additionally, this MR reworks `unify`s error strategy. Since errors in zig cannot include payloads, `unify` now captures error-related data is by setting a field in `Scratch` _before_ throwing. Then …
=> Add recursion check to unify

src/builtins/dec.zig
I added a simple sqrt to Dec and a few tests for it. In future PRs, we can work on a high perf one. This is only a starting point.
The current sqrt uses the float sqrt of Zig.
See also: https://roc.zulipchat.com/#narrow/channel/316715-contributing/topic/Roc.20Project.20Ideas/with/523159458
Related to: https://github.com/roc-lang/roc/issues/5831
=> Add simple sqrt to Dec

src/base/ModuleEnv.zig, src/check/canonicalize/NodeStore.zig, src/check/check_types.zig, src/check/check_types/problem.zig, src/check/check_types/unify.zig, src/coordinate_simple.zig, src/snapshot.zig
This MR updates the type problem struct to not store a `region`. Instead, at the time of error message generation, we convert the `Var` to a `CIR.Node.Idx` and lookup the region from there.
=> Don't store region in type problem

src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/NodeStore.zig, src/check/check_types.zig, src/snapshots/binops.md, src/snapshots/can_import_comprehensive.md, src/snapshots/expr/record_field_update.md, src/snapshots/expr/tuple.md, src/snapshots/expr/tuple_comprehensive.md, src/snapshots/expr/tuple_patterns.md, src/snapshots/records/record_access_function_call.md, src/snapshots/records/record_different_fields_error.md, src/snapshots/records/record_different_fields_reserved_error.md, src/snapshots/records/record_extension_update.md, src/snapshots/syntax_grab_bag.md, src/snapshots/type_alias_parameterized.md, src/snapshots/type_alias_simple.md, src/snapshots/type_annotation_basic.md, src/snapshots/type_same_var_multiple_uses.md, src/snapshots/type_two_variables.md, src/snapshots/type_var_multiple.md, src/snapshots/type_var_namespace.md, src/types/store.zig
This MR adds basic type solving for tuple exprs.
It also removes the sub `tuple_var` field in favor of using the `Expr`'s `Idx` as the type variable for the whole node, as mentioned [here](https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/zig.20compiler.20-.20.60var.60.20fields.20on.20Can.20structs/with/525909297) in Zulip. Depending on what shakes out from that thread, I can update this PR to match!
=> Implement tuple expr type solving

src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/Node.zig, src/check/canonicalize/NodeStore.zig, src/check/check_types/literal_size_test.zig, src/snapshots/records/function_record_parameter.md, src/snapshots/records/function_record_parameter_rest.md, src/snapshots/records/module_record_destructure.md, src/snapshots/records/pattern_function_parameter.md
Note -- I used temporary change in the parser to validate this which I haven't included here as it's not the intended solution. So we only supported a few record destructure patterns, like lambda args
=> Implement record de-structures

src/fuzz-canonicalize.zig
=> print input for fuzz-canonicalize

src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/NodeStore.zig, src/check/canonicalize/test/frac_test.zig, src/check/canonicalize/test/int_test.zig, src/check/check_types.zig, src/coordinate/ModuleGraph.zig, src/coordinate_simple.zig, src/snapshot.zig, src/snapshots/fuzz_crash/fuzz_crash_019.md, src/snapshots/fuzz_crash/fuzz_crash_020.md, src/snapshots/fuzz_crash/fuzz_crash_022.md, src/snapshots/fuzz_crash/fuzz_crash_023.md, src/snapshots/if_then_else.md, src/snapshots/if_then_else_1.md, src/snapshots/if_then_else_11.md, src/snapshots/if_then_else_13.md, src/snapshots/if_then_else_15.md, src/snapshots/if_then_else_3.md, src/snapshots/if_then_else_5.md, src/snapshots/if_then_else_7.md, src/snapshots/if_then_else_9.md, src/snapshots/if_then_else_if_chain.md, src/snapshots/syntax_grab_bag.md, src/snapshots/type_alias_simple.md, src/types/store.zig
This saves some memory and also removes the need for using `predictNodeIndex` with these.
=> Remove branch_var from if_then_else

src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/Diagnostic.zig, src/check/canonicalize/Node.zig, src/check/canonicalize/NodeStore.zig, src/check/canonicalize/Scope.zig, src/check/canonicalize/test/node_store_test.zig, src/check/check_types/occurs.zig, src/check/check_types/snapshot.zig, src/check/check_types/unify.zig, src/layout/store.zig, src/types/store.zig, src/types/types.zig, src/types/writers.zig
Gave it the same size reduction treatment as `Alias` in https://github.com/roc-lang/roc/pull/7901
=> Rename custom type to nominal type and reduce its size

src/check/canonicalize/CIR.zig, src/check/canonicalize/Node.zig, src/check/canonicalize/NodeStore.zig, src/check/canonicalize/test/node_store_test.zig, src/snapshots/binop_omnibus__single__no_spaces.md, src/snapshots/binop_omnibus__singleline.md, src/snapshots/binops.md, src/snapshots/expr/tag_simple.md, src/snapshots/expr/tag_with_payload.md, src/snapshots/expr/tuple.md, src/snapshots/expr/tuple_comprehensive.md, src/snapshots/expr/tuple_patterns.md, src/snapshots/expr/tuple_simple_unbound.md, src/snapshots/fuzz_crash/fuzz_crash_019.md, src/snapshots/fuzz_crash/fuzz_crash_020.md, src/snapshots/fuzz_crash/fuzz_crash_023.md, src/snapshots/if_then_else.md, src/snapshots/if_then_else_3.md, src/snapshots/if_then_else_5.md, src/snapshots/primitive/expr_tag.md, src/snapshots/records/record_different_fields_error.md, src/snapshots/records/record_with_complex_types.md, src/snapshots/syntax_grab_bag.md, src/snapshots/type_alias_decl.md, src/snapshots/type_app_complex_nested.md
Adding unit tests to ensure the variants roundtrip with the correct data to/from the NodeStore, includes `comptime` checks to mitigate future regressions if we add/remove variants in future.   
Implement missing functionality for the NodeStore to ensure 100% coverage.
=> Unit Tests for `CIR.NodeStore`

src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/NodeStore.zig, src/check/check_types.zig, src/check/check_types/problem.zig, src/check/check_types/unify.zig, src/coordinate_simple.zig, src/snapshot.zig, src/snapshots/fuzz_crash/fuzz_crash_019.md, src/snapshots/fuzz_crash/fuzz_crash_020.md, src/snapshots/if_then_else/if_then_else_9.md, src/snapshots/if_then_else/if_then_else_simple_file.md, src/snapshots/match_expr/literal_patterns.md, src/snapshots/nominal/nominal_tag_payload_two.md, src/snapshots/plume_package/Color.md
This PR improve how we set type errors during type checking to be more ergonomic.
* Reduce number of `Problem` variants
* Add a nullable `details` field to `TypeMismatch`, which optionally contains contextual information for better errors
* Remove region from `incompatible_list_elements`
* Make `problems.ReportBuilder` struct with common args, to improve ergonomics
=> Improve Type Error API

README.md
Hi, I have just started learning roc-lang.
I noticed that the tutorial link in README was not working, so I fixed it.
Old URL:
=> Fix tutorial link in README.md

src/check/canonicalize.zig, src/check/check_types.zig, src/check/check_types/unify.zig, src/check/parse/Parser.zig, src/coordinate_simple.zig, src/main.zig
Just trying to trace all the core things. This gives us a much clearer view of performance and where time is spent. As long as allocation tracking is off, this tracing should be light weight enough to be reasonable.
=> add tracing to core roc functions

src/types.zig
It enables faster compilation and is great.
In general, usingnamespace is best avoided anyway.
=> fix '-fincremental'

src/check/canonicalize.zig, src/check/canonicalize/test/frac_test.zig, src/check/canonicalize/test/int_test.zig, src/coordinate_simple.zig, src/snapshot.zig
Set it as this function casing by using camel case for all functions
=> Standardize function names to use  camelCase in `canonicalize.zig`

src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/NodeStore.zig, src/check/canonicalize/TypeAnnotation.zig, src/check/canonicalize/test/node_store_test.zig, src/snapshots/rigid_var_no_instantiation_error.md, src/snapshots/test_tuple_instantiation_crash.md, src/snapshots/type_two_variables.md, src/snapshots/type_var_multiple.md
* Canonicalized tuple type annotations
* Remove ad-hoc allocations in Can by moving into reusable scratch buffers
=> Canonicalize tuple type annotations & reduce allocations

src/snapshot.zig
This avoids ~35-40% overhead in the snapshot process, and is (as of yet) rarely used, especially in CI.
=> Add --html flag to opt-in to html snapshot generation

build.zig
On running `zig build test` you used to get no permanent output on success, it now prints "All tests passed!"
=> print tests passed msg

src/cache/CacheModule.zig, src/fs/Filesystem.zig
```
$ zig build roc -Dtarget=wasm32-wasi -Doptimize=ReleaseSmall
warning: Cross compilation does not support fuzzing (Only building repro executables)
$ ls -hl ./zig-out/bin/roc.wasm
-rwxr--r--@ 1 luke  staff   529K 10 Jul 14:28 ./zig-out/bin/roc.wasm
$ wasmtime --dir=. zig-out/bin/roc.wasm check test.roc
No errors found in 0.4 ms for test.roc
```
=> Add support for WASI

src/check/parse/AST.zig, src/coordinate_simple.zig, src/snapshot.zig
This improved the runtime for my `New-List-Cutoff_10MB.roc` from 23s down to 7.8s before it crashes, and reduces the memory used by approximately x30.
=> Re-use `line_starts` to save on memory

src/check/parse/AST.zig, src/check/parse/Parser.zig, src/snapshots/match_expr/wrong_arrow.md
When the wrong arrow is found on a match branch (`->` instead of `=>`), parse it but push a diagnostic error.
***
This comes after https://roc.zulipchat.com/#narrow/channel/395097-compiler-development/topic/List.20destructure.20syntax/with/527986682 and I decided to implement a simple change to check the new codebase.
I find it useful as someone coming from the old syntax, but feel free to reject it if it is not wanted or if it impacts other concurrent changes.
=> Accept both arrows in match branches but push diagnostic if not fat arrow

src/base.zig, src/base/parallel.zig, src/snapshot.zig
- **Extract commonality in snapshot tests between single-file and multi-file snapshots**
- **Implement multithreading for snapshot generation**
=> Implement multithreading for snapshot generation

src/check/canonicalize.zig, src/check/check_types.zig, src/check/check_types/copy_import.zig, src/check/check_types/instantiate.zig, src/check/check_types/let_polymorphism_test.zig, src/check/check_types/occurs.zig, src/check/check_types/snapshot.zig, src/check/check_types/test/nominal_type_origin_test.zig, src/check/check_types/unify.zig, src/collections.zig, src/collections/safe_list.zig, src/layout/layout.zig, src/layout/store_test.zig, src/types/store.zig, src/types/types.zig
This PR:
* Modifies the `SafeRange` data type to store `start` and `count` instead of `start` and `end`
* Add additional functionality to `SafeRange`, like `end()` and `dropFirstElem()`
* Add Range helper function to `SafeList`, like `rangeToEnd(start: u32)`
* Make `SafeList` & `SafeMultiList`'s `len()` return `u32`
* Updates everything in the types store to use `SafeRange` (previous some used `Span`)
* Fixes some bugs in instantiate and copy_import
No snapshot output was modified with the above changes
=> SafeList Tweaks + Range Refactor

src/check/canonicalize.zig, src/check/check_types.zig, src/check/check_types/copy_import.zig, src/check/check_types/cross_module_test.zig, src/check/check_types/instantiate.zig, src/check/check_types/let_polymorphism_test.zig, src/check/check_types/occurs.zig, src/check/check_types/snapshot.zig, src/check/check_types/test/nominal_type_origin_test.zig, src/check/check_types/unify.zig, src/layout/store.zig, src/types/store.zig, src/types/test_rigid_instantiation.zig, src/types/writers.zig
Update the types store to allocate a single list for all nested variables. That is, instead of having a `tuple_elems` array, a `func_args` array, etc that are all `SafeList(Var)`s, instead use a single `vars: SafeList(Var)` array.
There was no real benefit to having these things split out into separate arrays and joining them into one has the benefits:
* Less allocations (though about the same total memory used)
* Easier to (de)serialize in caching layer
Also does conceptually the same thing for `types/snapshots.zig`.
No snapshots were modified as part of this change.
=> Update types/snapshot store to allocate less

src/base/Ident.zig, src/base/ModuleEnv.zig, src/base/StringLiteral.zig, src/check/canonicalize.zig, src/check/check_types.zig, src/check/parse.zig, src/collections/SmallStringInterner.zig
This makes it so that in debug builds, we "freeze" interns at the end of canonicalization. From then on, any attempts to insert into it cause a panic in debug builds.
The point of this is to maintain the invariant that, after canonicalization is done, interns become readonly; we never modify them again. This in turn means we can get away with serializing/deserializing only the `id -> string` array and not the `string -> id` hash map portion of the interner, which is great because we would very much like to avoid serializing hash maps to/from disk if we can avoid it.
=> Freeze interns

src/base/ModuleEnv.zig, src/bench.zig, src/cache/CacheManager.zig, src/cache/CacheModule.zig, src/check/canonicalize.zig, src/check/canonicalize/CIR.zig, src/check/canonicalize/test/exposed_shadowing_test.zig, src/check/canonicalize/test/frac_test.zig, src/check/canonicalize/test/import_validation_test.zig, src/check/canonicalize/test/int_test.zig, src/check/canonicalize_bool_test.zig, src/check/check_types/cross_module_test.zig, src/check/check_types/let_polymorphism_test.zig, src/check/check_types/problem.zig, src/check/let_polymorphism_integration_test.zig, src/check/parse.zig, src/coordinate/ModuleGraph.zig, src/coordinate_simple.zig, src/eval/eval_test.zig, src/fmt.zig, src/layout/store_test.zig, src/main.zig, src/playground.zig, src/repl/eval.zig, src/snapshot.zig, src/test.zig
* ModuleEnv no longer owns the source - instead it expects a higher-level component to own that
* Removes dups from many callsites! (mostly tests)
* When we have a ModuleEnv, get the source directly from that rather than making it be passed in redundantly
=> Update source ownership and make source come from a consistent place

src/check/parse/AST.zig, src/fmt.zig, src/snapshots/formatting/singleline_with_comma/everything.md, src/snapshots/fuzz_crash/fuzz_crash_019.md, src/snapshots/fuzz_crash/fuzz_crash_020.md, src/snapshots/fuzz_crash/fuzz_crash_062.md
```
zig build repro-parse -- -b bW9kdWxlW318MAphcyBzfHx8MA== -v
```
=> Implement multiline lambda arguments on comma while fixing a parse fuzz crash

src/fmt.zig
This is cause because ModuleEnv does not own the source anymore. So it never free it.
We no longer need to dupe it.
=> avoid memory leak from extra duplication.

src/fmt.zig, src/snapshots/fuzz_crash/fuzz_crash_071.md
```
zig build repro-parse -- -b cGFja2FnZVtde2Q6e3tkOnswfT99fX0= -v
```
=> Fix parse crash caused by single question suffix formatting

ci/benchmarks/bench-runner/src/main.rs, src/fmt.zig, src/parse/Parser.zig, src/snapshots/fuzz_crash/fuzz_crash_072.md
```
zig build repro-parse -- -b bW9kdWxlW10oe30pKCF7MH0p -v
```
=> Fix parse crash caused by unary op formatting

src/eval/test/helpers.zig, src/fmt.zig, src/fuzz-canonicalize.zig, src/parse/Parser.zig, src/parse/mod.zig
This limits the maximum level of nesting for expressions to 128.
We use a nesting counter that decrements as we nest (enter parseExprWithBp), and increments as we unnest (leaving that same function using `defer`).  When we decrement, if the counter is already at 0 we throw a StackError.TooNested.
This requires the Parser to have it's own named error union and updating all of the parsing functions that can call parseExpr directly or indirectly to use that new error union, and all catches from those functions to handle that new value.
I think this will help the fuzzer in the short term, and is a pretty benign change.  Long term we might want to think about how we can get around this nesting limit -  even if 128 levels of nesting in an expression is probably already past the limits of human …
=> Use a nesting counter to protect against stack overflow in parser

src/fmt.zig, src/snapshots/fuzz_crash/fuzz_crash_074.md
```
zig build repro-parse -- -b -v cGFja2FnZVtde2Q6e3tkOnswfS5jfX19
```
=> Fix parse crash caused by field access formatting

src/eval/test/eval_test.zig, src/eval/test/helpers.zig
Some tests were incorrectly permitting tokenization errors (which are reported separately from parse errors). This fixes that and updates the tests.
=> Fix some tests

test/fuzzing/fuzz-canonicalize.zig
```
zig build repro-canonicalize -- -b MApwPXt7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3t7e3sw -v
```
=> Don't treat parser's too nested error as a canonicalize error

crates/language_server/src/server.rs
Tokio uses a smaller stack size for threads, I made it use the default stack size for a program instead. Fixes https://github.com/roc-lang/unicode/issues/28 .
Functions like this caused the stackoverflow: https://github.com/roc-lang/unicode/blob/f33fd561042f733da3a162b20709d6e96bdff528/package/InternalGBP.roc#L14
=> Fix stack overflows

src/cli/main.zig, src/eval/StackValue.zig
```
16:37:29 ~/Documents/GitHub/roc roc-test $ zig build roc
16:37:33 ~/Documents/GitHub/roc roc-test $ ./zig-out/bin/roc test all_passing.roc
16:37:35 ~/Documents/GitHub/roc roc-test $ ./zig-out/bin/roc test one_failure.roc
Ran 1 test(s): 0 passed, 1 failed in 1.5ms
16:37:37 ~/Documents/GitHub/roc roc-test $ ./zig-out/bin/roc test --verbose all_passing.roc
Ran 4 test(s): 4 passed, 0 failed in 1.7ms
PASS: line 5
PASS: line 6
PASS: line 7
PASS: line 9
16:37:41 ~/Documents/GitHub/roc roc-test $ ./zig-out/bin/roc test --verbose one_failure.roc
Ran 1 test(s): 0 passed, 1 failed in 1.5ms
FAIL: line 5
```
```roc
module [add]
add = |a, b| a + b
expect add(1,2) == 3
expect add(2,3) == 5
expect add(3,4) == 7
expect add(1,1) != 3
```
```roc
module [add]
add = |a, b| a + b
expect add(1,1) == 10
```
=> Minimal `roc test` implementation

src/cli/cli_args.zig, src/cli/main.zig, src/eval/StackValue.zig, src/eval/interpreter.zig, src/snapshot_tool/main.zig, test/snapshots/repl/string_edge_cases.md, test/snapshots/repl/string_equality_basic.md, test/snapshots/repl/string_interpolation_comparison.md, test/snapshots/repl/string_multiline_comparison.md, test/snapshots/repl/string_ordering_unsupported.md
```
$ zig build run -- test --verbose test_strings.roc
Ran 6 test(s): 6 passed, 0 failed in 0.4ms
PASS: line 9
PASS: line 10
PASS: line 11
PASS: line 12
PASS: line 13
PASS: line 14
```
```roc
module [concat]
concat = |str| "Got: ${str}"
longer =
"""This is a
"""multi-line string!
expect concat("foo") == "Got: foo"
expect concat("bar") == "Got: bar"
expect "hello" == "hello"
expect "hello" != "world"
expect "different" != "strings"
expect concat(longer) == "Got: This is a\nmulti-line string!"
```
=> Support string equality in the interpreter

src/fmt/fmt.zig, src/parse/HTML.zig, src/parse/Parser.zig, src/parse/tokenize.zig, test/snapshots/multiline_string_complex.md
Removes MultilineStringEnd: everything after """ until the end of the line is part of the string.
=> Remove MultilineStringEnd

src/fmt/fmt.zig, test/snapshots/fuzz_crash/fuzz_crash_027.md, test/snapshots/lambda_in_collection.md, test/snapshots/records/record_with_comments.md
I made a few small fixes to the formatter:
- closing `|` of multi line lambda gets indented correctly
- allow only one empty line in the code (same as old compiler)
- change indention of first comment inside a record (same as old compiler)
- doesn't throw away comments after record extension
=> Fix several issues with formatting

crates/packaging/src/cache.rs
This fixes #8231 
These types of info messages are typically sent to stderr.
=> log download to eprintln
